### ISSUE TITLE
Boss Idea: lost souls  -linked boss-

### ISSUE THREAD

**Issue by dennisheperol** [AngelArenaAllstars/suggestions#10]
https://cdn.discordapp.com/attachments/265223830123839498/269499320619761664/unknown.png

To punish/help you the souls can shoot multiple fragments after some time at some slightly different angles, harder to dodge for both you (punish) and the other soul (help)

Possible extra: souls stay separated but can be damaged while linked up, once you kill one the other will disappear and come back as a higher tier boss

**Comment by Haganeko** [comment]
This seems similar to the Buddy Io Boss idea (#4)
