### ISSUE TITLE
Boss 

### ISSUE THREAD

**Issue by Kris-Watson** [AngelArenaAllstars/suggestions#100]
A boss which can summon creeps,
Initially he fights normally  untill he reaches a threshold of 80% HP and has low armour and attack dmg unitll 80% HP is reached. Upon reaching this threshold he becomes invincible and summons a horde of weak to medium creeps.
Upon killing all the creeps he looses invincibility and can be attacked normally, however he has greater armour, mag resist and damage.
When he reaches 45% or so ( please balance if necessary) he becomes invincible and spawns 2 mini bosses who are significantly stronger than the creeps and are more built to be tanky rather than damage oriented. Upon killing these minibosses, a particle effect occurs which shows that he is absorbing the mini bosses and the boss looks like he has more armour visually. He looses invincibility and gains more armour, rocovers some HP, a small increase in HP regen and a bit of additional attack damage.
This is the last phase and periodically summons a few medium creeps to help him but he does not gain invincibility. Also in this phase, if he gets nuked down quickly he spawns a few weak(easy) creeps while the boss recieves high regeneration untill all the creeps are killed.
This boss would also be significantly easier to kill (less of a tank- less hp, less armour etc) as compared to other bosses as he should be more of a mage

**Comment by Haganeko** [comment]
Thanks for the idea!
Any thought on how the creeps/minibosses would work? Would they just be right clickers?
On another topic, what would the boss be doing while the minions are being fought? Attack, cast spells, stand around?

**Comment by Kris-Watson** [comment]
The creeps should be mainly right clickers while the minibosses shld have
some tiny / weak abilities that would damage and slow players also one that
would reduce player damage periodically

Thanks for looking into my idea

**Comment by Kris-Watson** [comment]
[EDIT]
I forgot to answer about the main boss.

if it is possible can he give dialogue about how worthless the players are
and cannot beat him...etc.

other than that he should periodically spawn healing wards for the 1st
phase (horde of weak creeps) when the number of alive creeps fall below a
certain threshold
OR
he could spawn some strong creeps(or smaller versions of him) that give
bonus attack dmg, attack speed and armour to the smaller creeps. However
when doing this he looses invincibility and takes time to "recuperate"
however he should not be able to fall below {10%+ threshold for 2nd phase}.
If he falls to this HP he goes into a "rage" mode where he gains bonus hp
regen and deals medium to heavy damage to all heroes and stuns them for a
duration. At the end of the stun duration he looses bonus regen and goes
back to the invincible state( this is to prevent players from skipping the
second phase and to punish them if they try, and would need to kill all the
creeps to progress)
OR
He could periodically transform random creeps to mega(stronger) creeps

Thanks again

**Comment by Haganeko** [comment]
Any updates on this, with you previous comment? Also, could you edit the formatting for clarity? #37 has a useful template for this.

**Comment by Kris-Watson** [comment]
Ok so this is the revised version
 (but srsly u guys legit reply like 2 months later lol)

*BOSS NAME:*
Can be anything really, but would appreciate if some part of the boss was
indicated of my suggestion (my gaming name: Alex0419)

*BOSS ARENA:*
Fairly large to incorporate additional spawns/hordes

*BOSS DESC:*
Boss should look kinda like a person who summons and some changes to
appearance for different phases (info for appearance change will be given
in phase description).

Boss is ranged

***TRANSITIONARY PHASES ARE SUPPOSED TO BE THE MAIN PART OF THE BOSS RATHER
THAN THE RIGHT CLICKING PHASES***

*PHASE 1 (90%-100%/ aggro requirement):*
Boss is a right clicker and deals low-med damage

*TRANSITION PHASE 1:*
Boss goes into an invincible state and spawns low-med strength "minions"
and says something like "u pathetic creatures now face the creations of
*"HERO NAME"*"

*UPON COMPLETION*
Upon killing all minions a transition phase occurs when animations depict
the main boss absorbing minions and saying "merely failed projects. They
shall not go to waste".

Boss gains a boost to attack and regen, also gains abilities that is
present on minions(give random weak abilities to  minions).Boss looses
invincibility

Boss looks more spikey (idk more minionlike)

*PHASE* 2 (60%-89%):
Boss starts right clicking and occasionally (around 20% chance) procs split
shots to all heroes and player spawned creeps in arena dealing low damage
but applying poison dmg (DoT) and attack speed slow.
Boss periodically spawn "incomplete" or curropt minions that run to the
closest hero and explodes dealing AoE damage.

*TRANSION PHASE 2:*
Regains invincibility.
Spawns 2 minibosses while saying "THESE ARE my perfect creations. ADVANCE
my sword and shield-advance.

(*Miniboss A*: has high magic resist and damage
  Appearance: has a "curropt" sword

*Miniboss B*: has high armour, a linkens effect and an active channelling
ability that heals in AoE
  Appearance: has a "curropt" shield

Both minibosses have high hp and occasionally sacrifices a nearby minion to
heal a bit).

Boss also spawns "incomplete" minions( that explodes) and weak fodder
minions for the minibosses.

*UPON COMPLETION*
Upon killing the minibosses a transition phase occurs when animations
depict the main boss absorbing the minibosses and saying "You are quite
resilient, but it's time I END this."

Boss gains bonus attack, armour, magic resist and changes to melee attack
using a sword and loses invincibility.

Boss looks more tanky (more armour visually) and equips a sword and shield.

Abilities: boss gains a linkens effect and a "sweeping sword" cleave effect
that periodically procs dealing cleave damage (has visual effect so that
players have time to dodge)


*PHASE 3 (20%-60%)*
Boss starts right clicking and regularly spawns alot of "incomplete"
minions (those exploding ones), however they have much lower hp and deal
less damage.
The boss also spawns a horde of very weak minions that have low-med hp and
very low damage however when any of these minions are alive the boss is
invincible and gains a slight regen boost.

**But when he spawns the horde he becomes 'tired' and takes time to
recuperate for 20 seconds- during this time his armour and resist falls to
0.

(complimented by the temporary invincibility he gains if any minions are
alive so players have to beat the insignificant minions to get bonus damage
in on the boss)

*FINAL PHASE (<20%):*
An animation depicting the boss loosing control of the absorbed minions and
spits them all at once and says "WAHT HAVE YOU DONE TO MEEEE"
*This spawns:*
 *The 2 minibosses *
* A horde of the transition phase 1 minions*
* Some scattered explosive minions.*

****All of the minions have boosted stats while the minibosses are much
weaker**

Players have to kill all the minions and minibosses to deal the "finishing"
stroke of damage to kill the boss

**The main point of the final phase is to give some story and should be
kinda easy**

****This version has some differences from the previous one and is
intended****

**Comment by Haganeko** [comment]
I am very sorry about the delay,
The team has been focused on implementation for the last two to three months. We have all of the bosses which will be implemented till v1.0, so taking suggestions just hasn't been urgent.

**Comment by Kris-Watson** [comment]
Noooooo

**Comment by Haganeko** [comment]
I've been going through issues slowly, closing the ones which are more fluff than mechanics or have little chance of being used. I hope this doesn't turn you off from giving suggestions.

**Comment by Kris-Watson** [comment]
Noooo


I spent like an hour to type that lol




Could you then specify like what mechanics you can actually implement in a degree of how easy it is to add to an hero and some examples of how it can be used( complex AI - simple AI )


Would also help prevent suggestions that are either too impractical or hard to implement.




Thx




Get Outlook for Android







On Wed, May 10, 2017 at 10:25 AM +0800, "Haganeko" <notifications@github.com> wrote:












I've been going through issues slowly, closing the ones which are more fluff than mechanics or have little chance of being used. I hope this doesn't turn you off from giving suggestions.
