### ISSUE TITLE
Item Idea, Win Button

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#104]
Item in shop, costs 1000 gold, description says active ability: Win game. BUT when you use it the item is consumed you get your gold back and the screen says " You just got pranked". Or alternativly it can kill them and not give them gold.

**Comment by Haganeko** [comment]
I see a couple of problems. For one, we want to cultivate a community which plays repeatedly, and the joke loses its impact after one use. For another, I don't think we should implement random pranks into the game. Makes it look less tidy.

**Comment by prodigiousking** [comment]
True it was more of a joke but i am going to close it because i have other serious ideas and i dont want baumi to see my name remember this and then not bother clicking on th

**Comment by prodigiousking** [comment]
Them*
