### ISSUE TITLE
Boss Idea, Count Stackula

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#105]
Easy Boss but must be faced by team. Normal attacks but once he gets to half health he dashes to the closest hero and imobilizes them doing damage and healing health(pudge dismember) until hit by 10 attacks(pheonix egg). Does this every 20 seconds afterwards (Hes a vampire). Super easy miniboss meant to be done early on. Drops aquilas

**Comment by Haganeko** [comment]
Thank you for the idea. Unfortunately, this does not conform to how our bosses work. The mechanics are not very innovative, and dropping aquilas from a boss is not something we're looking to do.
