### ISSUE TITLE
Obelisks [Boss]

### ISSUE THREAD

**Issue by UnMensonge** [AngelArenaAllstars/suggestions#108]
?= PLEASE balance around game
Unlike dark souls bosses which encourage micro reactions, this fight forces the team to make macro (dota's difficulty) decisions; based on hero composition, balance early rewards, late rewards, killing more objectives, and not dying. When players enter the arena, 3 obelisks spawn around the boss. Boss [I'll call him Razor] and the three obelisks are inactive. To initiate the fight, an obelisk must be attacked, activating only the attacked obelisk, no other can be activated until it is dead (2-4? second grace period between being able to activate another). Razor inherits the ability of whatever obelisk is chosen to be killed. After one is killed, the team will have the opportunity to kill the boss or continue killing the other obelisks then kill Razor.

**Each Obelisk**
Each is meant to counter a type of hero seen in Angel Arenas and be weak to another
Does not move
10000 health(?)
500-600 damage (?)damage should be life threatening to the wrong team composition because they cannot kill the obelisk fast enough

**Obelisk 1** (meant to counter ranged, encourage magic heroes)
Ability: deals aoe damage, the further the hero, the more damage. Similar to razor's q
Encouragement: 10% magic resistance
**Obelisk 2** (meant to counter melee, encourage ranged heroes)
Ability: slow in 325 radius for 10 seconds  
Encouragement: push all heroes caught in the aoe 800 units backwards  when ability is activated
(ability and encouragement activate simultaneously)
**Obelisk 3** (meant to counter magic, encourage melee heroes)
Ability: netherward damage when spells cast AND/OR increasing the cooldown of the ability cast by 6-10 seconds
Encouragement [probably needs tweaking]: low armor (ranged heroes tend to have lower damage then melee. Lowering armor increases the effectiveness of more damage)

**Razor**
4-5 times more hp than an obelisk
same damage as obelisk (multi attack (two attacks?))
Inherits abilities of each obelisk killed
%15-20 lifesteal for each obelisk not killed OR 700 hp healed every 20-30 seconds for each obelisk not killed
Base armor: 40-70 (becomes whatever Obelisk 3's armor is when its killed)
Base Magic resistance: 25% (becomes 10 if Obelisk 1 is killed)
Drop gold to each team member: 1000*4^(x-1)     x is number of obelisks killed. 
Minimum gold: 1000
Maximum gold: 16000
Each Obelisk kill guarantees an item meant for a certain type of hero when razor is killed. These items are meant to be strong earlier, and average later. By the time the team can kill all three obelisks and the boss the drops should be one tier up (think black knight sword power in undead burg vs lost Izalith in DS1). A team can then build around the boss so they can make killing the boss an objective earlier. Killing one obelisk and prioritizing the item on one hero making them strong. Or the team can wait later so three heroes can have boss items that are more average. 

The team attacking this boss must assess what their team composition is and then kill the obelisks that their team composition counters best.  If the team overpowers all three obelisks, Razor will have all three Abilities of the Obelisks, posing a challenge to every team lineup but giving lots of gold and boss items. A team will only be able to kill him once or each obelisk could regenerate

**Comment by Haganeko** [comment]
Thank you for the post!
I wonder how we could make this encounter intuitive. Without reading the abilities, how are the players supposed to figure out that they aren't necessarily supposed to kill all the obelisks, but can do it if they want all the items?

**Comment by UnMensonge** [comment]
Sorry for all the dark souls references. The boss item system can be a good model. Each Obelisk would drop a "soul" or what have you. Unlike dark souls where you do not know that you can use the items to craft, moba crafting directly says what is necessary. So players can see in the store that an upgraded item requires "soul of obelisk (1,2,3)" if this were the case, the names of the obelisks should represent their model i.e. colours.

As for representing the option of which to kill. A star storm would hit each killable unit. Players enter the arena and see the star storm hit the obelisks but not the boss. Based on item names, they can decided to kill one obelisk. Then, the star storm hits the boss and other two obelisk. Inducing based on the initial star storm, players know they can kill razor.

**Comment by Haganeko** [comment]
Sorry for the wait; things have been moving fast on the implementation front, so we haven't had as much time for suggestions.
Could you format this according to the template on #37? This is a really cool idea!
