### ISSUE TITLE
Boss Mechanic

### ISSUE THREAD

**Issue by tylerb418** [AngelArenaAllstars/suggestions#109]
In fighting games/sport there is a tag team option. Maybe a boss that's like a fighter and has to do a 1v1 but you can tag out/switch with your team. Ex: Ursa fights the boss for a little bit, then when he gets low on HP, tags in a Lina, who spams her spells, then trades off to someone else while the Ursa gets his HP back up. Or along with that idea, a 5 on 5 where each person gets one boss enemy to fight but when they tag out then the next person has their own boss to finish off.

**Comment by Haganeko** [comment]
Thank you for the post, and sorry for the delay. Right now we're not looking for 1v1 bosses. They're supposed to be efforts in coordination.
