### ISSUE TITLE
Boss Idea: Any tier boss

### ISSUE THREAD

**Issue by m4ru92** [AngelArenaAllstars/suggestions#11]
This was a boss idea discussed with Baumi a bit on 1-13-17. 

Original idea:
Boss is mid to short ranged. He has some sort of basic, mid-damage attack with no special modifiers. He then has two spells he casts in phases that alternate. Roughly every 10% of his health, he casts a spell in a line where he is facing that acts like macropyre. That line will do high damage/second and reach all the way from where he cast it to the edge of the arena in that direction, and it persists through the end of the fight. Then, roughly every 25% of his health, he will teleport himself and all heroes fighting him into the middle of the room, then run to out a little bit in a random direction. He could also potentially have a hook or push type spell of some sort that he would target a player with occasionally and move them with, dealing moderate damage. 
The strategy to this boss would be to move him to a corner or wall, and tank him there so that when he uses the macropyre effect, it doesn't cover much of the arena. 

Baumi's edits after discussion:
Boss would alternate being melee or ranged. No teleporting himself or players to the middle of the room, no hook/pull. Instead, he will cast the macropyre every 10% of his health in the direction he is facing, same as the original idea, but he will also charge around the room every so often (maybe also 10%, after the macropyre spell?), forcing players to have to chase him. Locations he charges may be random (not necessarily outside walls or inside). He switches to ranged after he charges and keeps attacking, forcing players to want to get close to him again.

Additional ideas:
Taking Baumi's ideas, perhaps make his ranged attacks more powerful than his melee, giving incentive for players to chase him and position themselves next to him. This will put the players in danger of crossing the macropyre effect though, so they will have to weigh whether it is worth being hit by the macropyre or his more powerful ranged attacks. The charge could also possibly do damage to anybody the boss passes over, but have a slight delay allowing players to dodge it.
I feel like this boss could be any tier of difficulty, with it being fairly easy to adjust how much damage his various abilities would do. Could possibly make harder difficulties do more macropyres (every 5% for example) or charge around the room more frequently. 

Lore-wise, this boss could probably be an angel or a demon. Any sort of fighter type being who specializes in moving around quickly in combat makes sense.

**Comment by Wujekklawy** [comment]
@m4ru92  

Uriziel The Fallen 
---

There is only few that remember times when worlds was connect. His name was forgoten even by himself. He was born on the border of lands now known as hell. The conneckted lands of Eden  was peaceful and was no difference between it's peaple. As he was eight  the war between cast of Angels and Devils began. From the unlished powers world started to crumble creating stars. But worst was just to come. The magic illness started to spread, the people started to change,  evry of the woriors started to be thirsty of life powers of unchanged. People that was not in the casts started to be feed for them. Only high ones and few people under their protection survived. In protection of high ones he learned to use magic and how to avoid becoming an abomination, but his soul was already corrupted.  When sanctuary got attacked by united forces of warriors after falling to save his family he took Sword from fallen nemesis and promised himself that he will not stop until he kill last of the woriors. Abandoning High ones while they was separating the worlds he vanished in to the deep hells. Slaying corrupted he became one of them.
And his sword Uriziel with him.


>i didn't know if you want something to create or something already existing so i made it myself. Can be something like this?  I know it is bad but i wrote it at 00:37 am on phone so can do better.  It needs a little enchanting but should be ok after it. Just give a word

**Comment by Haganeko** [comment]
Heavily outdated - lacks phase design, and is mostly a DpS race.
