### ISSUE TITLE
Boss Idea the Bellower (revised)

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#111]
Cone shaped arena

Boss auto attacks like a standard boss, maybe an Aoe stomp attack, but at a certain point (HP or time) he enters phase one, returns to this postition, and then at another point enters phase 2

Phase 1: 
The boss leaps into the air quickly and lands at the tip of the cone shaped arena instantly knocking all heros to the far edge of the arena. The boss then proceeds to constantly let loose slow AOE shockwaves that travel down the length of the arena effectivly creating a  moving maze like pattern of shockwaves. The shockwaves would do damage and knock back hero if it. Due to the nature of the shockwaves along with the shape of the arena it gets harder to dodge the shockwaves the closer you are proving disadvantageous to a team compised mostly of melee heros, a possible solution is an armor passive that deactivates if a hero is within melee range. This phase would end after time or when the boss is stunned or takes so much damage. After the phase ends the boss would leap back to the middle and normal battle would proceed.

Phase 2: 
The boss once again leaps in the air suddenly and lands at the tip of the cone shaped arena and all heros are moved close to but not super close to the tip of the arena. The boss starts inhaling, drawing heros towards him if they dont move and greatly reducing their movement speed if they move against him. At the same time projectiles( idk if they are considered projectiles) from the edge of the arena are drawn into the bosses mouth. If the projectiles hit a hero the hero takes damage and is stunned allowing the monster to draw them towards his mouth. If the hero is drawn into the bosses mouth they take a large chunk of damage but are knocked away. This phase ends after time or when a hero reaches the edge and triggers a button causing a large projectile to roll down the center and strike the boss dealing a good chunk of damage and stopping the boss. After the phase the boss would leap back to the center.

Touchups:
 I thought that if it wouldnt be too long these phases could happen mulitple time per fightbecoming more difficult each time (aoe waves becoming faster and more complex, inhalation slow increased and projectiles added and/or made faster), also im not sure if precautions need to be made against stuns being too powerful against the boss (ie mirana arrow), but i am not too against it as it would be a viable counterplay and stop the boss from taking too long. Also I am not sure if phase two is doable as far as the dota platform so it could just be phase 1 multiple times.

Possible Lore: I was think a dude with a big mouth, like the pokemon exploud. Phase one is him yelling sound waves. He could have drill teeth so the projectiles from phase 2 which were supposed to be rocks wouldnt hurt him, but the final large projectile would be too big for his mouth.

Thx for reading hope it is a positive contribution even if it itself isnt entirely viable/optimal

**Comment by Haganeko** [comment]
Thank you for your contribution, and sorry about the wait.
This looks interesting. The phases you outline are not quite phases in the way we've been using the term, however. Please acquaintance yourself with the template in #37 and reformat this post.
