### ISSUE TITLE
Fun Duel Arena 

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#112]
Can you make it an option or make it standard that the duel arena is slightly fun ie: pendulum from colleseum.

IDK if this is what you are looking for but its not out of question I quote/paraphrase baumi saying in a video or stream: I like unusual ideas, you may think "this is the stupidest idea in the world there is no way he will implement it", but i will implement it anyways

**Comment by Haganeko** [comment]
Thank you for the idea! We're always looking for innovative concepts. This one would add randomness to duels, which is not quite what we are looking for - duels are complex enough as is. Keep up the good work!
