### ISSUE TITLE
Radiance Variants

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#115]
A) Healing variant that supplies heals to your teammates
B) Slowing variant that slows all enemies in the radius
C) Evasion variant that gives evasion to your teammates
D) Blinding variant that reduces vision of enemies/gives vision to all allies
E) "Crossfade" variant that can switch between two modes, either giving allies a speed buff, or slow enemies
    1) This can be separated into two different variants that both build into the "Crossfade" one
F) Bash variant that will supply all allies with a passive bash chance
This was gatherd from my own ideas and from those within the @design place in the Discord server

**Comment by Vafnar** [comment]
Credit to @voidskeeper @chrisinajar @Melongod and @OxTheFifth for a few of those ideas forgot to post tat

**Comment by Haganeko** [comment]
A few of these (at least A and E) have been introduced in either Lucio Radiance or Rainbow Radiance.
