### ISSUE TITLE
[Boss Mechanic] Gain New Abilities and Temporarily fight with Inverted Controls

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#116]
Concept: Dota players tend to have specific setups to the point where it's muscle memory. Well, this boss is here to throw a wrench in your game by inverting your controls. It can be as basic as reversing qwer abilities in the game, to spatially changing how the mouse registers your inputs.

**Players and boss abilities:**
Q - Weak attack (low cooldown, mana) 
W - Strong attack (medium cooldown, mana)
E - Dash (medium cooldown, mana)
R - Special Attack (high cooldown, mana)

**Boss ability -  Invert Controls for players** (Spray in a 360-degree area after a short delay or Medusa Ultimate and anyone caught will have the debuff applies.)
 - mouse: up is down, down is up, right is left and left is right.
 - q,w,e,r abilities become r,e,w,q. (item hotkeys if possible)

Phase One: Does a telegraphed spray attack which will only impair movement (mouse). (blue color)
Phase Two: Does a telegraphed spray attack which will only impair q,w,e,r. (red color)
Phase Three: Does Madusa ability; if caught in the line of sight, forces everyone to fight with both debuffs. 

or 

Phase One: Does a telegraphed spray attack which will impair movement (mouse) and q,w,e,r for a duration.
Phase Two: Does Madusa ability and forces everyone to fight with both debuffs on permanently.

Boss Idea inspired by Shinji Hirako / Aizen

**Comment by Haganeko** [comment]
Thank you for the post! This sounds like a lot of hassle for the players... I don't think we're looking to mess with controls.
