### ISSUE TITLE
[Boss Mechanic] Fight versions of you that have died at different instances that game (w/ items and abilities)

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#118]
Concept: The Boss will resurrect a version of your character at the point you died. (The clones can use your abilities and items - use Dota 2 A.I.) Only heroes that are in the bosses arena will be summoned, so you don't need to worry about fighting someone else.
 
Can be executed in several ways:
 - You died 5 times; 5 of you are resurrected with the items and abilities you had at the time of death. (ie. if you died to creeps at level 3 and level 15 with farmed items, they will pop up for as many times as you have died.)
 - Spawn the last and strongest version of yourself that died this game. (abilities and items included).
 - Wall of replica (easy out)

Phase 1: Summon weakest versions of you that died this game. (abilities and items included).
Phase 2: Summon mean/median version of you that died this game. (abilities and items included).
Phase 3: Summon the latest version of you that died this game. (abilities and items included).

Angel Arena promotes deaths and so there will be many versions of yourself. And depending on when you fight this boss (early or late game), it can become a horde battle against decently strong units with abilities and items.

Counterplay:
-You pick you team and fight the boss with a group who haven't died recently or a lot.
-You might have an OP character which you don't want to deal with; leave them out of the boss fight.
- Ignore your clones and murder the boss

Boss Idea inspired by Genryūsai Shigekuni Yamamoto. Specifically, his Bankai ability "Zanka no Tachi, Minami: Kaka Jūmanokushi Daisōjin".

**Comment by Haganeko** [comment]
Thank you for the idea, and we apologize for the delay.
Could you please format this as in #37? That would help a lot.
