### ISSUE TITLE
[Boss Mechanic] Two Strikes and Your Out

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#119]
**Concept** 
- If the boss hits you in the same area twice you die.
- Your characters have 4 vulnerable target points. (front, back, left, right) [can be doubled if diagonal inputs are included]

**Telegraphed ability** 
- Fast attack in a straight line (like a joust or lunge)
- Leave symbol on players character to show where they have been hit.

**Counterplay**
- move/dodge
-rotate your body so that you are hit in another place (ie. if already hit in front, rotate so second hit gets your back)
- Items like Eul's Scepter of Divinity
- Stuns

Phase 1: Can have them try this move with other abilities
Phase 2: Can add a blink ability to the move

Boss Idea inspired by Soi Fong

**Comment by Haganeko** [comment]
Thank you for your submission.
I like the inspiration, but I am not sure these mechanics work for a game on DotA. We're also very hesitant to add insta death mechanics.
If you believe you still want to give this a shot, please format it according to #37 and open a new issue.
