### ISSUE TITLE
[Boss Mechanic] - Boss only Killable via Summoned Creature 

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#120]
Concept: Uses Boss Minion to fight with/for you. Damaging the creature is the only way to kill the boss.

Telegraphed Abilities
1) Overhead slash down (straight line ability that damages and slows) - Opens a portal which summons the right arm of your demon to do the attack.
2) Swiping slash across (cone attack that damages and disarms) - Opens portal which summons the left arm of your demon to swing right.
3) Overhead Stomp attack that is targeted on the ground (damages and stuns) - opens a portal which summons the foot of the demon.

Phase 1 - uses the combination of attacks to kill
Phase 2 - Summons a large demon which does the same moves. You now fight both boss and creature.
- Attacking the creature is the only way to damage and kill the boss. (use IO's link to show they are connected)
- If you attack the boss, the boss gains health
- If you attack the creature, the boss loses health

Boss Idea Inspired by Sajin Kamamura/Bayonetta

**Comment by Haganeko** [comment]
This is not very clear - could you please reformat it, according to the template on #37? As it is, I am unsure what this does. If you do clear it up, please open a new issue.
