### ISSUE TITLE
[Boss Mechanic] - 3 Cups/1 Ball Shuffling Game

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#121]
**_Concept/Mechanic:_** 3 Cup /1 Ball shuffle game.

**Boss Fighting Abilities**

1. Overhead slash - straight line ability that damages and slows.
2. Swiping slash - cone attack that damages and disarms.
3. An overhead ranged attack that is targeted on the ground which damages and stuns. 

**Boss Special Abilities**

1. After taking a certain amount of damage, the boss summons 3 cups, jumps in one of them and shuffles the cups for a short duration. Your team now needs to pick the cup with the boss in it within the allotted time. (The cups can be the phoenix ult with 1 attack required to break, and the duration can be represented by the abilities detention animation or alchemist timer over the egg)
- If right, the boss is stunned for a duration and takes damage.
- If wrong, the boss heals and the incorrect cups use Chaotic Offering (Bob and Bryan).
- If none are picked, default to the wrong outcome.

[can reward/punish player by tweaking the outcomes from the choices]

2. Abducts one of the team members and put them in the cup. Shuffle for a short duration, and require the team to save their ally within the allotted time while still fighting the boss.
- If right, Heal your ally and stun the boss for a duration.
- If wrong, the boss heals and the incorrect cups use Chaotic Offering (Bob and Bryan).
- If none are picked, default to the wrong outcome.

_**Boss Phases:**_
1. fight the boss normally.
2. 66% hp - have the boss use his 1st Special Ability. Periodically have it use the ability, having the cups shuffling faster and faster (approaching a mid-tier speed). 
3. 33% - have the boss use the 2nd Special Ability. Periodically have the boss use both abilities, having the cups shuffling faster and faster (approaching an extreme speed) 

[After phase 3, add more cups as time goes on, up to a maximum of 5]

**_Thoughts:_**
- How well you can code the shuffling, and actually trick people will cause this boss to be really easy or really hard.
- You can add resistance and damage penalties to make the boss more challenging.
- Adding more cups creates an inevitability of loss.
- Bob and Bryan can upgrade to Baby Roshans or downgraded to Large Creeps (Minotaurs with stun ability)

**Comment by Haganeko** [comment]
Thank you for the post. Unfortunately, this is essentially Swiper with a randomizing gimmick. Closed.
