### ISSUE TITLE
[Boss Mechanic] Switches Between High Armor and High Spell Resistance

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#122]
Concept: changes to either high armor or magic resistance based on which damage type was done within the threshold.

Phases

1) Normal fight after a threshold of damage goes into phase 2
2) Changes depending on damage received (assuming right click was the main source of damage, greatly increases armor and greatly reduces spell resistance) [can be represented by a changing in color]
3) After another threshold, changes to the opposite spectrum. (High magic resistance, and no armor)

Makes everyone in the team useful and requires a combination of spell casters and right clickers to effectively beat it within a decent time frame.

**Comment by Haganeko** [comment]
Thank you.
Since you made another post with this mechanic, I will close this one.
