### ISSUE TITLE
[Boss Mechanic] - Can only Fight with Spells (Ability cooldowns greatly reduced)

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#123]
Concept: 
- Boss can only take damage from spells (or extremely reduced damage from auto attacks).
- The damage taken from spells is amplified. 
- The cooldowns for anyone in the area while fighting the boss is greatly reduced.
-The character mana regeneration is greatly increased.
-Boss fights by using Telegraphed abilities
-Boss does AOE Lotus Orb effect which reflects all spells back to targets.

**Comment by Haganeko** [comment]
Thank you for your post. Could you expand on it? As it is, there is very little to go on here.
