### ISSUE TITLE
Boss Ability Idea inspired by Kiba's Shikai

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#124]
Concept: Ability doubles the weight of character every time they are hit by his sword.

Telegraph ability - if hit divide movement speed by 2. (stacks until base minimum of 100 movement speed)
- the ability can last for any duration.
- if the ability is permanent for the remainder of the fight this will cause a lot of pressure to not be hit.

**Comment by Haganeko** [comment]
Thank you for the suggestion! There isn't much here, but I believe it can work as an inspiration.
