### ISSUE TITLE
[Item] Bloodmage mask

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#127]
_Builds from_: 
  - Helm of Iron Will: 950g
  - Ring of Health: 850g
  - Recipe: ~1000g

_Stats:_
Nothing extra, just the sum of components:
 - 8 Hp regen
 - 5 armor

##### Version 1:

**Ability toggle**: Bloodmagic
While active, spells use HP instead of mana.

From balance standpoint, the removed HP can be increased or decreased; for example 1.2 HP per mana, or 0.8 HP per mana.

##### Version 2:
**Passive ability**:
Decreses manacosts by (lets say) 50%, Every time you cast a spell (or use mana even), you take damage proportional the mana used. 

#### Concept motivation:
Some heroes (Like Beastmaster, Tidehunter, Earthshaker etc) might have a though time in the early stages with farming due to their limited starting mana pool. This item should help with that; also might be a good choice (version 1) for support heroes in the mid-game, when they don't have enough mana to spam skills at bosses.

**Comment by Wujekklawy** [comment]
Actually i don't know if you know but beastmaster is one of strongest heroes in angel arena reborn ;)

**Comment by zelding** [comment]
I've never played with or against BM in AAR, but lets say I believe you :)

Nevertheless, I'm sure you can think of a couple heroes whom would benefit from this item,

**Comment by VoidsKeeper** [comment]
The recipe could fit ,though with a boss item. Thanks for the post :3
