### ISSUE TITLE
[ITEM] Anarchy Dagger (Chaos Dagger smth?)

### ISSUE THREAD

**Issue by szyjan** [AngelArenaAllstars/suggestions#129]
Build: 
 - Essentialy Blink Dagger + high dmg item or anything really (up to you guys)

Mechanic:
 - Usage - single click (like BKB)
 - Buff - buffs owner for very little time* with monstrous dmg
 - Effect - Blinks user to random location inside radius** and applies buff

Further description:
Idea behind is one like in gambling, you can get massive help during fight, but if you are out of luck nad blink to some remote area, away from your team and enemies it's just sad. You get buff in the moment of usage, so time in which buff lingers should be very small to block possibility of situation, when you blink away from enemies and then just run back into them and smack their faces. Also time needs to be low for item to not be OP - should allow to land 2-3 hits on enemy when blinked just in hit range to some enemy. (it should not be possible to just kill a guy with this, well meybe very week support something?)
Also, I think this item as mid game? Should not be obtainable in early and should be rather weak in late game - but just as I said, it's all numbers to be matched to mechanics.

*Needs to be tweaked and experimented during development a little to find time and buff just right to feel greatness of buff and not beeing overpowered.

**Radius - like anywhere around you or in cone in front of you of some radius.

**Comment by zelding** [comment]
The whole idea is flawed. The purpose of blink is to cover distance in a short time; which implies that you have a **destination**. If the item puts you at a random spot, then it is useless, no matter how much damage it gives, because most of the time it won't matter, because there isn't goin to be enemies near you.
On the rare occasion when it will move you at the right spot, then people are just going to feel cheated/ticked-by-rng, which goes against one of the base principles behind the game-desing: _reduce RNG as much as possible_, and give players as much control over their actions as possible.

**Comment by szyjan** [comment]
I guess you are right. But for some time I'm trying to come up with idea for usage of chance based mechanic, other than cirtical strike or evasion. This item idea is variation on that topic and attempt to make it happen. If it goes down to this, yeah critical strike can be calculated to reliable dmg value, but if you think of it, this blink buff mechanics too, as you calculate probability of appearing in range to amount of hits you can deliver. In that case buff should be proportional to loses when you blink away instead of into fight.

As I said - try of coming up with new mechanic, but it's not true that "it is useless, no matter how much damage it gives, because most of the time it won't matter," because same i think that same thing you can say about crits without luck, it gives you nothing - and same about evasion.

**Comment by zelding** [comment]
The main problem with your argument is attacks are fast, using items usually not. You can easily attack 7-12 times in 10 seconds, which makes crits and misses common, which makes them feel more balanced.

If your item is using the basic blink dagger cooldown, then you would only be able to use it in every 12 seconds, so when it puts you in a relatively good position it will **feel** lucky.

After considerable amount of calculations, and reply-deletions I think I've came up a more decent version:

 - It combines of force staff plus something that gives damage.
 - Doesn't blink you away, rather pushes you backwards (the opposite direction you are facing)
 - The buff has a preset cooldown, but it also has instances, like Ursa Overpower.

This way it would be more reliable, the effect is more manageable and balanceable; and most of all some heroes might consider buying it.
Might be a good sidegrade for Hurricane pike.

**Comment by szyjan** [comment]
What you say is basically nerfed huricane pike:

"When used on an enemy, it pushes you both away from each other 450 units each, and allows you to attack the target without range restrictions for 4 attacks for a maximum of 5 seconds. Grants 100 Attack Speed during the attacks."

Only difference would be that oponent is not beeing pushed, and instead of atk speed you get dmg...

About cooldown - it does not really matter and is purely optimization matter.
As for feeling lucky - same thing applies when you hit that one needed beautiful crit using stiffling dagger, doesn't it?

My Item (as it is beeing reffered to ;) ) would have gambling element and question of it beeing usable or fun to use comes down to just numbers.
You can think about it in various ways. When range is set to high number it is **chance** to get great gank, if set to low range (and lesser buff) it's **chance** for good positioning in fight.

As I said, it's concept so I do not really mind if someone will come up with some better usage to mechanic, but I think it is somethink to think about.

**Comment by zelding** [comment]
I get your point; It surely feels like a nerfed Hurricane pike now; It didn't when I was writing it.

About *your* version, it still bugs me that it blinks you to a random place. How about it blinks you to a random place in X range, where are no enemies in (lets say) 400 range - or the opposite.

I feel that activated items shouldn't have such random effects.
If you rephrase the items effect, it could be something along these lines:
*Teleports you to a random in 1000 units radius:*
- 25% chance to teleport you to safety
- 10% chance to teleport you to an enemy
- 65% chance to do nothing useful

At least that is how it feels to me.

**Comment by szyjan** [comment]
![image](https://cloud.githubusercontent.com/assets/16231958/22787650/4f01119e-eedd-11e6-881e-dc445de056d6.png)

Red dots - Enemies*

If you just make a graph (above)it will make easier to make calculations. If you assume that you have equal chance to appear in any place inside radius, you get around 50% chance, that it will do nothing (blinks you away from enemies*). Another 50% chance is that you will appear somewhere in range to get at least one attack on one of enemies (outer grey circle), and so on. So if you look on it from that perspective, you have chance based gain depending from amount of enemies in range of My Item and distribution of those enemies on that location.

Another thing is that those **2 hits range** is depending on let's say attack speed of hero, or hit instances implemented on buff -> depends of implementation and balance tweaks.

**Comment by zelding** [comment]
I understand now.

Ps: I like how this conversation escalated .D

**Comment by Haganeko** [comment]
This item's effects have too much variation. Interesting concept, but it's way too swingy.
