### ISSUE TITLE
Boss Idea : mid tier

### ISSUE THREAD

**Issue by Shtolz98** [AngelArenaAllstars/suggestions#13]
It's somewhat simple boss design. You have a boss with a LOT of armor and magic resistance. Somebody should tank the boss in mellee range or he will start firing laser's at people, which will wipe you. The key to killing boss is this sequence : after some time, boss will start spinning around while breathing fire. After surviving circle of death,  special zone pops up. Somebody from your team should go and "sacrifice" himself to lower armor and magic resistance of boss, so now it can be killed. The person lives but he is rooted.  Also boss receives buff to its damage or attack speed. You can repeat the process, but you should consider your "sacrificed" teammate and second "sacrifice". Armor and magic res goes below <0 and takes INSANE amount of damage, but he strikes as hard as you do now. 
PS This boss is some kind of damage check. You can kill him very fast, but its more risky. Or you can play it safe and spend more time on him.

**Comment by l34Um1** [comment]
Frustrating. Closed.
