### ISSUE TITLE
Boss idea for AAA

### ISSUE THREAD

**Issue by R0LL1NG** [AngelArenaAllstars/suggestions#130]
it would be pretty funny to have the strongest be roshan. But not to make it look too lazy, let him have stages. First stage: normal, beefed up roshan. Second stage: he would periodically (like 10s cd) spawn little roshlings that you have to kill before continuing to attack roshan, but he would be slighty weaker and roshlings buff him a bit, so after each roshling that gets killed, rosh loses those buffs and becomes easier to kill in that stage. Third: roshan breathes fire in a cone from left to right in 190 degrees and you have to dodge it. Would also be cool if different stages would have different skins, for example the last stage would have diretide roshan skin, where he's damaged and dark and spooky﻿. 
Of course, one stage would be enough for a bpss, if arent looking for bosses with stages

**Comment by Haganeko** [comment]
Thank you for your suggestion. Keep them coming. We are, in fact, looking for bosses with stages. However, we are looking mostly for mechanics suggestions, and this is summoner with an area attack; not very innovative. Closed.
