### ISSUE TITLE
Boss for AAA

### ISSUE THREAD

**Issue by R0LL1NG** [AngelArenaAllstars/suggestions#131]
A guy that creates a bunch of copies of himself surrounding the whole arena and changing his original position to one of the copies. This way you would have to guess which one is the real one. They would all deal same amount of damage and take the same amount of damage. To prevent all of the copies instant killing  someone, the boss would have a damage debuff for each of his copies that re still alive. Of course, the debuff is shared between all copies.

**Comment by Haganeko** [comment]
Thank you for the submission. This boss is a game of luck rather than skill, which is not the direction we wish to take this. Closed.
