### ISSUE TITLE
A numerical Boss fight

### ISSUE THREAD

**Issue by Nixer3** [AngelArenaAllstars/suggestions#133]
This is about new boss: DOMathTAs (DotaMaths), who needs die by Dota mechanics.

You can damage a boss only with an specific amount of DMG output per attack....some kind of passive to protect him from other amounts DMG. (no much more,no much less) passConstant(later)
scenario:
You come to boss /w your team, while attacking him you realise you dont deal any dmg. You start read spells and then you find out why. In passConstant will stant:"Protects from bad amount of dmg ..... The right amount is: { 15% of EHP (+-20%)}". ... then you must calculate the number and fit your items...
eg name: DOMathTAs (DotaMaths)  Base(or real) HP: 20,000   Armor: 150 ..... so, the EHP is: 200,000 and 15% is: 30,000(+-6,000)...(well need some ballance, but there can be shop with this boss to buy "numbers"-only for this boss)

**Comment by zelding** [comment]
I can't see a way to design such a boss where players would understand these rules by looking at him.

You even included that **they have to** look at the bosses abilities. That is going against the fundamentals of this mod: _players need to be able to figure out the general rules of each boss without looking at the abilities_.

This will never fly @Nixer3 , I'm sorry.

**Comment by Wujekklawy** [comment]
It's good idea but not for this :)

**Comment by Haganeko** [comment]
For the reasons stated above, closed.
