### ISSUE TITLE
Boss idea

### ISSUE THREAD

**Issue by Oliverphj** [AngelArenaAllstars/suggestions#134]
FOR BOSS   -  SHADOW SELF / SHADOWMANCER
Abilities
1. Can change its appearance to look like one of the heroes within the combat arena, when it does it teleport s (like doppleganger) all the heroes within the arena so no one knows who the shadow is. 
2. Some times when it changes it will cause one of the players to attack a friendly hero and it will itself only target the turned hero. (to cause confusion)
3. If only faced by one hero It will Simply copy that hero with all its items and have a +20% buff to all stats ( to force people to either be godlike skillful players or work as a team) 
4. When selected it will look like player it is copying and appear to take damage, but has a hidden health bar, if its perceived health drops to zero it will switch again.

Drop
1. Orb of changing - Causes the enemy team to perceive your team as allies (you each take on there models, team color and HUD, all superficial) you team sees it self how it actually is. simply used to cause confusion in a dual. team vision is shared between both teams for duration of effect e.g 30 seconds

**Comment by Haganeko** [comment]
Thank you for your submission. Keep them coming!
Something similar has been suggested before, in #85 . Most of the same issues apply.
