### ISSUE TITLE
The Grave Lord Boss Idea

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#135]
**For In depth view, check out the document at the bottom of the post, 2nd boss down**
Passive: Heroes cannot regenerate health and if they are healed, heal the boss instead
Phase 1 (when heroes first attack)
Summon 5 minions that will taunt nearby heroes and make the boss invulnerable
Phase 2 (after heroes kick the minions’ shit)
Tether all targets inside the passives’ AoE after the tether breaks stun prevent tethered units from using items while in the bosses vicinity.
Phase 3 (around ½ health)
Split into two different people, one ranged one melee
Melee: Can’t do shit aside from auto attacking
Ranged: Can summon Necronomicon units, Heal himself, and if heroes get to close nuke them back
Phase 4 (when the heroes hand them their asses)
Fully heal all heroes that took damage from the boss with a temporary “overheal” (straight from tf2) and drop a chest that will last for 10 seconds. Heroes loot is awarded based on the damage dealt to the chest.

https://docs.google.com/document/d/11U3O3Q9qvm75SX4LlwHWnT6QnqUaYl_xdeDuGTlYvSM/edit

**Comment by Haganeko** [comment]
Thank you for the idea. This is a boss with summons and a muting Puck ult. Doesn't seem very synergistic to me. If you wish to continue to pursue this, please reformat it according to issue #37 and open another issue. Keep up the good work!
