### ISSUE TITLE
The Puppet Master Boss Idea

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#136]
**For indepth view check the link at the bottom, STILL WORKING ON EXAMPLES, 3rd one down**
Passive: Summons minions that will attack heroes if they get close to the puppet master
Phase 1: When heroes enter the area
Summon a clone of the heroes that only takes damage from the hero they are a copy of, once all of them die then the boss itself can take damage
Phase 2: After the clones die/ First hit on the boss
Can only take damage from spells, and reduces basic attack damage/speed to 1, Spells deal x2 damage during this phase
Phase 3: 75% health
Reverse of Phase 2
Phase 4: 50% health
Copy the boss and turn the boss invisible for a few seconds after which it is the heroes job to find the correct boss out of all the copies. If a copy dies puppets are spawned. If all the copies of the boss die the phase is repeated. Basically, the shell game with copies of the boss
Phase 5: 25% health
The boss will offer the heroes a teleport gate that if the heroes go through they will be teleported to one of 4 places: Enemy Fountain, Allied Fountain, another boss spot, or on a ward cliff (chosen randomly). After teleporting  they have additional damage, if the heroes are Tped through the boss is healed to 100%.
Alternate Phase 5: If the heroes are dicks and kill him
Two puppets are summoned, both fire AoE nukes radiating from them similar to the Puppet Master’s Revenge event from Realm of the Mad God.
Phase 6: Death
Drops the same chest as the Gravekeepr

https://docs.google.com/document/d/11U3O3Q9qvm75SX4LlwHWnT6QnqUaYl_xdeDuGTlYvSM/edit

**Comment by Haganeko** [comment]
Thank you for this post. There is some definite potential here IMO.
I don't understand phase 3 - what do you mean by "reverse"? Does it reduce players' cast speed and receive double the physical damage?
Phase 4 is another shell game - with all the problems this entails, including being a game of luck more than skill, Should probably cut this.
The reference to "Realm of The Mad God" is cryptic and I have no idea what it means. Please explain what would happen.
Please reformat this according to the template in #37. It would help a lot.
