### ISSUE TITLE
Grand Sphinx Boss Idea

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#137]
**For in depth view click the link at the bottom of the post**
Passively reveal targets marking them while in the AoE causing them to miss attacks
Phase 1 (when the boss is first initiated)
Fire AoE nukes every so often that radiate from the boss in a cone formation, when one hits a hero the hero is silenced and has reduced vision
Phase 2 (around ⅔ health remaining)
Summon minions that cannot move and heal the boss for as long as the minions live. Heroes will be pretty much forced to kill the minions before the boss.
Phase 3 (around ⅓ health remaining)
Repeat Phase 1 and shoot a wave dealing damage and stunning enemies, while the units are stunned channel a second wave that can be dodged, if a hero is hit then they are knocked to the edge of the first passives’ range.
Phase 4 (when it’s ass gets handed to him)
Knockback all targets to the edge of the passives’ range dealing damage based on how many hammer units targets got knocked back. Items that the boss dropped will be dispersed by this wave.

https://docs.google.com/document/d/11U3O3Q9qvm75SX4LlwHWnT6QnqUaYl_xdeDuGTlYvSM/edit

**Comment by l34Um1** [comment]
Too complicated for what it offers. Closed.
