### ISSUE TITLE
Boss idea

### ISSUE THREAD

**Issue by Haubarker** [AngelArenaAllstars/suggestions#138]
How about a boss that has a projectile flying around him that does damage when you get hit by it.  And maybe everytime a new hero attacks that boss a new projectile would spawn and its flying radius is equal to the attackrange of that new hero. But there may be a maximum amount of projectiles with the same flying radius. The speed of the projectiles could also vary depending on what phase the boss is in and how far the projectile is away from the boss.

**Comment by l34Um1** [comment]
There is too little here for me to work with. Feel free to resubmit when you have a more fleshed out idea. Closed.
