### ISSUE TITLE
[Items] The Backdoor and the dislocator

### ISSUE THREAD

**Issue by Emprorofdirt** [AngelArenaAllstars/suggestions#141]
The Backdoor
Here I try for a fun item for the earlygame or support. Make you a little less squichy when you go for a bit of early game agression or warding.

Description: A upgrade from poor mans shield or stout shield.
The general idea is that it only triggers when attacked, it either gives protection when you are close to your base (maybe a stronger effect when you are closer to the base and weaker when further away), without nearby allies or just a decent defensive item with a recognizable name.

Passive: Something like a Timbersaws Reactive armor but with damage block instead of armor.

The dislocator

Active: dislocate

Dislocate - Dislocates you from you position on the map but also dislocates most of your limbs as well.
The use is meant to give you a defensive option when ganked, a somewhat shortish castpoint and then you will be teleported to a random spot on the map, not necessarily out of harms way. The debuffs I have in mind is ms-slow, disarmed, silenced, taking damage when you move/try to move/use items or abilities. The effects wear off after a while (perhaps one by one).

These two items are meant to be more of the fun options in spirit of the item discriptions of old DotA Allstars.

**Comment by l34Um1** [comment]
Our early game will be regular Dotas progression but accelerated, so these kind of items aren't required. Closed.
