### ISSUE TITLE
Two Unit Boss (Gemini)

### ISSUE THREAD

**Issue by Sworith** [AngelArenaAllstars/suggestions#142]
A boss based off Gemini from Binding of Isaac, could possible use Io's as the boss models.

Two bosses. One shoots you whilst slowly chasing you, however, when this unit reaches 50% life he begins casting damaging spells as well. The other unit is 'tethered' to the shooting boss, healing and giving damage mitigation. Once this healing boss reaches 50% health he untethers and charges the player at haste speed - possibly dealing AoE damage around him.

**Comment by l34Um1** [comment]
While this would work I am a little uncomfortable to just straight up take a boss from Isaac like that. Closed.
