### ISSUE TITLE
[Item/new mechanics] Eye of Seer / Staff of Visions / Peeking Crown

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#143]
#Eye of Seer#

Stats:
+200 day/night vision. 
Aura mana regen: 1.00
Aura bonus armor: 3
Aura bonus damage: 10

Active: Vision
Target: ground 
Cast range: map
Grant's vision of selected area for your team.
Vision Range: 2000
Duration: 20s
Cooldown: 80s

Recipe: (925g)
Observer ward   (65g) 
Ring of bassilus (500g)
Recipe                (360g)

#Staff of Visions#

Stats:
+320 day/night vision
+325 mana
+15 intelligence 
+350 spell range 
+3 armor 
+4s to incantations
Aura bonus armor: 7
Aura mana regen: 85%
Aura hp regen: 12
Spell amp damage 18%

Passive: Vision of Death.
 Reveals nerby low health enemy heroes below 30% hp.
Radius: 3500
Reveal below: 25% hp

Active: Greater vision
Grant's vision of selected area for your team.
Target: Ground
Cast range: map
Vision Range: 2500
Duration: 20s
Cooldown: 50s

Recipe: (4925g)
Eye of Seer (925g)
Aether Lance (2350g)
Oblivion Staff (1650g)

#Peeking Crown#

Stats:

+17 All Attributes 
+20 attack speed 
+12 armor 
+15% evasion 
+5s spell duration 
Aura bonus attack speed: 25%
Aura health regen: 15
Aura mana regen: 80%
Aura bonus armor: 30%
Aura bonus damage: 25%
Aura evasion: 10%

Passive: Peeking 
Changeing visions type from ground to fly.

Active: Staring
Sacrifice flying vision for full vision on one enemy unit and apply debuffs. Not dispelable, can see invisible units. Grants true strike while attacking target. 
Target: Enemy.
Range: 1200
-100% evasion, on target (OT)
-20% armor, OT
-10% movement speed, OT
-20% attack speed, OT
Change vision type from Fly to Ground, on caster.

-------------------------------------------------
Additional informations:

General idea that took me to creating this items was that in every gamemod carry always get some fancy stuff but supports almost never get new items. So i created this items to help supports doing they role and also get help from heroes that are less value in late game, like Zeus for example. The "Eye of Seer" is mented to be early game item, like Bracers, but being more maded for getting support role more options, "Vision" ability gives opportunity to make more successful ganks or making safer aggressive warding. This is for obvious reasons more power to supports earlier parts of game. Staff of Visions is item specify to suports with main strength are spells, big benefit can be additional time and range for incantations like pugna's ultimate or shadow shaman shackles (from obvious reasons sand king should be excluded from gaining that additional seconds). This item is also good for nuker heroes what makes more opportunities to teams without pure support also have some sort of supporting item. Peeking crown is item for more tankiers supports like omniknight or undying, but also can be sometimes being build on others heroes like lycan or dragon knight with good benefits. Also i wanted to this two items to be different than just copy paste so i icluded different benefits from each other, but still keeping them connected to make recipes more believable so item that require an ward in recipe and other one also having ward in recipe to not being one that grant vision and other one summoning 7 hells to burn enemy. Abilities are maked way that both upgrades benefits different styles of supporting,  staff is for supports that like to be away from center of fight and don't like being first line(like shadow shaman or pugna), staff would be very bad for support that like to be in center and be front liner (omni or undying are best examples) who can lead to battle, and for them instead of item that grant vision on things that are further better option is to them have flying vision(to balance purposes on cost of increased vision, for those who don't know what is ground type vision and what is fly type vision best example is balanar with axhs, with it he gaint flying vision in night)

Be sure that that items will be need to be balanced through time, it is not possible to tell how strong they exactly would be in proper match. There is just no other items to compare with but i forced myself to narrow the op <-> too weak ratio.

Feel free to make changes that would make them closer to your vision if you don't like something in them and still want to have something like that in game.  

Ps. I not bothered to make some sort of lore to items excluding names (to be proper for item mechanic). So you can do whatever you want with lore of them.

**Comment by Wujekklawy** [comment]
Pss. I forgot include recipe to Peeking crown so i writing it here.


#Peeking Crown#
Recipe: (5430g)
Helm of the Dominator (1800g)
Solar Crest (2625g)
Eye of Seer (925g)

**Comment by Wujekklawy** [comment]
Psss. If any of items in recipe will be made as an upgradeable like dagon it's also possible to implement that to these items.  So i don't think that would be a problem.

**Comment by prodigiousking** [comment]
I think they have potential, i personally am not incredible at dota and dont know too much about what numbers would be fair and balanced vs broken, i will say that I made a similar item except its vision was based off of a hawk like BM's, and i was rold to make sure I differentiate my item from hero abilities in order to avoid devaluing a hero as well as other problems. I think your item could maybe be interpeted as interfereing with some hero spells (bloodseeker, bounty hunter, winter wyvern,)but idk it looks fine for the most part it juat comes down to what baumi and them want

**Comment by Wujekklawy** [comment]
It's hard to not make similarities to hero abilities in dota where you can easily say that 90% of items are like heroes abilities but worser or rebalanced, vanguard - craken shell, Orchid - sky's silence, basher-lot of heroes with bash, blink dagger -any hero with blink ;)

**Comment by prodigiousking** [comment]
Yeah certainly just saying that its worth keeping in mind

**Comment by l34Um1** [comment]
Please don't submit any numbers. I'll close this. Feel free to resubmit your ideas without numbers though.
