### ISSUE TITLE
Stacking Items?  

### ISSUE THREAD

**Issue by Sworith** [AngelArenaAllstars/suggestions#144]
An interesting mechanic in Smite is the implementation of stacking items; Items which when you kill creeps improve in power. A mechanic like this fits the gameplay of Angel Arena very well, farming creeps at the start for 10 minutes will increase the power of your early game items allowing you to transition into killing the Tier 1 Boss.
For instance:
" You permanently gain +5 Health and +1 damage per Stack and receive 5 Stacks for a hero kill and 1 Stack per unit kill. (Max. 50 Stacks)"
 The difference in max stack numbers would change the times at which you could move onto the next Tier Boss.
You could even make high-risk high reward items like this that work similar to Necromastery but you lose all of the stacks on death, which would require you to be careful for full effect.
-Sworith

**Comment by Wujekklawy** [comment]
I think it could be "little" overpowered in angel arena ;)

**Comment by Sworith** [comment]
Granted, the mechanic would need to be tested fully to make sure it is not overpowered, however, the concept could be implemented to allow Heroes who are behind to squeeze extra value from their items in the case that they aren't able to fight the bosses on time. Though their main purpose would be to allow most heroes to make sure they are able to kill the next tier boss every 10 minutes like Baumi said is a priority.
The mechanic wouldn't be limited to just health and damage, it could improve any stat: AS, Spell Power, Armour, Evasion even something like Cast Range. 
The item could also gain stacks -like Flesh heap- based on kills or assists. 
P.S When I said "permanently" I meant for as long as you're holding the item.

**Comment by TomStavengar** [comment]
How about?
"Spellslingers Amulet"--------
+15 Intelligence
+75% Mana regen
"Permanently gain +0.4% Spell Power per Stack and receive  5 Stacks for a hero kill and 1 per creep kill. (Max. 50 Stacks)"
Built from Void Stone (850g)  2x Robe Of The Magi (900g) Recipe (1500g) = 3250g
Upgradeable 4 times

**Comment by l34Um1** [comment]
Uninteresting way to handle upgrades. Closed.
