### ISSUE TITLE
Boss Recommendation - The Triumverate

### ISSUE THREAD

**Issue by hayme153** [AngelArenaAllstars/suggestions#145]
Just a heads up.. I posted this boss idea on one of your videos but I forgot wc one. I will create another one for the Orb of Disdain later on. Btw I am foing this on my pjone so im sorry if i have to keep it short.

Level 1 ( Power Lvl 10)

Name: Badu WrathMan

Boss Type - Tanky Physical Damage Dealer

Skills - 
1.Lunge - boss winds up for 1.5 seconds. After the wind up he will deal 300 Damage to units in front of him and will stun for 2 seconds.
2. Scream of Wrath - The boss sends out a scream that will deal 100 damage in a small area around him.. Units that are hit by the scream will be pushed 200 units away and will be slowed for 4 seconds
3. Block - Badu will not move for 5 seconds and will receive 60% less damage from all sources when he is hit on the front. Damage on the sides will receive 20% damage reduction. While Damage from the back will deal 30% more.

Drops: Random Physical damage items and at a low % Essence of Wrath.

Essence of Wrath - Gives 10 to all stats and Gives you the ability to use a lvl 1 scream of wrath.

Level 2 (Power Lvl 15)

Badu - will have all skills improved and will gain access to his Ultimate.

Call of the Triumverate - Badu will be invulnerable for 5 seconds. While invulnerable, he will then talk smack and He will then create a Portal that will Summon the 2nd Boss Unit Guda LightChild. Upon appearing Guda will Cast Shot of Life on Badu.

Name: Guda LightChild

Boss Type: Support Healer

Skills : 
1. Shot of Life - After 1 sec delay. The Boss sends a missile of light forward that will Heal the 1st target hit by 50% of their Max HP. ** note: this is similar to a hook that may be blocked by other units.
2. Blink - same as skill in dota 2 with 3 sec cd.
3. Flash of Light - Guda will shine for 1 second and will pull all units within 500 aoe to his location. All heroes hit will take increased damage and will deal reduced damage for 5 seconds.

Drops: Random Utility items and a low% of dropping a new item Shards of Light 

Shards of Light - gives 10 to all stats and an additional .3 mana and hp regeneration per level.It also gives the Flash of Light ability when activated.

**** level 3 will be continued later on as well as the completion of the Triumvrate item when you get all three since I am at work..

**Comment by l34Um1** [comment]
Abilities aren't obvious. Bosses aren't heroes and need to be designed differently. Closed.
