### ISSUE TITLE
[mechanic] Glory (hero kill points) 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#146]
In one of earlier posts i mentioned idea for custom "currency"(from now i will call it "Glory") gained by getting kills or assist. I want to describe it more clearly here. Glory points would be spendable for flat hero upgrades.
------------------------------------------------

Earning Glory points:
 
There are several ways that could be able to optain.

 -Obtaining mega kills

 -Getting killing sprees.

 -Stoping an killing spree

 -Assist sprees. 

 -Wining duels.

 -Defining Bosses.

 -teammate abbadons match.

And others. 

The basic mechanic to gain them could be based on level of killed compared to killer's. For example,  you fight 1v1 against enemy on same level so level ratio is 1-1 (no matter that you have both lvl 1 or 7000). So to earn Glory point you was need to win in 10 scenarios like this if that would be only option to get them. It's easy to understand the basics but after that is more complicated.

 For keeping track of progress with gaining points(or even being able to program that) we need to add Variable to that(let's call it Glory progress). Let's set that we need 1000 of glory progress to gain one of glory point. Using example from earlier we can easily tell that solo kill in rato 1-1 without modifications give uss 100 Glory progress. About assist let's set that evry hero that gains assist get 60% of Glory progress that would get if did finishing blow (that give 60 Glory progres for evry additional hero in fight on 1-1 level ratio). As i mentioned earlier could (and probably should) be modifications with can boost ouer gain of Glory points. Example list below:

 -Double kill +10% Glory progress (Gp)
 -Triple kill +10% Gp
 -Ultra kill +20% Gp
 -Rampage +20% Gp 
 - For every kill in killing spree +5% Gp (constant, resets only on death)
 -For every assist in assist spree +5% Gp (constant, resets only on death)

--------------------------------------------------------------

Spending Glory points.

Glory points could be spend in few ways like:

-Haveing somewhere glory shop on map

-In normal shop

-Hveing special icon on HUD to open menu with upgrades.

Below list of example hero upgrades to buy:

1) +1% damage converted to pure per point 

2) +10 range per point (only ranged)

3) +1% deflect chance per point (only mele)

4)+5% projectale speed per point(ranged only)

5)+2% evasion per point

6)+1 split attack per 5 points (only ranged)

7)+2% combo attack per 5 points (only mele)

...

As you see its possible to do a lot with that. I want to inform you that this is only example to explain how that "could" work in game mod if even will be added.

--------------------------------------------------
Minuses and pluses:

-Not clear mechanic to instantly learn.
-More things to balance. 
-Look complicated... 

+...but only looks.
+benefits more aggressive playstyle(shorter matches)
+add more depth 
+add more options and builds
+perfect testing ground for new attack modificators and mechanics 
+easy to implement 

---------------------------------------------
Honorable mentions.

Level ratio give modifies to gained Gp, for example if ratio 1-2 (lvl 6 vs lvl 12) lower level gain +200% bonus to gain Gp and higher one earn less, like around 50% (this is only example, numbers can change to be more balanced)

Deflect, ability with enables bounce back projectile to attacker, target don't take damage, if not purged off (or missed, work like normal attack)  deal damage to attacker (if attacker have attack modificators they can apply on attacker, attack on target cannot apply to target any attack modificator if deflected)

Combo attack, have chance to instantly attack again (like echo sabre,just without slow), second attack is counting as normal attack and also have chance to combo attack, evry next combo attack have lower chance and deal less damage. Resets after not triggering.

**Comment by prodigiousking** [comment]
I saw the potential in the last post as well, I like this one too but i will warn you i have read a lot of proposals and Team Baumi seems to consistently reject any sort of buyable consumable stats buffs, so I think that eliminates the idea of buying buffs with it, but i still think they have potential as far as buying special items, maybe it is required to unlock a special boss or area, or even required to unlock god tier heros

**Comment by Wujekklawy** [comment]
Prodigiousking, i know from dev that they rejecting all sorts of things like tomes in aa reborn, but he seemed interested about this. And this meaby is upgradeing hero but you not buying it with gold. And as you see in my opinion that source should be very limited, to be able to get like 40-50 in duration of match, and some of upgrades need to be locked on certain level, like evasion for example

**Comment by prodigiousking** [comment]
True

**Comment by Wujekklawy** [comment]
Btw, @prodigiousking  what do you think about items i proposed today?

**Comment by prodigiousking** [comment]
I dont remember exactly which items were yours, remind me?

**Comment by Wujekklawy** [comment]
https://github.com/AngelArenaAllstars/suggestions/issues/143

**Comment by Wujekklawy** [comment]
@prodigiousking did you saw my posts for bosses?  You seem to seen a lot of people suggestions so meaby some ideas to improve them?

**Comment by Wujekklawy** [comment]
They are #82 #87 #92

**Comment by prodigiousking** [comment]
I want to go to bed rn so i will try to look at them later, tho generally
make sure your description is not in the slightest bit flowery/lore based
or at least seperate the flowery bit from everything else

**Comment by Wujekklawy** [comment]
It's hard when you write for head and on phone what makes it more than hour of writing ;) and i dont have available computer to write properly and try do some corrects ;)

**Comment by l34Um1** [comment]
This heavily encourages toxic behaviour, destroys balance and adds very little value to the game. Closed.
