### ISSUE TITLE
[Boss Encounter]Suppressed Boss

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#148]
# Supressed Boss

## Arena
The arena is divided between two areas. In one (Area A) is the boss, contained by a suppressor of some sort (magic circle? cage? chains?). In the second (Area B) is an NPC, clearly attached to the suppressor. The areas are separated by some kind of barrier which does not impede movement.

## Boss
The boss sits still in the center of Area A, as notated above.

## Phase 1 (100%-80% HP)
Phase 1: The boss has no autoattack, and does not move; it summons small projectiles which move around Area A. If they pass near a hero, they zoom towards them and explode, causing damage. They do not  enter Area B.
It is impossible to attack the boss from Area B, much like trying to attack roshan outside the pit.

## Phase 2 (80%-50% HP)
The boss strikes at the container somehow (electrifying it, setting it aflame, or something else), and the NPC's health starts draining.
Once the NPC dies, the boss starts freeing itself. If no hero steps onto the supressor (and has their health gradually drained as a result), the boss breaks free. It is fast and deals heavy damage, but does not enter Area B. As soon as a hero steps into the supressor, the boss is bound again.
All the while, the projectiles keep being summoned

## Phase 3 (<50% HP)
The boss shatters the barrier between Areas A and B. The projectiles can now go there, as can the boss, and they are increased in number and speed. The boss can now be attacked from Area B.

## Additional Notes
The NPC is supposed to teach the players the mechanic of the suppression and health drain, before the true battle begins. It should last some 20 seconds once phase 2 begins. Attacking it should probably be disabled.

**Comment by Wujekklawy** [comment]
"These are some interesting mechanics. Please focus on them, instead of flavor/lore. For example, instead of saying the boss throws daggers, say it throws projectiles." ;)

**Comment by Haganeko** [comment]
I tried. How would you have me word it, to make it more mechanical? I appreciate the help.

**Comment by lizciz** [comment]
Yes, wording can be difficult I have noticed, but I kind of like this idea :)
Perhaps like this (made some slight modifications as well)?:

Setup:
- Arena is divided in two parts, A and B.
- Boss is imprisoned in A.
- NPC is standing in B.

Phase 1:
- Projectiles are summoned and fly around in A. Will damage players on impact.
- Boss cannot be attacked while standing in B.

Phase 2 (80%):
- Boss tries to break free from prison (preferably audio and visual queue).
- NPC steps on a marked plate, looses a lot of hp but strengthens the boss' prison.

Phase 2.5 (when prison starts breaking again):
- Repeat phase 2, but NPC dies.
- From now on, players must step on the plate to stop boss from escaping

Phase 3 (30% or if prison breaks):
- Boss becomes free, projectiles can fly both in A and B
- Boss starts attacking players?

**Comment by Haganeko** [comment]
Couple of clarifications:
If a projectile passes near a hero, it zeroes in on them (this should reduce the number of stuff spawning, and make positioning even more important).
The NPC (or whoever is standing on the supressor) takes constant DoT - once the NPC is dead, it's one less hero fighting, and taking the projectiles. If no one is standing on it for too long (say, because the one who was there died), the boss breaks free. It is very strong, players will have to scramble to get someone on the supressor.
Phase 3 means the one who is standing in the supressor is now vulnerable. Besides the DoT of supressing the boss, they now also have to tank the projectiles - and they can't move too much to dodge, or the boss will get free.

**Comment by l34Um1** [comment]
This boss worries me. It seems impossible to kill for certain team compositions.

**Comment by Haganeko** [comment]
How so? The team needs to have mobility or tankiness, and be OK with having one less fighter, but so long as they can either kill the boss quickly or have some sustain for their sacrifice, it should work.

**Comment by Haganeko** [comment]
Yeah, this is terrible, It also depends on a particular arena, which is a deprecated concept.
