### ISSUE TITLE
[Boss Encounter] Runaway Boss

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#149]
This boss moves around the boss arena in a pattern, shooting projectiles in its wake. Maybe it is moving backwards and shooting, maybe it is shooting from its back.
Anyone standing directly on the way gets trampled (damaged and stunned).

Phase 1: Simple movement pattern (a circle? at most an 8). Rate of fire is slow.

Phase 2 (80% HP): More complex movement pattern, taken from a pool of two ( Hexagon.png, for example)
![hexagon](https://cloud.githubusercontent.com/assets/25013178/22769267/a6307c6c-ee6e-11e6-9c0d-ae88883e027b.png)
Shooting is faster.

Phase 3 (40% HP): Movement pattern is erratic, changing between a few patterns every now and then (can be comprised of all the earlier ones). Bullet hell.

This boss is supposed to test players' ability to find safe spots from the projectile spray, as well as adapt to changes in pattern quickly. High movement speed, range, and/or tankiness are suggested.

**Comment by Wujekklawy** [comment]
If he is constantly moving and shoting how do you fight with him?

**Comment by Wujekklawy** [comment]
Ps, shooting is not a problem but moving can be big one.

**Comment by Wujekklawy** [comment]
What you say about something like that:

Boss rise himself on summoned structure (pillar or zgiggurat like) in middle of arena. After destroying structure Boss falls down and is stuned. After stun he raise himself again and go to one of phases depending on his life. Boss is constantly incanting while standing on a structure. 

Phase 1 spawns projection of himself. Projection movies in circle on middle of distance between boss and borders of map

Phase 2 (80%) Boss spawns three projections of himself, one of every type, projections move in more complicated patern. One of altars starts glowing, structure cannot be damaged while altair is glowing.

Phase 3 (40%) boss spawns 7 projections, 1 bassic, per 3 or other types. Projecktions move in more complicated paterns.

--------------------------
Short descriptions

Structure, building or object that boss spawn under him to stand on it. Requires to be destroyed to be able to attack Boss. Immune to magic damage.

Altar, structure or object that enables to spawn 2 additional projections, per one Rapid and one Disabler. Activated make structure immune to any attack. Destroyed despawns projections bounded to it. Immune to disables.

Projections:

Units bounded to boss or altars. Disapere when bounded unit is stunned or killed. Immune to any sort of attack. Not targetable.

Types:
Bassic, always bounded to boss, attack in wide long area (damaging similar to invoker meteor). Percent of damage dealt transfer to boss as heal.

Rapid, bounded to Altair

**Comment by Wujekklawy** [comment]
shoots series of projectiles towards enemy ,  evry projectile go in randomed way (width 500max units, attack in cone).

Disabler, bounded to Altar,  have lot of disables, short range,  disables are instant.

**Comment by Wujekklawy** [comment]
Sorry that in 2 comments but i write on phone (still no computer :/) and trying to scroll i pressed button to send

**Comment by Wujekklawy** [comment]
One thing more about disabler, cannot target if used spell on same target earlier than 5 seconds ago. To ballance purposes.

**Comment by Haganeko** [comment]
That's a whole different boss.
It's possible to fight my boss - it doesn't move that fast, and the players can learn the pattern.
But yeah, it's easiest with range.

**Comment by Wujekklawy** [comment]
@Haganeko it's not that different boss, i used same base mechanic that your boss have ;). I tried to balance that movement, in your way if boss move fast (same movment speed like heroes) that will be hard to catch up with he, so fight would be only be long for no reason, if he moves slower than heroes it will be too easy to catch and that he moves would be useless. :| and second thing i wanted make him little more interesting ;)

**Comment by Wujekklawy** [comment]
Ps, if you ask why if he move with speed like heroes is too fast, you catch him up hit once (melee) and he got away, repeat...

**Comment by Haganeko** [comment]
Being hard to catch is the idea - this makes melee'ing it hard, so players will most rely on high mobility, slows, ranged attacks, and spells. If you picked ursa, good luck... the shooting is secondary, as a way to discourage standing still, or chasing the boss around with lycan or the like.
The key would be to read the pattern and anticipate the boss, so as to get attacks in. It won't be that tanky.

**Comment by l34Um1** [comment]
Sick idea. Maybe a bit tough on melees but that depends on his actual speed. Needs a bit of work but can go into the game

Edit: Oops didn't mean to close.
