### ISSUE TITLE
Boss idea. Mid-High tier. The Chained Soul.

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#15]
The idea for a boss, the kit is going to be at the top, with some lore below.

So the main theme for a boss is going to be interaction with the "Chained one".

The boss probably sould just attack between casting spells, even though it probably shouldn't be too painful to tank.
**Spell 1**: When the boss is aggroed ,he casts an instant spell on the one who aggroed the boss and is **_Chaining_** him. The **_Chained_** unit can't walk away too far from the boss as he is chained, always prioritized by the boss  and also has a stacking, unpurgable debuff on him, which shares a small portion of damage taken by the boss with the **_Chained_** target . The debuff is going slowly rise, from small numbers to higher and higher. The **_Chained_** effect can be broken by attacking **the chain** and breaking it, when **the chain** is broken, boss staggers for a 1-2 seconds, then chooses the closest target and **chains** him. The **_Chained_** debuff stops sharing the damage upon breaking, however it still lingers on a target for 20-30 seconds(those numbers are up to balance team and are hard to guess) , so he should wait out the removing of the debuff to tank again.

**Spell 2**: The boss pulls hard on the chain and thus pushes the **Chained one** to himself and stuns him for 1 second, if the **chain** is below 25%  , it breaks stunning the targen previously **chained**, but doesn't pull him.

**Spell 3**: The boss starts a 0.5-1 second cast, which if finishes, deals moderate damage to himself put a 10 seconds debuff on all units in a boss pit 40% damage debuff and 20% damage taken increase.

**Spell 4**: The boss starts the 1 second channel, after which he  heals his chain for 25-35% of it's HP.

**Spell 5**: The boss grabs the chain and pulls the **Chained one** in the air and dropping him hard on the ground , dealing damage to the **Chained one** and everyone around him, stunning every taget hit for 2 seconds and the **Chained one** for 3 seconds. The the **chain** is 30% hp or lower it breaks while the **Chained one** is in the air and instead of hitting the ground he flyes straight untill he hits the terrain where he take a lot of damage and is stunned for 5 seconds.

**Spell 6** When the boss gets below 15% HP , he starts uninterrupteble channel for 2 seconds, after that he chains everyone within the boss pit with **chains** which are easier to kill then the original and the boss no more staggers when the **chains** are being broken. Every other spell also is being casted twice as fast.

**LORE**:
"Insert angelic name here" was a fearsome general in a first war between angels and demons , slaing countless demons and earning endless victories for the angelic counsel. The demonic horde saw him as a thorn in their side, so jailer "Insert sinister demon name here" was tasked to deal with him. "Insert sinister demon name here" ambushed "Insert angelic name here" and his brigade. Even though "Insert angelic name here" fought ferociously he was overwhelmed by demon forces and captured. Instead of killing him "Insert sinister demon name here" decided to use him instead. He asked the keeper of Inferno forge to fuse the very soul of "Insert angelic name here" with darkest of chains, which are to forever be bound to him. After eons of smelting inside the forge , the process was complete, however instead of pure white soul of an angel , what came out was dark soul colored as the blackest of ash, with only intent to force anyone to suffer what it had suffered, so thus The Chained Soul was born.

If anyone read until that part, thank you for your attention and have a nice day.

**Comment by Sixtrings** [comment]
Wouldn't heroes like dazzle and slardar defeat the purpose of this design?

**Comment by Sixtrings** [comment]
Oh, and meepoes

**Comment by Valiens** [comment]
I can see that meepoes are going to be strong against him, but I am not sure how slardar or dazzle are supposed to defeat the purpose of the design.

**Comment by Sixtrings** [comment]
Ok, potentially not dazzle, depending on whether bosses are going to be able to be affected by the debuff. But if the boss is designed to be tough through armor and magic resist means, heroes like slardar take off 20 of that easily, and that's assuming his ult doesn't get buffed. Bristle can also apply a good amount of armor reduction, and a lot of other heroes, so here's the question. How are you going to balance the armor design of this boss to be beatable while also making the sacrifice armor reduction worth while?

**Comment by Valiens** [comment]
Well armor reduction always is the question for every boss figure as long as they are supposed to be hit a lot, why exactly do you think about armor ? I mean it's a fair point but the thing is , the boss doesn't have a single ability which is affected by the armor and even more so, the more you debuff armor of this boss the more damage the Chained unit is going to take, so extreme armor reduction can backfire. And armor problem can be solved by addition of a passive which doesn't allow  armor of the boss to be lowered below some X, this way armor reduction is still going to be effective but not overpowered.

**Comment by warpdragon** [comment]
LOVING this idea. 
* Many of the chain mechanics you need are already in the game (Meathook, Fatal Bonds, Telekinesis, Toss, etc). I'm not sure how you'd make the chain keep people within a certain range, but the code for this _might_ be in the code for pets or maybe Duel.
* Forces multiple heroes to engage/tank/dps
* It's fun and interesting, and requires teamwork

**Comment by Sixtrings** [comment]
Ok, the whole point of debuffing the boss through other means is to remove the necissity of having a Chained unit. Why would I try to debuff him so bad if there's already a Chained unit? Why would I want a Chained unit in the first place then? Armor is important not only because of the effective hp, but also the effectiveness of health regeneration. Sure you can make a passive that forces the armor to be hard locked, but you are just making another creep that Ursa takes longer to kill


________________________________

**Comment by Valiens** [comment]
Well, first of all, there is no necessity in the chained unit to begin with, it is just what is going on while the fight is going on, since **the first unit** who aggroed the boss **will** become **chained** that is not an option and not something that can be avoided. And about Ursa, the idea is that he is not the best hero against that boss, since the boss is not going down very fast and since there is a **Chain** to kill (which shouldn't be possible to ignore ,since otherwise Ursa will just kill the **chained** unit) and that means that there is more then 1 unit to hit, that makes Ursa ,even thou by no means bad against that boss, but not insanely powerful either, at least not more insane then any other boss and since Baumi and developement team is likely to address an issue with Ursa and bosses anyway, I don't belive that every single boss must have a " Kill Ursa when he is near me button" at least not to begin with. If that concept is interesting to anyone and will end up being tested which is already going very much in the future, then if Ursa will become too strong against him there are ways how to counter it. However I am very thankful for your responses, since it is very interesting to hear what  people think of my idea, if you have anything else to add ,please do so and I will try to reply.

**Comment by Valiens** [comment]
Oh, and about programing inability to walk to far away, there is simular skill in Imba, bounty's Q chains you and restricts you from moving too far, so that should be possible Warpdragon.

**Comment by Haganeko** [comment]
Pounce has a "can't move away" mechanic... Nice idea!

**Comment by warpdragon** [comment]
Splendid!

**Comment by l34Um1** [comment]
Again, too complicated. Closed.
