### ISSUE TITLE
[Boss Encounter] Carapace Boss

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#150]
This boss has a carapace of some sort. Could be armor, an exoskeleton... It has a slow turn rate.
The carapace shows some chinks. Hitting the boss from that direction (+/- 5 degrees) automatically crits (so the players know it causes extra damage).

Phase 1: A few chinks (one or two).

Phase 2 (80% HP): Every now and then, one of the chinks will start to glow. After two seconds, it'll release something (energy? acid? shrapnel?) which will deal damage to heroes in a cone (the directions that dealt extra damage)

Phase 3 (30% HP): There are more chinks (three or four), but they spew damage quicker (one second glow) and more frequently.

**Comment by Wujekklawy** [comment]
That would work awesome with mechanical theme, when boss would be a giant machine.

**Comment by l34Um1** [comment]
Yes. Very cool.

**Comment by Haganeko** [comment]
I left it vague, since I didn't want to put too much flavor around. My original concept came from a huge beetle which would spew acid from wounds, but a machine also sounds very cool
