### ISSUE TITLE
[Mechanic] The Tank.

### ISSUE THREAD

**Issue by Tavinqrs** [AngelArenaAllstars/suggestions#151]
Hi, I watched Baumi's video about AAA/AA2 and I had an idea about a boss fight mechanic. It would involve the ability to manipulate aggro differently than Dota 2 current way. It would force (like an Axe's taunt) boss enemies to attack a specific hero (The Tank). It shouldn't be in a way so that a team is required to have someone build The Tank or get rekt, but doing so would make the boss fights easier. The way I thought was to make the boss attack the one hero who is currently doing the most damage to him (I don't know if this is possible in Dota 2). In that way, if someone goes for a pure damage build, he will eventually get in the boss's crosshairs and will be destroyed. But, it is still possible that he could tank those hits by lifestealing away and so on. Now, the tank bit. I thought about vinculating with tank itens a sort of passive ability that, when the wielder deals damage to a boss, the boss gets charges. While he has those charges, it will attack the owner of the item. When he takes damage from other sourcers, he loses charges. When the charges are gone, the boss will behave like before, focusing the one hero that is dealing the most damage. It's probably waaaay too hard to implement this, and maybe it wont even work at all like this, but the idea of having someone build tank to make boss fights easier seems fun.

**Comment by yommi1999** [comment]
The threat system from epic boss fight?

**Comment by Tavinqrs** [comment]
I dont know this system, how does it work?

**Comment by l34Um1** [comment]
Manipulating aggro will be a thing although we haven't settled how to do it exactly yet. Closed.
