### ISSUE TITLE
Boss Recommendation: The Wandering Swordsman

### ISSUE THREAD

**Issue by dekardellion** [AngelArenaAllstars/suggestions#153]
The Wandering Swordsman's main graphical detail is that the boss has a Katana weapon, and wears a Sakkat( Also known as: Asian conical hat, Farmer's hat, or Asian rice hat) but that's really just optional.

![wandering sword](https://cloud.githubusercontent.com/assets/25660574/22780907/56d13af2-eefb-11e6-941f-7149912d7863.jpg)

note: The abilities' properties will change depending on the boss's hp: 
                     76% & above / 75%-51% / 50%-26% / 25% & below
Abilities:
1.) Phantasm: The boss will disappear for 0.75 seconds then create a circular formation of 2/3/4/5 illusions and the boss which will all face the circular formation's midpoint, each illusion will slightly look different from the boss. During this phase a player must attack the boss using a right-click attack, If a player attacks the correct boss then the illusions will disappear leaving the boss, If a player attacks an illusion or nobody acts for 10 seconds then the illusions will stay and attack the players for a duration of 20 seconds and if there are still any illusions remaining these illusions will gain a damage and health boost.

2.) Slice Dash: The boss will perform a taunt pointing it's weapon at a target player, when the taunt is finished the boss will dash at a straight line towards the target player 1/2/3/4 times.

3.) Multiple Strikes: The boss attacks 3/4/5/6 times in quick succession on a cone area to the front of the boss.

**Comment by l34Um1** [comment]
Uninteresting. Closed.
