### ISSUE TITLE
Boss Recommendation: Tarrasque

### ISSUE THREAD

**Issue by dekardellion** [AngelArenaAllstars/suggestions#154]
Based on Starcraft's Ultralisk Torrasque strain, and Dungeons and Dragons' Tarrasque.

![tarrasque](https://cloud.githubusercontent.com/assets/25660574/22781748/e710ed58-eefe-11e6-94e0-a075118df3ea.jpg)

Note: The boss has 2 health bars, one for the boss itself and one for it's "egg mode".
Abilities:
1.) (Quasi)Immortality:  When the boss "dies" it enters "egg mode" for 10 seconds being unable to act and permanently losing hp for it's egg mode. After 10 seconds the boss will resurrect with full health until the egg loses all it's hp effectively killing the Tarrasque.

2.) Burrowstrike: The boss disappears for 3 seconds and warns an area on top of a player, after 3 seconds the boss will reappear on the area and deal damage to all players in that area.

3.) Roar: The boss will deal damage, stun, and knock-back all players in a cone area infront of the boss (with warning ofc).

**Comment by zelding** [comment]
the egg mechanic is interesting

**Comment by l34Um1** [comment]
Egg seems like a hastle. Especially towards the later stages you would be spending most of your time just waiting for the egg to be done. Closed.
