### ISSUE TITLE
[Hero Idea] Become Boss Ranged Assassins

### ISSUE THREAD

**Issue by stew0709** [AngelArenaAllstars/suggestions#155]
Concept: The idea of becoming one of the bosses would be cool, so I thought that after defeating the Ranged Assassins you could walk into its escape portal and become one of the boss members. The hero's skills are based on the actual boss fight and the fighting style its using is long ranged skill combat, squad members, and different types of arrows to immobilize and shoot down the enemy.

Q - **Machine Gun Arrows**: Target a direction to channel, firing a barrage of arrows over the duration hitting the first enemy they touch. Consumes mana per arrow fired. Each arrow deals damage plus a % of your add/base damage in Physical Damage. Activate mid-channel to turn toward your cursor while firing allowing you to rotate. https://www.youtube.com/watch?v=pKSEM63cS3A

W - **HON's Forsaken Archer Stun**: Fires a volley of arrows that lands in target area after a duration. Deals damage and immobilizes/stuns targets in radius for a duration on impact. (This ability has no cast time, and can be cast without interrupting your other orders.) [This will allow you to have Q on and then shoot W. Thematically, summon a squad member to shoot the volley for you] https://www.youtube.com/watch?v=oUn20hcd3qI

E - **_Precision targeting_** - Passively grants your Hero a % chance to fire a damage arrow at enemies that slows their movement speed by a % for a duration whenever they deal non-DoT damage. (Meant to work with Q) This chance is doubled if the target is stunned/rooted. (Meant to work with W)

or

E - **Scatter Shot Arrows**: Does a quick 360 spins and shoots Mirana Arrows in all directions [2:15] or shoots in a cone in front [2:04]. (Deals damage and greatly slowing)
https://www.youtube.com/watch?v=2Msz2JFR4Fc

R - **_Triangle of death:_** Target an area with your triangle cursor. Teleport to one of the triangle points at random with the other points summoning illusions. Then after a duration, the ability detonated and does massive magic damage and stuns in an AOE. Illusions stay around for a duration and have 100% of damage and take 100% of damage. [thematically this can be like you called in your squad mates for help]
![image](https://cloud.githubusercontent.com/assets/25628508/22774049/49264c86-ee73-11e6-9602-63d797c128cb.png)

**Inspired by [Boss Encounter] Ranged Assassins - Bosses Can Hit Each Other:** https://github.com/AngelArenaAllstars/suggestions/issues/125

**Comment by l34Um1** [comment]
Doesn't work for the pace of our game. Closed.

**Comment by stew0709** [comment]
Cool. This hero was an offshoot of an idea I posted. I like the idea of transforming and fighting as the bosses you beat. **[Boss Encounter] Ranged Assassins - Bosses Can Hit Each Other: #125** I would appreciate some feedback.
