### ISSUE TITLE
[Item] Hurricane Pike sidegrade

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#156]
> Disclaimer: the original idea belongs to an other user, whom I had a conversation on a slightly different item, but he deleted the suggestion; it was #129

Builds from:
 - Force staff
 - some mid-tier damage item, like javelin or claymore
 - recipe?

Stats should be around the sum of the bonuses that the components give.

**Acive**: Untargeted, always acts on user.
Pushes you backwards (the opposite direction you are facing), and gives you bonus attack damage for a short time, and for a predefined attacks (Like Ursa Empower). 
For example: the buff stays for 5 seconds or 2 attacks.

Notes:
I think it should push you farther that the original force staff, somewhere between 400 (the original) and hurricane pikes effective distance (which is 2x400?). This way it is better for traveling, and somewhat decent when you just want to get away from a melee hero.
It would also benefit heroes who can use the buff without consuming it. (I can't think of any)
The more I think of it, the more I want to try it with PA.

**Comment by szyjan** [comment]
No i have not deleted it O_o

**Comment by zelding** [comment]
well someone did.
it should be #129 but it doesn't exists

**Comment by zelding** [comment]
now it decided to work again, github is on crack

**Comment by szyjan** [comment]
ohh nevermind I'm just bored as hell in work

**Comment by zelding** [comment]
me2 :D

**Comment by Wujekklawy** [comment]
That "pushing you backwards" can be unnoing, very unnoing, if you want to use it you need to turn back to enemy, use it and turn back again because enemy is behind you. Now imagine that enemy have Batrider.

**Comment by VoidsKeeper** [comment]
Sounds like an interesting concept. Preferably would be used as an upgrade to the normal hurricane pike. Could also be used as an upgrade for one of the higher tiers of the hurricane pike

**Comment by VoidsKeeper** [comment]
Thanks for the commitment

**Comment by lizciz** [comment]
Another possibility for a Force staff variant, would be one that acts as Magnus' charge, i.e. you bring other players along with you if they are in your way. Allies? Enemies? Both?

**Comment by VoidsKeeper** [comment]
^ that sounds interesting

**Comment by l34Um1** [comment]
We have plenty of Force Staff upgrades atm. Closed.
