### ISSUE TITLE
Boss idea

### ISSUE THREAD

**Issue by Oliverphj** [AngelArenaAllstars/suggestions#157]
A simple suggestion for a boss idea,
the boss has 2 phases which it switches between, 
phase 1: immune to magic damage, heals for a portion of magic damage done to it.
phase 2: immune to physical damage, heals for a proportion of physical damage done.
some sort of visual indicator for each state e.g color change

does normal attacks with some aoe that can be prevented,e.g by stuns 
the aoe attacks are of the type it is currently immune to, it also hits itself with those attacks healing itself, if they are not prevented

**Comment by zelding** [comment]
How would you telegraph physical immunity? Keep in mind, that the bosses abilities _have to be_ self-explanatory. Players have to be able to tell what is going on without looking at the abilities them self.

Also the attacks have to be easily recognizable, like a Tiny toss, with more delay in the impact and with a shadow on the impact area.

Magic immunity  is easy, just a BKB effect.

Otherwise I think this could be a decent Tier 1 boss.

**Comment by stew0709** [comment]
I agree this is an interesting idea, very similar to one I posted, but mine doesn't make the boss immune. Instead, it swings between extremely high armor to extremely high spell resistance (and visa versa). https://github.com/AngelArenaAllstars/suggestions/issues/122 I like the touch you added about having the boss heal from the damage they are immune to. It's a clear indication to the player that they are doing something wrong.

For the Physical Immunity, the Ethereal Blade sound and effect (Necrophos ability) should be enough to hint to plays that something has changed. Another suggestion is the Barbed Armor effect.

**Comment by szyjan** [comment]
Does resistance can be set above 100% by code? If so, there is no need to magic immunity, attack immunity, just switch of resistance states (f.e. Red glow - Phys. REs., Blue glow - Mag. Res.). I think it would be possible by setting those to around 110-120% ressistance - wasn't something like this possible in nyx build with fountain camping (Bristleback, burrow, and that spectre thingy) ?

**Comment by Wujekklawy** [comment]
Soo... you want Gabriel Belmont apere in game?

**Comment by szyjan** [comment]
Man, it's like destiny, because I've just started playing LoS few days ago :) I don't know if my subconcious threw me that idea, but idea repeats itself in many games. I's one of most obvious ways for creator to point player that boss is in some state

**Comment by l34Um1** [comment]
Idea noted for futher discussion. Closed.
