### ISSUE TITLE
[BOSS IDEA] Zen Beast

### ISSUE THREAD

**Issue by kerorol** [AngelArenaAllstars/suggestions#158]
The zen beast is a melee boss basically just deals regular right click damage. 

Abilities:
1) Punishing Aura- A debuff Aoe very much like Pitlord that reduce & soak up heroes damage as well as suppress heroes normal hp regeneration but not from items or heroes' abilities. Hero died within the AOE will significantly increase the boss's damage.

2) Magic Immune - Obviously not taking any magical damage.

3) Great claw - Swing his claw in front of it dealing a huge damage to heroes in the aoe everytime he receive a certain amount of damage (don't know how much). Of course the cast animation can seen 2s or 3s earlier but cannot be interrupted.

4) Zen Mode - Everytime the boss reach 50℅ hp, it will summon two of his minimis and make himself into zen mode(much like a stone or statue form). During zen mode the boss will not be taking any damage from heroes and regenerate hp until full. Zen mode is interrupted once the two minimis have been killed. After zen mode, the boss is clear from any debuff applied. This ability has cooldown ticks (maybe 20s or 25s).

The minimis - physically identical to beast but smaller and weaker (less hp and armor).
1st minimis - running around leaving a toxic trail that does dps to heroes as well as slows movement speed.
2nd minimis - shoot rocks at random places within an aoe with visible shadow on where it will land. The interval of rock shooting is 1s and takes 4-5s to land. Hero hit with the rock will be stunned for 1.2s. Shooting projectile cannot be interrupted.

Both minimis have the ability of 70℅ magic resistance.

That is my boss idea. Feel free to criticize or add up anything for betterment. All the numbers mentioned are not precisely measured though.

**Comment by prodigiousking** [comment]
I like the zen mode idea

**Comment by zelding** [comment]
The Zen mode sounds interesting, but right-click enemies are boring.

**Comment by kerorol** [comment]
The reason why i didn't come up with flashy type of attack is because of the zen mode itself. It is too much of a hustle to fight a boss that deals damage with a lot of spells at the same time have time for healing himself.

Usually a boss with a lot of casting spells have it's cooldown time where it is vulnerable to be attacked. This contradict with the zen idea where it heals and invincible during that period.

I think the fun part of this boss is getting around those two minions in order to interrupt the boss zen mode.

**Comment by prodigiousking** [comment]
Lol then it would be the Dark Magus from the event

**Comment by szyjan** [comment]
About Zen mode.
Do you want it to just trigger at 50% of full hp? Or 1/2, 1/4, 1/8 so on?
And amount of health regenerated should be drasticly lower than it is available to receive in cooldown period, otherwise it will be annoying as hell. I would think minimis about something like chicken from darkmoon that runs around like crazy.

**Comment by kerorol** [comment]
The triggering point for zen mode is up to balancing it. The annoyance with CD wont matter if the measurements are spot on with boss timing and/or heroes level. I dont mind if it will have CD or just based on remaining hp (1/2, 1/4, 1/8). Whichever better is fine.

And yeah i also imagine the 1st minimi would move as fast as the chicken in dark moon while the other move a bit slower since it can stun people.

**Comment by kerorol** [comment]
Ok, here is my improvisation of the boss since @zelding mentioned that right click boss is boring.

The boss does not do any right click damage anymore. Instead it shoot boulders and fire. And it can change places inside 'the pit' after it finish casting its ability.

Abilities:

1) Ancient boulders - Shoot boulders in a pattern with shadow indicating projectiles across the pit ( boss arena). The pattern is randomized (provides 3-5 types of pattern). The cast cannot be interrupted and each cast will shoot 10-15 boulders simultaneously. Each boulder hit will deal physical damage and 4s stun. (The ability can be dodge that is why it is severe when got hit).

2) Firesplinter- The boss swing its tail creating a small/medium aoe of fire pit that deals dps. Heroes got hit directly from the splinter get greater damage. It is an area targeting spell. The boss will target the area of hero that deals the greatest damage to him.

3) Punishing aura - Passive aura where the boss will greatly soak up the damage in an aoe surrounding it (Pretty much to f*cked up melee heroes only). This ability is disengage during the zen mode.

4) Zen Mode - Everytime the boss reach 50℅ hp, it will summon two of his minimis and make himself into zen mode(much like a stone or statue form). During zen mode the boss regenerates hp until full at a substantial speed but can be attacked by heroes. Zen mode is over once the two minimis have been killed or the boss is fully heal. After zen mode, the boss is clear from any debuff applied. This ability has cooldown ticks. ( it is better to have CD rather than hp phase trigger since it will be more variety in each fight. The longer it takes, more frequent the boss will use zen mode).

For minimis, both will run around the pit only that the 1st minimi is much faster.

1st minimi's ability: 
Blinding lazer- A casting point where it shoot a  lazer (similar like tinker's) at random hero at interval of time causing the targeted hero to be blind and miss the attack.

2nd minimi's ability:
March of machine -  a channelling cast similar like tinker. Can be interrupted.

And much like roshan, the boss and minimis have a percentage of natural magic resistance. No longer magic immune. About the abuse of scythe of vyse and silence, i dunno how to counter it. Maybe nullified it perhaps.

**Comment by l34Um1** [comment]
Punishing Aura is pointless. I like the rest though. How does this boss work with phases and what mechanic could we use for an item?

**Comment by kerorol** [comment]
The concept of the boss fight is basically about teamwork. The mechanic could be used are the defensive items like linken, shivas, lotus and blademail. These item are needed for destroying the minimis faster. So two or more heroes should always be ready to cast on the damage dealer heroes. Or implement mana on the minimis so that mana drain option is available.

For the boss is probably bash to stop its movement since it will cast spell once  or twice everytime it has moved. Debuff like deso, cuirass could also be used but not casting point debuff like solar crest. (Too OP)

My thought on the punishing aura is to avoid from heroes tanking the hit and keep hitting the boss. I can see why it's pointless since the boss can move around and his attack can stun which require everybody to move around. My bad, just discard it.

Regarding boss phases, I didnt come up with phases since i've seen so many boss suggestions with phases. So why not this one is a little bit different. The only phase it has just the zen mode trigger when its hp reach 50℅.

If you insist on phase implementation, i would suggest like summoning more minimis or make one of them magic immune or so.

**Comment by Haganeko** [comment]
This is essentially a DPS gate (can you get the boss low enough during the cooldown of its stone form?). Closed.
