### ISSUE TITLE
[Item] Shivas + Drumms

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#159]
**Passive aura**:
MS/AS to allies

**Active**: 
Damage, Slow and -AS to enemies - as Shivas do

**Comment by VoidsKeeper** [comment]
Heh , you were a week too late 😅 . We already have a very similar idea.

**Comment by VoidsKeeper** [comment]
But thank you for your commitment

**Comment by zelding** [comment]
I've added it to my "already approved list" :smiley_cat:
