### ISSUE TITLE
Boss Idea.High tier. The Caged Monstrocity

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#16]
The main theme for that boss is that , even tho he is in the boss pit, he is not ready to fight , you will have to work towards making him fight you through different stages. Lore will be below kit.

The boss himself wil be trapped in a  soul shard and is being  guarded. When you come in the pit in the first place it is divided in 2 halves, in the first half where you come in the mini boss, the holy guardian is standing with the barrier of light behind him, he is equiped with the shield of his size and a giant hamme wielded by him in 1 hand. In order to break the barier and get to the actuall boss you need to defeat the guardian himself first.

**The Guardian** is not pushover himself , he is tanky boss with defensive abilities and a lot of additional creeps being spawned.

**Phase 1** of the **Guardian**:  
**Spell 1**: Each X seconds( up to balancing, hard to tell exact numbers) reinforcements are  summoned which consist of  2 angelic solders( beefy creeps with 10% damage resistance aura which doesn't affect themseves), 2 angelic marksmen (ranged creeps with 10% bonus damage aura) and 1 angelic priest who uses straight line skillshot which heals all friendly targets hit and damages all enemy target hit.

**Spell 2**:  1.5 seconds channel after which boss gives shields ,which are equally shared between all friendly units. So if the creeps which boss summons are all fully cleared , then the boss is going to get a bigger shield.
**Spell 3**: The boss channels for 10 seconds and puts a large frontal barrier in front of himself, which decreases all damage from that direction by 90%. So if you still want to deal damage to boss or creeps behind the barrier, you will have to walk around it.
**Spell 4**: The boss burns with holy fire,channeling for 2 seconds and after empowering his next 5 attacks to deal large cleave in front of him and knocking all targers hit away.

So the **Guardian** is supposed to be just a **1st phase** of this fight, after you beat him , you see a dark crystal levitating in the air with 3 support pillars under it. 

The **2nd phase** is to break **_the pillars_** under the crystal. The crystal is a prison for the demonic monstrocity and it is not powerful enough to completely seal off dark energy of the beast, so after you broke the sealing barier set up by the angels , the dark energy started to seep through, which condenses into **_Dark elementals_** under the crystal. Usually the  support pillars are 99% immune to damage and in order to damage then you need to lead **_Dark elementals_** under the pillar and kill them there . When **_Dark elemental_** dies he dissoves into a pool on the ground and everything in the pool takes additional damage, pillars included. After 10 seconds the **_Dark elementals_** reshape again.
When **_1st pillar_** is destroyed the crystal starts to crack and hence more **_Dark elementals_** escape and also they get an ability that heals **_Dark elementals_** if they stand in the pool left by other dead **_Dark elementals_** . When **_2nd pillar_** is destroyed even more **_Dark elementals_** spawn and get a spell, where every once in a while they can charge some distance in front of them knocking in the air every enemy hit for 1 second.

When the **_last pillar_** is broken the crystal shatters and all dark energy escapes, all **_Dark elementals_** condenses into one **_Monstrocity_** which is the final boss for **phase 3**.

**Spell 1**: The boss , every 10% of his health which he loses, leaves a pool under him, which slowly spreads out. When boss stands in the pool he heals %health each seconds and deals 50% more damage with every spell, players are taking large DoT and are slowed when standing in the pool.
**Spell 2**: Every auto attack , the boss bites the taget and spread corruption on them, which dissolves armor. Every auto attack % of target's armor get reduced for a minute, stacks, each 20 stacks the target starts to slowly flee in terror for 2 seconds, slowly moving away from the boss.
**Spell 3**: The boss is using its corrosive breath in a large area in front of it, channeling for 5 seconds, dealing large physical damage each second and applying corruption stack each second on the targets hit.
**Spell 4**:  The boss picks up a target and starts chewing on it for 4 seconds. While boss is chanelling this spell, he can't be interupted , applys stack of corruption each second and deals a large physical damage each second, the chewed targer is stunned for the duration , you can't be purged out of it. After the duration ends the target is spitted away ,  in the pont of landing additional damage is dealt and everyone in it gets 2 stacks of corruption.
**Spell 5**: After the boss is lowered below 20% HP, he goes into frenzy, starts bleeding and leaving a trail of black pool behind it, gets 50% Attack speed increase 100% damage increase but also take 50% more damage.

So that is practicly it, the boss with 3 completely different stages, I will include lore below, but I am not sure how it is going to fit in the setting which is used in AA AS.

**LORE**:
Deep down in the darkest corners of everburning hell, something born from the worst nightmares lives. The creature of horror and terror, none can stand in front of it bravely and every brave soul ends up runing in terror. Even the demon lord himself was not sure in his ability to tame the monstrocity however he could set its tacks on the angel armies, so he did just that. When first seen by the angelic forces , they were pertified by the horror and were slaughtered. The angelic court tried their best to despose of the beast but all their attempts were destined to failure. Only defeat afer defeat after defeat they finally decided to go for the last resort, prepared for the demon lord himself , the Soul prison, powerful artifact forged in the light of Heaven and souls of many angels. After clutch victory, the angelic army even tough wiped out managed to seal the beast. Since then the unnamed guardian stand by it, because if he will be gone, even prayers are not going to help us.

If you are still reading this disgstingly long suggestion, then thank you for your attention and have a good day.

**Comment by l34Um1** [comment]
Too complicated. Closed.
