### ISSUE TITLE
[BOSS IDEA] Ocean Master or Wave Master or something

### ISSUE THREAD

**Issue by Chewy316** [AngelArenaAllstars/suggestions#161]
QUICK CHARACTER DETAILS
He/she likes waves, he/she does not like people. DONE. Make him look like clinkz cause he is my favourite.

CHARACTER ATTACKS
Phase one. The boss will shoot out a wave (tidehunter water gush with ags) that deals damage and pushes enemies away and every third wave instead is a circular wave (AOE around the boss) with less range but more damage and knockback. (To battle you must dodge waves and attack the boss, but the third wave forces the heroes to stepback, the repeat)
Phase two. Kunkka torrents are spawned around the arena dealing the same effect but have massive damage. (Image the bosses that shoot meteors or something and you need to dodge them). The boss is also consistently using the AOE wave. This means he can not be hurt by melee during that time. The Boss will be in Phase one most of the battle but when he gets to 25/50/75% health he changes to phase two forcing players to dodge the torrents for about 10-15 seconds. 

NOTES
-The boss its self does little to no movement.
-The waves and torrents should also have the highlighted area to show where they will be. 
-The waves and torrents could have other effects such as movement speed slows or armour reduction
-The boss could also have a normal right click to make him more effective. 

JUST FOR FUN
When he gets to 5% health he shoots out a massive wave that covers the whole map and acts like engmas black hole, swirling the heroes around, not dealing damage but slowing movement speed. Hitting an ally would deal massive damage. (If two heroes come into a close range they take damage)
He/she could also have a movement mechanism where the boss surfs on a high speed wave around the arena. Being hit by the wave causes damage, movement speed slow and heals the boss. He is also unable to be hit by attacks while like this. This could be a activated if the boss takes more then 10% of health in a short time (2-5 seconds)

**Comment by l34Um1** [comment]
I am not a fan, sorry. Closed
