### ISSUE TITLE
[BOSS IDEA] aura damage boss

### ISSUE THREAD

**Issue by angron1375** [AngelArenaAllstars/suggestions#164]
No idea what to call this but I'll give it a shot. Basically, the boss has an auto attack that does 0 damage but has 100% chance to do a small aoe bash (so that melee characters behind the boss are not hit). It has the capability to permabash anyone within its area of effect.
The boss's damage comes in the form of an aura that deals heavy damage to a portion of the arena (big enough that no hero can our range the aura). 
The general idea of the boss is that it requires some amount of teamwork. The boss must be stunned periodically so you can switch out the person who is essentially permastunned in from of him before he dies to the aura. At this point, they can leave the aura to heal up (if you wanted to keep it quick you could give te boss a second percentage based regen aura that affected the entire boss zone but was canceled by the damage aura.
The team basically has to cycle to prevent the boss from rampaging and stunning the whole team while also killing it quick enough that they lose to attrition.  As the boss gets to lower levels of health you could add other effects like silence, blind, break etc. to the aura, though this would make it far more technical of a fight since you would eventually lose your ability to stun the boss at all.
Its counter-play is built around organization and movement without having too many difficult to understand mechanics. If I failed to explain something and you're curious feel free to ask.

**Comment by Wujekklawy** [comment]
Interesting idea but baumi is against bosses that are gambling and chance to permbash whole team is kind of it.

**Comment by angron1375** [comment]
The aoe is small (~250) and only prevents more than one unit being directly in front of the boss to split aggro. The bash would never affect the rest of the team unless they got too close.

**Comment by l34Um1** [comment]
Permastun is uninteresting, closed.
