### ISSUE TITLE
Boss Mechanic - Stat Steal

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/suggestions#165]
# Boss Mechanic - Stat Steal

## Stat steal
Basically Undying's Decay, but three seperate abilities, each steals a type of Stat from players in an AOE (for, say, 45 seconds on a 10 second cooldown). Ability is telegraphed to allow dodging.
* Steal Intelligence (reduces cooldowns of boss's damaging abilities)
* Steal Strength (gives boss hp/hp regen)
* Steal Agility (gives boss attack damage and armor)

## Steal your stats back
Players cooperate to attack the boss in order to get the stolen stats back.
* Return Intelligence (intelligence will be returned when players deal enough spell-damage against the boss)
* Return Strength (strength will be returned when players take enough damage)
* Return Agility (agility will be returned when players deal enough attack-damage to the boss)

## Teach the players the pattern
The Boss has 3 abilities with visual indicators designed to show players his "weaknesses".
* Magic Shield - Similar to linkens. This sphere is BLUE, once broken the boss takes significantly more magic damage. In most cases, the damgae will be enough to proc the "intelligence return".
* Slam Weapon - Difficult to dodge. His weapon glows RED, the slam deals significant damage. In most cases, the damage is enough to proc the "strength return".
* Frontal Shield - Boss is holding a shield in front of him. If attacked from behind, the shield will glow GREEN. Boss takes significantly more physical damage from behind, enough to proc the "agility return".

**Comment by l34Um1** [comment]
There isn't enough here for an actual fight. Closed for now. Feel free to repost when you have a bit more.
