### ISSUE TITLE
Hero Idea, Name: V2 ( name/lore is work in progress)

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#167]
I know we arn't at heros yet but i just wanted to put this here so I wouldnt forget. Close it if you want I will reopen later.
 Other notes: I really need help balancing numbers and talents, as well as coming up with better lore if anyone wants to help.

 Stats: 
Primary Attribute: Int
Base Health: 500
Base armor: 4
Base Attack: 35
Base Range: 475
Base Strength: 20.          Str.Gain: 1.9
Base Agility: 20.             Agi.Gain: 1.9
Base Intelligence: 20.    Int.Gain:  2.4
Standard for everything other stat

1rst ability: Wave Dance
Dash to target area quickly wile letting out 2 attacks to the closest unit
range 100/200/300/400, cooldown 20/15/10/6

2nd ability: Morph Damage (toggle)
Morph a portion of your physical damage into magic damage(right click and other sources)
Mana per second 50/65/80/95
Maximum % 25/50/75/100
Speed (%/s) 2/5/7/10

Hidden ability: Reverse Morph (like morphling it reverses the previous ability and shares the %/s upgrade and mana/s)

3rd ability: Breaching Wave
a medium speed aoe circular wave  originates from the hero and travels to the maximum range applies a slow and a debuff that lasts 8 seconds and reduces armor and magic resistance

range 150/200/250/300
slow% 5/10/15/20
armor reduction 3/5/7/10
magic resist reduction % 10/20/30/40

4th/ultimate ability: Tidal Strike
fires a thin aoe shot in a straight line (windrunners powershot) that does physical damage(affected by morph damage ability)
Damage 200/300/400
Range    800/900/1000

Talents: 
+ 20% mana regen/+ 200 health
+ 200 attack range/ + 35 damage
+ 15% Lifesteal/ + 8 all stats
+ 300 cast range/ Max movement speed

Other/lore: So this is a hybrid of a hero from another game and morphling so idk how unique it is which might be its killing point, but i think it is interesting enough as a hybrid damage semi carry that isnt too tanky, has good mobility/chasing skills, and is an adaptable source of damage. I didn't really have lore in mind while creating it but i thought since it is similar to morphling I could use that to my advantage so here I go.
After Experiment 1 went haywire the Midigurshian, a sentient race of lifeforms with a knack for science, forced a group of their scientists to send experiment 1 to the far edges of the galaxy in an asteroid and cease their research. Upset with his creations banishment, Klyaxos, a particularly insidious researcher, stole away with a single cell from experiment 1. Night after night Klyaxos toiled in his own lab, desperately trying to recreate the semi-sentient creature from before to no avail.Years went by and noone saw or heard of the old reasearcher, until one night the townsfolk woke up to Kylaxos's lab exploding. The Goo had bonded with Kylaxos! The now monsterous scientist slew many Midigurshians on his way to the asteroid cannon where it launched of in search of its first creation. 
Well that was sorta fun. Pretty much it is a green morphling that is slightly taller and has 4 tentacles instead of arms. If anyone wants to make better lore I have no problem.

**Comment by l34Um1** [comment]
Closed to keep the github clean. Repost it when we are doing heroes.

**Comment by prodigiousking** [comment]
Understood
