### ISSUE TITLE
Boss Idea, Gold Miner

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#169]
This is not an original idea it is from another game but i like it as it gives another objective. 

Basically there is a simple boss that is not to difficult to kill in the center, I imagined he would have basic attacks and one simple close range aoe slam but really it could be any boss. The important thing comes when you defeat the boss. Instead of dying the boss is captured and while captured the boss gives your team additional gold per second and is considered an allied neutral( he will aggro onto enemies in the area).The other team would want to capture him so you dont get the additional gold per second and so they get the benifit meaning it would almost always be an objective/ important aspect of the game and would force a bit of action early on. 

Alternatively instead of gold per second the boss can actually compile gold and distribute it to your team after 5 minute intervals. If the opposing team captures the boss they get whatever gold was stored up and then the boss starts compiling for them. This is truer to the other games mechanic which is a downside, but it prevents the boss from being to large of an objective where the opposing team would need to recapture it immediately

**Comment by l34Um1** [comment]
Interesting but would impact the game too much. Closed.
