### ISSUE TITLE
Double Character Boss idea

### ISSUE THREAD

**Issue by Sixtrings** [AngelArenaAllstars/suggestions#17]
An idea for the two charater boss: 
Phase 1, there's a giant angel floating in the middle of the arena, with an aura that reduces the damage that you deal based on a percentage. This percentage increases over time. It does not auto attack, but any damage you deal to this boss is reflected 100% via hp removal. The only way to stop this reflection is if the team hits the boss from four sides, which gives a window of opportunity to really deal damage to the boss without consequence.
Phase 2: Once the boss is at about 75% hp, he will stop the channel, say something, and another boss pops up. The old boss attacks the new boss and is going to be the main source of damage. You can still attack the new boss, but the new boss reflects more than 100% damage. Minions are going to spawn around the map, trying to swarm the old Boss. So the main objective is to clear out the minions.

**Comment by warpdragon** [comment]
So the old boss is a bad guy. Then the "true" evil shows up (new boss), and you team up with the old boss. Meanwhile the new boss's minions try and kill the old boss? If I understand this correctly I'm all about it.

**Comment by Sixtrings** [comment]
Yes. Old boss helps a lot in killing the new boss.


________________________________

**Comment by l34Um1** [comment]
Don't like it. Closed.
