### ISSUE TITLE
[Boss Idea] Illusionist

### ISSUE THREAD

**Issue by Sanshoo** [AngelArenaAllstars/suggestions#171]
The premise of this boss is that he summons special illusions. These illusions deal and take 100% of the damage, but when they get targetted they disappear. So it wont work if you try to aoe them down, you have to use single target spells or basic attacks to make them go away.
I haven´t decided upon phases or specific attacks or anything like that, but i wanted to throw the idea out anyway. Some abillities of the boss could be he blinking away and summoning an illusion to replace him, or doing something similar to phantom lancer´s W, or spawning illusions of the players.

**Comment by l34Um1** [comment]
This is too little for me to have anything to work with. Closed.
