### ISSUE TITLE
Frost demon[boss]

### ISSUE THREAD

**Issue by erklp** [AngelArenaAllstars/suggestions#172]
A simple ice based boss
## core mechanic
The boss has an aura, that adds stackable debuff to every affected hero over time.
Each instance of the debuff deals very small, but pure DPS.
Heroes gain stacks faster with each one they allready have. Stacks don't run off, but are instantly purged, when the hero is not affected by the aura.
We end up with an ability, that is not dangerous at first, but can rapidly scale and do a lot of damage if not carefully  played around.
## First phase
I call this one a learning phase
It's not long and very easy(100%-90%health). It's only purpose is to teach new players the core mechanics of the boss.
Boss is stationary.
When players first walk inside the arena, the boss casts a spell on them ( aoe works like bigger gust and will apply a frostbite-like spell on players hit by it (we need to teach players the cast animation of this spell, since he will use it later on. Rest of the phase is normal right click boss, that gives player time to mess around with his aura.
## second phase
Boss purges himself at the start (ursa would be too good otherwise) 
He moves slowly
He gains 3 new abilities:
-arctic winds: 
adds some debuff stacks to all players in aura range(speed things up a bit)
-winters command: 
chooses a player and a point in the arena. Chosen player is disarmed and silenced, until he stands on that point, then the effect disappeares. There can be only one curse at a time
-frost strike:
 A strong single target nuke. Damage gets reduced with each nearby ally.
(Players have to back off to purge aura, but also group up to negate frost strike damage)
## third phase
Second phase follow up
+1 ability:
-snow swipe: that frostbite gust spell from first phase
(An unlucky root can be devastating)
## final phase
Boss moves faster and prioritizes keeping players in aura range
uses only 3 spells:
-snow swipe
-circle of frost: aoe spell, that applies root and some aura debuff stacks
-cold pact:channeled:while chanelling, the boss slowly purges aura debuff stacks from players, healing himself and damaging players for each stack purged

(The boss tries to get as much stacks as possible with roots and then deals big damage with cold pact)

**Comment by l34Um1** [comment]
I find the base idea interesting and worth exploring, I however do not like your implementation. Closed but if you want to try again feel free. Either way I'll discuss it with the team at the next meeting.
