### ISSUE TITLE
[Boss Idea] 

### ISSUE THREAD

**Issue by GrandShinobi** [AngelArenaAllstars/suggestions#173]
The boss uses a heal mechanic which can be "abused" by the team to their advantage 

Boss Ability:
As boss is engaged it will summon a few structures a few good lengths from its position. These structures will have a clear line linking to the boss to make it understandable to the players.  Every second the boss is healed by the pulse coming from the structures, the pulse speed is very slow and steady much slower than the Magnus first ability ( for reference). This naturally makes the boss tanky. However players are able to intercept these heal pulses by standing on it healing themselves and denying the heal from the boss. The boss may do cleave or single target (both are fine I believe).

Recommendations: 
The boss is a 10-20min killable boss.
The boss should be a medium health pool boss with a medium to high damage output. The heal should negate most of the damage. Stuctures are not huge but relatively small. Shrines in dota 2 will be a good reference. A reasonable amount of structure will be 3-5 ( assuming its a 5v5 game). This depends on how team base you want the game to be. Five structures will need five people standing on it to negate the heal or three structure would mean fewer players are needed to stop the heal.  This means the remaining two players can complete other objectives. The boss should be rooted in place so people can just stand on the heal easily.

Here's my suggestion, hope to see this game come to fruition ;)

**Comment by GrandShinobi** [comment]
Oops forgot to name the boss. I'll leave you up to that :)

**Comment by GrandShinobi** [comment]
Edit: Structure cannot be attack they are invincible.

**Comment by l34Um1** [comment]
Interesting. Noted. Will be discussed. Closed.
