### ISSUE TITLE
[Item mechanics] Drawbacks

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#175]
This might be a stupid idea, but what about Items with drawbacks; such as negative attributes?
It is present in the current game, although not much.

If any of you played Diablo II with the ZyEl mod, than you probably encountered the Demon box recipes, that is the basis of my idea.

For example an item, that gives a lot of damage, but reduces your attack speed severely (Kinda like Tiny - Grow),
or an item that reduces your maximum mana, but gives a lot of regen.

The hard part would be, that the stats would have to op to justify the drawbacks; which might result in unforeseen op builds.

**Comment by VoidsKeeper** [comment]
This is in no way a stupid idea and , I believe,  it will get its place on certain items in [...AA...] (cause this could help us balance some items/hero builds) . I don't know if we have such an item atm, though...perhaps not yet.

**Comment by Wujekklawy** [comment]
@VoidsKeeper #177 i also had similar idea with third item there, it gives big bonuses but active ability of it removes them from you for also strong effects.

**Comment by Haganeko** [comment]
We're doing something like this with the transformation items.
