### ISSUE TITLE
[Item] Hearth of the Archmage

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#176]
**Builds from**:

It is basically HoT but with mana in mind.

- Mystic staff
- Energy booster
- Recipe

**Gives**:
- intelligence
- mana
- manaregen based on your max mana

**Comment by Wujekklawy** [comment]
Equivalent of HoT is a Bloodstone so i dumno it is necessary to have item like that

**Comment by zelding** [comment]
I admit they are quite similar, but this Item would satisfy the needs of a very mana-hungry hero (such as Skywrath or CM), I can imagine some players would pick up this one, instead of Bloodstone.

Anyway, it would be a nice alternative imho, also could start a different upgrade branch.

**Comment by VoidsKeeper** [comment]
Thanks for your idea ;)
Sounds cool. I like your way of solving mana-issues. Could be an upgraded bloodstone, that specifics on mana. Wrote it down :)

**Comment by zelding** [comment]
> that specifics on mana

I just gave up giving you numbers; there is no point :roll_eyes:

**Comment by Haganeko** [comment]
Thank you for the suggestion! This is a duplicate of #117, item K. Closed.
