### ISSUE TITLE
[mechanic idea] Duels

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#178]
As all know duels in AA are in concept punching each other in the face. This is good solution to force two teams to fight (not always it works, everyone hate that losing guy who running away by infinite time). here i want to suggest additional Duels ideas to make them more interesting.

1) Boss battle
 
Teleport both teams to separate arenas with random boss (same for both teams). Who kills it first or die last will win and take points. 

This would nice be as latest duels when given higher tier bosses and if that's not work give uber boss who is amazingly hard to kill, first team to kill him or last to wipe out win game. But this is only idea about baumi's idea.

Death is permanent for time of duel (cannot join again to duel after death)

2) Capture the artefact.

Teams teleported on same arena. Death is not permanent for duel (if killed hero can join again after short time). 

Goal of arena is to hold artefact for longer time than enemy team. Hero holding artefact is sillenced, disarmed and cannot use items (can be also slowed but it's not necessary). If hero with artefact die it transfer to his killer.

After some time duel ends, team with had it for longer time wins.

3) Siege

Teams are teleported on same arena.
One team must defend and other attack. 
Attackers have one unit that goes from they side to destroy building (or whatever else, building and unit cannot be targeted manually).

Defenders goal is to grader resources and deliver it to one of attack stations (when delivered they attack attackers unit once per one resource). After hitting Attaker unit x times it dies and defenders win.

Attackers goal is to defend unit.

Death is not permanent for duel.

4) Extermination 

Teams are teleported to same arena.

Arena is a "maze" with camps of creeps in in.
After killing a creep it drops points.
When hero die he drops all of his points.
Team which have more points wins.

 Death not permanent.

These are just some ideas but i think others can have more of them. Post your ideas under this submit if you have any ;)

**Comment by zelding** [comment]
Are you sure you are not confusing AA with Uther party? :smiling_imp:

Don't get me wrong, I like the ideas, but I'm not sure they fit the theme.

**Comment by Wujekklawy** [comment]
I just know that someone will say that xD, but to be honest. Uther party is pure skill ;) here are more to show with team is stronger/better, so no simon says etc ;D

**Comment by Willib0** [comment]
Duels are what the name implies Duels,so 1,3,4 are completly different modes and 2 would be like the capture the point element that will be in every duels to make tanks more usefull in duels.

**Comment by Wujekklawy** [comment]
@Willib0 as name Duel suggest is 1v1 so if we break that why not make them more like competition instead?

**Comment by Haganeko** [comment]
I don't think we are messing with duels to that degree. Some specific reponses:
As has been stated, there is already a capturable objective in the arenas.
There are plenty of bosses outside duels; we don't need them in there.
The others look like minigames.
