### ISSUE TITLE
[mechanics] Duel Manager

### ISSUE THREAD

**Issue by erklp** [AngelArenaAllstars/suggestions#183]
## mechanic
An Npc, that lets you choose, which duel will you fight (all players, strongest ones etc.) for some gold.
Teams can outpay each other.
## premise
Can help win games( for example if you have weak team, but one strong manfighter, you pick strongest hero duel)
Players can force enemies to sink money 
Forces team fights
Useful for gangs

**Comment by erklp** [comment]
Should be locked a minute before duel to prevent sniping(only if nobody payed)

**Comment by zelding** [comment]
I feel this would just make the winning team snowball even more. Just think about it:
If a team is in the lead, then they have more gold - so they can outbid the other team to force a teamfight, when they only want a 1on1.

**Comment by erklp** [comment]
I guess you're right. But it could be interesting with some balance( in order to choose or re choose, you have to pay specific amount of gold. The cost can be calculated like buyback(in favour of the team with less gold)). I agree there are some flaws to it thou.

**Comment by l34Um1** [comment]
The problems created by this outweigh the benefits if we were to implement it. Closed.
