### ISSUE TITLE
[Boss] (actually i don't have name or lore, feel free to suggest some) 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#184]
Idea of boss i got reading submit doned by Haganeko ( #149 ) 

Boss rise himself on summoned structure (pillar or zgiggurat like) in middle of arena. After destroying structure Boss falls down and is stuned. After stun he raise himself again and go to one of phases depending on his life. Boss is constantly incanting while standing on a structure.

Phase 1 spawns projection of himself. Projection move around arena

Phase 2 (80%) Boss spawns three projections of himself, one of every type, projections move in more complicated patern. One of altars starts glowing, structure cannot be damaged while altair is glowing.

Phase 3 (40%) boss spawns 7 projections, 1 bassic, per 3 of other types. Projecktions move in more complicated paterns.

Short descriptions

Structure, building or object that boss spawn under him to stand on it. Requires to be destroyed to be able to attack Boss. Immune to magic damage.

Altar, structure or object that enables to spawn 2 additional projections, per one Rapid and one Disabler. Activated make structure immune to any attack. Destroyed despawns projections bounded to it. Immune to disables.

Projections:

Units bounded to boss or altars. Disapere when bounded unit is stunned or killed. Immune to any sort of attack. Not targetable.
Deals damage per second in aoe around themselves. 

Types:
Bassic, always bounded to boss, attack in wide long area (damaging similar to invoker meteor). Percent of damage dealt transfer to boss as heal.

Rapid, bounded to Altair shorts series of purojectiles towards enemy , evry projectile go in randomed way (width 500max units, attack in cone).

Disabler, bounded to Altar have lot of disables, very short range, disables are instant.

**Comment by l34Um1** [comment]
I rather go with Haganekos idea. Closed.
