### ISSUE TITLE
mechanics for abilities 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#186]
Here i want to submit some mechanics for Passive and Active abilities for Heroes and item's. Some are in base dota but lot of people don't remember them.

  >Change damage types.
  >Deflect projectiles.
  >Revile area of map.
  >Change projectiles speed.
  >Increase spell duration.
  >Change vision type.
  >Change vision distance.
  >Apply multishot.
  >Force enemy to move in certain direction.
  >Add health to damage.
  >Mimic enemy spell.
  >Apply random effect.
  >Increase x by doing y.
  >Force target to attack his friends. (i know, you don't have friends)
  >Make target sleep. 
  >Resurrect fallen units/heroes.
  >Place traps.
  >Change area to be slipery.
  >Step by step ability (enables to use it x times for short time from first usage)
  >Improve by attacking.
  >Purge target.
  >Heal x depends on y. (example,  health depend of target max hp)
  >Get x if y. (example,  get 100% crit chance if enemy missed)
  >Ghost walk.
  

I tried go not write mechanics typically for hero mechanic but more to inspire new items. Remember that baumi don't want yet ideas for heroes so even that you can use that list for some hero mechanics wait with that until Baumi will want to look for new heroes.  Sincerely, me.

**Comment by l34Um1** [comment]
We are already using a lot of these things or at the very least have considered them. I find the idea of resurrecting very interesting though, noted. Closed.
