### ISSUE TITLE
Small Item Dump 2

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#187]
Force Staff-Eul's upgrade: Purge and target to leap forward (gives a tornado effect that carries you forward). I think it'd be cute if this were a reference to the original Legend of Zelda, with a song it plays. This could have some significant upgrade potential to it, to compensate that the item might otherwise be boring. Like, it purges teammates in an area. Maybe it could do some healing instead, with a euls-force staff-guardian grieves combo. And it'd carry this effect with the tornado, healing and dispelling in its path. Maybe you could take this the other way and have the tornado's path deal damage or utility, such as a push/CC.

Radiance-Eul's-Dagon: Single tap cooldown spell item. Sends out dodge-able tornadoes that deal concentrated spell damage.

Maelstrom-Radiance: Maelstrom is no longer a single chain effect, but has a chance to proc on multiple heroes and units in a smaller radiance style area (max 3, similar to Drow with aghs?).

Portable Duel: Locks two characters into a local duel, where they can only take damage from each other. Maybe this could be an upgrade of another item, like BKB. Use on self is spell immunity, use on enemy is a duel.

Sacrificial Bond: Whenever your health or mana decreases, increase the primary stat of target friendly hero by ~0.1% per 100. 

Rain of Frogs: Rain frogs in an area, doing AOE damage and gives a 5% chance to hex for 3 seconds per rain (3 waves?). 

Spear of Light: A spear lodges into the ground, and shockwaves (like the Magnus Q) curl out in a spiral. Does magic damage and slows enemies. You can use the item again to charge or leap to the spear.

Shackle Column: Creates a blackhole at target location on use. Enemies caught in the spell can still cast and attack, but lose control of movement as they're whipped around a central point. 

Edit: Cursed Farsight Item: Curses an area of the map at a high minimum distance, stealing farm or discouraging enemies from walking there. It might reveal the area as well. Kind of like Ancient Apparition's ult, but focusing on denying an area for a short time. 

Edit2: Pushback+AOE physical crit item:
Decent damage upgrade item. When used, slams into the ground, doing a critical hit that because a physical AOE (100% cleave) and pushes back enemies. Moderate cooldown.

Spiked Flail: Attack damage increase item. When used, sends out a short flail that serves as an unreliable hook (curved, flippant path, if possible, so the hook effect will only work part of the way) and deals your physical damage on contact.

Throwing Chain: Works like pudge's hook, except it only does a set amount of physical damage. Gives stats. Maybe upgrades into something else, so it's a reliable mid-game item. Meant to extend the diverse capabilities of a melee hero to range slightly.

**Comment by Wujekklawy** [comment]
Force staff + eul disables primary reason why you buy eul in first place.

Rad+eul+dagon, same as above. 

What is point of this duel thinni? 

Rain, so it's basically aoe dmage with chance to hex?

Spear, w8 what? So you throw a spear and it's aoe, on target or in line damage?  And I like idea to be able dash to it.

So it's black hole or shackle? Btw, that can also fuck up team who use it, imagine drow in it and she can attack and move in same time, abd you have only melee, slowed to be exact.

**Comment by JSampersand** [comment]
Eul's used to be a good team support item. You could negate incoming heavy damage to a teamate, dispel a negative effect. My idea with above is to bring some of that functionality back. Obviously you don't have to upgrade it if you just want it for the disable, or it could still work that way when targeting an enemy.

Point 2: same reasoning as B point above. Eul's would certainly not be the reason you'd buy this upgrade, I'm just playing on the Tornado idea, into a radiance that does its damage in a concentrated way via an area hazard instead of an AOE aura. Obviously an AOE Eul's would be too powerful, unless it would be more like Invoker's tornado CC.

The point of the duel would be to lock yourself, mid-teamfight with a comparable or lesser strength hero. A lot of the time with Angel Arena, we see single right-click heroes dominating the fights, but you could use this item to lock them out, effectively assuring yourself a more fair fight. This'd probably have to come paired with some sort of stats or passive to keep it from being only situationally useful, which isn't something a right-click typically wants to buy.

It's meant to be a fair AOE hex, and a pocket crystal maiden ult. 

AOE line damage, as described.

"So it's black hole or shackle?" -- "Enemies caught in the spell can still cast and attack, but lose control of movement as they're whipped around a central point." Visually, I'd image it looking like a torture device when placed, like a rack of chains spinning around.

**Comment by l34Um1** [comment]
I find the idea of a Euls that can move to be somewhat interesting, the rest not so much. Closed.
