### ISSUE TITLE
[Boss Idea] Tank viability

### ISSUE THREAD

**Issue by GrandShinobi** [AngelArenaAllstars/suggestions#188]
This boss is to open the idea to tanky heroes as picks and not only 5 man hard carries team. Very common sight in many AA. Like by previous three boss I suggested, I want to give many heroes a great reason for picking them. 
In this boss the ability to tank damage is significant in taking down this boss making durable hero an attractive pick.

(Passive) Ability 1:  Small radius magic immolation damag around the boss.
Refer to Scorched Earth for reference .

(Passive) Ability 2: diffuse damage taken to a nearby player. Similar to specters diffusion except it is single target. Suggested damage: physical, 8% of total dmage taken.

Ability 3: At 30% health threshold the boss summons an invincible shield infront of itself. Immune to any damage if attacked from the front.

Let me tell you more about the three abilities and why a tanky hero is needed.
As the boss is melee, it will walk towards ranged heroes and attack them exposing themselves to the magic immolation damage ( if a player tanks it, the range carries will not need to expose themselves to the magic immolation damage). One person will take damage from allies due to the diffusion thus someone tanky. One person has to tank the damage because it cannot attack the boss. The boss will face a target with its frontal shield thus that target cannot attack, all pther players will have to attack its back. (When the boss attacks a target it faces straight towards the target, like any other boss but because of the shield that target cannot attack. If the players tries to move around it it would not work because the boss is still attacking the player. Get it?)

 Thus the a tanky hero will be required to tank the damage to kill the boss. 

Suggestion: It could just be the third ability and that's enough to force people to do the strategy. 50-60 killable boss, enables player to buy tanky items. Tanks and support items upgrades may be needed. (I will suggest some on a later date). Boss should be medium health and medium damage for a (50-60 min boss) Consider this, if the boss is 50 thousand health, to tank the entire diffusion one needs 5 thousand health (assuming that diffusion damage is 10%) 
On top of all the other damage so please keep that in mind.

**Comment by l34Um1** [comment]
I am unsure why you are assuming tanky heroes won't be needed for bosses. Either way, I don't find this idea to be interesting enough to pursue. Closed.
