### ISSUE TITLE
[BOSS IDEAS] Cerberus, Vampire, Chainman

### ISSUE THREAD

**Issue by Chewy316** [AngelArenaAllstars/suggestions#189]
[BOSS IDEA] A Couple of Ideas
Just a few things, my names and lore suck because I am uncreative. Someone please fix them. Also, the Just For Fun does not need to be used they are, just for fun.

**Cerberus, Hound of the Underworld**
QUICK CHARACTER DETAILS: Based on Cerberus from Greek mythology. He is a large 3 headed dog, that guards the gate of the Underworld. 
CHARACTER ATTACKS: This boss has 3 phases. Phase 1 he runs towards the nearest hero and attacks with all 3 heads. (3 sets of physical damage). Once he deals a set amount damage he will toss up to three heroes in front of him to the edges of the arena. (There should be a highlighted area for where Cerberus will grab heroes for toss). He will then repeat this phase until he has lost 50% of health. When phase 2 begins Cerberus gains 50% movement speed. In this phase a large ball is thrown from outside to arena aimed the hero with the highest Health. This ball (should look like a chew toy) will deal little damage but adds a debuff of lowered movement speed and armour. (The Ball should be made dodge able) Once the ball hits the other side of the arena it disappears and Cerberus will charge through the path of the ball grabbing any hero in the paths range. If Cerberus does grab a hero they taken to where to ball disappeared, stunned and hit with massive physical damage. If Cerberus does not grab a hero he will hit the wall, and be stunned. Once the stun is over the ball is thrown again but to the next highest health points and so on. The last phase activates when Cerberus is at 10% health. In this phase his three heads separate so there are 3 small one headed dogs.(Health is 4% of Cerberus original heath) This dogs will just run at heroes and auto attack. However when they are killed they explode dealing massive magical damage in an AOE around is body and adds a debuff to all heroes which is less armour and greater damage taken by the other dogs.
NOTES:
-Cerberus should always have a high movement speed, and gain more depending on the phase and such
-Each of the 3 heads are able to hit different heroes if in range. (if there is only one hero they take all 3 sources of damage, if 3 heroes in range each head will attack one splitting the damage by 3)
-When in Phase 2 Cerberus grab range should be the same as a medium AOE spell
JUST FOR FUN: 
Each head should be a different dog and deal different types of damage. E.G. a Pitbull head which deals high physical damage, a Poodle head which deals magical damage and a Chihuahua which deals pierce damage

**Lord Someone, Master Vampire**
QUICK CHARACTER DETAILS: Born many a century ago, Someone was bitten by a vampire and lived, which turned him into a vampire. 
CHARACTER ATTACKS: This boss has two phases however his attacks and spells remain the same only the become more powerful in the later stage. Phase 1 he is in human form and has high armour and health but weak physical auto attacks. Phase 2 he is in bat form and has same armour and health but increased damage, life steal to attacks, movement speed and attack speed. Phase 2 activates every 2 minutes or so and lasts a minute or something (the arena should also become night time lowering visibility). He normal attacks are normal auto attacks that deal physical damage and have a set life steal passive. He has 3 spells, one is like Pugna’s ultimate which acts as a channel drawing life out of the target and healing the boss, however the boss must be in contact with hero. When the channel starts, the hero is stunned and cannot escape until the channel is over which is about 4 seconds. The second spell Lord Someone activates a large AOE around him which applies a minus armour and damage debuff to heroes with in it. Any hero in this AOE also take increased life steal from the boss. The last spell is used to begin the first spell. Lord Someone will glow red for a second or two, which leaves him open to attack then turns invisible. Once invisible he will he will dash to the nearest hero and start spell one. Just a reminder these spells are shared both phase but have increased stats and life steal during phase two.
ARENA: The Arena should look like a square room, with an uphill throne near the top. (This is where the boss spawns. Also, the main thing is that the day night cycle is different. The day cycle last 3 minutes then night lasts 2 minutes. During day, the boss is in Phase 1 and at night he is in phase 2.
NOTES:
-When invisible from spell 3 he is undetectable from wards or dust.
-Life steal should be at least 20% of damage dealt
JUST FOR FUN: 
-In Phase 2 he could become a flying unit which gives him more movement options
-Using a light type ability, such as KOTL’s illuminate should do 25% more damage.

**Chainman, the Guy with Chains**
QUICK CHARACTER DETAILS: Someone was once an ordinary man until he found some old chains. From that day he became, Chainman the guy with chains.
CHARACTER ATTACKS: He has only phase but as he takes more damage his attacks and spells increase. He has large chains that surround the boss that makes him invulnerable, however as the chains take damage they start to tighten around the boss. (When they have all lost their health the will kill the boss like an python killing its prey. The boss is surround by five chains each with extremely high damage and armour. The only auto attack is from the boss who shoots a range projectile at the heroes for decent damage. The Chains all perform each of their spells together. The first spell all the chains spin around in a large AOE. The spin is slow they can be dodged but if hit by the chain the hero takes massive damage and is thrown to edge of the arena. The second spell each chain will aim at a hero (shown by a large highlighted AOE) then it slams it one the ground also dealing high physical damage. This time however after the slam each chain becomes stunned (even if it hits a hero). Once stunned their armour is decreased by 20%. The final spell all chains burrow into the ground. Then they start to erupt from the ground at random spots around the arena, dealing high damage in a small AOE and decreasing movement speed by 20 for each time hit. This lasts for around 10-20 seconds. (Again, before the chains erupt the ground highlights where the AOE will be.) There is also a 5 second standby phase between each spell, which allows the heroes to deal damage to the chains.
ARENA: The Arena is a large circular base where the boss is stuck in the middle. The walls however are covered in chains which when contacted with deal damage and pin the hero for 2 seconds
NOTES
-The chains could all have a health link (all health is shared as well as damage between the five chains). However only physical damage is shared. Magical, pure and spells only hit the targets health bar. Example (numbers are only an example) each chain has 100 health. If a hero deals 5 physical damage all chains will take one damage. If a hero uses a 20-magical damage attack only the target losses the health.
JUST FOR FUN
-I don’t know maybe the chains can be made with different metals which change individual stats. E.G a gold chain has 10% more magical resistance but an iron chain has 10% more damage.?

**Comment by Wujekklawy** [comment]
Li'l fix to your post, avoid flavor and lore in describing fight and mechanics. I suggest you to close that post and make new one with fixed boss suggestions, i can make them more clear so i will do that in comments to this one. Feel free to change whatever you want. Please in additional write everything i removed, to make it clearer, and flavor/lore also all ideas you have to enhance fight or visual aspects.

**Comment by Wujekklawy** [comment]
Cerberus, Hound of the Underworld


Combat:

 Phase 1 (100%-50% hp)


-Boss move towards nearest hero and start attacking it (boss have 3 sources of auto attack, suggesting 3 heads)

-After dealing x damage he toss enemies in front of him to edge of arena. (affect max 3 units, give time to avoid) 

Phase 2 (50%-10% hp)
 
Passively gains more movement speed.

-From outside of arena apere projectile aimed to hero with most health, don't despair on hit, goes in straight line, desapire on other side of arena. Apply debuff to movment speed and armor.(preferably visually as chewing toy, ball shaped)

-After projectile desapire Boss charge through path of projectile, charge work like magnus one, after getting to edge of arena evry grabbed hero is stunned and gets massive physical damage. When noone grabbed boss get stunned. (when boss gets out of stun phase repets)
 
Phase 3 (bellow 10%hp)

Boss splits to 3 lesser ones with one source of auto attack. (every have 4% of max hp that original had)

Lesser ones ackt like in phase 1(with reduced max tossed units to 1)

After death lesser ones explode dealing aoe magic damage and buff other lesser ones.


-----------------------
Additional:

**Comment by Wujekklawy** [comment]
Ps, i suggest make separate submits for bosses.

**Comment by Wujekklawy** [comment]
Note to creator, boss fights should not include auto attaks and length of boss fights can't be longer than 2 min so i reworked one or two things,  also lore wise as you wanted. I don't see reason to make him invisible so i removed it. It just makes more work to dev and not add anything to fight. 

Lord Balmont, Master Vampire

The Dark King stand again on earth to conquer it again. Maybe yet weak but soon in full power.

Combat:

Passively morf to his stronger version evry x second of fight, last y seconds.
This increases both types of damage dealt, incised life steal. Armor stays same.

HIS attaks have lifesteal and spell life steal

He's base attack is AoE in front of him in 2 shapes, cone and rectangular(width and long)

Boss after taking certain damage dashes to random enemy stunning him and draining percentage of his health to interpretation by dealing damage equal to max hp of target. When preparing to it boss is weaker and not able to attack. (can be nerfed if necessary)

Boss have ability to deal aoe magic damage around him with also debuff enemies around for duration of fight. Preferably apply minus armor and lowers damage, can stack.

ARENA: The Arena should look like a square room, with an uphill throne near the top.

----------------------
Additional:
On arena day/night cycle could be simulated to make night when he is in stronger version and day when i weaker.

Some abilities that have light theme like kotol iluminate or omni heal could deal more damage

**Comment by Wujekklawy** [comment]
Note to creator, i added some  lore and added mechanic to boss to make him li'l interesting.


Forgotten , the mad prisoner.

Powerful wizard brought to end of his mind. Once locked in another realm now free killing everything on his way.

Combat:

Power of attacks increase as his health decrease. 

Boss have "shield" that block damage to him. "shield" have 5 separate health bars. When all health bars drop to 0 boss die from 1 hit. (preferable visuals are chains) 

"shield" accompanying boss with attacks, attacking in synchronization with boss doing same attack, not necessarily to same target.

Boss base attack is damage in line towards random enemy. 

Boss attack in large AoE dealing damage over time, slows when sdand in, after standing x seconds it roots.

Roots creates similar "shield" on rooted, health of it depends on max hp of rooted unit, deals damage per second (around 1%max hp) to rooted unit. Also accompanying boss with attacks. 

Boss root everyone in lane,  "shields" that accompanied boss with that attack get stunned and weaken, also when noone was rooted (after attack line of it is visible like in earthshaker wall, but can be attacked and share hp bar with caster)

Boss deals damage in aoe in random places, similarly to event boss new-year beast attack with kunkka torrents, roots on hit. Last for 6-12s

 
ARENA: 
The Arena is circular, boss is stuck in the middle. The walls of it when contacted with deal damage and bouce back (similarly to spirit braker bash)

Additional:
-The chains could all have a health link (all health is shared as well as damage between the five chains). However only physical damage is shared. Magical, pure and spells only hit the targets health bar. Example (numbers are only an example) each chain has 100 health. If a hero deals 5 physical damage all chains will take one damage. If a hero uses a 20-magical damage attack only the target losses the health.

-I don’t know maybe the chains can be made with different metals which change individual stats. E.G a gold chain has 10% more magical resistance but an iron chain has 10% more damage.?

**Comment by l34Um1** [comment]
Too much flavor, too little content. Closed.
