### ISSUE TITLE
Boss idea: honor angel? First or second tier

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#19]
An "honorable angel" type.
At first, he's mostly a tough right clicker, with good armor and damage, who can't be bashed. Then, once he's down to 80% HP, he gets fed up with people ganging up on him. Every now and then he'll scream "fight me honorably, curs!" and push away and disarm everyone near him who's not his current target. This can, of course, be interrupted.  
At 50% HP, he'll start saying "I challenge thee!", and basically using the CK teleport on the farthest hero (there'll be an indicator and time to interrupt). 
At 20%, he'll scream "Foul sorcery!" and become magic immune for the rest of the fight.

**Comment by l34Um1** [comment]
I don't like the magic immunity. Don't mind having a simple boss like this though.

**Comment by Haganeko** [comment]
This has been added.
