### ISSUE TITLE
[Item] Friendship Tango

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#191]
**Recipe**:
- 4 Tangos 
- 4 Shared Tangos

*Active*:
Chop tree for double heal or duration, or even better, chop down an area, and heal based on the chopped down trees like in AABS.

**Justifications**:
- nobody ever would think of using shared tangos in a recipe
- would be a nice gesture from the teammates to build an item for the carry at the start of the game

**Comment by GrandShinobi** [comment]
It will work well against one of  my suggested boss XD. Which I don't really mind.

**Comment by VoidsKeeper** [comment]
Lol , this could be a neat item (or even an Easter egg type thing). I like this

**Comment by l34Um1** [comment]
Cute idea but impractical. Closed.
