### ISSUE TITLE
[item] Shield of Godus

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#193]
>Actually i don't have idea for recipe or name (i >writed first thing in mind) but i think ability of >item can be interesting.
------------------------------------------------
Stats, depends on recipe.

Recipe, maybe vanguard plus something, depends on strength could be also some boss items.

Active: 
After activation creates shield that blocks x damage.

----------------------------------------------
>shield hp will depend on how strong and on 
>with part of game to be used.
>
>i leave to dev team everything about that item.
>if it's only selftarget or targetable, or hp of 
>shield depends on attributes of caster or 
>simply percent of hp of caster, i leave that to 
>dev to decide.

**Comment by Wujekklawy** [comment]
Also active could be like :
>
>passive:
>grant's stack depending on damage dealt.
>
>active:
>convert stocks to shield, evry x stacks is converted to y shield health.
>

Or something like that:

>
>passive:
>enables to over heal with life steal to x hp. (could be some percent of stats or max health, or no upper cup but decying over time)
>
>Acktive: 
>Grants 300% life steal for 3s
>

For that could be upgrade of satanic, so recipe something like vanguard + satanic.

**Comment by l34Um1** [comment]
Not really interesting. Closed.
