### ISSUE TITLE
[item] Blink items ideas

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#196]
Once baumi said that is hard to come with ideas for blink dagger upgrades, i think he was wrong. Before you read, latter on i using word "trash" to analogy of items that preferably are not an upgrade of other items and i leave dev team to discuss about it. I chosen this word because i like it, i could also use word "ponny" but I'm not trash and like "trash" more than "ponny", so no need to offence. Above that i use two types of brackets(?) "[]" and "()" first one are my comments on stuff second one are addons to suggestions [important ones]. And i warning you,  i writing it at 2am so this time and mental effort are destructive combination, for me work like alcohol poisoning [if you want be mentally safe don't read these for anu reason, it's your last warning ]

1)Blink Blink. [someone just won on lottery :D]

Recipe, Blink dagger plus recipe.

Ability: have chance to increase distance of blink (work similar to multicasting blink in old times of LoD)

2)Healing dagger.

Recipe: blink dagger plus tranquils (can be also recipe if needed) 

I think everyone will know what it does. 

3)Wind Dagger. [I think Merlin Monroe would not be very happy for that item]

Recipe, Blink dagger plus force staff.

Ability, have x charges that can be used to dash foword. Charges replenish over time. (suggest 3 chares where max length of using all 3 will be around 1.5 blink dagger range)

4)Warp dagger.

Recipe, blink plus something.

Ability, blink you and nerby units to target. Targets ground like normal blink.

5)Dual Dagger. [Who are the cutest backstabber? Yes you are :)]

Recipe, blink dagger plus diffusal 2 (or some other diffusal blade)

Ability, if target enemy unit blink to it and apply diffusal debuff, when no target work as normal blink.

6)Blink Hammer [13 out of 13 Thor would take it]

Recipe, blink dagger plus basher (or abbysal blade if you want)

Ability, after blinking stun enemy around for x second (0,75s should be ok with radius 350, with abbysal in recepe ofc should be more powerful)

7)Arcane dagger

Recipe, blink plus some int trash

Ability, after blinking next ability used have shorter cooldown and needs less mana if it was casted in x seconds of blink.

8)Flame dagger. [someone took knife to a flamethrower fight]

Recipe, blink dagger plus something with fire theme.

Ability, after blink put in flames path traveled, deal damage per second (damage dealing similar to meatball)

9)Acid dagger. [Maybe look like cheese but i bet it not taste like one]

Recipe, blink dagger, orb of venom and some trash.

Ability, after blink evry enemy unit that was on path is poisoned, poison deal dmg over time and resources armor. 

10)Frozen dagger. [be careful, it's cold]

Recipe, dagger and some trash.

Ability, after blinking create ice path on traveled path(?) (work like invoker ice path but this version is long and narrow instead of short and wide)

11)Earth Dagger. [yep, still elemental family,youngest child but hit like a grandpa]

Recipe, as always, Dagger plus some trash.

Ability, after blink create wall on path, enemies hited by wall are stunned (work like es wall)

12) Heel Dagger [Worst nightmare of Achilles]

Recipe, dagger plus medalion or his upgrade.

Ability, after blinking aply debuff on caster and surrounding enemies.(debuff of medaliin or his update, or creative variation) 

13)Time dagger [i rly wanted to finish in this one, i promise i wanted end on 13 ]

Recipe, dagger and some .........  [yep, you guessed right]

Ability, if targeted hero work like glimpse, if not work normally [i dunno how to describe it better on 2am]

14)Crossbow for daggers [you shoot daggers? Damn son, that must hurt]

Recipe, blink dagger plus daedalus (preferably crystalis [but i get hilarious name for daedalus one so i was must use it instead of crystal dagger or something like that ])

Ability, after blink have 100% chance of critical strike for 1 attack within x seconds (having in mind kunkka it shouldn't aply any type of cleave[trust me, you don't want it ever])

15)Hero dagger [he is doing super hero landing... Woo... hoo...!!!]

Recipe, dagger plus some [yep].

Ability, after blink in destination every unit in small aoe is pushed away, deals damage to enemy [add to this hero landing animation and crater from sun strike then it will be top level hero landing :D]

16)Shadow Dagger

Recipe, blink dagger plus shadow blade [surprisingly every recipe have blink dagger in it, accident? I don't think so.]

Ability, when blinking make caster invisible and create illusion with walks towords for some time [rip old Phantom lancer chlip... I wasn't have even time to learn how to not suck with it, clip ;_; ]

17)Dagger The Dagger. [Clapp... Clapp... Clapp... Most creative name i ever heard of, anyway, there is something in your back ]

Recipe, [like most of it, skip...]

Ability, work like normal blink but enables to deal more damage when attacking from back. (could be fused with dual dagger or dual dagger could be upgraded version of Dagger The Dagger[it's catchy and fun to say, for your and your family, annoy your surrounding, today!])

18)Gold Dagger. [someone was touching it before]

Recipe, blink dagger plus hand of midas 

Ability, work as normal blink but passively increase every gold income by 25% (not safe one, forgot the name [where i puted my brain? Where it was? Heh... I think it's on a Walk]

19)Blink shield [rly? You have so many options to choose from, and you choose dagger with shield? Wow, you are truly a wise guy]

Recipe, blink dagger plus vanguard (could be also other shields) 

Ability, after blinking create shield around hero that block all damage,lasts 7 seconds or until destroy, hp of shield is 5% of wielder hp, have no reductions.[maybe because it is an reduction, but who am i to debate about it]

20)Nightmare Dagger [sweet dreams dear enemy]

Recipe,  Blink dagger plus some trash

Ability, after blinking causes fear in surrounding enemy (work like lone druid one, not work on illusions) [i bet he is saying "bu" when apire from nowhere]

21)Miracle Dagger [you still reading it? Wow, ok, i know that i writing it like 2 hours but man... This is so much text, how you even have strength to read these]

Recipe, [skip...]

Ability, after blink casts random spell at random unit in range (for ballace spells should be categoried for enemy one's, can be casted only on enemies, neutral, can be castet on enemies and team, friend [zone], can be casted only on friend's) [ballance in item that his main fuel is 0 ballance... Gj]

If you get to the end i want to thank you and leave comment what you liked and why or maybe you dislaked something and you want share why then feel free to also comment. I hoped even if you dislaked ideas at least you had fun. Thanks, now comment time. [Free ban for first person that write "First", get it quickly or you will be to late]

**Comment by zelding** [comment]
In general, I don't think there should be more blink dagger recipes, some were already suggested  [link](../blob/master/doc/suggestions/items.md) and some are against the general rules [this](../blob/master/doc/items.md).

Please read the Guidelines and the already suggested things list, and filter out some of your ideas, I like the elemental flavored ones especially - there should be a _pencil_ icon in the top-right corner of your issue 😉 

Also, if you want to create an ordered list, just type the number follower with a period and a space: `1. `
Everything else is [here](https://guides.github.com/features/mastering-markdown/).

**Comment by Wujekklawy** [comment]
I don't have available computer to be able edit this, there is no such button on mobile version as i can see. Did that tranquil plus dagger was just added? C'man, it's neat upgrade to tranquils, you not lose healing while fighting with creeps. It's like mini portable heart ;D and rly, one recipe to up blink is not enough :)!BTW, i think my upgrade for same recipe is more interesting :)

**Comment by zelding** [comment]
In regards of tranquil + blink:

It wasn't added, it is basically on the auto-deny list.
Baumi explicitly used this as an example for "only giving and extra inventory space".
If you think about it, it is true; it gives nothing more, just the combined effects and consequently one less space; and it is uninteresting - boring. 

Sorry

**Comment by Wujekklawy** [comment]
Same thing you can tell about daedalus, you combine dmg item and crit, and you get nothing new from it.

**Comment by Haganeko** [comment]
Since you have referenced this is a more recent issue, I will assume you have taken whatever you thought  were the best ideas and reposted them there. If you haven't, please do so.

**Comment by Wujekklawy** [comment]
@Haganeko it was not my post xD or that is not to me (?)
