### ISSUE TITLE
[ability] (not a life steal)

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#197]
I got idea when writing my few ideas for blink upgrades (#196) but it doesn't work with blink so i created new [T]issue for suggesting it.

---------------
**Ability: Cannibalism**

**Heal 3% of max health for every fallen unit in radius.**

------------

Actually it could be pretty good ability for new hero so dev please comment if you like that idea and if yes that you want to me create hero around it and save it for time when you will be want hero suggestions or use it in item? [I'm tired, it's 3am so use it in some boss drop item or something, i dunno why it matters cuz while reading your comment i will not be tired but still]

**Comment by Willib0** [comment]
It is not 100% lifesteal,but in AA 95% of the units dying in your Area would be your kills so why would you not go for a Lifesteal anyways.The only way this would work would be if the hero that has Cannibalism is very spawnbased,

**Comment by Wujekklawy** [comment]
@Willib0 ye, i got to similar conclusion that i add at end that i could make hero with this ability if devs will think it is somewhat interesting

**Comment by AndrewLouw** [comment]
This mechanic is already in the game - it's actually in regular DOTA 2...it's called Flesh Golem.... Undying's ult. it's pretty good for an aura tank hero who doesn't deal damage on their own. (making it very different from lifesteal) As an item on it's own it might not be worth the slot at any teir of the game but as a mechanic within a larger item it could work. I'll pass it on.

**Comment by Wujekklawy** [comment]
@AndrewLouw actually i based it on ghoul ability from w3, and little enchanted by multiple targeted and aoe so it will be not shit in gamemod like that

**Comment by AndrewLouw** [comment]
Like I said I'll pass it on, but fundamentally it's weaker than lifeateal if you're a carry because the benefits only occur once the target is dead - and you could die first. And the same problem with a tank where it's weaker than survivability items early on and then not worth the slot later. But I like the mechanic and I think it'd go well as part of an upgraded lifeateal item or upgraded tanking item or both. For example vlads + crimson guard + recipe and you gain this effect on the new item while also saving a slot.

**Comment by Haganeko** [comment]
We're trying not to take abilities from heroes. This works mostly for farming, and as an interaction with summon heroes. Could be useful with a smaller value, and as a small item.

**Comment by Wujekklawy** [comment]
@Haganeko acktualy i can imagine it replaceing tangos :)

**Comment by Haganeko** [comment]
We don't really need a farming regen item right now. Closed.
