### ISSUE TITLE
[Boss Encounter] Daughter of Cosmos

### ISSUE THREAD

**Issue by Helvettium** [AngelArenaAllstars/suggestions#198]
# **Daughter of Cosmos**

### **Base abilities:**
   **1. Through the Cosmos:** The boss would charge the lowest hp (flat hp, not %hp) target within ability range (quite long) stunning all those hit during the charge for a small duration and dealing flat magical damage. At the end of ability there would be a small explosion silencing all those in the area and dealing further flat magical damage. The charge would lock-on to the position of the target player when the ability is activated rather than following the the target. The boss would be untargetable during the charge until the explosion has happened.

The ability would make a slightly faint red line on the ground that would fill up from the middle to the edges in darker red to show where the charge is aimed, it's hitbox, and to show when the charge would start, the explosion would also show it's area in a similar way after the travel has finished, but would would be faster than the charge so that it leaves little time for the intended target to dodge the explosion if he didn't move away from the charge.

The boss would transform to look similar to _Io_ for the duration of the ability and then transform back during the explosion.

   **2. Frenzying Blood:** The boss spews her own blood upon her enemies in a cone in front of her, deals %max hp magic damage to all those hit, preferably a large amount. The skill would have a noticeable cast animation and a red warning area where the ability hits to allow for possibility of moving out of the way. The warning area could have similar color mechanic to _Through the Cosmos_ where the warning area cone would fill up in darker red starting from the boss and filling up to the far edge of the cone to give better idea about when the ability hits, to allow for last second dodge with a blink ability.

### **Second phase:**
Activates at **66% hp** remaining:
Gains an ability called **"A Call Beyond"** that has a noticeable casting animation / red warning area to indicate the area, the ability is a big aoe that deals a large amount of flat magic damage to all those hit and stuns them for a short period and silences them for a medium period. Once again the warning area could fill up with darker red starting from the boss and filling towards the edges to give better idea when the ability actually hits.

The casting animation could have the boss raise whatever appendages it has in place of arms or their equivalent towards the sky and gather a growing sphere of energy that would explode to the affected area.

### **Third phase:**
Activates at **33% hp** remaining:
Gains an aura called **"Otherworldly Wails"** that continuously deals %max hp magic damage to all enemies around her in a medium sized area, similar to _heartstopper aura_. The aura could also be stronger the closer you are to the boss, so that tanks and other melee heroes would take more %hp damage and ranged characters and supports would take less %hp damage, though the area could be short enough to allow most ranged characters to attack from outside of it when not tanking. 

The aura could have a visual appearance similar to _Naga Siren's_ ultimate except that it would be a bit more visible and red to show that it's a negative aura, in order to show the affected area.

### **Design philosophy:**
The boss idea is intended to punish participating players that have very little hp, or are trying to switch aggro while low hp. The boss deals large amounts of magic damage to incentivize players to have magic resistance items or to play heroes that gain magic resistance from their kit. The abilites are intended to deal large amount of damage and incentivize players to dodge the abilities with movement where possible. _Frenzying Blood_ is to make tanking harder and _A Call Beyond_ is there to disrupt the players and make heroes with very little hp vary of continuing to participate. _Otherworldly Wails_ is also intended to make tanking more challenging and to make the boss charging low hp targets that much more dangerous, whether the aura would be active during the charge itself is  up to you and whether it's possible to turn the aura off for the duration of the charge.

The boss would use _Frenzying Blood_ regularly and to compensate would deal less basic attack damage than others of the same tier. _Through the Cosmos_ should be something that happens only a few times so that it doesn't make fighting the boss too annoying, but is still present and something to be aware of. _A Call Beyond_ also shouldn't be used too frequently, but should happen more than once in the fight.

### **Boss item:**
Called **"Heart of Cosmos"** grants large amount of intelligence, mana and mana regen as well as an activatable ability that is a weaker version of _A Call Beyond_. Could have a upgrade path with both _Octarine Core_ and _Heart of Tarrasque_ allowing the player to choose which stats he wants to combine to the item. 

The player version of _A Call Beyond_ would have a small delay after activation showing the affected area in a similar way to the boss after which it would deal flat magic damage in a medium sized aoe causing a mini stun and a slightly longer silence. Upgrading the item would retain the ability and possibly give slight increase to the damage, but not affect the aoe size or the duration of the stun and silence. The ability could have a medium to long cooldown timer.﻿

### **Other notes:**
Though the boss item could have been suggested as a separate item idea, but I think it should be connected to the boss itself rather than be something that could be bought from the shop, so I included it here.

I'm not sure what kind of base model / appearance this boss should have, it is of course alien / otherworldly in origin, but whether it should look completely alien or be somewhat humanoid in appearance I can't say, so I'll leave that to you =P. I also can't think of any good lore for the boss on the spot so I'll just leave that out as well.

**Comment by Haganeko** [comment]
Thank you for the submission.
Your post can be improved by clearing out the fluff and focusing on the mechanics. For example,

> Charge
> Charges in the direction of target player. Upon arrival, deals magical damage and silences in an AoE. Boss is invulnerable while charging.

is much  cleaner. Reformatting according to issue #37 will also increase clarity.

**Comment by Haganeko** [comment]
This is unclear, and once the fluff is stripped, not that interesting a design. Closed,
