### ISSUE TITLE
[Boss Mechanics] [Boss Idea]

### ISSUE THREAD

**Issue by Akkaren** [AngelArenaAllstars/suggestions#200]
Ideas I had:

* A boss that can't be damaged directly but only by destroy buildings right beneath him dealing aoe dmg to the boss. (like an explosion)

* A boss that works kind of reversing:
   - You deal dmg - he heals.
   - You heal him - he takes dmg.
   - You stun/slow him - he gains movement speed.
   - you silence him - he gets CD-reduction.
   - ...
Allow to use friendly heals on him (Voodoo Restoration, Shadow Wave, ...) also allow to use items on him like mekka or other stuff.
Let him switch between normal and reverse, so you could accidentally heal him 

* A boss that splits up in identical clones (same dmg taken, same dmg, same all) and then you have to figure out which one the real one is. If you kill a clone your team takes IMMENSE dmg. Let him split up every once in a while so it is difficult to remember which is the real one by just look at his hp or simply follow his movement. (or remove visible hp).
attackwise you can let them interact with each other. eg:
   - they link up and this link deals dmg. they also move fast around.
   - they get 'bouncy and push you all over the arena (and deal dmg with every bounce)
   - ...

* 2 Bosses in one arena. One mainly deals dmg. The other mainly heals and buffs the dmg-dealer. If you kill the dmg-boss the fight is over but it will be extremely hard while the healer is alive. if you kill the healer the other will fall in some kind of rage.

**Comment by Haganeko** [comment]
Thank you for the submissions!
On the first one, how is that different from attacking the actual boss?
On the second - that seems like it would be almost impossible to defeat during reverse phase, for most heroes... and Winter Wyvern would rekt him.
The third one has been proposed a couple times.
The fourth has also been proposed.

**Comment by Akkaren** [comment]
The idea behind the first one was to force him near the buildings. The boss is usually moving a lot and very fast. Needs also to be ranged so he can attack from different spots.
But it seems like the idea is kind of similar to the charger... (Force him to a specific spot)
