### ISSUE TITLE
The Floor is Lava (literally)

### ISSUE THREAD

**Issue by RighteousBacon** [AngelArenaAllstars/suggestions#201]
This is a pretty simple idea, and I've seen it done in plenty other games, so somebody may have already suggested it.

I think it might be interesting to build a boss around death traps, for example giant pits of lava with narrow walkways that the players have to navigate. This might make for a great tier 1 boss, since with a tier 1, you can justify insta-killing a player when they fall for a trap. And while we're at it, while not add extending spikes, moving platforms and more?

**Comment by zelding** [comment]
Instakilling won't happen, but high damage traps should be okay.

**Comment by RighteousBacon** [comment]
I'm thinking that for a tier 1 boss, assuming you're not being harassed by the enemies, health is basically the same as lives in other games. I understand the reason for giving players more than 1 chance to nail the boss, however insta-killing players might actually enforce teamwork (whether or not it's a good idea to do so through such drastic means is beyond me).

Since you as an individual player only have 1 chance of clearing the encounter, you can bring teammates, who can learn from your mistakes and finish the boss fight, benefiting the whole team. At the very least, it's food for thought.

**Comment by Haganeko** [comment]
Thank you for the contribution!
We have quite a few boss ideas based off of mazeing and reducing the available floorspace.
