### ISSUE TITLE
[Boss Idea] Weaponsmaster

### ISSUE THREAD

**Issue by AceXS2X** [AngelArenaAllstars/suggestions#202]
I don't know if this idea has been suggested before, but I'm going to make it anyway.
 
This boss will have multiple stages of the fight  : 

The first stage will be just like a normal rightclick boss with nothing special, with the boss sometimes jumping for a massive AOE attack, with not a lot of health and respectable armor.

However when the Weaponsmaster HP drops to 50 %, ALL HELL WILL BREAK LOOSE as this boss stops attacking, becomes invulnerable for a few seconds and buffs itself with around 70-90% spell and physical damage reduction and starts spinning like juggernaut making him spell immune, as well as the spin will deal massive amounts of damage and also act like a black hole and sucks you in (there is a channel time(around 1-2 second(s)) and visual cue for this).

Then when the Weaponsmaster reaches 40 % HP he will also fire homing missiles at every player in the boss area that stuns and does massive damage, the only way to counter this is either to purge it or run away until the homing missiles dissipates (it's slower than Gyro's homing missile) also he will also be able to send out air slashes while spinning (visual + audio que). Also by the way, he can do all of these abilities AT THE SAME TIME. Also he has a chance to instantly jump after spinning. 

Right now you're probably asking "HOW THE HELL ARE WE SUPPOSED TO KILL HIM ?!?!!?!", well the answer is simple, there will be time periods after the Weaponsmaster spins where he won't do anything at all, and also while he is channeling his spin ability meaning you can stun/silence him while channeling this ability to prevent him from using any of his abilities because this is a boss fight where stun/silences are your best bet in killing this boss.

His final and on my opinion his most frustrating stage is when he has 10% health remaining, because at this stage he will do.......   NOTHING, absolutely nothing....

Well except using a spell to run away from you making you waste your time trying to kill this boss and get nothing in return... Yep this is the BS part about this boss, he is a god damn bitch because when he is on 10% health or lower he WILL cast a channeled spell to run away from the fight with a channel time of 2-5 seconds ? maybe, I really don't know how long this should channel. So you're going to have to deal enough damage around said time to kill him while he still has a massive spell and physical damage reduction.
Also, you should notice something interesting about what spell he uses to get away... 

Yep, his escape spell is a CHANNELED SPELL making him vulnerable to stuns and silences which will extend your time frame of killing this boss before he runs away.

Extras : 
The boss will purge all negative effects every 5 seconds ( only for the final stage of the fight (so people can't just stunlock him for an easy kill)
This boss is inspired from a boss in Final Fantasy.
His homing missiles casts automatically when its cooldown is off.
Will instantly cast spin if he hasn't cast it in 20 seconds.
There will be around 10-15 seconds interval after he has finished spinning to cast his spin again.
If you fail to beat this boss (he runs away), either the boss camp spawns another boss from the same tier or from a higher tier (I still don't know about this one)

Additional abilities (Optional):

These are abilities that this boss might have when he has 30%/20% health remaining which could be added if this boss is too easy to beat which are : 
- The boss will be able to move while spinning (doesn't cast homing missiles if he moves)
- The boss uses a hammer to create a fissure that will stun you for a long time (can be used while spinning and moving)
- Throws axes in a circle around him that will disarm anyone it hits.

That is all I can think of about this boss at this point and time, I designed this boss to be a very misleading boss since for one second you think that this is an easy boss and then it changes 180 degrees once it reaches 50% of his HP, and also the heavy reliance of stuns and silences against this boss will make the usage of stun gun morphling, and mirana very important for this boss fight, as well as the many heroes with a lot of stuns as well. This boss will also prevent full carry teams and full rightclick item builds to beat this boss because unless you have a beyond godlike luck with bashes for the final stage of this boss,you will get nothing for your efforts in trying to kill this boss. Well that is all for this boss idea, I hope you like this boss idea, and if you don't I'm sorry for wasting your time, and for your attention I give you my thanks.

Edit : 
I forgot to mention that someone else should make the lore, I still have 0 ideas about his lore.

**Comment by l34Um1** [comment]
Overly complicated and not interesting. Closed.
