### ISSUE TITLE
We are electric Boss theme and the "Soul of storm/lightning"

### ISSUE THREAD

**Issue by preddator32** [AngelArenaAllstars/suggestions#203]
# Continuing with my previous Elemental bosses idea

### Brief discription
The boss is all about electricity (duh). His active skills shoot electricity, his passives work on electricity principles, he also can't ever shut up about the electricity. Yeah, very original, right?
Back to the point: he has innate evasion from all sources of phys dmg, while his magic resistance is pretty low (might be even 0). But casting spells on him potentially might cost you lots of hp. He is immune to almost all stuns, with minor exceptions breaking through everything (like "Black hole" etc). Starts with 0 mana and 1 % mana reg/sec (his manapool should be big enough to not get countered by the manaburn completely, but make it quite usefull in battle against him (also something shoud be done to prevent total anihilation by the "Mana void", don't know, what exactly, duh). Also, I would consider, making his attacks deal magic dmg instead of physical. 

### The Arena
His arena is some swamp-like place. Picture myself maps from the night elves campain from WC3FT 
(loo
![warcraft-3-the-frozen-throne-large-44](https://cloud.githubusercontent.com/assets/25621583/23097962/64d11d16-f653-11e6-9662-0dfc52d80535.jpg)
The closer to the center of the arena the more water is around (but there are still lots of tiny isles (u will see the point). 
There are two "Grounding pillars" on the arena (on water surface). When used (takes about 3 sec to activate) pillar casts shackles of the Boss (like Shadow Shaman's, but blue). They STUN him for 5 sec burning 60% of his mana (10% mana = 2% Hp loss). If he runs out of mana before shackles end he gets stunned for 5 more sec. Have 50 sec cooldown.

### Abilities:

1)Neon Body - Passive: Due to his Electric nature, he is partly immune to physical damage.
Has 25% chance to avoid physical damage (both spells and rightclicks). Kinda old Void's passive, though gets countered by True strike and might be disabled with items like Silver edge. Regenerates 10% of his max mana per spell cast on him.
2) Static charge - Active: That's basically Razor's Plasma field. It deals decent damage and stuns for about 2-3 sec. Though it goes only through water and can't deal damage to characters standing on land( that's the purpose of isles). 
Costs 25 % of his max mana.
Has 12 sec cooldown and some delay on cast (about 2-3 sec). While Razor casts it he uses his tp animation (to let u know he is about to start his electro-show).
3) Ball lightning - Active: He emits 8 electric balls, moving to all directions from him by serpentine trajectory. If is hits someone - deals AOE damage and shocks him (stuns for 2 sec). If the hit target stands in water, after 1.5 sec delay the effect of the ball spreads to the next closest "wet" person. And so on. The charge of one ball can't hit the same targer twice. Though the effect (as well as dmg) might be reapplied from the other hit ball lightnings. 
Balls' ms is 200. (Any faster will probably cause the chain reaction one-spell teamwipe)
Costs 50% of his max mana.
Has 20 sec cooldown and 1.5 sec delay on cast.
Balls disappear, reaching arena's edge.
4) Raging storm - Active: Creates "Eye of the storm" clouds above each hero and the Razor, which move in random directions over the arena with 75 ms. Every 4 sec they generate one charge that comes on enemies in 125 radius in form of "Thunderbolt". Deals decent damage and causes a ministun. The damage spreads through water, though doesn't stun other heroes. The cloud above Razor is special. It deals less damage, hits the closest target, has 1 sec cooldown, but replenishes his mana (5 percent per hit) and applies "Static anomaly" effect on hit target (up to 5 stacks). Creates an aura effect that drags clouds to the source of the aura (the radius of dragging is 100/200/300/400/500). Clouds will be dragged to the closest hero with the aura ( in case of different people having stacks).
Costs 95% of his max mana.
Has 3 sec delay on cast.
Endless. Stops on death or when there are no heroes on the arena.

### Stages:

- 1)Full Hp- The Boss fights in usual ways. When he has enough mana he uses his 2nd ability. Everything is pretty obvious.
- 2)70% Hp - The Boss saves his mana for his 3rd ability, though when it is on cooldown he actively uses 2nd.
- 3)35% Hp - The Boss uses all his skills, prioritising his ult.

### Ways of winning:
1)Poke him to death (very gimmicky, I know).
2) Use the pillar, Luke! They should be pretty effective. One by one they might be used at the very beginning of the fight to stun the Boss and skip the first phase almost entirely, and both of them afterwards, to deal lots of damage and protect yourself from his active spells by getting rid of his mana. The point IS - activated at the same time pillars burn through 120% of his mana (while he is capable of regenerating only 5 % for the whole shackles' duration, what garantees 5 sec stun and (at least) 20% of his Hp burned, if timed perfectly.

## The "Soul of lightning"
The soul of the boss, as well as one dropping from the Phoenix in my previous suggestion (https://github.com/AngelArenaAllstars/suggestions/issues/88), will contain his mana and spell manipulating powers, as well as his defensive abilities.
Here are its effects:
Evasion (the same the Boss had) (15% - 45%). Increases for 1% with every damaged evaded.
Adds (25%-55% of your current attack damage) magic damage to your strikes. Increases for 3% with every enemy killed/assisted).
Spell damage conversion - absorbs and turns 15% of magic damage taken into your mana. If you have max mana causes "Energy overflow" proc.
Energy overflow - deals (200-500 magic damage) and burning the same ammount of mana in (100-400 AOE). Increases for 30 with each proc.
Gives + 1% mana reg per sec.
Downsides:
Decreases spell resistance to 0. 

### Conslusion:
The Boss concept seems not that bad to me. Gives players some unique experience as well as some nice item, which might be a great thing on such heroes as Wraith King, Medusa (or even Antimage). 

## Afterwords:
I tried my best to take to account the advice I've got after my last post. This one should be a bit easier to read..I hope.. Wanted to make this boss's fighting style a bit more related to the arena itself. Also, the 2nd Soul Orb (Soul of Lightning) item is meant to be a good addition for rightclickers, while previous ove (Soul of Fire) was utterly casters' theme. However, I'm still sure, that such effects don't really need to take an item slot (because: 1st-  such rarity shouldn't be possible to just be dropped; 2nd - it doesn't really need any upgrade, cause it gets upgraded by itself (more like by your actions even). So I think, they might be much better as consumable-passives. But nvm, would be happy seeing these accepted either way ^^

### Waiting for your responds and hope to share some more ideas in couple days!

**Comment by preddator32** [comment]
### Energy overflow "fix-buff":
The wave of the effect (something like Invoker's EMP) also applies 0,7 sec 70% slow on all movements of hit enemies (atacks, casts etc).
Has (12-6) sec cooldown (decreases for 0,1 sec for each proc)  !OR! uses (dmg + range)/2  mana points on activation (to prevent endless devastation AOE on every instance of magic dmg). Guess, cooldown would be much better in general (for the point of the item - make you never really run out of mana in fights).

**Comment by preddator32** [comment]
### Some Boss rebalancing

Razor's passive mana reg:
Should be incresed from 1%/sec to 2/3/4% on every stage.
Pillars' manaburn:
Increased from 60% for 5 sec to 65% for 3 sec. Looks like a big buff, however shorter shackles' duration means shorter disable period for the Boss. The way of burning all his mana by activating both the pillars at the same time is still avaible (130% -(100%+12%(mana regenerated in 3 sec in the final phase)=18%. 18/4=4,5 sec to think about your life before activating the second pillar after first one to guarantee the 5 sec stun).

The general purpose of the change - make the Boss capable of casting his spells frequently enough even without heroes using their own spells on him.

**Comment by Haganeko** [comment]
Thank you for your continued contributions.
Rewriting the post to remove fluff would help with readability, which is currently not stellar. Use the template from #37 as well - it is very useful.

**Comment by Wujekklawy** [comment]
Can you a little enhance text? Its hard to read when important stuff look same like not important stuff.  It's not a lot of work ;) you can take my submissions for an example ;)

**Comment by Wujekklawy** [comment]
Ps, you know that you don't need any oudside programs to create screenshots? You can click "Print Screen"  on keyboard and paste it to any graphical program,  even paint.

**Comment by Haganeko** [comment]
This is very complicated and depends on the custom arena. Closed.
