### ISSUE TITLE
Bob Ross Boss

### ISSUE THREAD

**Issue by Patrickthehuman** [AngelArenaAllstars/suggestions#208]
# Bob Ross Boss

## Arena
The arena for this boss can be plain as the boss will create the terrain elements during the fight

## Description 
The boss just needs to look like a painter. A palette and brush in hand. _(Extra style points for an Afro)_

## Phase One 100% - 80%
Bob traps players in trees _Like in Furion's Q_ only half of which despawn after the spell effect is over. The aim is to place about 20 trees in this phase. It might be necessary for Bob to spawn the remaining trees upon the end of this phase as the players might kill him too quickly. During this phase and all other phases Bob whacks the players with his brush as an auto attack.

## Phase Two 80% - 60%
Bob stops creating trees _The trees can still be cut down however_ and begins throwing rocks into the arena which are targeted on heroes and should be made hard to dodge. The rocks stun and damage heroes upon impact. the rocks remain in the arena and cannot be destroyed by any means. about 10 rocks should be thrown in this phase. in a similar fashion to the trees the remaining rocks should be spawned at the end of this phase.

## Phase Three 60% - 40%
This is more of a pseudo phase to highlight the upcoming transformation. Bob stops throwing rocks _The remaining rocks cannot be destroyed_ and begins to draw a circle surrounding the entire arena.  The circle grows smaller until it touches Bob Ross and upon doing so causes a high damaging knockback explosion which sets his hp to exactly 40%. 

## Description 2.0
So shit starts to hit the fan and Bob Ross your beloved friend and inspiring painter has sacrificed his soul to become an awesome... I mean terrifying Demon. This dude is literally insane and since the inspiration for this next phase comes from Warcraft's Mal'Ganis (or at least how the Hearthstone card works) this boss should probably look like him

## Phase Four 40% - 0%
I'm so edgy my boss has four phases. This is where the fight gets really interesting. After the knockback explosion Bob has sacrificed part of his soul to become a demon and upon the activation of this phase he starts turning the terrain features into creatures that fight for him. He is invulnerable but does not attack in this phase until every creature has been defeated. He should start with the trees _Creating powerful treants_ and and then create stronger creatures by raising the rocks _Creating Warlock Golems (aptly called the rock by some dota casters)_. After all the creatures have been defeated he is once again vulnerable and will attack the players with an arsenal of fiery spells such as Chaos Meteor, Light Strike Array, Liquid fire, forge spirits and Doom. Since this boss' talent is summoning minions he should prioritize attacking summoned units in the arena before heroes as he sees them as an insult to his artistic and beautiful creations.

**Comment by prodigiousking** [comment]
Lol i like it i dont think they will implement it though

**Comment by Patrickthehuman** [comment]
I don't think so either, but it's all part of the creative process. Someone might come along, see this and draw inspiration from it, and come up with an entirely new boss that is just better. It is important keep the ideas coming so that sometime soon we might hit the 42 boss goal!

**Comment by Haganeko** [comment]
This is pretty interesting. Please try to format it according to #37

**Comment by Haganeko** [comment]
The description is hard to read, and the different phases don't seem related at all. Closed.
