### ISSUE TITLE
[Boss Idea] Balance in all Things

### ISSUE THREAD

**Issue by AceXS2X** [AngelArenaAllstars/suggestions#209]
Well hopefully nobody has suggested this yet

**Inspiration**
I was thinking about boss mechanics and I thought about this one

**Mechanics**

This boss is a boss that doesn't attack you at all, but : 
-Gets more physical resistance if you deal physical damage to it but reduces its magic resistance and vice versa(max 90%)
-The arena has 4 obelisks/spires/towers/whatever that apply an aura that reduces your magical and physical damage resistances and only vulnerable when the boss is at 50% health.
-Has an AOE spell that does magical or physical damage that does a percentage of your health (70%-90%)(damage type based on its resistances)
-Casts silence when its physical resistance is at max and disarm when the magic resistance is at max to all heroes in the arena.
-The boss is a white orb, but turns red if there is more physical resistance and blue for magic resistance

**How to Beat**
Well constantly rightclicking this boss is a horrible idea, as well as spell spamming, well it can work but it will take forever, not to mention that you have to dodge the boss's massive AOE spell, cause if you don't, well RIP in pepperoni my friend. Heroes for this boss either need have the ability to resurrect, prevent death, or negate/reduce either magic or physical damage to survive the AOE are useful in this boss fight, otherwise you're going to have to run everytime the boss starts casting this spell, however taking down all of the buildings will remove the resistance reduction aura making you able to survive one of its AOE, also it is recommended to use heroes that can deal a lot of damage in magic and physical damage in a small number of attacks. Also as the title suggest this boss AOE spell will deal 0 damage if its physical and magical resistance are equal.

**Other**
I really don't know if this is too complicated of a boss to code in but I just suggested this because I thought it was a cool mechanic of a boss and well I also thought about the buildings also attacking with spells with blue and red circles representing the type of damage it will deal, but i think it'll be too complex to be put in.

**Closing Remarks**
I apologize if this boss is too complex, I just thought this was an interesting idea, also for your attention I give you my thanks.

**Comment by Haganeko** [comment]
Interesting concept, but it raises a few questions:
Does the boss have phases? We're trying to give bosses phases (generally three) so that we can introduce their mechanics one at a time.
Silencing when at maximum physical reduction and disarming when at maximum magic resistance seem needlessly punishing.
The spell seems too harsh as well. 70% max health as damage at a minimum is *a lot*. How large would the area for this be?

**Comment by Haganeko** [comment]
Additionally, you may wish to reformat the post using the template on issue #37. it will add clarity and make reading and discussing your idea easier.

**Comment by Haganeko** [comment]
None of the issues with the suggestion have been addressed. Closed.
