### ISSUE TITLE
Boss idea (Charger):

### ISSUE THREAD

**Issue by VoidsKeeper** [AngelArenaAllstars/suggestions#21]
Boss fight idea:

When you tp to the boss dungeon from the portal room , you'll be greeted by a Horseman/Centaur/Minotaur(basically anything that looks like "it wants to charge straight at you" will do). The arena should be(imo) in the shape of a circle with a few pillars(3-5 will do)

1)
So , the fight begins. At first this is just a normal right-click boss with a lot of armor and health. Just beating it will do for now.
The boss will slowly move around following the players. It attacks slowly , but deals a lot of damage (physical). Maybe give it a stun (Centaurs would look nice) and some leap-smash ability (jumps-->falls-->hits the ground-->does damage(physical) and maybe lowers some other stats for the attackers)

2) When the boss's HP drops to a certain amount (maybe 60-50%?) it becomes enraged , drops its weapon and , with a decent channel up,  starts running towards the SLOWEST hero around (Dunno at what speed , but it should be enough to outrun the targeted hero). 
At this phase the boss takes 80% less damage from all attacks  (except "pure" of course) , so it is advised to not attack him. The only "weakness" the boss has is that it doesn't stop running until it hits a wall/pillar or the TARGET
If the TARGET gets hit whilst the boss is charging , the boss stops and slams the hero into the ground , beating him up for some damage(it should work like Pudge's ult: holds in place and deals damage over time). While the boss is doing this to your ally is your chance you attack(the boss becomes vulnerable  , now losing his 80% damage reduction and instead gaining 20% more damage taken from attacks for the duration of the stun) (dunno how much time this will last).
If any other hero gets hit while the boss is charging at the TARGET , it'll be "bashed" for a fair amount of damage.
If the boss misses the TARGET then it'll either hit a wall or a pillar which will stun it and make it lose its 80% damage reduction buff and gain a 50% more  damage taken debuff for the stuns duration .  (Upon hitting a pillar , the pillar should break?)

3) (less than 20% HP)
The boss becomes magic immune.
The delay between the channel and the charge is shortened.
The strategy stays the same until you kill the boss.

Note: the boss doesn't always charge at phases 2,3 , but it does have the buff of 80% damage reduction (so the heroes should mostly run away or tank somehow). It still uses its other abilities and still hits with its normal (slow attack speed) attack. But the boss should use its charge attack fairly often in order to let the players fight back and not just stupidly run around forever.

**Comment by VoidsKeeper** [comment]
Correction: the numbers should be 1,2,3 and not 1,1,2 in accordance to the phases descriptions  D: Sorry if anybody got confused

**Comment by warpdragon** [comment]
* The magic immunity at phase 3 is a little bit silly. Replace it with something interesting. As it is now a team could be perfectly capable of getting the boss to 20% but no further (which is rage inducing).
* I like the idea of the pillars breaking after 1 (or more) impacts.

**Comment by Haganeko** [comment]
Maybe when the boss charges, his target gets slowed to a fixed speed? Should make it easier to predict the collision.

**Comment by VoidsKeeper** [comment]
How about this: phase three of the boss doesn't have magic resistance , but makes the boss have improved attack speed whilst not charging?

**Comment by VoidsKeeper** [comment]
Or something else , if anybody has good ideas

**Comment by l34Um1** [comment]
Love the pillar idea, definitely using it. Closed.
