### ISSUE TITLE
Small Item Ideas Dump 3

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#210]
Mana Umbrella: Cast a small AOE that gives an early to midgame team mana buff (regen gain or something like KOTL/OD).

Staff of Forest Friends: Consume a tree every 60 seconds. Gain a critter that gives a random stat boost which gets better over time. The critter can be killed by players and creeps, and yields gold comparable to its current level of development. You can then breed your critters to add to your critter index count, where you gain achievements for completing certain cultivors of critter. Players can then battle or trade creeps in a separate IOS and Android game called Baumi Critter Arena, with a match three minigame. Players can then buy currency to level and evolve their critters faster in Angela Arena 2. You can also buy

Magma Boots: Turn the boots on to leave a trail of magma to slow and burn anyone who walks in your path.

Bubble wand: Spray out bubble that pushes enemies away in a tight formation.

Bubblegum Wand: Surround yourself in a Bubble, which makes you invincible and only able to move. Grants flying. When the Bubble ends, one meele range enemy is stopped.

Dash sword: Inflict a piercing attack on enemies in a line, dashing through them.

Wrestler bands: Grab an enemy, spin them, and throw them at target location.

Punting shoes: Stun an enemy, then kick them within a random arc in the direction you're facing.

Telekinetic Displacement: Your next ability occurs at any selected location on the map.

Globalism: Your next spell is global.

Freezing infusion: Your spells cause a slow (skadi for spells). 

Fire orb: When active, your physical attacks become split into a magic damage DOT debuff. 

Rolling bear staff: Turn into a bear and roll. 

Magma Suit: Usable item, makes you invulnerable to magma boots.

**Comment by AndrewLouw** [comment]
Bubble wand works like gust but no silence -this is a good idea 
Dash sword is good - essentially is sleight of fist in a line and it moves you - good for getting at backline
Freezing infusion - could be made to work if it was a debuff aura which causes slow on taking magic damage (otherwise the coding is a problem)

Most of the others suffer from the following issues:
1) You high? - Staff of neopets, bear staff 
2) there is no reason to buy them - reworked eules, reworked force staff with no extra functionality. 
3) fundamentally change the game - everyone is global

Thanks for suggestions though

**Comment by JSampersand** [comment]
Staff of greased chest hair: Grow chest hair and movement is now reworked to sliding on chest. Napalm ignited when taking fire damage. 5% chance that enemies in aura range stop and vomit at the sight of your greasy chest hair.

**Comment by JSampersand** [comment]
Item with long cooldown: The next non-ultimate skill you use, get 5 copies of that skill.

**Comment by Haganeko** [comment]
Some of these are clearly jokes ("Staff of greased chest hair"), others are copies of abilities from dota ("Magma Boots" are a nerfed Firefly).
Please open a new issue with the serious ones.
