### ISSUE TITLE
Boss Idea, Gopherlord

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#211]
Arena has five holes in a dice pattern.

Boss phase 1 starts in center hole. Autoattacks. Pops down under hole and heals for a bit. No indication to what hole he will pop out of is given. Once he pops up there is 2 seconds to get out of the way before he lets loose a very powerful AOE slam that covers that corner of the arena does damage and ministuns. Boss resumes phase 1. Since the boss heals every time he burrows its hard to straight up kill him in phase 1 but it is possible. The final mechanic that makes phase 1 interesting is that heros can select a hole(melee range) and channel an ability that will destroy the hole. Note the boss will automatically activate his burrow attack if noone is in his aoe and hopefully he has enough damage that there needs to be at least 3 people occupying him or else he will make short work of whoever is tanking. Additionally the aoe is large enough that it is very hard to escape the aoe in time if he pops up while you are channeling which means that you can either give up and save your HP or gamble and continue channeling and hope he pops up at another hole (note the aoes ministun means you cannot tank it and channel). 

Phase 2. Its actually somewhat easier than phase 1 since phase 1 is somehwat complicated now this is up to you and you can change the difficulty of either. But without holes the boss now remains on the surface(for the most part) and actively seeks out heros. He has a special attack where he burrows under the ground and zips around. You can see where he is undergtound at all times by the earth being pushed up (like burrowstrike or burrow). I thought that either he could move around and if he catches someone then he instantly pops up and does a large strike dealing massive damage. However if after a certain amount of time he does not catch anyone he pops up and does not move for a bit (he is tired) giving and opening for attacks. He does not heal underground and I actually didnt  even imagine him invulnerable because noone should be attacking him because the risk of  him catching you is too high.

The lore is he is a giant mole. He could also have spikes on his back.

**Comment by prodigiousking** [comment]
Lol I said mole I meant gopher

**Comment by prodigiousking** [comment]
Alternate idea that would make round 2 harder instead of not moving after he is done with a burrow attack the boss would instead proceed to spew a constant aoe stream that has a certain width and he rotates around while spewing it. Lore wose this is the dirt being spewed from his gopher pouches

**Comment by Haganeko** [comment]
Try to be more mechanical in your description. There are examples in the main repo (look up "implement Mirror boss" for example).
Additionally, you may wish to use the template on issue #37 for clarity.

**Comment by Haganeko** [comment]
There seems to be no mechanism for phase transition, and the whole thing is unclear. Closed.
