### ISSUE TITLE
Item Idea, Tangerine Core

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#212]
Name is a work in process

Build up: octarine core+ octarine core + boss item(of your choice or i can make one if you want)+ recipe

Effects:
Stats 
Passive increase the duration of all buffs by___%
Passive increase the amount of dot procs by ___procs
Passive decrease cooldown of spells by ____%
Passive + ___% spell amp
Toggle: increase or decrease the duration of channels by ____ seconds

I figured this would be a good idea for a superpowerful caster item if you still needed one of those. This might be a bit OP the bit that inspired me was an item that increases the duration of dots, buffs and channels (the channel increase is toggleable for heros like shadow fiend and sand king) Idk about balancing so I left the numbers blank.

**Comment by prodigiousking** [comment]
It could also decrease the duration of debuffs if you wanted

**Comment by prodigiousking** [comment]
Tought of a bit of "lore" and an item name as well as a different possible mechanic. The item name would be Ezras timekeeper or something like that and it would be an hourglass made of what looks like 2 octarine cores. The alternate mechanic would make it a bit weaker more fitting lorewise and possibly more interesting mechanic. The toggle would affect time indiscriminately and affect danage inversely, increasing the cooldown of any spell used under the toggle as well as the duration of any dot, channel ,buff, or debuff while decreasing spell amp. Or on the other side of the toggle it would decrease any cooldown duration while also decreasing channel, dot, buff, and debuff duration while increasing spell amp. Idk about this mechanic now that I have it spelled out.

**Comment by warpdragon** [comment]
what a really clever idea. do you see anything wrong with this item?

**Comment by VoidsKeeper** [comment]
I don't see any problems. Only balance-issues

**Comment by warpdragon** [comment]
Hell yeah! But you gotta give it a better name, JEEZ
Tangerine core?

**Comment by prodigiousking** [comment]
How about Metatron's Timepiece. This is angel arena Metatron is an archangel.

**Comment by warpdragon** [comment]
I was thinking Trampoline Core, but thats good too!

**Comment by AndrewLouw** [comment]
I worry that the implementation of this will essentially involve remaking every single item (for the duration and dot) but in terms of a general boosting item to have a spell god i'm all for some solid spell amp and cd reduction. if you're making it from octarine you'd get spell lifesteal too, it'd make spell casting a viable carry strat

**Comment by l34Um1** [comment]
Not different enough from CD reduction. Closed.
