### ISSUE TITLE
Azazel

### ISSUE THREAD

**Issue by RighteousBacon** [AngelArenaAllstars/suggestions#213]
_Here is Azazel, the Middle Boss, as was agreed upon after the Town Hall Meeting._

**Description**
Azazel taught mankind to make weapons and cosmetics, for which he was cast out of heaven. In AA2, he is the boss in the middle of the map. When Azazel is defeated, he becomes a shop. Both teams can use this shop to buy boss items of lower boss tiers. He will likely be a tier 5 boss (the highest of them all).

**Appearance**
The arena in which Azazel is located is rather small compared to other boss arenas, and Azazel himself is only slightly bigger than a hero. He wields a crossbow that can shoot 2 bolts at once, which is his greatest invention and the one he uses throughout most of the fight. At phase 3 he wields a short spear.

**Abilities and phases**

- **_Phase 1_**

Crossbow Attack: _Azazel shoots 2 bolts into the air that comes down after a short delay with a visual indicator._

Regular ranged rightclick.

- _**Phase 2**_

As soon as phase 2 is triggered Azazel shoots (2 bolts) from his crossbow. As the bolts land he teleports to one of them, while the other location spawns an illusion.

The illusion and Azazel are linked up together. They then move in a circular fashion around the arena. If you touch the link, you get damaged and stunned. Both Azazel and the illusion still do regular ranged attacks during this. 

If you damage the boss enough, the illusion disappears and Azazel enters phase 3. If you kill the illusion he receives damage, which is just enough to trigger phase 3.

- _**Phase 3**_

He gains a spear, becoming melee.

Spear Ability: A swiping attack that after a windup, pushes enemies caught in it across the arena.

Meatballs: Meteors start raining down, leaving permanent fire marks where they land.

**Boss Item**
Azazel's Crossbow: Select 2 AoEs, deals damage based on your attack damage.

**Comment by prodigiousking** [comment]
Coooooool

**Comment by prodigiousking** [comment]
As for the effect of azazels crossbow it is confusing. Are the AOEs rigid in repect to eachother as far as distance between them, or do you get to select both AOEs. I figured both bolts would fire at the same time and it would be a true AOE (not like snipers ahgs) based on the boss. Also i imagine that range, cooldown, mana, and % of attack damage will come during balancing.

**Comment by RighteousBacon** [comment]
This post is in the wrong section. It's supposed to be in aaa as an "implement boss" issue. Closed. Hopefully.

**Comment by prodigiousking** [comment]
Where would you see this implement boss thread.
