### ISSUE TITLE
[Mechanic] Aggro System

### ISSUE THREAD

**Issue by christopherwira** [AngelArenaAllstars/suggestions#214]
So i propose an aggro system.
The aggro here is in a form of debuff, the hatred. This debuff is cast by the boss every time player deal X damage to the boss ( example : 1000 damage ). The boss always target or attack the hero in arena with the highest stack. The tank and DPS have more control on how the boss will attack them. The bosses only checks their own aggro buff. The good thing using this mechanic is : 
1. The player can check and manage their own aggro according to their own role.
2. There is a certain item or skill that help the tank to generate more aggro like lowering the threshold X for the boss give the aggro stack
3. There is a certain item or skill that enable the "Taunt" that targeted to a boss by a hero that gives an instant stack of aggro for a certain duration.
4. There is a boss encounter where the boss is more than one, the player can manage their own aggro on each boss and build a certain strategy like kiting one boss and dps the other.
5. There is a certain skill or item that reset the aggro stack ( ex : invisible )
6. There is a certain skill on boss that the boss deal a lot of damage in a certain area ( ex: Huge cone area in front of the boss ) and the tank must make the boss face properly so the entire team not get wiped by the boss.
7. There is a aggro switch strategy on the team when the boss is dealing based on stacked damage ( ex: fury swipe, shadow poison ) and need a minimum of 2 tanks so the tank can survive the damage.

**Comment by Haganeko** [comment]
This seems very complicated.
