### ISSUE TITLE
[Boss Encounter] Azazel Phase 3 Meteor with Aggro System

### ISSUE THREAD

**Issue by christopherwira** [AngelArenaAllstars/suggestions#215]
So i have a little proposal about the Azazel meteor phase. The fire of the meteor is not crossable safely ( either with very high damage or raigor like fissure ). The meteor is land on the middle of the arena and walk towards the current position of the highest aggro hero in arena. 

This enable the strategy for the player to place the meteor nicely. The best strategy is the highest aggro ( tank ) is only move a bit every time the meteor land and stand as close as possible to the edge of the fire so the next meteor is close to the current fire. If the tank is not stand properly. they will fragment the arena and the time to beat the boss is shorter.

**Comment by Haganeko** [comment]
Azazel has been discussed an is okay for now.
