### ISSUE TITLE
[Item] Soul Breaker

### ISSUE THREAD

**Issue by Kolkonut** [AngelArenaAllstars/suggestions#216]
Mid to late game item, self targeted effect, intended for casters/tanks.

**Switches mana and health pools as well as their values.** Returns them to the original values after x seconds. 

_ex_. Pudge has 4000/5000 health and 1000/1500 mana. He uses the soul breaker. Pudge now has 1000/1500 health and 4000/5000 mana. _(Values not certain, just example.)_

**Health and mana cannot be switched beyond certain base values.** That is, a hero must have at least X health and Y mana to use the item.

Provides nearly no stats. A good amount of HP/Mana regeneration and pool.

Builds from Soul Ring + Vitality Booster + Energy Booster.

Can be upgraded by crafting with more Soul Rings.

**Comment by christopherwira** [comment]
I have a suggestion that this item is reworked to become a toggle item that switch the hp and mp without cooldown but with a hp and mp percent cost every toggle.

**Comment by AndrewLouw** [comment]
Toggling hp gains can be awkward with the abuse that came with the old armlet. But aside from that can you think of any reason to ever buy this item? The only use i can think of would be for synergy with a high mana regen item or ability.

**Comment by VoidsKeeper** [comment]
Thanks for the suggestion  ;)
I'll post this at the next Townhall

**Comment by l34Um1** [comment]
Too complicated, adds little value. Closed
