### ISSUE TITLE
Ahgs mechanic

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#217]
I think it would be cool if ahganims was a very significant commitment to aqquire(boss item/lots of money) or if it was just an upgrade that was hard to get and it gave heroes amazing, broken, and crazy ahgs effects. 
For example:        Note    ●= personal favourite

• Crystal Maiden- + 30 mana regen aura, no cooldown on ultimate
• Alchemist- Permanent chemical rage,  unstable concotion can be toggled to autocast and has full charge instantly
• Earth spirit + 15 stone remnant charges
• Ancient Apparation- Ice vortex + 500 radius, + 100 cast range, + 15 % slow and spell amp
• Pugna- infinite range on nether ward and ultimate, but must have vision
● Dark Seer- Wall is longer, illusions are more powerful, and it rotates about its center
• Legion Commander- reset bonus damage to 25 each duel doubles the amount of bonus damage
• Nyx Assasin- Can move while burrowed 
• Permanent shapeshift and wolves do not have timer for Lycan 
• +2000 attack range for sniper
• Permanent nighttime for night stalker
• Permanent split shot for gyrocopter
• -75% mana consumption for storm spirit
• Essence shift steals 9 stats for slark
● Lone Druid- 3 bears 
• Troll Warlord- No max attack speed or fervor stacks
• Tidehunter- 3 ravage charges 
• Zeus-Thundergods Wrath does + 30% maximum HP in additional damage 
• Spectre- Dispersal upped to 50%, Desolate always applies
• Treant- Ulti range up 1500
• Natures Prophet- All vision
● Morphling- Strength and Agi stat are combined and shared, adaptive strike does max damage and stun
• Enigma- Black hole is an 1000 radius aoe around enigma
• Winter Wyvern- Toggle doesnt cost mana and, every 4th attack is a splintershot
● Witchdoctor- plus 1000 cast range, Ultimate now summons three death wards in a triangle around targeted spot and maledict is cast inside the triangle,  ward attacks bounce twice
• Weaver- Duplicate attack becomes quadruplicate attack, shukuchi is like riki perma invis
•Brewmaster- Brewlings buffed, Ultimate is a toggle. Individual brewlings respawn timer is half of the normal respawn timer.
● Omniknight- Ultimate lasts longer, still global heal is stronger, Casting the heal now affects all untis in the ultimate, and buffs are shared by all units in the ultimate
• Antimage- bloodseekers thirst but stronger and with mana not HP 
• Terrorblade- now summons 2 illusions per pop, shapeshift is a toggle.
• Mirana- Sacred arrow shoots 8 arrows around her in all directions in addition to her aimed arrow, and when the arrow connects it casts a starfall in the area
• And Many Many more

 Once again this item would be very very hard to aqquire (maybe even only 1 per team/game) also maybe some of these ideas could be used but toned down a ton as far as power level. The only issue i see besides balance is people fighting over who gets the cool as fuck spells.

**Comment by prodigiousking** [comment]
Idk what i was thinking writing this.

**Comment by zelding** [comment]
I think the ideas are cool, even tho most are `OMGLOLWOW` level op.

This could be a new endgame item, an **aghs lvl 2** if you will. Just keep in mind, that this would require an extensive amount of extra coding - basically all modified spells would have to be created from zero, and all affected heroes would probably need a good amount of patching up too.

**Comment by prodigiousking** [comment]
Yeah OP but cool af

**Comment by VoidsKeeper** [comment]
I believe, Agh's upgrades and how they work has already been discussed at multiple Townhalls :/ (And they won't do such things ,cause it'll be messy af)
But , I mean - miracles happen , so don't close the issue and wait for Baumi too look at it

**Comment by prodigiousking** [comment]
I wonder if they could be modified talents instead.

**Comment by Wujekklawy** [comment]
morfilng evry game... no thx...

**Comment by prodigiousking** [comment]
Why would it be morphling every game
These are endgame mechanics not available until after probably 30-40
minutes (depending on how long baumi aims to make games). Additionally why
morphlings is very strong it can always be nerfed such as 80% of strength
and Agi are shared, and I would not even consider it the strongest on the
list.

**Comment by prodigiousking** [comment]
I have a new idea it borrows off of a few things. First this is angel arena
and i think it would really be cool if we upped the whole theme. Baumi
mentioned an insta win boss. Winning could be considered the ultimate goal
or Heaven, therefore that Boss you defeat should be Satan and when you
defeat him God "sees your righteousness" and takes you to heaven/you win.
However if you decide to face God instead of Satan and beat him Satan gives
you insurmountable power in the form of these OP af abilities affectivly
turning you into god ranked heros you dont win the game but you pretty much
are going to because you are so damn powerful plus its more fun.

**Comment by Wujekklawy** [comment]
i have one problem with "some" of them... too op

**Comment by prodigiousking** [comment]
I mean but of course. Most of them can be scaled back although a few are
fundamentally broken. I still want a line druid with 3 bears tho.

On Mar 7, 2017 11:47 AM, "Wujekklawy" <notifications@github.com> wrote:

i have one problem with "some" of them... too op

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AngelArenaAllstars/suggestions/issues/217#issuecomment-284782523>,
or mute the thread

**Comment by Haganeko** [comment]
Most of these would require extensive rework of spells and would be very hard to balance. I'm not saying no, but if these go in, they'll probably be some of the last things to.
