### ISSUE TITLE
[Boss Idea] Clock Boss

### ISSUE THREAD

**Issue by xXM1g420Y0lO5wAG8laze1tN05c0p3Xx** [AngelArenaAllstars/suggestions#219]
This boss is based upon the idea of a clock face and the hands of a clock.
Its uses the three hands of a clock for each of its abilities with the boss centred in the middle of the clock face.
(note: hands wont have to move at the real speeds of a clocks hands)

 **1st Stage**  The "_Hour Hand_" (the slowest of the 3):
This would start from the 12 o'clock mark and 'very slowly' move around the face of the clock leaving behind a high % damaging AOE effect that stays till the boss dies, Or till the players die.
(this forces a time limit on the players whilst also reducing the size of the arena and reducing room for movement.)

**2nd Stage**  The "_Minute Hand_":
This would travel around the clock in a similar way to the hour hand (but faster).
This hand would deal very low damage and reduces attack speed, movement speed and pauses cool downs for a long time on contact with players.
(This slows players down which puts even more pressure on them from the hour hand.)

**3rd Stage**  The "_Second Hand_" (the fastest of the 3):
This hand Travels around the central area of the clock missing the very outer edge at a fast speed.
This hand deals high damage and causes a very short slowing effect similar to the "minute hand".
(This hand makes it more difficult for players as they near the end of the fight and forces them to move away from the boss towards the outer edge slowing them even more.)

**Comment by VoidsKeeper** [comment]
The mechanic sounds intriguing. I wonder what the others think. I sympathize this idea.

**Comment by OriginalHastur** [comment]
It's sound great but shouldn't minute hand suppose to deal more dmg than the second hand ? It's easier to dodge right, so we should  punish those who didn't dodge it.

**Comment by VoidsKeeper** [comment]
The base mechanic is what matters  (an obstacle-evading -traning-ground boss has not been submitted or suggested yet). The rest can be discussed more thoroughly later with the the Captain and themembers of the coding,design,art and other teams. I'll pick this up on the next Townhall, if someone doesn't do it before me.

**Comment by Vafnar** [comment]
For an example to help people understand, could we look at the Arcane Punisher from Heroes of the Storm.
What he does is he spawns beams around him that deal damage to all things. What i am imagining is a clock face on the ground that the hands pass around as the players fight the center of the clock where all the hands connect. As the hour hand passes around it leaves behind a filled in area that the heroes cannot enter. This area when walked on will instantly kill the hero so as the heroes fight the boss they have less and less space to dodge the incoming attacks.

**Comment by xXM1g420Y0lO5wAG8laze1tN05c0p3Xx** [comment]
Yes what he mentioned is the general idea, as this is simply the raw idea of the boss with no balances or changes made so its completely up for interpretation and its in no way to be considered complete.

**Comment by l34Um1** [comment]
We are going to use the base idea. I don't like this impelementation. Closed.
