### ISSUE TITLE
[Boss Idea] Siege Tank

### ISSUE THREAD

**Issue by Jinjinjinrou** [AngelArenaAllstars/suggestions#221]
# Siege Tank MK-I

## Arena
A long narrow road with the same width as the siege tank. Has a fiery pit at the end of the road where the tank is headed to.

## Boss
The siege tank is a monstrosity of various scrapped weaponry welded together into a tank. Front has spikes that scoop upward from the base of the bumper. A flamethrower at the bottom middle of the tank. 6 spiked wooden wheels. Two rocket launchers at the top operated by two goblins.

## Phase 1 (100%-70% HP)
-[Long Range Spell]
The boss will periodically shoot 2-3 projectiles that will seek the farthest hero and mark the ground under them. After 2 seconds, the boss will cast a high damage AoE spell on those locations.

-[Melee Attack]
Bashes enemies forward by pushing everyone in front 500 units away from the tank and then stuns the affected hero for 1.5 seconds. Triggers when heroes stay too long in front of the tank.

-[Movement]
The tank moves forward in a slow and steady pace. Pushes back heroes as it moves forward.

## Phase 2 (70%-40% HP)
-[Buff]
The tank gains bonus damage on its attacks. 

-[Healing]
The tank stops for a few seconds to repair itself. All of it's other actions are stopped during repair.

-[Melee Attack +]
Bashes enemies forward by pushing everyone in front 500 units away from the tank and then stuns the affected hero for 1.5 seconds. Triggers when heroes stay too long in front of the tank. Also deals damage.

-[Long Range Spell +]
The boss will periodically shoot 2-3 projectiles that will seek the farthest hero and mark the ground under them. After 2 seconds, the boss will cast a high damage AoE spell on those locations. Also burns the targeted ground for 3 seconds.

-[Long Range Spell 2]
Flame Thrower
Siege tank will mark a strip of the road and then after 3 seconds will shoot out a high damaging beam.

## Phase 3 (40%-1% HP)
-[Buff 2]
Tank gains bonus movement speed and a slight boost to damage.

-[Healing +]
The tank stops for a few seconds to repair itself. All of it's other actions are stopped during repair.
Now moves during repair but stops all attacks.

-[Melee Attack +]
Bashes enemies forward by pushing everyone in front 500 units away from the tank and then stuns the affected hero for 1.5 seconds. Triggers when heroes stay too long in front of the tank. Also deals damage.

-[Long Range Spell +]
The boss will periodically shoot 2-3 projectiles that will seek the farthest hero and mark the ground under them. After 2 seconds, the boss will cast a high damage AoE spell on those locations. Also burns the targeted ground for 3 seconds.

-[Long Range Spell 2 +]
Flame Thrower
Siege tank will mark two strip of the road and then after 3 seconds will shoot out a high damaging beam.

## Vulnerabilities
-Attacking the flamethrower instead of the front of the tank.
The flamethrower only appears when it attacks with it.
-When the tank is repairing, heroes can attack as much as they want.

**Comment by Wujekklawy** [comment]
Flame thrower is a damage over time? Is it stack? Don't get me wrong, this is well written post but little to much flavor. For example i was must read 3 times what battering ram does to finally get that is just a dash/leap that stuns everyone in way.

Also spike barier i think is to rare.

**Comment by Wujekklawy** [comment]
Ps, gains armor by destroying it? Games logic ;)

**Comment by Haganeko** [comment]
Thank you for the submission!
Please rewrite this to focus less on fluff and more on mechanics. Example (rewrite of Heat Seeking Rocket]):

>  [Long Range Spell]
> The boss will periodically shoot 2-3 projectiles that will seek the farthest hero and mark the ground under them. After 2 seconds, the boss will cast a high damage AoE spell on those locations.

Additionally, please reformat your post to use the template on #37.

**Comment by Jinjinjinrou** [comment]
Updated the formatting.
Will add images to it on another update.

**Comment by Haganeko** [comment]
This is cleaner. Thanks. It is still a bit padded with fluff, but I think we can manage.

**Comment by Haganeko** [comment]
Unfortunately, arena modifications are deprecated and this depends heavily on them. Closed.
