### ISSUE TITLE
[Boss] Cerberus by Chewy316

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#222]
Cerberus, Hound of the Underworld

Combat:

Phase 1 (100%-50% hp)

-Boss move towards nearest hero and start attacking it (boss have 3 sources of auto attack, suggesting 3 heads)

-After dealing x damage he toss enemies in front of him to edge of arena. (affect max 3 units, give time to avoid)

Phase 2 (50%-10% hp)

Passively gains more movement speed.

-From outside of arena apere projectile aimed to hero with most health, don't despair on hit, goes in straight line, desapire on other side of arena. Apply debuff to movment speed and armor.(preferably visually as chewing toy, ball shaped)

-After projectile desapire Boss charge through path of projectile, charge work like magnus one, after getting to edge of arena evry grabbed hero is stunned and gets massive physical damage. When noone grabbed boss get stunned. (when boss gets out of stun phase repets)

Phase 3 (bellow 10%hp)

Boss splits to 3 lesser ones with one source of auto attack. (every have 4% of max hp that original had)

Lesser ones ackt like in phase 1(with reduced max tossed units to 1)

After death lesser ones explode dealing aoe magic damage and buff other lesser ones.

------------------
I adding this because original one was closed because of too much flavor and all three bosses was in one post. I rewritten them and some i did little rework on boss fight. It's not mine idea and i don't want to steal ideas, only what i do is give them chance to shy.

-----------
Orginal post: #189

**Comment by Wujekklawy** [comment]
There is that much closed posts on that submits because text was wording out for some reason that i have no clue on. Just to everyone know.

**Comment by Haganeko** [comment]
The charge aspect is like charger, the splitting is like Slime, and the tossing ressembles an early idea for Azazel.
