### ISSUE TITLE
[Boss] World Turtle

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/suggestions#23]
**Concept:** TURTLE/TORTOISE (very large boss)
**Name**: World Turtle / World Tortoise
**Lore:** Based on various creation stories.

**Phase 1:** 100-66%
Medium-high DPS. Insanely tanky vs all types, Summons lots of annoying minions. This forces the team to devote a lot of time to clearing minions.

**Phase 2:** 66-33%
Environmental hazards. High damage Acid falls from the sky. Turtle spins sending out shock waves, throwing opponents away. No minions. Avoiding damage is difficult.

**Phase 3:** 33-1%
Turtle bounces around the arena knocking up opponents. Turtle leaves trail of acid behind him. Summons minions occasionally. Stun the turtle to flip him over for a brief time.

**Phase 4:** 1-0%
Turtle explodes doing medium damage in a large area. The turtle is destroyed and a human form remains in its place. This person rewards you with a single very rare unique item.

**Arena:** Small and open. Swamp theme?

**Animations:** Target reticles, acid torrent, acid splash, acid trail, turtle spin, shockwave, turtle flip, massive explosion.

**Comment by l34Um1** [comment]
Uninteresting mechanics. Closed
