### ISSUE TITLE
[mechanic] Quality 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#239]
It's just a free idea that just randomly comed to my head. I don't think that will get to mod but why not suggest it. What about give items a quality check, independent from recipes value that can boost some of item statistics or abilities it could be losing quality by upgradeing those items to better ones and in base could be a blacksmith or something that could upgrade quality of item for cash. I know that there will not be a stat tomes so that could be great idea for lategame money spending. Also make stomps less possible, more cash you have more you upgrades items, more items you upgrade more cash you need to restore quality. This can give opportunity for less powerful heroes in early to get items that they need to fight back. It will not necessarily increase gamemod duration but will add something to do if match will be taking longer. As i mentioned it should be independent from crafting so it will not mess up shop system. Quality could also give some negative stats for items if it will be very low. 

It's just random idea, i not even know if it would be possible on source engine.

**Comment by Haganeko** [comment]
This seems too convoluted. It'd work for an RPG, but our item system is already very complex as is.
