### ISSUE TITLE
[Boss] Deirdre of the Sorrows

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/suggestions#24]
**Name:** Deirdre of the Sorrows
**Lore:** Irish Legend. A child born, prophesized to bring great beauty but also great war. She fell in love but this started a battle and she was kidnapped by a jealous suitor. She lived an unhappy life with him until committing suicide.
**Story of AAA:** Deirdre returns from the dead as an apparition.
**Themes:** Beauty, Jealousy, Contempt, Duality
_____________________________________
**Fight pattern:** Boss starts off in Form A, this must be destroyed for Form B to appear. Once Form B is also defeated the battle continues to the next Phase. There are 3 phases. So it goes ABABAB. Boss gains better attributes each phase.
**Form A:** Beautiful maiden of **_innocence_** - Primarily spellcaster, slow move speed, teleports, burst damage.
**Form B:** Frost apparition of **_hate_** - Primarily attacks, Fast move speed, illusions, darts in and out.
_____________________________________
**Form A -** 
* Slow/Slow/Normal MS
* Creates columns around her that do dmg (Light/Fire/Pure) in a (small/medium/large) area
* Shoots a laser that spins around her; drains life (slowly/moderately/quickly)
* Has blink.
* Summons (militia/footmen/knights)

**Form B -** 
* Fast MS. 
* Moderate-High Melee damage
* Creates (1/2/3) illusion of self that does 100% dmg but takes 400% dmg. 
* AoE dmg upon death
* Has a slow, telegraphed spell attack-animation (line-missile type) but insane damage 
* Basic attacks reduce armor by (3/5/7?)
* Can charge, knocking back first hero hit.

**Comment by l34Um1** [comment]
The two forms are essentially just phases. Closed.
