### ISSUE TITLE
[item] Blood Talon

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#240]
Recipe:
Iron talon
Recipe
(can be added more items)

------
Stats:
Upgraded iron talon

------
Active: same as iron talon + after usage on enemy hero deal pure damage over time for x second, damage depends on caster stacks(from passive) and level. Cooldown is longer if used on hero.

Passive:Evry usage give stack, evry stack grants +x damage to creeps and upgrade ability. After death lose x% of stacks (if not that can be pretty op)

-------
I got this idea thinking about something that can give other way than buying a battlefury or equivalent of holybook. As a mod that is all about farming it needs something more than battlefury/holybook to give player choice. Most will get from it probably heroes that already have cleave but also gankers will get cheaper and better item for them. (they usually don't have much farm anyway comparing to others). This item is an early game, for gankers also mid game and for nukers could work well as late game.

**Comment by Haganeko** [comment]
Farming boots are our answer to the "mandatory farming item" problem.
