### ISSUE TITLE
[map] Tutorial

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#243]
it is something that i never saw in any gamemod in dota, ewen if its posible to put more maps together than only one. Adding map for only one player could be good way to introduce to mehanis new heroes and bosses. Additionaly it could have option to pracktice fighteing vs bosses additionaly haveing similar options to demo mode in dota, so you can change hero in game. it could have option in loading screen to play basic tutorial[or rather to not play it] and if base tutorial is turned off go to part that is after it with is a pracktice hub where you can go to boss arenas and fight any boss in game or change heroes and learn they abbilities(mostly to try out if they are any good, there is no new heroes anyway yet) etc. maybe in the future it will be option to fight vs bots (just not thhat op like in pimp  my peon ;} )

**Comment by Haganeko** [comment]
People can play on the map alone. How would this be different?

**Comment by Wujekklawy** [comment]
Diffrent cuz if u play map alone u need learn evrything alone. that would be using simpler map and "tutorial eagle" to teach how to play and what are diffrences betwen OAA and DotA. (if u remember tutorial for dota in source 1 days you will know what i mean)

**Comment by Haganeko** [comment]
Still feels unnecessary, given that the hardest part of the game is learning to cooperate with a team. Closed.
