### ISSUE TITLE
[Boss Idea] Shell Boss

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#244]
So the idea behind this boss is that when initiated on the boss will spawn a bunch of illusions/clones of himself that when killed spawn even more illusions until the boss dies. **I will be using Clone and Illusion interchangeably for the rest of the post**
Phase 1: Initiation
Spawn few clones of the boss, while summoning illusions the boss is invisible and when the boss reappears it spawns 2 more clones. When an illusion dies it spawns 2 more illusions
Phase 2: 50% health
The clones are dissipated and are re summoned where the boss is standing, the clones are healed to full health and the boss will be invisible for a few seconds, after summoning the illusions, when the boss reappears Phase 1 is repeated.
Phase 3: Death
When the boss dies the items will be surrounded by the remaining clones, the clones will deal bonus damage and will protect the items until either the items despawn or the illusions die.

**Comment by Haganeko** [comment]
This seems like a long fight, one which would test more the players' luck than their skills. Also, looking back, tons of similar ideas have been submitted. Closed.
