### ISSUE TITLE
alo? anyone here?

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#249]
are you alive maybe? if you are dev can you at last read issues? for example mine ones are laying like almost month (other peaple even longer) and looks like noone give a shit about them :/

**Comment by Haganeko** [comment]
We're currently focusing on implementation of what we do have, since we're nearing an alpha. We haven't purposefully ignored your issues, and development is still going strong... we've just paused the design side of things.

**Comment by Wujekklawy** [comment]
@Haganeko good to know :) when to post my 4 billion ideas for heroes? ;)

**Comment by Haganeko** [comment]
I'd say there's still a couple weeks before we'll be dealing with heroes.

**Comment by VoidsKeeper** [comment]
@Wujekklawy , hang in there man ;D . Keep writing down and/or posting your ideas. As Haga said - we're not purposly ignoring the ideas , but rather don't have much time to check or work on their implementation.  The first launch showed many things that need fixing and other things are already awaiting their implementation(that's the main job right now , as we do not want to f' up the base of the mod; hope you understand why).  
So just bare with us ;)

**Comment by Wujekklawy** [comment]
@VoidsKeeper you know that i have alredy around 16 new heroes? (for that moment 10 on "paper", 7 alredy doned in 100% ) and i can bet that i will do more. as i said i have "some" heroes waiting for apruve ;), i hope one will be not dissmised by baumi cuz he hate invis heroes :) [there is no invis mechanic like that n dota, but there are similar to that, youll see when i'll post] (and jugger is best stealer of abbility names,,,)

**Comment by Wujekklawy** [comment]
@VoidsKeeper i lost fucking evrything ;_; i given my laptop for 2 days to my friend and he just "sorted" my deskop... and he deleted evrything ;_;. i will try to restore that but i have not so much hope :| and i not lost only that but also my almost all backups for evrything

**Comment by VoidsKeeper** [comment]
@Wujekklawy :O That's horrifying... Don't you have any posts here? Try to remember stuff , I guess... damn, that's sad man. Hope something gets recovered.

**Comment by Wujekklawy** [comment]
@VoidsKeeper thankfuly i get that stuff back, ye i got some stuff here but not like this


> "Strengh, semi-support, mele. [could looks like buffed omni, main color white and gold, weapon >choice two handed sword]
> 
> 
> Q [Healing totem] spawn healing ward. totem cannot move. need x attacks to destroy
> 
> W [Electric shield] create shield that deal damage to evry attaker. can target allays. cannot be >destroyed (similarly to dark seer one).
> 
> E [Chapel of salvation] create ward that teleport to himself evry allay below x% max hp in area, teleport > is almost instant. can teleport only once same taret. Range should cover whole arena if placed on >middle. [can be used x times until destroyed, cannot be used twice by one target, teleport cannot be >canceled]. can't be attacked. lasts long time, long cooldown.
>
>R [God's panishment] incantation, deal AoE damage around hero, damage depends on time spended >incanting (similarly to powershot).
>
>
>
>Tree
>
>lvl 10 Spell amp. / electric shield now block x damage [like vanguard block, have 100% to triger]
>lvl 15 + x% max hp heal for healing ward if unit is not being attack by hero [similarly to blink/heart] / >AoE reststs reducktion [like -20% phisical, -25% magical, around 450 range]
>lvl 20 Incrise spell range [including E and Q aoe effeckt range] / Attacks deal x% more damage as >magic damage type
>lvl 25 Electric shield is now AoE [apply on evry ally hero in range] / Charpel of salvation now heals to >x% hp teleported hero
>
>
>
>agh upgrade, God panishment now slows when incanting, incrise damage per tick of incantation.
>
>------
>
>Flavor:  paladin of Rome, faithfull servant of pantheon etc. (i can write Lore and flavored spell >discription)" 


;) i have more stuff like that :) this is just a teaser, man... talent trees are fucking desaster if you wan't make them interesting ;), i rarly put in them +stats or +hp etc. ;)

**Comment by VoidsKeeper** [comment]
Awesome-sauce!

**Comment by Wujekklawy** [comment]
but this still is not for posting now :)

**Comment by Wujekklawy** [comment]
@VoidsKeeper i think support players and omni carry players will be happy if that would be in game ;)
