### ISSUE TITLE
[Item Suggestion] Tank item, weaker in early and stacks up in late.

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#250]
How about make an item which allows sacrifice portion of current HP in order to permamentely increase your maximum HP. That allows to give an interesting early tank item, which isn't straight up a Heart or Abyssal. It should have a huge cooldown ( Something like Midas) so you can stack it up with cooldown reduction and refresher. May be an upgraded version can give some benefits if you reached (X) bonus HP.

**Comment by Wujekklawy** [comment]
idea is broken as F. but if lose stacks similarly to bloodstone it would be acktualy cool item

**Comment by Haganeko** [comment]
This feels a bit too similar to the tome idea.
