### ISSUE TITLE
[Item suggestion] Tank Octarine core.

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#251]
Octarine core is a very fun item for heroes such as Bristleback ,Axe and such, but they don't care for cooldown reduction as much as for pure stats and Spell Lifesteal, so what if you made a combination of Octarine core with Heart , something that may be gives less cooldown reduction but more raw stats and spell lifesteal.

**Comment by Wujekklawy** [comment]
actualy bristle like it becouse cd reducktion and spell lifesteal ;)  ps, i never saw axe with Octarine

**Comment by warpdragon** [comment]
That item already exists.
