### ISSUE TITLE
Display item level in picture

### ISSUE THREAD

**Issue by Falkenx1** [AngelArenaAllstars/suggestions#252]
I think it is already planned, but items should display the level inside the picture, so you don't have to hover over the item to check it...

![item_lvl](https://cloud.githubusercontent.com/assets/25637958/24336257/057ad172-128c-11e7-9f93-1256e7173449.jpg)

**Comment by zelding** [comment]
That is an excellent idea, I can not confirm if it's already planned, but it should be.

**Comment by Wujekklawy** [comment]
if i'm good informed there will be not stacking items (excluding stacquila)

**Comment by Haganeko** [comment]
Upgrade levels exist. The level will be indicated by a changing icon, which has more glance value than a small number. Should have quite a few ready for our next test stream.
