### ISSUE TITLE
[Item Suggestion] Early duel item with no upgrades. Upgraded Drums.

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#253]
Most of the items for early aggression in DotA are pretty much unusable in OBA since usually high cost items which do upgrade are so accessable. So what about making some of those items , like drums have a cheap , very accessable upgrade which would help your team in early duels, if you think that your line up is at slight disadvatage early. For example Drums of Safety, an upgrade for usuall drums which gives simular stats to the normal Drums , also with charges, but on use, the aura for attack speed is disabled and instead it gives more defensive buff, for example a bit of armor and Hp per sec and lasts longer , the more people it buffs.  That can give an interesting item decision for early game which you can safely sell after all charges are used up and can still be a usfull item in first few duels.

**Comment by Wujekklawy** [comment]
acktualy i think that maybe not drums etc should be cost reduced but items like ring of regen or broadsword

**Comment by Haganeko** [comment]
We have a drums upgrade which requires no charges... But this idea seems to have merit.

**Comment by Haganeko** [comment]
We have decided to avoid introducing early non-vanilla items where possible. Closed.
