### ISSUE TITLE
[Basic Idea] percentage of mana untouchable by mana drain and such

### ISSUE THREAD

**Issue by YorozuyaLost** [AngelArenaAllstars/suggestions#254]
But basically as an item it will make a quarter of a hero's mana not beeing able to be mana drained by any hero ability or item. 

Could also be something that is only slowly filled once the hero's mana is full......

Could just tack it to an existing item since it isn't that usefull as a solo effect....or use it as solo effect so you can counter a AM or PL but lose an itemslot?

You could also see if it's applicable to bosses so they're not cheesed if they use mana for skills.....

**Comment by Haganeko** [comment]
I believe both of these heroes took a nerf hammer to the face.

**Comment by Wujekklawy** [comment]
am and pl are weak early so they need more time to properly start farming, you need to take that to counting. they rae nerfed by fact of base mechanic of AA
