### ISSUE TITLE
[Item suggestion] Problem with scaling of mana burn effects. More mana stats.

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#255]
Since the scaling system at a moment provides increase in mana costs and some heroes ( AM, Lion, etc.) have mana burn/suck abilities which also get amplyfied, together with increased mana costs and the fact that there is no actual viable item for more right click oriented heroes which also gives decent mana, appart from Diffusal Blade , which in turn burns mana itself. Even though it is true that mana costs should be limiter of how much you can spam abilities, it gets a bit too limiting towards later stages (lvl 28 onwards). So what about either some random bonus mana stats on items which upgraded at least 3 times or more viable items which do give mana ?

**Comment by Wujekklawy** [comment]
or upgrade for diffusal that additionaly burn % of max mana :)

**Comment by Haganeko** [comment]
Most mana burn has been nerfed.
