### ISSUE TITLE
[mechanic] Duels

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#257]
watching videos from OAA i saw issue that there is still issue of "wussy" contestants who prefer to runing around instead of fighting. My sugestion is to make something to force or limit that. i have few ideas how to do that. 

1. make other duel not wait for end of other (it do benefits for both teams giveing them more time to farm so both teams will be want finish duel fastest way possible,in theory)

2. make time limit for duels and give win to team that was have better stats (more %hp on end of duel, did more dmg in duel etc.)

3. after some time start dealing damage based on they max hp (like 2% max hp per second)

**Comment by VoidsKeeper** [comment]
Duels are an overall problem for us at the moment , so we've really started looking into them after today's stream. Thanks for the suggestions  ^_^

**Comment by Wujekklawy** [comment]
@VoidsKeeper i saw on videos ;) , that gangbangs after duels can be unnoing ;D

**Comment by chrisinajar** [comment]
We're already solving this problem with planned high ground capture points in the duel areas. When you sit there undisturbed you get random rune effects, then go hamburgers on the runners.
