### ISSUE TITLE
[Item] Soul Fragment

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#259]
**Consumable.** **Early** **game** **item.** **No recipy.** **Early** **duel** **item.**

Stats:
---
+hp regen
+armmor

Acktivate:
------
X% damage taken by target is transfered to you.

**Comment by Haganeko** [comment]
Thanks for the post! A couple questions:
So activating it would consume it? And in doing so lose the active part?
Now, who do you see buying this? It seems like an abaddon item.

**Comment by Vafnar** [comment]
Abadabonembabadon buys it, Maybe axe, legion, and Huskar would want it. seems good on general Gankers as well if just for the active.

**Comment by Wujekklawy** [comment]
@Haganeko  like abba, huskar, tidehunter, ogre magi, dk. 
 
@Vafnar legion? Why? Damage taken is transfered to you not other way. 

@Haganeko  @Vafnar  item is to be honest weaker version of one abbility of one of my heroes that i created (trees are f*cking disaster to create).  So I'm half way sure if i want this item to be in game :) if yes and hero will be also accepted this should be weaker than abbility.  [u know,  one of those "have"  perm invis ;), (perm invis like one granted by oracle ult on release, but pernament) and to be honest,  it's balanced ;). ]

**Comment by Wujekklawy** [comment]
I closeing issue, i made my mind.  I will repost it if hero that item is based on will not make in to the gamemod itself.
