### ISSUE TITLE
[item] Magma Dagger

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#260]
**Recipe:**
---
- Ogre club
- Ogre club
- Belt of strengh
- Recipe
>
>Possibly to be combinable with Diffusal blade like Sange with Yasha. Could give longer cooldown but infinite stacks.
>

Abbility:
----

**Passivly:** Evry attack deal x% of target current/max health.

**Acktive:** Apply wound on target.

>
>**Wound:** Deal over time damage depending on target lvl. Target lose all bonus damage for full duration.[Could be buffed if too weak]
>

**Comment by Haganeko** [comment]
This is a ripoff of Feast. I don't like the passive part. The active may have a future, but I don't see it working here.

**Comment by Wujekklawy** [comment]
@Haganeko feast? How? Feast heal you for x% of current hp of target.  Or you mean something else that i don't know of. Basic idea was to create diffusal blade for strength heroes ;) as you probably know by recipy.  Ps, i renamed debuff, i was useing previous term a lot with certain mechanic behind it with is different  to this one. Ps. Imagine kunkka with two rapiers losing + 600 bonus damage in moment for 4s ;)

**Comment by Haganeko** [comment]
Feast deals a % of the target's Mac HP as damage, and heals naix for that amount.
