### ISSUE TITLE
[Item] Eldritch Sword. 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#264]
>Keep in mind that dev can change any part of item while implementing in.

Recipe:
-----

- Iron talon
- Sange
- Morbid mask

Stats:
---

- Lfesteal
- Armor 
- Attributes 

Abbilities:
---

**Graiter Maim: [Passive]** Stronger version of Lesser Maim. 

**Graiter Quell: [Passive]** Stronger Quell, grants splash effect on hit.
>Can work only on creeps if too strong. 

**Oblivion Strike: [Acktive]** Deal 15% of target current hp as pure damage to it. Heal same amount.  Can overheal creating shield. Max hp of shield is 300. Deals 50% of current hp if target is a creep. If target is creep cooldown is significantly shorter. 

>numbers are just for example to visualise how powerful item is in my mind.

Lore Description:
---

**Sword made by Grandmaster of Oblivion Arts. Burried in Altair with his body abbadoned by new master survived conflagration only thanks to his powers.**

>Item is 100% in symbiosis with Dota 2 lore. Description and item name refers to pugna lore who in short was new Grandmaster of temple of Oblivion arts he burned it up.  Name of previous Grandmaster is reviled in description of Oblivion staff. Also Abbilities of that Sword is in symbiosis with lore when you compare abilities pugna learned in temple and abbility (nether blast is only one abbility that pugna was knew before, with high probability he killed other 2 children's with it) of Sword is high probability that if such item would existing it would be there. Only thing that description adds new is that Sword survived because of reapering itself with souls of regends dying in flames, with is pretty dark back story for weapon with is common in dota 2 lore, for eg. Demon's edge.

**Comment by Vafnar** [comment]
only change i would make is if it is used on a hero, then the max shield is 500, and if it is used on a creep then the max shield would be 250. I would also make it a drain, as in over X amount of seconds you drain XX% of the targets current hp, and you gain the shield over those few seconds.

**Comment by Haganeko** [comment]
15% HP ure damage on a hero should not be an instant ability. especially if it's a drain. We're talking half a laguna blade on a tanky hero.
I like the idea of it being a gradual drain; I also support making it magic damage.
Just to make it clear, I actually like this one, though I'm not sure I am too on board with the whole "overheal into shielding" concept.

**Comment by Wujekklawy** [comment]
@Haganeko take in mind that is current hp not a max hp.  That is significantly weaker also incantation would completely destroyed the item. And i puted 15% because it looks good,  in true i was thinking about 12 or 13 percent.  15 is slightly too much but it looks better. With shield i also doned same thing. And 12% of current hp is not that much.  In order to kill someone only with that if it would be max hp i would take around 8 uses in case that it is current hp and modify that to kill if target have 1hp left (in way it is now would take infinite uses to kill someone only using that abbility) it would take probably more than 60 uses( if you want you can calculate that, i have no feeling for that). Also when teamfight is on whois running with full hp? Even if you use it on tank who have full hp and you almost dying, you still need to deal him a tone more damage to kill him. Also for that is that additional health cup so you cannot go for like 5k additional health. That item have two usses. For dealing damage or too keep yourself alive.  it's very good ganking item cuz deal a lot of damage to full hp heroes. It's good for surviving ganks. To have benefits from that item you definitely need use brains. It might seem op on paper but it is not that strong in reality.  If it had only that abbility it would be actually trash item. Dealing splash damage and slow is more powerful than it seems on paper.  In 1 v 1 situation if you not overpower power enemy yourself you will not make much of a difference even with that item cuz you cannot use it for surviving. (using that on enemy that have like 300hp will damage/heal for like 39.  it's not that much)  and to be honest it is a good item don't get me wrong but when you put numbers it's could even take a buff. 12% from 1700hp(most of heroes mid to late game)  is around 204. And you want to make it magical so with basic 25% reducktion it would be like 153 damage / heal. Actually i think it definitely need a buff to like around 23% to be somewhat useful abbility.

**Comment by Haganeko** [comment]
I say make it magic damage and we can balance it later.

**Comment by Wujekklawy** [comment]
@Haganeko if you want so, just keep in mind that item was meant to be a farming item (like  bf, but splash is weaker than cleave and item does give nuke damage instead of right click damage ) but with survival/ganking potential. Also to counter tank heroes, they usually get pretty nasty in mode like that. U know,  bristle, timbersaw or beast master(he's not rly a tank in dota but depending that he can do early strong ancients he usually is pretty tanky)

**Comment by Haganeko** [comment]
Iron Talon is not even a thing anymore, and this starts to look a lot like the new MKB. Closed.
