### ISSUE TITLE
[Question] Clossed issues. 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#267]
Recently (3days ago)  2 of my posted bosses was closed.  And f i good remember dev liked ideas. Also there was no description why it was closed.  Is it being implemented?  It get rejected?  Mode got rampaging brawl of closing all stuff? Most of times i saw closed submissions person who closed it wrote a reason #193  or #196 for eg. So what happened?  suggestions are #87 and #92

**Comment by Haganeko** [comment]
Generally the reason is there were concerns which were not addressed, we couldn't understand the post, or it was a duplicate.
