### ISSUE TITLE
[Item] Dirk of Eternal Sacrifice

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#269]
# _**Recipe**_
Boss Item A
Dagon 5
Divine Rapier
# _**Stats**_
+1000 Health
+1 Damage
# _**Bonuses**_
Slider (Think of 7.0 Morphling slider between strength and agility): Toggle how much damage you deal as physical damage per 1% health is changed to damage you gain 2$ more damage and visa versa
Passive: Whenever an active ability or spell is cast gain a shield of 300 health as seen in #248 
Active: Sacrifice all but 1 hp and deal that much damage in a line as magical damage (Pierces all spell immunity) Heal for 67% of damage dealt  long cooldown

**Comment by Wujekklawy** [comment]
So... Why not name it cannon of super ultra mega hiper destruction?  it's too op and recipy is kinda bad, it's better to avoid items that have upgrade levels like necronomikon or diffiusal blade. Acktive sounds cool but definitely need rebalancing. 

Ps, "gain 2$ more damage"?

**Comment by Vafnar** [comment]
The numbers clearly need to be reworked, but the active is the point i'm trying to make, wouldn't it be cool if there was an item that you can use that takes you to one health, but every hpp you sacrifice gives you 1 more damage, and what ever damage you deal heals you, this could be an awesome high risk high rewards skill shot item, that can be devastating when you hit, but if you miss, you are completely fucked.

**Comment by Haganeko** [comment]
So... basically ripping off Huskar's thing?
I don't see what design purpose this serves, except for being a convoluted "kill a hero" button.
Additionally, recipes involving rapiers will be weird.

**Comment by Wujekklawy** [comment]
@Vafnar imagine now enemy team have necro, alchemist, doom, enigma, zeus or any carry who bought radiance. You are in 100% situations dead if you use that item
