### ISSUE TITLE
(UI) The after boss kill loot destribution

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#27]
Even though you probobly already thought about it, I will still meantion it, that on the screen where the loot is distributed there should be a skip vote button and if all team members voted, then the voting process will end instantly, so the loot can be earned faster.

**Comment by Haganeko** [comment]
That's... basically the Pass button. Except for every item, I guess? A "pass all" button.

**Comment by l34Um1** [comment]
Yes. Will be there. Closed.
