### ISSUE TITLE
[Boss/Mechanic] Power Creep

### ISSUE THREAD

**Issue by Vafnar** [AngelArenaAllstars/suggestions#270]
A boss that has 1 health and 1 shield, every 10 seconds that the game goes on the shield is doubled until the 10 minute mark and then it goes up 1 every two seconds, one the shield is down to 100, the doubling process starts all over again

TBC...

**Comment by Haganeko** [comment]
This serves little purpose. This incentivizes taking the boss early... but there is already incentive for that (namely, getting cores for your team and making it harder for the opposing team to get it).
So the only thing this does is turning this boss into a jackpot for whichever team can fund him immediately... or a dumb unkillable rock if no one does.

**Comment by Wujekklawy** [comment]
@Vafnar you have drinking contest?  how you think it would work?  Most of times he will be almost one shoted. And if not he will be unkillable. I prefer play  wk with no item build build vs cancer lancer than that. At least it would be fair. As haganeko said it would be more of a gamble, you kill him in one shot or you have one less boss spawn cuz of a guy with 99% phisical reducktion and 2mnl health.

**Comment by Vafnar** [comment]
This isn't the real numbers, but the point is to get the idea out there, imagine a boss that starts off weak, but can't be accessed that slowly gets more powerful over time, after a certain time when he is available you see what team can beat him first.

**Comment by Haganeko** [comment]
That doesn't address my points - taking a boss as early as possible, in a way competing with the other team, is already something you want to do - so this is redundant.
