### ISSUE TITLE
Announcement for dev

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#271]
I suggested here a lot of ideas and i have also a lot more for the future implemanations (like around 18 heroes that are fully  designed,  they only need nubers) But due to recent events i cannot update or answer on any questions with recent issues or add new. I don't know when i will be able to come here and do something.  (it most likely will be longer than a month)

**Comment by Haganeko** [comment]
That is OK. Thank you for telling us.
