### ISSUE TITLE
[boss/item] how should final boss effect the game +art explanation 

### ISSUE THREAD

**Issue by Apisal** [AngelArenaAllstars/suggestions#276]
for me i think final boss (the op boss) should not end game just like this and let the team win cuz thats sounds boring ... so i suggest that when he die he drop 6 op items that helps the team to win the game way easier 

i have sent 3 art works lately on discord 

![reverse radince](https://cloud.githubusercontent.com/assets/25623847/25811339/a3654b0a-341b-11e7-9554-1ff02db241cb.jpg)
 this one i made it for one of the items he drops (pure imagination xD)
i thought if i can implement it in the game i would name it (reverse radiance) and make it take a percentage  of the max target hp as dmg (pure dmg\pierces spell immunity) and heal the owner with the same amount (aoe effect like radiance)

![untitled-1](https://cloud.githubusercontent.com/assets/25623847/25811389/cef62136-341b-11e7-945c-5aec866b870a.jpg)
 this one is totally random (was trying stuff on Photoshop and worked out randomly)

![helm of madness](https://cloud.githubusercontent.com/assets/25623847/25811367/b5c96916-341b-11e7-81ed-68e1ba96246c.jpg)
i made this one long time ago (mixed helm of dominator with mask of madness )

feel free to use them where ever you like

**Comment by Haganeko** [comment]
About the icons: They've been posted on the dev discord, and people especially liked the third one!
About the last boss: he's not going to be boring because he'll be a hail mary - something which almost never happens, but when it does it'll be very very memorable.

**Comment by Apisal** [comment]
well looking forward to it :)
