### ISSUE TITLE
[ITEM] Trumps Fist Weak?

### ISSUE THREAD

**Issue by prsnnami** [AngelArenaAllstars/suggestions#278]
I was playing a tiny against a lifestealer. I was beating him (with difficulty) with the lvl 2-3 skadi and desolators. After I upgraded to the trumps fists, I was significantly weaker. Couldnot do bosses anymore, Lifestealer just wrecked me and i was overall useless after that. Maybe it is intentional because of the ability but should it make me weaker against a lifestealer. Atleast let me disassemble it.

**Comment by Haganeko** [comment]
Trump's Fists is actually considered one of the stronger items against bosses, given that they regenerate a nontrivial amount of health each second. We'll see about it.

**Comment by Haganeko** [comment]
We've actually needed to nerf the item.
