### ISSUE TITLE
Boss suggestion - Avnas, Prisoner

### ISSUE THREAD

**Issue by Minnakht** [AngelArenaAllstars/suggestions#279]
Avnas uses one of the big rooms as his arena.

Avnas stands in the center of the room, surrounded by ten water pools. Seven of the pools are corrupted, two are dry and one is pure. The pools encircle the center of the room in a fairly large radius, and form two pentagrams - both based on the same circle, just offset by slight rotation. Each pool has a small fountain in the middle - smaller than a shrine, but just as tall.

There are corrupted guardians - water spirits (stand-in model: ghost) in the corners of the arena, outside of the circle of pools. They have no gold bounty and are about as strong as a camp of medium creeps - one per arena corner. Each camp drops at least one bottle guaranteed, and occassionally respawns.

The more pools are actually corrupted, the more powerful Avnas is. Thus, the fight does not have usual phases - the fight progresses as players purify the pools, making Avnas technically weaker but angrier and craftier as he resorts to new abilities. 

Avnas has an ability which lets him dry a pure pool or corrupt a dry pool. They might actually be two different abilities with independent cooldowns. The cooldowns are actually higher when there are more corrupted pools.

Players can remove corruption from a pool by activating it like a shrine by clicking on the fountain. The pool, ejecting the corruption in it, will stun nearby heroes (so they can't just run out) and deal heavy magic damage over a few seconds in the area while they can't escape, splitting the damage between all heroes present (like Mystic Flare.) When the damage is over, the pool has run out of corruption and is dry. 
This would, obviously, require players to somehow restore their HP. Lifestealing from corner minions is a way, drinking from bottles is a way (especially since the corner minions drop them), friendly neighborhood Lucience is a way and so on. This could be helped by pure pools having a low-radius aura which increases bottle regen to a level more viable for the game time the boss is intended for by tier. Alternatively, since the damage is magic, it could be avoided or mitigated - reduction orb, magic resistance sources, whatever. Any preparation would need to be preemptive because of the stun, however. 

Players can fill a dry pool with pure water by standing in it and using their bottles. (OMG BOTTLE BOSS!!!!!!!!!!111) (seriously though this is why the corner minions supply them.) The pool keeps track of the amount of time heroes with the bottle effect spend in it, and it takes several seconds. Do note that taking damage from Avnas interrupts bottle regen, so a player tanking can't help fill a pool. Trying to activate the fountain in a dry pool makes the player use a bottle charge if present, thus new players can 
just do the (hopefully intuitive and obvious) thing of clicking the fountain.

Avnas has ridiculously high HP at the start of the fight, as each non-pure pool doubles his HP capacity. Example numbers: Base HP of 10000 means 5120000 HP at the start of the fight. 

Avnas's base HP should be low enough that a team should be capable of killing him with 7-8 pure pools, so it should be about 25% of "reasonable". As Avnas's HP capacity changes due to pools becoming pure or not, he keeps his current health percent, so progress in getting him to 0% is always kept - but is very, very slow when his HP is high.

Alternatively, instead of pools changing Avnas's HP, they'd give him his own version of boss resistance in lieu of the standard one - each non-pure pool halves the damage he takes. Thus, with all but three pools pure, he'd "only" have 87.5% damage reduction, at par with normal boss resistance. A HP change would be more visible to players, though. 

Specific abilities are left to be determined. One of them could be a fire spell which applies a DoT, thus keeping the players hit from using bottles for its duration. 

The pool-drying ability could be implemented as a Doom-like spell - a very high damage, very long DoT which is removed by stepping into a pure pool in exchange for drying it. Thus the players could elect to have the "Doomed" player die to preserve a pool, should players find that "optimal". Of course, seeing a player die to a neutral creep would alert the enemy team about the boss attempt, which is a far-reaching consequence...

The pool-corrupting ability could target the nearest dry pool, thus giving the players some control over which pool would be targeted. Additionally, as it would have limited range, stalling Avnas could keep him from recorrupting a pool. This would add strategy but could be hard to balance.

Too complex? Opinions, please.

**Comment by Wujekklawy** [comment]
- Can you rewrite it a little?  #37 can help. Also too much flavour. Try making it clear as it can be, for eg. Instead of "throws dirk of destruction on enemy with burst in flames" something like that "projecktail that deal damage" is more clear. Also you can write visuals at the end.

- pretty cool idea, is doomed hero corupts pool when he goes in it? If pure pools "heal" that corrupted ones damage?  Does shrine have its normal cooldown? Ghost spawn from pure pools or just apire from nowhere? How people will know to purify pools? Did all pools are pure and boss corrupts them when ingaged to show that they are not just esthetics? How you will show that pools give boss hp and not just he buffed himself? Ghost will be standing on corrners or they will be roaming? If ghost can't go in to pentagram can boss go outside?

**Comment by Haganeko** [comment]
Thanks for your submission. 
As mentioned above, please format your boss concept. Also, please remove fluff and focus on mechanics. As it is, the lore ideas obscure the mechanics parts. 
And I agree, this is way too complicated. I don't see players learning this. There's no easy way to explain "throw bottles at this!" 
PS: can we not design based on a meme?

**Comment by warpdragon** [comment]
you need to read the submission guidelines and resubmit. Closed.

**Comment by warpdragon** [comment]
https://github.com/OpenAngelArena/oaa/blob/master/docs/design_primer.md btw
