### ISSUE TITLE
[Hero] Mirror Sorceress

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#28]
Name/Title: Terris, the Mirror Sorceress

Appearance: Model is based on Lich with the Frozen Star set equipped, with his frost orb being replaced with a floating shard of glass, and the stature on his back being replaced with a mirror with an ornate wrought iron trim. Wears black robes with silver trim, has extremely pale skin, eyes are reflective, hair is concealed under the robes. Uses her glass shard as a floating sword.

Primary Attribute: Intelligence

Stats:

- Strength: 19 + 1.9
- Agility:  23 + 3
- Intelligence: 20 + 2

Base Armor: 1 

Base Damage: 25 - 30 

Range: Melee (200)

Movespeed: 295

Abilities:

1. Divining: Gaze into Terris' mirror, revealing an area and creating illusions of any enemy heroes revealed this way.
Ability Type: Target Area
Range: 1500/2500/2500/4500/Global/Global
Revealed Radius: 800/1000/1200/1400/1600/2000
Illusion Damage Dealt: 10%/15%/20%/25%/30%/40%
Illusion Damage Taken: 400%
Duration: 6/7/8/9/11/15
Cooldown: 55/45/40/35/35/35
Mana Cost: 100
 

2. Shimmer: Teleport forward, creating illusions equally spaced between you and your destination
Ability Type: Target Point
Cast Point: 0.2
Range: 300/400/500/600/800/1000
Number of Illusions: 2/2/3/4/5/6
Illusion Damage Dealt: 25%
Illusion Damage Taken: 300%
Illusion Duration: 5/6/7/8/10/16 
Cooldown: 10/9/8/8/8/6
Mana Cost: 30/45/60/75/100/160

3. Fracturing: When Terris takes damage, broken shards of glass coalesce to form an illusion of her.
Ability Type: Passive
Damage Threshold: 50
Illusion Damage Dealt: 10%
Illusion Damage Taken: 500%
Illusion Duration: 20
Cooldown: 6/4/3/2/1/.1

4. Hall of Mirrors: Bends the fabric of reality, causing allied units to get stronger and enemy units to get weaker the closer they get to Terris.
Ability Type: No Target
Warp Radius: 1600
Minimum Attribute Increase/Decrease: 10%/15%/20%/30%/35%
Maximum Attribute Increase/Decrease: 25%/35%/45%/55%/75%
Duration: 20
Cooldown: 150/130/110/90/90
Mana Cost: 300/350/400/500/900

Possible Aghanim's Upgrades:

- You may now cast spells through your illusions (The spell still goes on cooldown. When casting Shimmer, Terris teleports, not the illusion)
- Hall of Mirrors is now passive (reduces attribute change by 33%)

Lore: Needs Work

**Comment by Haganeko** [comment]
If this hero used the same progression we've been using for other heroes, her illusions would deal
10/15/20/25/30/40% damage. The cooldowns should not progress beyond level 4, unless the progression of other aspects is weak. Shimmer mana cost would go 30/45/60/75/105/225, and Hall of Mirrors would go 300/350/400/500/900. There are only five levels for an ultimate.

**Comment by LordZenth** [comment]
Fixed the mana costs, illusion progression, and some of the cooldowns. If the cooldown for Fracturing didn't go down after the fourth level there'd be no point in putting more levels into it, so I left it as it is. I'm worried that they'll be extraordinarily weak during the early game farming segments though, maybe we should give her an easier way to generate illusions?

**Comment by l34Um1** [comment]
We aren't doing heroes right now. Closed.
