### ISSUE TITLE
Boss suggestion 1 v2

### ISSUE THREAD

**Issue by Minnakht** [AngelArenaAllstars/suggestions#281]
# $BOSS

## Arena
$BOSS's arena is one of the bigger boss rooms.
Arena has ten $areas placed in it. An $area is a circle of moderate radius with an $object in the center. The $objects are small and about as tall as a human. The centers of the $areas are laid out on a big circle centered on the room's center with diameter equal to about 80% of the room's size. The $areas' centers are placed at 0° + 72k° and 18+72k° of the big circle.
The room's corners have camps of $minions. $minion camps are similar in strength to medium creep camps, have no gold bounty, and are guaranteed to drop at least one Infinity Bottle. They respawn every $respawntime seconds. $minions are $blue with $red markings.
$areas are divided into $areaAs, $areaBs and $areaCs. An $areaA is $red, an $areaB is $grey and an $areaC is $blue. Above the $object in a given $area, a bar is displayed, empty for $areaBs and $red or $blue for $areaAs and $areaCs respectively.
The initial count of $areas is seven $areaAs, two $areaBs and one $areaC.

## Boss
$BOSS is a big monster in the middle of the arena, thus also in the middle of the big circle. $BOSS is $red and all of $BOSS's active abilities have $red graphical effects too.

## Phase 1 (10-5 $areaA)
Heroes are capable of interacting with $areas like so:
Clicking an $areaA's $object causes heroes and friendly units in the $area to be stunned. A spell effect is placed in the $area deals $high damage over time split equally among units present. (Exactly like Mystic Flare.) As damage is dealt, the bar above the $area's $object drains. When empty, the $areaA becomes an $areaB. Duration of the stun and damage is $short to $moderate.
Clicking an $areaB's $object causes the hero to use an Infinite Bottle item in that hero's inventory, or display a message if the item is not present. As heroes with an active bottle regeneration effect stand in the $area, the bar above its $object fills with $blue. When full, the $areaB becomes an $areaC.
Clicking an $areaC's $object does nothing. The $object has an aura which grants units $low health and mana regeneration bonuses.
 
$BOSS has the following passive abilities:
$passive1: Each $areaA and $areaB present in the arena has one of the following effects (both effects are multiplicative) (choice of implementation):
* $BOSS's HP pool is doubled. (If this option is chosen, $BOSS's $baseHP is about 15% of $average. As the number of $areaAs and $areaBs changes, $BOSS's remaining health % is kept through HP pool size updates.)
* $BOSS's damage taken is halved. (If this option is chosen, $BOSS has no Boss Resistance passive.)
Thus, initially, $BOSS either has 512x$baseHP or takes 99.8046875% reduced damage (0.001953125 damage taken multiplier.) 

$passive2: $BOSS's attacks apply $debuff1. $debuff1 has $short duration and deals $low damage per second. $debuff1 is dispellable.

Damage from $BOSS interrupts the bottle regeneration effect.

$BOSS uses following abilities:
$ability1: Target hero is given $debuff2 debuff. $debuff2 has $superlong duration and deals $huge damage per second to the hero. $debuff2 is undispellable. $debuff2 has significant $red graphical effect. $debuff2 is removed when the hero enters $areaC. $areaC used this way becomes an $areaB.
$ability2: Target $areaB becomes an $areaA.
$ability1 and $ability2's cooldowns scale with number of $areaAs present - the more present, the higher the cooldown.

## Phase 2 (5-4 $areaA)
Due to cooldown scaling, $ability1 and $ability2 are cast more often than in phase 1.
$BOSS uses an additional ability in this phase:
$ability3: $BOSS deals $average damage in a cone beginning at $BOSS's location. Heroes hit gain $debuff3. $debuff3 deals $moderate damage over time with a $high duration. $debuff3 is dispellable. 

## Phase 3 (3-0 $areaA)
At this point, $BOSS takes either at most 87.5% reduced damage or only has up to 8*$baseHP which isn't much higher than $average, so heroes can effectively deal damage to the boss. $ability1 and $ability2 are cast often due to $moderate cooldown. It is difficult to for heroes to turn $areaAs into $areaBs and $areaBs into $areaCs at the rate $BOSS uses $ability1 and $ability2 to turn them back.
$ability3 is used more often this phase too.

**Comment by warpdragon** [comment]
You have proposed this [already](https://github.com/OpenAngelArena/suggestions/issues/279).
We gave you feedback, and recommended you read the [doc](https://github.com/OpenAngelArena/oaa/blob/master/docs/design_primer.md) outlining exactly what to do. The second sentence stated, in no uncertain terms, "Be concise and to-the-point." 

Obviously you can read. So the only answer is that you must either be a smartass or a troll. This board is a place for people to work on OAA, not a place to pull dumb, disrespectful fucking stunts and waste everybody's time.
