### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by XochiERT** [AngelArenaAllstars/suggestions#291]
Hello after a duel whe got sent to the lowest part of the map and got bugged. I dont really know why it bugged bet it just happend after the duel ended.

![untitled](https://cloud.githubusercontent.com/assets/29054634/26568666/153e114a-44ba-11e7-9bc9-5ea113f0133b.png)

**Comment by Wujekklawy** [comment]
Pls resubmit that to proper category and close this one. Link for you to bug reports: https://github.com/OpenAngelArena/Bug-Reports/issues
