### ISSUE TITLE
Overall suggestions

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/suggestions#292]
Btw i love the game and thinks its great just from all the games ive played these are the things ive noticed(played about 30 games so far n about 15 of those were proper game tho ). Responses appreciated. Please read all might find some of it interesting
1) Heroes which are strong early, completely destroy. Especially ones that can farm well. It is near impossible to do anything as they sit outside your base and take your creeps. The farming cave  grows in power too much  and doesnt give enough money this results in new players being deterred and players leaving early because they cant do anything. 
Maybe be made better by:
- One way is too make the map larger if easily doable? As this would mean it takes longer to get to oppositions side n make it less pressurised early as there isn't any escape. 
- improving farming cave
-  make another exit to so that players can leave through a different route maybe to medium camps  by a back trail route behind the tier 1 boss which is only accessible by that team.

2) Quite allot of the supports and some other heroes **abilities** do not scale enough into the late game. As items seem to scale so much more than abilities. For example crystal maidens w deals 450 damage at level 45  means it becomes redundant late game as it deals no where near enough dmg to even hurt all the heroes with hearts n 10k health or dazzles heal which only heals 400 late game. This could be improved by **scaling the abilities dramatically**.

3)Improve summons. This could be by tweaking the summon abilities which are completely pointless in mid to late game and some even early. They die too early and dont do enough damage. This makes it unviable to centre ur build around summons and means u always have to go right click to stand a chance. 
Another way to improve summons is to add items which are made for summons and improve necronomicon and give it upgrades using cores (in the way of stats or abilities(eg radiance, slow, stun) and at core 4 add a really powerful extra summon or earlier depending on power level.

Ideas for extra summon: Flying **or** one that acts like a cannon or sentry gun and is rooted in place when summoned (like siegemode item but on a summon) **or** a demon(keep in theme) which deals aoe dmg (like a radiance) **or** a mini charger with high health (which charges around every x amount of seconds and stuns when it is near creeps and prioritise enemy heroes) this would go with the twins as they look like normal necronomicon creeps **or** combine them into one bigger summon

Ideas for summon items: 
- Add utility summons this could also be normal items but summons sound more fun which are aimed for mid or early game and help tank early. For example one that deals aoe dmg as a spell(helps for bad farmers early), one that increases dmg to bosses or with just hp regen n health (helps with heroes which have no tanks for the core 2 boss), a walking ward which cannot attack but is invisible(reduced vision and much more expensive than wards)
- a item that amplifys the power of summons either by static(+1000 health) or by x2
- a item that means u can infest in summon and makes ur summon ur in lasyt infinite time. This means people can get tons of auras and buff there summon and ride around it. You cant cast spells but can use items? maybe or not? not sure how powerful that is.
- item which summons a pet like lone druids ability. have simple abilities be kinda boring but can be made cool by the items above. Like a spell one, a glass cannon, a tank
- a suggestion for the pet could be that it grows in strength the more times u complete the cave.

4)Item ideas and improvements: 
- chanceinator(or some-other name...) its an item which can randomly amplify one of yours stats for a certain period of time. It randomly amplifies the stats of another items or ur stats. Or it could have a bunch of different effects like rune effects or slows on attacks. All given randomly. The idea of the item is to give a chance to become super powerful for a bit completely luck based.Perfect for duels. Arguments against this item is that it could be frustrating playing against. But it could be a bit of fun.
It could also maybe give negatibve effects less often aswell. The other effects it could have could be give gold or xp or take gold away. (This item would 100% need a good description) 
This could also have a counter part for supports which gives a buff to other heroes.

-Items should contain the qualities of what they take to build into it. Etc trumps fist shld maybe have armour reduction or slow. maybe weaker but still present. Or heart transplant should have armour from the sun crest used to build it.

-Charge bkb, is utterly terrible, much worse than normal bkb and costs more. It should either be made cheaper or have a basic starting charge number as most ppl want to use there bkb before they get hit with spells not wait till they been hit by everything to use it.

-tranquil boots, are not very good either. Maybe making them cheaper and/or increasing stats they will be more viable or by changing there effect. As if u want to kill creeps its better to buy treads everytime as it is so much faster to kill than if u had tranquil. You also dont want to waste cores on them as they dont help with ur ability to kill heroes as the others do. Suggested effects these tranquil could have 
- togglable regen so that u can turn it off before being hit n turn it back on. also increase regen as levels increase
-make an active which freezes heroes in a small aoe (make them defensive as the others arent and goes well with idea of the defensive regen)

- add blink boots, smaller than normal blink(like half and doesnt scale with upgrades to not make blink redundant) for supports to let them have another defensive option aswell as glass cannons who dont want to use a slot for a escape. Also have a farming aspect like gain extra experience which scales or sight bonus for glass cannons or a active spell like the purple ball from the hard camp creep.

- add upgrade options to blink, this could be longer distance shorter cooldown, or spell amp. Could have different paths like invisibility blink which is glimmer and blink(crystal maiden or witch doctor or enigma etc) or a extra damage buff after blink. It could also add stats or deal damage to all enemies which you blink through.

-an item which acts like a item set. You click it and can switch between two sets of items from ur backpack. So if u had tanky items in ur backpack u could click this item and take themout of ur backpack and switch places with some of ur other items in inventory. Have an interface which can be opened by holding down the button to choose which items are in each layout. This is for fighting and ease. As it takes time to move items in and out of the backpack

- A item which when gettiung attacked takes a negative buff to u and makes u have it. For example if spectre was attacking you. Then youwould gain desolate and that abiltiy would be broken on spectre or if u attacked spectre then that you wuld gain dispersion and spectre would loose it. Comes with a cooldown like linkens.

-the invisibility crystal should have an upgrade which makes u invisible as u never end up upgrading it as its better than the upgraded ones.

- tomes of knowledge quicker spawn rate so its easier for weaker heros to catch up. As in  games it seems they come every 10 mins.

-cores icon doesnt look like the cores that you get and to new players which im guessing its targeted for will not help.

- edible detection, as late game there are no spots for a gem left and u dont want to have to sell a item to get detection. So making a charge based detection like edible dust would help. And a button which needs to be pressed to use. Edible gem would nerf invis heroes too hard tho unless it was super expensive.

**- siege mode type item but for spells instead which is built from aether lens instead of dragon lance**

5)**Runes**
Possibly put a bounty rune in the middle of the entrances to the 4 bosses. (Gives more oppurtunity for heroes which are weak early to get sustainable money this again would be support heroes). Then a special rune in the middle (creates fighting after duel if wanted) but this could potentially lead to early game heroes being stronger aswell.

6)Leavers
Added benefits is there is only 3 on ur team. Especially dramatically increased gold n maybe other things.

7)Arena
- could be larger as it feels very crampt n reduces possibility for more strat plays. with a center place to hold could be quite cool. As everyone attacks around it. (compared to other angel arena which has made theres bigger and has a nicer feel to arena fights, still a worse mode tho)

8) Talent tree
Add another talent tree could be interesting and a bit of fun customization which are unique to each hero.

9) healing
all healing including items like guardian greaves, heal so little late game, as heroees are dealing 400 damage per hit which they get out 2 in a matter of half a second. Making healing pointless

Thank you for reading if u did :+1:

**Comment by Wujekklawy** [comment]
1. There is already working in progress about balancing heroes, expecially ones with cleave and other ways to farm very fast. Probably will be achieved by reducing number of creeps on the map and impruving gold bounty on them to keep same amount of gold from every spawn

2. Same as above,  also keep in mind that supports are mainly early game heroes and later stage is for carries to shine.


3. Same as above, balancing of heroes is still in progress. Any suggestions about new items pls put separate to be easily accessible and noticeable.

4. Forget blink boots, any item that is only for merging two items to create more space will be automatically thrown away. Tome of knowledge it is apiring evry 10 min and keep in mind that most of the time they are being used by one of strongest heroes in team. If you are behind others that mean either that you wasn't farming enough or made lot of mistakes. One of fastest way to farm as weakest person in game is following strongest one in team and assisting Him(not stealing byt by supporting him)

6. That is already is work in progress 

7. They are quite small for reason, pussies who ran away for end of duel. Also there is a point to hold already so i don't know why you mentioned there should be. Also they grants more oportunities for iniciateing and counteriniciateing cuz lot of high and low grounds.

8. Most likely will be not even consider, too much work to little to gain. Trust me, it looks easy but it is very hard to do. 

9. Ballance is work in progress,  probably will be added percentage heal for that

**Comment by 101necro** [comment]
Thank you for the response :). Yh didnt realise how hard map changing is.
Just to answer some of ur points.
Response to 2. was mainly trying to bring to ur attention some of things ive noticed through playing supports to help with balance.
Response to 3. u say that merging two items is rejected, but merely is going off the concept of treads which is battlefury and boots combined and but weaker than battlefury. Which would be a item bought nearly all the time on carrys. Same is with all ganking heros with blink.
I will also create a separate post for item ides.

**Comment by Haganeko** [comment]
The idea of farming boots is that all heroes buy boots, and all heroes need a farming item. Blink is not an obligatory item.

**Comment by Wujekklawy** [comment]
@101necro keep in mind that in mod that is mainly about farming almos evry hero need farming item. and how much u have farming items in dota? maelstorm/mjolonir battlefury and thats acktualy all of it. and to be honest it wos suggested by me but got rejeckted ;) #196

**Comment by Haganeko** [comment]
This is outdated and so not that relevant. Still, some of the ideas here were actually implemented. Thank you!

**Comment by 101necro** [comment]
Thank you for taking time to read again. It is so old now though, and game has developed allot since then (well done btw). 
Especially supports viability. 
But I still think a relevant idea is summon based items and improving summon abilities. My ideas aren’t the best, now I’ve played the game allot more and it’s developed, but the idea of it remains. One summoner you have done great on is warlock, only tweak I would have there is attack speed. The enemy buys a shivas. Even if you buy tons of attack speeds auras. Like drums and assault cuirass. They still attack too slow, as attack speed is such a rare commodity. It’s makes them useless.
