### ISSUE TITLE
Necronomicon extra creep idea

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/suggestions#296]
Ideas are for later upgrades of necronomicon
 -Flying
-one that acts like a cannon or sentry gun and is rooted in place when summoned (like siegemode item but on a summon) 
-a demon(keep in theme) which deals aoe dmg (like a radiance)
-a mini charger(similiar too the boss) with high health (which charges around every x amount of seconds and stuns when it is near creeps and prioritise enemy heroes) this would go with the twins(the boss) as they look like normal necronomicon creeps
-combine them into one bigger summon

**Comment by Wujekklawy** [comment]
Please focuse on what they do what Stats should be high with low etc. In some points you put too much flavour and it's hard to imagine how you want to them work

**Comment by 101necro** [comment]
Im not putting stats as thats too specific and thats a balancing issue. This is just a suggestion. My posts are for ideas which can built upon if liked. Stats are only a minor thing to consider. I thought its pretty obvious what a flying necronomicon would be. Or a combination... or even a mini charger as its based of the idea of a boss already implemented

**Comment by Haganeko** [comment]
These might work, although perhaps on other summon items. Formatting is a bit of an issue, though.
