### ISSUE TITLE
Summon item ideas (3 ideas)

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/suggestions#297]
Ideas to make summon builds viable.
- a item that amplifys the power of summons either by static(+1000 health or damage etc) or by x2

- a item that means u can infest in summon and makes your summon ur in last infinite time. This means people can get tons of auras and buff there summon and ride around it. You cant cast spells but can use items? maybe or not? not sure how powerful that is.
This means people can make one summon really powerful and use that as basically there character.

- also for heroes with auras to compliment the infest item is to make one time use only pets (use courier models) with maybe one abilities for example a spell caster pet a tanky pet and a high damage pet. Would be for late game as well maybe costing like 10000.

**Comment by Wujekklawy** [comment]
alredy are items that enchance summons, they have that thing, it's called "Aura", strengh of summons is for balance through lvling. But acktualy i like the idea.

P1 raw stats is not very good to add, ya know. Its boring, it not do a lot and it's way of League of Legends :)

P2 "a item that **means** u can..." sorry but i not care if my item got upset or not.  Also if other peaple are mean and get adored by it.  But jokes aside, that would do lifestealer ult usless. that is just his ult avitable for evryone.

P3 acktualy pet system would be prety fun. To have unkilable unit that can't be engage or attack but provides aura and bonuses to owner. it could be "trash can" for not needed  cores and lvling up by them.

**Comment by 101necro** [comment]
Yes but new items. Just because there are items available to certain things doesn't make it bad. Like adding range (dragon lance) was already in the game doesn't make the item siege mode a bad idea... I hope for u to consider opening ur narrow minded views in the future.

p1 response) Of course this interchangeable it could be toggle-able. Its the basis of a idea which can be stemmed off.
p2 response) Just because a item is similar to abilities does not mean it shouldn't be a item... Butterfly and Phantom assassins passive for example. Also by the way looking at your other comments your English isn't that great so when i say mean it has two different meanings. Also its example is spelt example not egxample. (I did find that pretty funny not going to lie)

**Comment by Haganeko** [comment]
We do need summoner items. These particular ideas are somewhat lackluster, however.
