### ISSUE TITLE
Detection idea

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/suggestions#298]
Basically edible dust 
- edible detection, as late game there are no spots for a gem left and u dont want to have to sell a item to get detection. So making a charge based detection like edible dust would help. And a button which needs to be pressed to use.

**Comment by Haganeko** [comment]
We are not going to use edible detection - it makes invis useless. What we are doing, however, is working on ideas to make fighting it possible. Soon, we'll implement detection on scan.
