### ISSUE TITLE
Spell caster mode item idea

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/suggestions#299]
A siege mode for spell casters that acts like siege mode and has magic splash damage and magic amp. While of course being rooted in place and is built same as siege mode except with aether lens instead.

**Comment by Wujekklawy** [comment]
yyy.... what? sorry but that is just confusing me and i feel i missing something important, can you write something more about it?

**Comment by 101necro** [comment]
The item siege mode which is already implemented but adapted and change the name to make a version which can be used for spells.

**Comment by Wujekklawy** [comment]
@101necro i not played gamemod cuz i don't have network atm. So what this item do actually?

**Comment by Haganeko** [comment]
It's an idea for a transformation item. Moriah's Ring already sort of fills this niche, though. Thank you for the post!
