### ISSUE TITLE
[Boss] Apsinthos

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#30]
This boss comes from the meteor/fallen star/sometimes called an angel, mentioned at Revelation 8:11. It's name is the inspiration for the drink Absinthe, and it's a star that falls into the seas and causes them to become poisoned. Alternative names are Wormwood and Absinthe.

In my depiction, it would look a bit like IO, a big black ball that floats. It would have a solar halo around it, like a star, despite being all black, and it would glow a sickly green at the edges. The tendrils would be erratic, more so than an octopus, sprawling in all directions. It should be about three times larger than Axe, in my mind, as long as there's enough room in the boss area to do stage 3 at that size. The fight area could look like a natural creek bed or sea-themed.

The boss fight music could give homage to Final Fantasy 7's instrumental of One Winged Angel, due to the meteor theme. As, in that fight, Sephiroth summons a meteor that destroys the Sol system one planet at a time.

In the first stage, Apsinthos knocks about random heroes with its tentacles. It will occasionally do a spin, damaging everyone in the boss fight area.

In stage two, Apsinthos raises to the air and craches back down with light green shockwaves, which push back and slow heroes.

In stage three, Apsinthos will fly into the air, and become invincible as it moves to the corners of his boss fight area, a wave of poisonous water following beneath him, which must be dodged or else inflict massive magical damage and slows.

Throughout these stages, it should probably use all attacks from the stages previous, to keep it varied and have some break between stage 3 invincibility.

**Comment by warpdragon** [comment]
Visually interesting. A giant pissed off amoeba. What if there was a stage where he splits in two after taking certain amounts of damage.then maybe keeps splitting.
You could also have him melt into poisonous water and reappear in a different place. He could maybe solidify and shoot spikes in a dodgeable pattern or he turns into a perfect sphere and becomes untargettable while slamming into the ground at random.
Amoeba designs are fun. Also what, if anything, is inside it? Does it have a true form that reveals itself? Doesnt have to.

**Comment by JSampersand** [comment]
It could get in a bumper car.

**Comment by JSampersand** [comment]
Amoeba were far from my mind when I wrote this. It's supposed to be an evil/destructive star, pretty much. As I said, this model could be substituted for an angel by the same name if a Biblical anthropomorphic star of doom was outside the theme in some way. The boss fight was thought of to fit with the mythos, and not the other way around.

**Comment by l34Um1** [comment]
Boring mechanics. Closed.
