### ISSUE TITLE
Make Tranquils not useless

### ISSUE THREAD

**Issue by gregrzick** [AngelArenaAllstars/suggestions#300]
All boots are mean to help farm right?  So how about another farming mechanic for these extremely useless as of yet boots.  Have them give bonus gold from creep kills, but here's the catch the bonus gold grows over time and it's not great if you're killing creeps constantly only if you do so sparingly.  I'm thinking the amount of gold you get would have logarithmic growth with the curve increasing with level of your boots.  The point of these boots would be they allow you to harass the enemy directly without losing out on gold too much so long as you take the occasional creep kill.

**Comment by Haganeko** [comment]
Tranquils have been reworked. Thank you for the help.
