### ISSUE TITLE
[Enchancment]Boss drop shop information

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#301]
First thing first. i dunno if that is alredy in the game cuz acktualy i not played it (i have no way as i mentioned while ago, i have my stuff back but still not reialable networc conecktion, i an use only public ones for now and probablyy for longer while)

i suggest include patern desryption for cores and items that only drop from boses and buyable from shop at middle with include something like:
"Drop from x Tier bosses"

also i suggest indicate that there is "secret" shop in Azazel place but if wanted to acces show comunicate "Shop open after Azazel killed" instead of standard "shop is out of reach" or "tutorial shop is not avitable"

>for items that can be bought would be nice to add little "S" in corner to show that it can be bought in secret shop

**Comment by 101necro** [comment]
Im not being funny. But if you dont play the game then how can you have any idea of how to change it. I see you making allot of comments but if you dont actually play the game and not know whats in the game. Then you shouldn't really be disputing peoples ideas who actually play the game and experience it.

**Comment by Wujekklawy** [comment]
@101necro if i would say that "this need to be changed cuz its op" or something similar you would be 100% right. But on the other hand if someone work on game or gamemod he mostly work on paper. Only last stage is on actual product. And if you would read my suggestions they are only hypothetical stuff and suggestions of new things or comments about stuff that other people suggest.  And trust me, i would play gamemod if i could. Then i would spam Bug reports with op stuff and bugs.  ;)

**Comment by Haganeko** [comment]
We do have an explanation on the workings of cores on the shop.
