### ISSUE TITLE
[Map, Enchancment, Mechanic] Wishing Well

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#302]
>Recently going through some issues in suggestions i got some ideas for items but i thought that combaining them in to this would be an amazeing option. Mechanic that is not neesairly needed to understand, but make easier, is one from Gamemod "Guarding Athena". In short, there was an option to upgrade certains stats of Athena mentioned in title. Upgradeing these statisticks also upgraded person that spended money on them, and when maxed given all team special bonus. In short Roshan of OAA 

Wishing well could work in several ways. Here are that i think are best way to do certain mechanic's of it. Keep in mind that some of suggestions are not intended to work with certain other ones.

Acktivating:
---

 1. Wishing well acktivate for short time evry x min. That could also create objecktive teamfights, such as teamfights over Roshan.

 2. Well is Acktive all the time and can be accesed anytime. (not recomended)

 3. Can be accesed after xTier boss is fallen. Or have his own Boss. And then switch to point 1 or 2.

Captureing:
---

 1. One hero must finish incantation on Well. Similarly to tombstones frome Valve gamemods.

 2. There is small area around Well that need to be captured by standing enough time on it by heroes from only one team. Similarly to CTP mechanic from Valve gamemod "Colosseum" earlied called "Haunted Colosseum".

 3. don't need to be captured and work like a shop. (not recomended)

Core mechanic:
---

 1. Enables to gain pernamently or temporary (until next opening of Well) Buff/Debuff on Whole team (debuff on enemy team).[Wilingly enable to chose buff and debuff, buff are pernament and small debufs are more powerfull but temporary, temporary effeckts should disapire when Well will be reacktivated so if need fight over it this effekts are not anymore acktive]
>If need capturing and is acktivateing from time to time for free. If not as a tiping it. Can be as a lottery where how much team donated comparing to other one set chance of wining. [for eg. if teams donated 1000-1000g wining chance is 50-50%, if tipped 1000-500g is 75-25%]. With buff and debuff.
 
 2. Enables to enchance items to rise they stats.
>For this should have max 5 charges and being usable only once per acktivation for one player, so one person can't enchance 5 items and need chose one. Enchanted items should be  possible to further enchance. Lvling up item lose enchance but higher tier item get more from enchanting. Enchanting would  incrise effeckt chance, effeckt value and stats of it.

Buff/Debuff egzample list:
---
 
Here is list of statisticks that could be manipulated by wishing well. Buffs should not be higher than around 5% of base value so to gain significant advantage it need tk be captured several times.

 - Spell amplification.
 - Vision radious.
 - Bonus damage.
>as debuff could reduce bonus damage by for eg. 15%
 - Coldown manipulation.
 - Spell cast distance.
 - Attribute bonus 
>for eg. give bonus 2% attributes as buff, 2,5% as debuff decrese 
 - Item manipulation. [similarly to enchanting items from ealrier, can incrise attributes, incrise values given by effeckts and chance to gain it]
 - Expirience gain [incrise and decrese]

Post word:
---

Primerly i thought of it as a thing that will incrise teamfights, with lack of can dramaticly incrise time needed to end of the game. Also it force more of a team based gameplay as well of benefiting teams that are better in fighteing than farming. Buffs and debufs work on whole team not only on player that used it. For chosing buff and debuff could use moddificated system that is implemented in to Black star angel arena. To be more precise chosing items afted killing a boss.

**Comment by Haganeko** [comment]
This is a very complex mechanic for a side objective which has little to do with the core gameplay. Also, permanent buffs like this would increase snowballing. Closed.
