### ISSUE TITLE
[Item] Golden Ticket

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#303]
>avitable from start, Recipe have limited stock (one avitable on start, around 15 min restock time)

Golden Ticket
----

**Recipe:**

 - Iron Branch
 - Iron Branch
 - Mantle of Int.
 - Ring of protecktion
 - Recipe

**Stats:**

 - +All stats.
 - +int
 - +mana regen 
 - +Armor aura

**Abbility:**

 - Grants gold bounty when allay killed creep. Incrise Assist gold from heroes.
> around 1200 aoe Grants stacks for both of that. 1 for creep 5 for asist.

 - Grants gold for hiting heroes. 
> Ammount of gold depends on stacks item have.

 - Evry stack incrise mana and health regeneration. stacks are lost on deadh or while geting kill [Both creep and hero kills reset it].
> denying dont reset stacks. Give around +0,25 mana regen & +0,2 hp regen per stack

**Comment by 101necro** [comment]
The first part of the first ability is exactly the same as the greater greaves. And the 3rd ability is in the greater tranquil boots. As you have stated earlier in your previous comments that these are already implemented in the form of different items :). We also encounter the same problem as shivas cuirass where your reducing options of buying the other two items.

**Comment by Haganeko** [comment]
101necro has a point. Also we're trying to avoid early, non-vanilla items.
