### ISSUE TITLE
[Resource] Hero Suggestions

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#304]
For people that want to Suggest a hero for OAA in the future i share template and few tips for doing that. Keep in mind that before heroes can be suggested can be some time. Game first need to have all bosses fully implemented as well as items. 

Before you start:
---

 - thougt of something that is not used in dota. Not need to be new but at least in way that no hero have that. that will make your hero more unique and interesting

 - if you want balance hero you need at least 1 abbility with defencive potential (trust me, all heroes in dota have it) and at least 1 with damage potential.

 - have all time in mind if you creating support or carry, mele or ranged. A lot depends on that.

 - try to imagine hero in difrent scenarious and make him stronger in ones and weaker at others.

 - easy way for tree you neend knew what you want from your hero, also think what builds would work on it, chose your favorites and try to fill holes in them.

 - harder way for tree (my favorite) is focuse on manipulating abbilities, for that you need good balanced hero so you will be able to create 2 ways he could go.

 - don't care about strengh of abbilities, this will be balanced latter.

Template:
---
>not need to necesairly put name in suggestion, just name suggestion by hero name

>here put infotmations such as "mele', "ranged", "Int" etc. not implementing them is leaving choice for dev team to chose. 

>if needed put here explanations to **core** mechanic that need to be known before knowing  hero

Q [] 

W [] 

E [] 

R []

>D[]
>
>F[]
>
>place only if hero have more than 4 abbilities

>Aghanim Scepter Upgrade: (if have)

>Hero Abbility (if have, hero abbility is binded to hero and not need lvling, in dota abbility like that have sillencer or pudge[in coding gathering stacks for flesh hip is seperate from that abbility])

Tree
>that will be necesairly to do and not leaving that for dev team. I know that it is most hard think to do expecialy when you completly have no idea what hero is capable of and how it would be played.

**lvl 10**  / 
**lvl 15**  / 
**lvl 20**  / 
**lvl 25**  / 

**Here is link to the file:**
>file dont have any coments and is just raw blueprint.

[HLayout.txt](https://github.com/OpenAngelArena/suggestions/files/1060996/HLayout.txt)

Example:
----
 
ranged, inteligence, support/core.

Q [Blinding Fog] AoE, evry unit standing in it have reduced damage up to 60%
>work similar to rikkimaru's smoke

W [Moon Blesing](Wolfs need no armmor ;} ) self heal, heals wolf queen and wolfs. If number of wolfs is lesser than max number of them possible 

E [Pack] passive, spawns up to x [min 3 on lvl 1] white wolfs [spawns 1 per x seconds].* [wolfs should be also teleported to duel]. Wolfs don't have timer. After respawn wolfs that are still alive are trated like neutrals and Wolf Queen start with 0 wolfs after respawn. (i thing yoy should know what i have in mind)

R [Ambush] spawns two white wolfs on target. all wolfs gain +x damage for x seconds. [around 100 at lvl 1] wolfs guaranted by ultimate don't desapire or despawn wolfs guaranted from E. If they not died before next ult disapere to spawn new ones. 

>
>* Wolfs cannot be controled, they are controled by bot. They follows Wolf Queen. 
>White Wolfs suggested stats for lvl 1:
>HP: 250
>Damage: 20
>Armmor: 1
>Att. Speed: 287
> 
>They agro ladder:
> 1. target that Wolf Queen attacks. 
> 2. targets that attacking Wolf Queen 
> 3. closest enemy.[excluding neutrals]
>
>if Wolf Queen is dead they seak for enemy and follow it. Only enemy tatgets. 
> keep fighteing if they was doing it when Wolf Queen dies.
>

Tree

 **lvl 10** White wolfs +x dmg and y hp / Wolf Queen +2x damage and 2y hp [around twice as much what wolfs gain] (for ppl that will want play more like a support)

**lvl 15** White wolfs gain critial chance / Moon Blesing now work on allays [aound 600 AoE around Wolf Queen]

 **lvl 20** White wolfs gain x damage per attack on same target [work like troll's fervor] / Incrise radius of Blinding Fog

 **lvl 25** White wolfs gain invisability [don't brake when attacking] / Blinding Fog reduce 100% damage

**Comment by Haganeko** [comment]
We are not currently looking for hero suggestions. Thank you for the post.
