### ISSUE TITLE
Natures Prophet Teleportation

### ISSUE THREAD

**Issue by Darksold** [AngelArenaAllstars/suggestions#305]
I think Natures Prophet should be able to teleport through the cliffs of the boss area but not into the enemy Farming Cave.

**Comment by Wujekklawy** [comment]
It would be very difficult to do that. Easiest way to make np not tp somewhere is by makeing terrain impassable. And you can't do that in farming cave. I dunno if they will do that, implementation will be such a bullshit. But maybe they will ass defense structures in cave and program them to not attacking neutrals. That way or another you can just have it warded and kill him.

**Comment by Haganeko** [comment]
The farming cave is mostly safe due to the offside penalty. On the other hand, zone control has been introduced in order to stimulate fighting over bosses.
