### ISSUE TITLE
[For Dev] Let's talk

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#307]
Is there a way to contact you guys/ I have a lot of hero ideas and i would love to hear how you like them (atm. 24) and your opinion so i would know how to modyfy them or what you guys would like to see in one of them. Also that would help answering your questions if something would be not clear enough. If you want to comunicate live me where to send you link to folder on mediafire? (better get backuped, i lost my all work one time)

Ps, discord or any voice chat is out. Only way for me to have stable networc is librery. So i wold be need to know when and how. txt  chat or e-mail.

**Comment by Haganeko** [comment]
Hello. Sorry for not answering much lately, life has been crazy. We just aren't taking hero suggestions right now. We barely have the manpower to implement the things we're doing right now - fixing bugs, putting in the bosses... Thank you for the offer, but I don't think we can take it.

**Comment by Wujekklawy** [comment]
@Haganeko its mainly for me to know what things you would like to have in heroes so i could work a li'l on that earlier and if you have some suggestions for that matter :) all of it is just raw blueprints and i know that you will not implement them for like half of year probably
