### ISSUE TITLE
Venomancer

### ISSUE THREAD

**Issue by 101necro** [AngelArenaAllstars/suggestions#308]
Buff venomancers Ultimate.
Reason: It deals so little damage.

The damage output of the venomancer ultimate at max is the same amount of damage as a max level radiance. I just found this quite funny how his ultimate is actually much much worse than radiance as it has a cooldown and cant kill you and only last 15 seconds.

**Comment by Haganeko** [comment]
This comment is half a year old and likely has nothing to do with current balance. Closed.
