### ISSUE TITLE
[Map design] Fill the empty spaces in the map

### ISSUE THREAD

**Issue by Sam-Kruglov** [AngelArenaAllstars/suggestions#309]
In the latest OAA Baumi asked for ideas.
What about you put there actual bosses standing in line to take the place of the previously killed bosses? And have halls to each boss arena. For example, a boss dies, the respective hall opens, the same boss walks in, the hall closes and the line makes a step forward. There can be many different lines of the identical bosses. The bosses can talk some funny shit with bubble pop-ups.

**Comment by Wujekklawy** [comment]
Or why not  make fight with all of them with more to win?

**Comment by Haganeko** [comment]
This would look cool, but it would have no mechanical purpose. Closed.
