### ISSUE TITLE
[Boss] Golem

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#31]
This is a boss referencing several character in Jewish mythology and Semetic religion. It comes from the traditions of the Wandering Jew, a ghost who travels the world. Golem, a rock monster in Jewish mythology, and Judas Iscariot; a character sometimes said to be all three. The Wandering Jew is also said to be or be associated with Pontius Pilate. Instead of transformations for a single boss, this could be a gauntlet of three bosses. I really like the idea of this boss being activated by planting a tree, perhaps a secret item/core. If so, perhaps switch the positions of the first and second bosses.

This boss would change the way it looks across three stages. The first stage, it would be a rabbinic looking character with a great gray beard and dark clothing. Jewish looking outfit. He could be ghostly, but not overtly so. Maybe something like this but not to the point where it's just you're fighting a Rabbi, lol: http://freethinker.co.uk/images/uploads/2014/01/Belz.jpg

Second form, it'd be a hung man, flying in the air. The rope end in space. He'd be corpse-like, bloody. Of course, Judas Iscariot in the Bible's noose broke and he was dashed on the rocks some below a cliff. So, he could look particularly gruesome. 

The third form would be a rock/mud monster. 

The tree, if you do that, would be gnarly and dead. Pale. Perhaps a dead cyrpress. http://www.asergeev.com/pictures/archives/compress/2006/517/jpeg/05l.jpg

In the first stage, Golem blinks around the map, dealing magic damage in arks that could be telegraphed on the ground (if you plan on doing that, design wise). After a bit of damage is inflicted, he blinks away to another spot and flashes his magic damage.

In the second phase, the hangman version follows players and lashes them with the end of his noose like a tentacle, while maybe splashing blood at farther characters. Perhaps the lashing could do substantial damage, forcing the chased player to kite the boss, and then he alternates to another played.

In the third phase, Golem becomes a rock monster and rolls about the map, striking through players and has a chance of stunning himself on them. This could be a traditional 'rolling boss' fight, where the objective is to get him to stun himself on the environment. Either by moving the environment or standing where the environment is in his path to you. To aid this, spikes could jump out of the ground periodically, and Golem could target and telegraph specific players.

**Comment by l34Um1** [comment]
Uninteresting mechanics. Closed.
