### ISSUE TITLE
[Item suggestion] Item for support heroes which makes them better versus bosses. 

### ISSUE THREAD

**Issue by Valiens** [AngelArenaAllstars/suggestions#311]
Since heroes which more utility spells are usually the ones who struggle the most against bosses, how about make this downside an upside? Now it is not really possible to properly CC a boss outside of getting a Skadi and MKB and just hope that you will cancel every AA animation. So what if there was an item which makes it so you deal less dmg or may be take more dmg from bosses but instead all CC spells which you use on them last longer? This way tanks or high dps heroes which already were effective wouldn't want to bother with this item, but supports who can't damage or tank would be able to stun or root a boss in a right moment, so your tank would die to that last hit. Or at least that is the idea.

**Comment by Haganeko** [comment]
The issue is that CC'ing bosses makes the fight less interesting, since it becomes a matter of keeping the boss disabled while punching it. TBH I'm glad MKB ministun is gone.
