### ISSUE TITLE
Sollution for Caster vs Bosses

### ISSUE THREAD

**Issue by Emprorofdirt** [AngelArenaAllstars/suggestions#312]
An item that damages or weakens the bosses if the dispells a disabel from the carrying hero.

My suggestion would be an Euls since Schyte already have a great mechanic and Abyssal Blade isn't really a caster item, and it would be nice if the item it self where to have an active disable.
(Could also be Rod of Atos but since I am a absolutely terrible player I never really like to use Euls thus I love the irony if my suggestion would be forced to buy Euls more frequently)

Situation: Crystal Maiden cast Frostbite (let's pretend it's a stun in this fictive situation) stunning the boss, boss dispel stun and get an increased damaged recieved from spells over a balanced period of time.
She cast Crystal Nova, when purged it does a larger portion of damage wich in turn is increased by the effect from purged Frostbite.

The obvious effects that a boss would/could dispell are: slow, disarm, stun and silence but I bet you will get a few good ideas for details.

Effects could be: damage over time, instant damage, decreased spell resistance/increased spell damage taken, miss chance, interupt or any you feel good.

This would make smaller diffrence for the likes of Dazzle but could make Lina much more powerful when combined with a caster using Euls.
With Omniknight who have a passive slow you would face the question if you want the effect only to trigger from an Activate or also from a passive, also items such as Skadi are a question to consider.

I feel that this idea could further the benefits from taking team composition in to account and could make a caster based line-up more viable.

**Comment by Haganeko** [comment]
Reducing boss magic resistance has mostly solved the issue. Closed.
