### ISSUE TITLE
Making everyone useful in boss fights 

### ISSUE THREAD

**Issue by Goliathcraft** [AngelArenaAllstars/suggestions#313]
My idea for an item that help heroes like CM would work like this: The item would have a passive that activates as long as a certain contribution threshold when fighting bosses is not meet. This means that the game checks how much damage you are dealing or tanking against that boss, and if this contribution is under a certain threshold you get some bonuses that help you fight this boss, like spell amp, regen, etc. This enables "weaker" heroes to contribute when fighting bosses without giving strong heroes the opportunity to abuse the item.

**Comment by Wujekklawy** [comment]
U know,  balance in dota is a bit tough topic, evry hero is good with one things and intentionaly weak in others. For eg Ursa is good vs tanky heroes and is very good in situations when he have only one target but in teamfights or fighting a supports when he isn't much ahead he is pretty weak. Stun, eul or slows and Ursa starts to have a lot of troubles. Going back to my point, in my opinion item like this only would destroy balance. You will not need to care about team composition or with hero will do what role. When there is no downside of something then why to care about it. And if you don't care about something in game it makes you noob or that thing totaly useless. And when core of game would be useless (Boss fighting) then noone will enjoy it.

**Comment by Goliathcraft** [comment]
#I most definitely agree with you that every hero in the game has a certain role and that we don't want every hero being able to fulfill every role in the game. But what I proposed was targeted towards the developments team request for ideas on how some characters who struggle with helping in any conceivable way when it comes to boss fight, meaning that them being there had 0 effect and that these character would have been nothing but useless. The core idea was to give those few heroes a very slight "buff" that could be nothing more then temporary effects that help them while fighting bosses. My problem with the proposal of most other people was that their simple wanted to buff those weaker heroes with stuff like "double damage on this ability against a boss", so I was looking for a way to universally buff characters who might be struggling to extent of non existing when it comes to boss fights, without messing to much with the overhaul game balanced, and ensuring that this could not be abused to trivialize any of the mods content. Like I already said a few times now, the buffs would only apply to you if you weren't doing a lot to help with the boss kill compared to your teammates, and would have only had minor buffs that won't make them suddenly kill their boss on their own, but would let us see small increases in maybe regen or slight spell amplification. To give a numerical example, while you have this buff when fighting a boss, you would get 5% spell, increased regen and whatever. I hope you were able to follow my line of thought a little.
But again, I do agree that we don't want ever character being good at everything, which was exactly in what way I wanted my idea being different from most others who addressed this issue

**Comment by Wujekklawy** [comment]
acktually, from what you wrote peaple are just damdams who want these heroes give more damage. I don't know whitch heroes u mean exacktly but folowing your example i think it is mainly problem of supports. So as a support your role is to help team, why then evryone wants to these heroes deal more damage? It could be achived by makeing support items better, for eg. greaves mek could get dispell or greaves make affeckted units immortal for like 1s(good use would save team asses when fighting boss that deal a tone of damage with one spell and now is to late to doge it, abusable? too strong in teamfights when more than 1? Team shared cooldawn is still a thing in dota ;)  ) just by makeing support items more valiuble at boss fights you can make any suport a god that can save your ass when something goes wrong or sacrafice you becouse you flamed on him. Carry role is to deal damage, nuker role is to kill enemy hero that can fuck you up faster than he can do it, support role is keep team alive longer by destroing enemy plans or helping team outlive enemies. That is just how it is, there is no support that can deal alone with roshan 20 min in game and there is a bunch of carries who can do that. (ursa can do it even in like 12 min). Nukers anyway should don't have that much what they can do to boss. Nukers are not well equiped to deal with something tanky. Theyre main porpouse is to nuke heroes like enigma, lich or bane. A lot of burst not that much of a dps.

**Comment by Goliathcraft** [comment]
Well our little discussion doesn't matter anymore since with the latest update bosses lost magic resistances and now take just flat 20% more magic damage overall...

**Comment by Wujekklawy** [comment]
@Goliathcraft it's sad cuz supporting options in my opinion would be more interesting that just removing magic resistances

ps. i don't rly care if that wwas fixed that way, we still can do ouer discussion about that ;), it's fun so why end it cuz that minor factor that it was "fixed" xD

**Comment by Haganeko** [comment]
As pointed above, casters are better vs bosses now. And in any case, the idea was not a supporting item.
