### ISSUE TITLE
[item] My idea for eatable gem that will work

### ISSUE THREAD

**Issue by Sam-Kruglov** [AngelArenaAllstars/suggestions#314]
Gem "lvl N" can only allow eating an item of "lvl N" and costs appropriately.
The problem to be solved is to be able to upgrade eaten items.

**Comment by Wujekklawy** [comment]
If i good remember Baumi said straight forward that he don't want to have eatable gem in this gamemod. However maybe he changed mind. I don't think it will pass tho. Ps, for now dev is focused on programing and implementing stuff so any response from them will take a longer while ;)

**Comment by Sam-Kruglov** [comment]
He only said he doesn't know a way that would make the gem work. Not that he doesn't want the gem at all.

**Comment by Haganeko** [comment]
Edible Gem effects completely disable invisibility. It's not a counter, it's a hoser. Closed.
