### ISSUE TITLE
Shielder debuff for huskar.

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#315]
evryone knows huskar just wreack shit from shielder becouse of his burn that don't get reduced damage  then my suggestion is to change a little coding on this abbility to deal damage from where huskar is standing  and not from target. that will force huskar to be more acktive if he want to be efficient or incrice time of dealing with this boss.  its A debuff that will affeckt nothing that just that one scenario where he is a little of op.

**Comment by Haganeko** [comment]
Doesn't seem to be an issue people have.
