### ISSUE TITLE
An alternative solution to solve the weakness of casters vs bosses

### ISSUE THREAD

**Issue by Patrickthehuman** [AngelArenaAllstars/suggestions#316]
As having 'an' item to increase spell amp versus bosses would reduce the potential for interesting and different item builds. I would suggest that a special modifier for spell amp versus bosses be placed on many items, support and utility items in particular. This could make casters such as CM, who do very little physical damage to bosses, to be able to contribute to boss kills. While also making sure hybrid casters, such as lina, do not become too strong against bosses as commitment to purely utility and support and support items would reduce physical damage potential and purely physical damage item commitments would not come with the increased magic damage that bosses currently take. Hopefully this is not too hard as I think it would be a great solution to this problem.

**Comment by Haganeko** [comment]
Reducing boss magic resistance has mostly fixed the issue. Closed.
