### ISSUE TITLE
Website for OpenAngelArena Tournament

### ISSUE THREAD

**Issue by SchadowofMorning** [AngelArenaAllstars/suggestions#317]
Dont know where else to put it but here, made a MEAN-Stack website, posted it here on github:
https://github.com/SchadowofMorning/OpenAngelArena-Tournament-Website

**Comment by Chronophylos** [comment]
Why post this here? You should post this in the discord....

**Comment by Haganeko** [comment]
Is this still a thing? A relevant one?

**Comment by Chronophylos** [comment]
Doubt it
