### ISSUE TITLE
Unity[TRASHED HERO], feel free to use any mechanic in other things

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#318]
>i make that haveing in mind cool idea of hero that you could play as nuker or durable or carry or hatever you want, but... puting aside that programing that hero would take a "while" when i was writeing it with evry second i was realising that it will be acktualy a garbage, don't get me wrong, myself i acktually like some of this stuff like for eg. **[Ethernal Haunt]**, i acktually find this as good and pretty powerfull abbility with ocasionaly tendency to be teamfight wining. It is just... too few and too much at the same time. Abbilities have own sinergies but they just... don't realy work with each other, at tthe other hand it is just what i wanted to and yet it is something that will not work at any way... so.. wise words to remember fo evryone, as some peaple say, if something is for evrything... it will be for nothing (polish saying, li'l sence could escape thro window cuz translated 1:1 and some words in both languages have slightly diffrent meaning)

 ranged.

Q **[One with all]** Change primary attribute, each stat provide diffrent buff. Leveling up incrise all attributes and incrise main attribute. (for ballance could use incantation while changeing)

W **[Sacred Javelin]** projecktile, ground target,longer cast animation,  Knock back, stun and deal damage 
>can depend on main attribute for eg, str -> more knockback, agi -> more damage,  int -> longer stun)

E **[Ethernal Haunt]** AoE dps, apply debuff affeckted hearoes, debuff decrese phisical and magical reducktions.

R **[Multitasking]** [Passive] Give diffrent buff depending on att. type. [Active] Change betwen mele and ranged. (for ballance could use incantation while changeing)

 **attribute stats:**
-Strangh, Bonus Health & bonus regen.
-Agility, Armor & Attack Damage.
-Inteligence, Spell amp. & Cooldown Reduction.

 **buffs:**
-Melee, Attack Speed & Cleave
-Ranged, Movment speed & Resist's Reducktions

**Tree**

**lvl 10** More main attribute gain from One ith all / Grants splash effeckt on attack
**lvl 15** x% more attribute gain from One with all / Ethernal Haunt now stacks
**lvl 20** You can now blink to unit hited by W / +att range
**lvl 25** Ethernal Haunt is now aura (if stack's it do it in tick's [~0.7s]) / x% of non main att give dmg

**Comment by Wujekklawy** [comment]
ps, no i can't send this on discord, i can't find that F. link

**Comment by Haganeko** [comment]
We are not currently looking for hero ideas. Thank you for your post.
