### ISSUE TITLE
Black King Bar rebalance

### ISSUE THREAD

**Issue by CicadaOTT** [AngelArenaAllstars/suggestions#319]
So bkb in regular DOTA is boring and kind of op, but fits in frames of general idea: casters are strog in early/mid game and fuck caster in late game. In angel arena early/mid game is not so important because players interact less then in regular dota because there is no a laning phase and you are getting 6 sloted in 10min or so.

so my sggestion is

Make BKB togle and work like armlet, so it gives you soft disable imunity (not sure if i got it right, but i mean same disable imunity like bkb curently gives), but drains 3-5% of max hp per second, and additional magic damage resistance like 30-50% when on.

**Comment by Haganeko** [comment]
You provide no reason why this should be done, and it is a major break with vanilla (which is something we want to avoid). Closed.
