### ISSUE TITLE
[Hero Design Idea] Hell Cannon

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#32]
This is a laser cannon, perhaps mechanical with legs or flying. Obviously, completely fantasy/sci-fi. Basically, what this boss does is phoenix's beam attack, except nothing but that.

It could look futuristic/space laser-y. It could be all gnarled with grotesque and heavily ornate features. I think the latter sounds cooler. Legs might be more interesting, design-wise. I'm thinking it'd be a copper-black with foiled, boxy geometric shapes thinning toward the end of the barrel (perhaps taking inspiration from a coal blower http://www.lostcrafts.com/images/Blacksmith-Forge-Blower.jpg or an old-timey camera http://tse2.mm.bing.net/th?id=OIP.M2a0c1584fdfdaa6c7850c89a091bf86bo0&pid=15.1). More ornate wise, I'm thinking something that looks like the walkers in Final Fantasy 6 (http://tse1.mm.bing.net/th?id=OIP.M07959ff4cd7998851d9b65cdefd7e526o0&pid=15.1), but maybe with more styling like a gargoyle and with the sort of texture as the nether quarts from Minecraft (http://www.bing.com/images/search?q=nether%20quartz&qs=n&form=QBIDMH&pq=nether%20quartz&sc=8-13&sp=-1&sk=).

It shoots short burst lasers about 400 units away, which only hit the primary target. In my mind, these are wide beams. It's first ability would be a shorter phoenix burst, which is pretty straightforward on damage. The second might be a shorter duration use, burning effect beam. The third could be a passive relating to improving the utility of these beams. The ultimate could be a charged beam which does piercing damage at the target. The aghanims upgrade might allow all of these to be used in charged (and more powerful form) at once when the ultimate is used.

**Comment by warpdragon** [comment]
I like laser bosses but what makes them interesting are interesting attack patterns like Piety from Path of Exile who has a spinning phase where u learn u have to stand close to her, and VelKoz from League of Legends, which uses complex geometric patterns and timing windows to create fair and interesting challenges, punishing atupid opponents harshly. There are probably other examples involving mirrors and shit. And also consider breaking up the one trick laser with aomething non-laser related. I know it sounds crazy but it could work.

**Comment by JSampersand** [comment]
This is a hero concept, by the way.

**Comment by l34Um1** [comment]
We don't do hero concepts yet. Closed.
