### ISSUE TITLE
Give gold to all players every 10-20 minutes

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/suggestions#320]
Recently i noticed that new players often have poor expirience in their first game.
Good players outfarm them too much. And it is a good thing in its own way. But right now a player that know the rules can become 6 slotted before newbie even finish his second slot.

Also people farm too much in this game. It would be great if they could focus more on teamfighting for bosses instead of killing creeps after 15 minute mark.

I think it will improve the game expirience a lot (at least for new players). Of cause there is an arcane boots, but new players usually dont find them in their first game. And they have their problems with illusions (I reported [this bug](https://github.com/OpenAngelArena/Bug-Reports/issues/73) in the bug section already).

**Comment by Haganeko** [comment]
We already have passive gold; in fact, passive gold grows very quickly with time. Don't know what to think about passive EXP, though.

**Comment by VTVTVT** [comment]
Its too small. Doesnt even impact the game when you need like 20 000 gold for recipe.

**Comment by VTVTVT** [comment]
IMO we need some way to give everybody gold. At least some basic amount. It could ease snowballing effect a bit.

**Comment by zelding** [comment]
The gold/exp feels quite balanced right now; isn't it possible, that you are not using the items and the environment to their full potential?

If you are using the farming boots, and participate in the ganks you should have no gold and exp issues

**Comment by VTVTVT** [comment]
Its not about me I am worried. We usually snawball our every game, because I play in party. We build mana boots and don't have problems with gold.

I just dont like the idea of some farming boots you need to buy almost in every game. New players usually pick carries and build treads and phase boots. So they are usually underfarmed. Which makes their game miserable.

**Comment by Haganeko** [comment]
All gold and experience, inclusing passive values, is being reworked. Closed.
