### ISSUE TITLE
Give gold and expirience for killing bosses (to the whole team)

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/suggestions#321]
Again, to make more organazied teamfights happen.
I know that expirienced players will go for bosses anyway. But most of the people playing custom games are casuals. So, in my opinion, you need to create additional motivation for team movement.

**Comment by Haganeko** [comment]
We have debated this. So far, the major position is that we want cores and gold/exp to be separate resources. It helps to prevent too much snowballing.
