### ISSUE TITLE
Decrease stats given by item upgrades

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/suggestions#322]
To prevent excessive snowballing.

**Comment by zelding** [comment]
What are your issues? Provide examples, and suggestions for solutions; don't just spam your petty concerns in threads

**Comment by VTVTVT** [comment]
I have no issues. I just want to improve the game I love. But if I am not wellcome here - then tell it openly.
Dont just spam your passive-agressive comments.

**Comment by zelding** [comment]
By definition your post is an Issue. One half line of text is not an explanation, it is spam. You can't possibly imply that all upgraded items should be modified, or you are out of your mind. 
Please read the [Guidelines](https://github.com/OpenAngelArena/suggestions/blob/master/doc/guidelines.md), give some time to think of your suggestions/issues, form an opinion, add examples, suggest solutions.
Maybe look around the other peoples suggestions, maybe you'll notice some differences.

**Comment by Haganeko** [comment]
As zelding noted, this is not exactly actionable.
