### ISSUE TITLE
Create early game objectives on the map.

### ISSUE THREAD

**Issue by VTVTVT** [AngelArenaAllstars/suggestions#323]
To make early game more complex and interesting.

Right now you can either farm creeps or bully enemy. Thats it.

**Comment by zelding** [comment]
I pretty sure that is by design. The mode is supposed to be very similar to the vanilla dota until lvl 25.

What would you suggest? 'Mini-quests' ?

**Comment by Wujekklawy** [comment]
#302

**Comment by Haganeko** [comment]
That is something we have had in mind, but this ticket provides no specifics. Nothing we can really do with it. Closed.
