### ISSUE TITLE
[Question] Old submitons

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#324]
So, there is some submitions that are hanging like a yeaar now and a lot of them still in outer space stopped in time and with no destiny... so... did they are accepted to gamemode cuz still they are not trashed or they are "in concidering" cuz almost all of them have no proper responce or just evryone just forgot them? They even "survives" all cleanings and hang for ethernity now. Most of them are bosses that suposed to be in development now. Some are items and some are overall ideas. So my question, wa happen...?

**Comment by Haganeko** [comment]
We're back on it! Thank you for sticking with us.
