### ISSUE TITLE
Eatable Gem secondary objective

### ISSUE THREAD

**Issue by Nortlen** [AngelArenaAllstars/suggestions#325]
I have an idea that could help solve the true sight problem. It is a miniboss that would spawn either periodically (for example: every 10 min) or he could be summoned by just purchasing an item (the way a courier was upgraded in the earlier versions). The item would have a cooldown, which should be probably shared for both teams. The boss would be globally announced for both teams. After killing the boss it would drop a consumable item that would give true sight until death. The boss should scale over time (the way creeps do) so killing it would be difficult at any point.

**Comment by Haganeko** [comment]
We have some ideas as to how to fix the invisibility issue. The problem with gem effects is they completely nullify invisibility, instead of providing tools to deal with it.

**Comment by Nortlen** [comment]
I thought the problem with eatable gem was that anybody could just get at any point or you couldn't get it in the early game. And this way it wouldn't happen because the enemy could contest you get it and it would have quite a long cooldown so you couldn't just retry. But thanks for the feedback.
