### ISSUE TITLE
Bloodstone Soul Ring Merge idea

### ISSUE THREAD

**Issue by yztrash** [AngelArenaAllstars/suggestions#327]
Ring of whatever (name tbd)

X HP
X MANA
X STRENGTH
X HP REGEN

Passive: Bloodpact
Begins with 14 charges, and gains a charge each time an enemy hero dies within 1600 range.

Each charge grants 0.35 mana regeneration per second, and reduces respawn time by 3 seconds.

If the bearer dies, the Bloodstone loses a third of its charges.

Passive: (name tbd)
Converts all of your HP regen to Mana regen

**Comment by Haganeko** [comment]
We are not doing item merges. Closed,
