### ISSUE TITLE
A couple item suggestions

### ISSUE THREAD

**Issue by murapix** [AngelArenaAllstars/suggestions#328]
**Titan Bane**
Gain some % more damage to enemies with more maximum health than you. Bonus damage increases with the health difference.
\- Attack Speed
\+ Attack Damage
Active Effect: For a few seconds, your attacks shred armor too. Only works against targets with more health.
_Become stronger vs tanks, but not as useful against squishier targets. T4/T5 item, possibly built from Desolator_

**Helm of the Black King**
Gain a charge each time you are disabled, up to a limit. Does not count slows.
Gives some strength
Gives some armor
Active Effect: Consume all charges, giving target ally the BKB effect for a short time per charge, or dealing some damage to target enemy per charge and stunning them for a second.
_Helps in dealing with CC-heavy teams, as well as having a supportive option for tanks other than soaking damage. Possibly built out of BKB and Abyssal Blade_

**Comment by Haganeko** [comment]
The Helm is too similar to Charge BKB, to be honest. As for the Bane, we want to encourage long fights, not anti tank tech.
