### ISSUE TITLE
[Boss] Adrian, Saint of Butchers

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#33]
This boss is based on St. Adrian who died in 306. He was an Imperial guard who converted to Christianity while torturing Christians. Hes normally depicted with a pike and with an anvil on his head. Obviously, he'd be angel-like, with a halo. With the butcher theme, maybe you could do something with a Pudge or meat motif. The hurled meat as described below would be ham hocks or whatever you fancy.

Stage 1: Adrian swings his pike, dealing AOE damage in arcs. He changes target randomly, but goes for clustered groups, reavaluating positioning after each swing.

Stage 2. Step 1 attack, plus Adrian periodically hurls meat all over the place. Think Fire Lord ult from Warcraft 3. These meat chunks target players from their launch point, who must anticipate and move out of their trajectory.

Stage 3: Everyone in the boss areas is put in bumper cars, and so is Adrian. It's Carnival (although he was a Byzantine pre-dating that holliday)! Get it! No? Well, in any case, the boss continues to hurl meat chunks and players must bump the rest of Adrian's health down. He'll try to bump a single player, hitting anyone in his way when he zooms at them. Bumping Adrian's car will cause a knockback.

Maybe evil carnival music here? Carnival/merry-go-round themed boss area. If we're at bumper cars, we can afford to take a few more liberties.  Well, the Carnival motif would be because of the meat and he's so far the only saint and thus a strong tie to Catholic tradition.

**Comment by warpdragon** [comment]
HahahahahahHhaha yes this absolutely needs to happen. Meat hurling bumper car carnival. Sound like a lot of fun. 
Based on the level design afaik this kind of battle simply wont be practical because of the rare chance of boss sniping. Unless the guy invading also gets a bumper car. Now if im wrong and there is no boss sniping, then yeah. Totally bad ass!

**Comment by JSampersand** [comment]
Yeah, everyone who enters the area would be placed in bumper cars. It'd be a debuff, if it's not too much work to pull off.

**Comment by l34Um1** [comment]
Good theme, bad mechanics. Closed. Tell the writing people about the theme though, it's a cool character that we should use.
