### ISSUE TITLE
Linken's Lotus Bauble or Linktus Sphorb 

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#330]
A bit of a meme but It is a legitimate item idea. 

All names and numbers are tentative  and subject to Baumi's taste and balance

*O* = optional mechanic wether it be for aesthetics, balance, or design theory 

*PREFACE* 

If implemented this item would be beyond amazingly cool (in my opinion), with a unique/original active (as far as I know), and most importantly it would appease twitch chats need for an Lotus orb.

*BUILDUP*

Linkens Sphere + Lotus Orb+ possible recipe   (Tenatively I thought about requiring a reflex core as well but idk how this fits into your ideology/concept of reflex cores) 

Gives you a passive and an active

*STATS&PASSIVE:*

Stats:
Whatever stats balance deems necessary but it could just combine linkens and lotus orb
However since lotus orb and linkens are fully fledged items by themselves I maybe thought that nerfing the stats and having the item be purchased mostly for the effect would allow linkens and lotus orb to retain their individuality/viability and not overpower either item as the go to defensive item like Shiva's Curiass was.

Passive: 
Exactly like linkens sphere except the single target spell is reflected as well as blocked combining the lotus effect (*O* longer cooldown for balance purposes) 

*ACTIVE, (named Magic Distortion Field):*

No longer targetable on allies *O* (I decided this for griefing purposes as well as to give linkens and lotus orb individuality/support capability but it's optional)  

Possibly puts passive on cooldown upon activation?  *O* (I decided this for balance reasons but it might not be necessary)

Applies a strong dispel upon activation

Long Cooldown of ? duration. *O* Passive is disabled while on cooldown 

Duration is ? seconds (3)

In ? Radius AOE indicated by some sort of particle affect while the item is active (500)

All of your enemies flying magical projectiles as well as all single target abilities upon casting are rerouted  to your hero with a ?% (25) chance to block, a ?% (25) chance to reflect, and of course the chance to both block and reflect said abilities. (*O* this could include enemy buffs as well which would be interesting) 

 ( this block/reflect percentage could be a different type pseudo random/ the percentage drops with each sucessfully blocked or reflected projectile though this would be hard to indicate to players althoguh not all dota mechanics are clearly indicated numberwise, additionally if you do not like the RNG you could do away with the block/reflect chance and simply let the passive block and reflect the first one and then just have the user tank the rest of it )

*SCALING*

Stats, duration, cooldown, and block/reflect percentages could all be scaled

Duration and reflect/block chance  scaling would be more powerful while cooldown and stats scaling would be less powerful

I imagined that the passive would remain static

*GAMETHEORY*

I envisioned it as a sort of tank/disruption item that would be quite useful in teamfights because at the very least you stop your opponents single target abilities and/or redirect single target abilities from more valuable targets to your tanky self. The passive would also make it a decent item for self defense. I like the item desgin wise because it is reactionary and thus reminds me of a fast paced fighting game (its sorta like a fox/falco shine), for this reason I thought that it would be good to include a reflex core in the recipe despite it using regular dota items in the buildup and name.  

*POTENTIAL DRAWBACKS:*

The item is a bit convoluted/complicated and thus possibly a bit user unfriendly and hard to explain in tooltips 

The item does combine 2 high tier items which could potentially result in the Shiva's Curiass affect. However by nerfing stats and making it only self targetable enough I think it differentiates it to the point that all three items are viable and have their own niche.

Some difficulties I forsee in this item is possibly balance as there are a lot of numbers involved as well as multiple aspects to the item. But it is doable and is just a question of does someone want to go throught the trouble

It also might be a bit hard to code as far as projectiles changing course mid air and redirecting buffs and such, but with my limited knowledge I do not believe it impossible and thus it once again is an issue of does someone want it enough to go through the trouble.

One legitimate possible issue and solution is the interaction of Linktus with BKB/other forms of invulnerability making it too strong/fundamentally broken. I reasoned that a clause can be put in the coding that makes it so (with the exception of buffs) the hero must be a valid target for the spell in the first place for it to be redirected upon the casting of it 

(if you can pull a projectile mid air and then make yourself invulnerable then good for you, you deserve to block that).

The rules regarding multiple bounce spells, orb effects, and huskar and juggernaut ultimates would be the same as linkens sphere. 

*OTHER*

If the concept proves to be too fundamentally broken, hard to code, or aesthetically poor as a last ditch effort to save the Item there are 2 additional precautions which can be used in conjunction or by themselves.

1 disable the passive 
make it an active only item which is still quite powerful, simplifies the item, and once again makes lotus orb and linkens sphere more unique thus avoiding the Shiva's Curiass effect. Honestly this is probably a very smart thing to do and would improve the item but I enjoy my lotus orb upgrade being fundamentally quite powerful providing both the active and passive.

2 Alternate Active
You can change the active from a self cast item to an item that applies a debuff on all enemies hit causing their single target abilities to have a backfire chance redirecting onto themself or a nearby ally (buffs would target enemies) and/or a miss/cancelled chance where the ability simply goes in cooldown. 

I do find this version much easier to implement/balance but quite a bit more boring and less unique. It also changes the item from being reactionary and defensive to a proactive offensive debuff which fundamentally doesnt fit with linkens and lotus orb. However if this option is more enticing then feel free to use it in this item or as a another item. 
 

*CONCLUSION*

A Big Thank You to anyone who read this whole long thing as I put quite a lot of effort into it. I hope you liked my idea for a Open Angel Arena Item. Please let me know what you think of it as I am afraid it migth be a bit too complicated for Baumi's tastes and I might need to refine it. Does anyone have any ideas on how to improve this item?

Also let me know what you thought about the formatting of this issue, I tried to make something easy/pleasant to read/view, but I am afraid that my lengthy typing, bad grammar and overuse of /'s and ()'s clutters the page. 

A big thank you once again.

-prodigiousking (I found the 7.7 morphling bug that existed for 3 hours, thats my call to fame and I am never letting it go haha)

**Comment by prodigiousking** [comment]
Really hoping this makes its way into the game

**Comment by Haganeko** [comment]
We had a lotus sphere design before, It was essentially this. We scrapped it when we noticed, from our experience with Shiva's Cuirass, that these sort of "merger" items reduced build variety. Closed.

**Comment by prodigiousking** [comment]
I don't blame you for not doing so but I feel that you did not read my issue I pointed several design choices that made it its own unique item thus acoiding the shivas curiass dilemma
