### ISSUE TITLE
[Boss] Nuckelavee 

### ISSUE THREAD

**Issue by dennisheperol** [AngelArenaAllstars/suggestions#34]
So the Nuckelavee is a creature that comes from the sea during the winter, he doesn't really kill people but he makes them and their recources (crops/lifestock) sick with his poisonous breath which also causes long periods of drought. The Nuckelavee however can't touch clear water (for example from a river)

Phase 1: every attack on the Nuckelavee stacks the negative regen, making you lose health/mana faster and faster untill you cleanse yourself from it in a nearby water source (which is in the boss area).

Phase 2: The Nuckelavee also breaths out poisonous clouds, hitting them stacks up the debuff. Also the debuff now reduces your attack speed and increase your cooldowns (getting rid of the debuff also lowers your cooldowns again)

Phase 3: the Nuckelavee becomes stronger the more poison stacks are on targets in the arena, getting life steal, attack damage and damage reduction.

**Comment by warpdragon** [comment]
Putting aside balanxe for a moment, this hero is one dimensional. He does 1 thing. He snowballs. Not very fun. I assume the clean water dispells every debuff, not just the one from stage 1? If so, then the major counterplay to this hero is to run away. And the punishment for running away is that the boss snowballs even more bc your team is at a disadvantage.
I imagine this boss fight devolving into a perpetual water camping clownfest or being simply not very fun in general. Maybe chose one of the gimmicks and expand it into something with more substance.

**Comment by JSampersand** [comment]
I like the idea of using this character. Not all the boss fights need advanced mechanics.. There could be a few that just hit really hard, require magic absorption, etc.

**Comment by warpdragon** [comment]
Simplicity and one-dimensionality are two different concepts.

Putting that aside for a moment. Take your degen attack for instance. It forces the caster/support heroes to never attack it or else they won't have enough HP/Mana to finish the fight. But why? Why punish them for nothing? You assert that my suggestion is that your boss be more complicated when it's actually the opposite. Your boss is a rare bird that is simultaneously complicated and one-dimensional - you're punished for attacking, you're punished for taking agro (your tank is gonna die - period), you're not given any choice in the matter there's no counterplay. Pools of water aren't a counterplay, just a chore. And when the battle is finally coming to an end and everybody's almost dead the fucker gets increased lifesteal?

**Comment by JSampersand** [comment]
"You assert that my suggestion is that your boss be more complicated" -- Did he even reply to you?

**Comment by warpdragon** [comment]
Wow. I didn't notice the OP and the reply were from two different people. Satisfied?

**Comment by JSampersand** [comment]
I thought he might have deleted it. What I don't like about this boss is it gets lifesteal in the last stage. So, You've come this far, and then all of a sudden you're possibly not doing more damage than it's healing. Also, the poison clouds in stage 2 shouldn't do anything at all after they spawn, since the boss seems to be stationary.

**Comment by l34Um1** [comment]
Phase 1 and 3 interesting, phase 2 isn't. Gonna keep this open.

**Comment by JSampersand** [comment]
With the sea monster sort of theme, you might have where the arena turns into a sea (through a transparent visual effect), and have stage 2 take place in a whirlpool where you're being sucked toward the center and back out, and you have to dodge the clouds while being tugged around by the current.

**Comment by Haganeko** [comment]
Idea for phase 2: give it a Heart of Tarrasque like regeneration - if the players leave it be for too long, it starts regenerating quickly.

**Comment by Haganeko** [comment]
From Town Hall: change poison to fire, combine with #5

**Comment by Haganeko** [comment]
Essentially a DPS race. Closed.
