### ISSUE TITLE
Is it possible to make cores take less space?

### ISSUE THREAD

**Issue by vldgthb** [AngelArenaAllstars/suggestions#341]
Like make cores of the same level stack together like healing flasks.
That would make lategame item-management a bit less messy.

**Comment by Haganeko** [comment]
Unfortunately, it is not. Items which stack can't be used in recipes, lest the recipe eat the entire stack at once.
This is due to how such items are coded. They "eat" other copies of themselves to gain charges.

**Comment by Sythrus** [comment]
could you make a core stash? cores would prioritize going into this stash before the regular one

**Comment by Haganeko** [comment]
That would require extensive overhaul of the interface. We'd rather have a place people can dump cores, which we're working on. I'm closing this issue.
