### ISSUE TITLE
Pick-up-games

### ISSUE THREAD

**Issue by RighteousBacon** [AngelArenaAllstars/suggestions#349]
As an alternative to a matchmaking system, you could have a system for pick-up-games (PUGs). 
What happens is players ready up, then captains gets assigned based on certain criteria, then they draft for players (this is the pick-up phase of the PUG) and play.

Here is an iteration of that system made for competitive tf2:
https://na.pug.champ.gg/
and its sourcecode:
https://github.com/fwdcp/pugchamp-legacy

**Comment by Haganeko** [comment]
We can't really mess with the connecting system. Only with what happens once players are in game.

**Comment by RighteousBacon** [comment]
I don't see why not though. It's how faceit works, and if I'm not mistaken that's how most online tournaments go down in dota 2 as well (in the sense that everything leading up to the game like teambuilding, scheduling, ect. is set up outside of the actual game).

**Comment by Haganeko** [comment]
You meant for tournaments? Our captains mode works well enough for that, but we did use outside tools in the previous one.
