### ISSUE TITLE
[Boss] Larunda

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#35]
Larunda is a Greek mythological character, a nymph. If that doesn't suit anything (Greek mythology played heavily into Catholic theology, if as a curiosity) find other applicable. 

Maybe she'd be fairy-like, or something closer to a classical Nymph. She'd be themed around beauty, and not look monstrous at all. She was murdered by Jupiter for telling his wife about an affair, and he cut her throat out. She then became an underworld demi-god of silence, pretty much. Sometimes called Muta. 

In Stage 1, Larunda takes reduced magical damage but greatly increases the mana regeneration and decreases their spell cooldowns of all heroes. This is stylized as she's talking to the point of overloading everyone's minds. Players with above 80% mana take damage.

In stage 2 Larunda's area is hit by lightening, symbolizing Jupiter's wrath. This is a burn stage, and everyone takes damage until it's over. The boss area would be full of lightening.

In stage 3, Larunda silences and blinds everyone, stopping all magic damage. The silence is dispensable by strong dispels.

**Comment by warpdragon** [comment]
Stage 1 doesnt make sense. Why would she buff enemies?  I understand that its supposed to make it a challenge to keep casting spells ao u stay below 80% mana, i guess its pretty clever.
Stage 2 everyone likes lightning
Stage 3 everyone gets blinded and silenced.... ok. Why? And in what way? Is it 100% of the time? Dispellable by strong spells?

Im afraid there simply arent enough details to make a proper assessment. Plz refine.

**Comment by JSampersand** [comment]
My idea here is sort of an operatic retelling of her story. At that stage, she becomes the demi-god of silence, and thus silences everyone. And, of course, to contrast her previous life as conducting supernatural levels of blabbering.

Not 100% blind, but either of these are countered by items characters will naturally be building.

**Comment by JSampersand** [comment]
Oh, I just remembered I had first intended that the last stage be invisible gargoyles that slam, to reference that Larunda is the mother of house spirits.

**Comment by l34Um1** [comment]
stage 1 is interesting and noted. closed.
