### ISSUE TITLE
[Boss] Old Georgie

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#36]
Old Georgie, from the book and movie Cloud Atlas. If there's a worry about the rights owner, change it up a bit so there's just some inspiration. As I'm inspired by the posting of Nuckelavee with this, the wikipedia page says Old Nick is another name for the Devil. Could use that instead. But Old Georgie is the combined evil thinking of 'old world men'. Hes the spirit of greed, bigotry, distrust, and ignorance.

In the book, he is the Devil who opposes the light spirit Sonmi, who is God and symbolizes freedom and sacrifice. He looks a bit like a leprechaun the height of a man in the movie, but hes kind of a dead old businessman. This character terrifies me. I might have nightmares just thinking about him. The top few images are what he looks like in the movie: http://www.bing.com/images/search?q=Old+Georgie&FORM=HDRSC2... Andy Dandytale from the old Druthers logo also kind of reminds me of him: https://s-media-cache-ak0.pinimg.com/736x/63/32/7e/63327e1f68cc718046427c01c688b788.jpg. My thought there is, strangely spooky with a southern American vibe.

Stage 1: Georgie hovers around the map, tossing away players and moving away from them. He casts a debuff on everyone so they take damage for every tick they're not hitting him, which stacks.

Stage 2: Old Georgie mind controls one of the team members, locking that player at current health and mana, and forcing them to attack teammates. This will switch back and forth every few seconds. If no teammates are present, Georgie will recall all of the attacking player's teammates to the back of the room, and that first attacking player will be mind controlled.

Stage 3: Georgie goes inside of a teammate, giving them a huge stat increase buff, and mind controls them until they're at 10% health. When that happens, Georgie will die.

**Comment by warpdragon** [comment]
Cool concept. What do you see Stage 1 looking like? Is there gonna be anything to indicate what is happening to the players who are taking damage because they aren't attacking? Are they gonna understand what to do to respond? What kind of visual feedback do they get when they: take damage/deal damage?

**Comment by JSampersand** [comment]
I imagine everyone who plays dota checks when they get a new debuff. I'd suggest they simply tooltip that. However, there could be a visual to the debuff cast, like maybe a ghostly white mist engulfs the heroes. There could be a boss audio queue, like a 'try to catch me' sort of thing.

At least my idea of design principle with boss fights, is that maybe you should fail a few times to really learn what's going on. As long as all the tool to learn how to do it are readily available (cues, debuffs with tooltips), there should be no problem failing a first attempt because players weren't paying complete attention. Obfuscating the objective lends itself to the boss rush mentality. Where the other AA mods fail in making bosses 'tank and spank', this one can give a little more depth and let part of the challenge be figuring out the fight.

**Comment by warpdragon** [comment]
@JSampersand not entirely, no. You need to give some other visual indicator not because it makes it easier or less mysterious but because if your game mechanic needs to deceive players and force them to metagame by looking at their Debuffs or else the mechanic doesnt work, then its a bad mechanic. If the mechanic works regardless, then give them a visual particle or else the design seems lazy. An audio queue is also nice.

**Comment by JSampersand** [comment]
If a similar mechanic is used elsewhere, it could be like the bloodseeker ult where the effect is different when charcters walk. Of course, that doesn't seem to help people intuitively understand what Bloodseeker is doing to them.

**Comment by warpdragon** [comment]
@JSampersand yeah i love it when they run while ruptured. Rupture is a very good example of what I mean. Bloodseeker has a somewhat obvious spell casting animation (and he has to be near the target and also facing the target). There's an extremely loud sound effect, the effected player squirts blood, and then trails blood when they move. It doesn't give the effected player everything they need to solve the puzzle, but it ensures that players are aware that "something" is indeed happening that they need to solve.

**Comment by JSampersand** [comment]
I didn't understand at first that you were asking if there'd be no visual or audio feedback at all. That wasn't my implication with the initial suggestion or my followup post.
