### ISSUE TITLE
[BOSS]Tower of Nereza

### ISSUE THREAD

**Issue by whoisswhoo** [AngelArenaAllstars/suggestions#38]
Tower of Neraza
Tier: High, mechanically can be soloed but nah.

Inspiration: Ancient tower from d3

Primary Damage Source: Minions, Debuff
Primary Defense Type: None
Attack Type:AoE, summons
Attack Animation(2nd phase only): TBD

Lore:
-Tower: Situated in a distanced island , the tower itself was once a gathering point for the island's cult which worshipped a Goddess named Nereza. The tower was used as a place where high priests would make human sacrifices as an offering to Nereza so that in return she would protect the island from evil beings that roams the realm. Underneath the tower were series of flooded dungeons that were meant to kept the offered humans, now with only remains of the misfortunes and the foul creatures that are attracted to the land.
-Nereza: Nereza is a nephalem, a half demon half angel born in times of chaos and corrupted in times of chaos. After being banished for her crimes of turning men to misshapen creatures that attack their own kind, the heavily injured Nereza proceeded to reside in a small island where she took the form of a human and plans her recovery. Using what's left of her strength, Nereza tricked the local into worshipping her as a goddess and bring her souls to feed on. When she was founded out, the cult tried to cull her but only succeeded physically. Nereza demonic soul became a curse to the cult and the whole island with the tower in the middle became an interception for dark energy across the realm to converge.

Environment
-Arena: River surrounding a small high ground with an extra size tower

Phases
Phase 1: Tower phase
Tower is immune to all physical and magical dmg. Underworld minions run in from the water and skeleton raised from the ground attack players. Periodically(10-12s?), the tower releases a small AoE represents the dark energy converged peaking and escaping from the tower. AoE lasts for 2-3s, does small dmg but mainly to grant summons(enemy only) that walks inside with atk dmg and atk speed.  Every 15s, the tower transform a random player into an angry beast that will be taunted by players standing too close to them, transformed player can navigate with beast to run straight into the tower to deal dmg to it. That player will regain his form after a 2 sec stun on impact. At 50% health the tower will release the AoE more often and minion will also receive speed, armor and health buff, making them harder to kill and cant be ignored.
-Tl,dr: survive the AoE and creeps, kill the tower with charge from the beast transform.
 Phase 2
After the tower reaches 0%, it collapses, releasing the ghost of Nereza and also ending the endless stream of summons therefore starting phase 2.Ghost is affected by all dmg(yes it is a ghost). The ghost will now raise a barrier that prevents the player from reaching the water around the island and continues to release the AoE in phase 1 but now deals significantly more dmg and now slows. At every 25% health, the ghost will charge an attack that will kill everything inside the barrier. 1 player(most likely the tank or someone mobile) has to run up to the ghost to channel at a spot(for 1s), gaining a debuff that deals dmg over time from absorbing the dark magic to weaken the barrier so that the team can seek shelter in the water. The water will be crowded with the many underworld minions trapped outside the barrier at the start of the phase. At the 50% then 25%, Nereza will summon 1 then 2 cult fanatics that do knockbacks to prevent you from breaking the barrier. 
-The fight ends when the ghost reaches 0 hp and the physical body of Nereza appears where the tower used to be.

**Comment by JSampersand** [comment]
Nereza is a character from Diablo III. Does she have a presence in any other mythology?

**Comment by l34Um1** [comment]
I like the idea of a tower being a boss. Rest is uninteresting. Closed but I noted down the general thought for further exploration.
