### ISSUE TITLE
[Boss] Galgaliel

### ISSUE THREAD

**Issue by Shusama** [AngelArenaAllstars/suggestions#39]
Galgaliel is an immobile boss with 3 phases he goes through.

**Gameplay**
In phase 1: He creates a ball which bounces at random in the arena, with an indicator showing where it'll bounce next. It deals heavy damage (maybe stun for a short duration), but is easy to evade if the players are paying attention. After some time, the ball returns to the boss, healing it for some of the damage caused, then goes out again. He sends out more and more balls after  (for example every 5 seconds comes a new one and they stay out for 15 seconds bouncing 5 times)

In phase 2, the boss produces many smaller energy balls, which orbit fixed points across the arena, they cause damage on touch (less than the big bounce ball but they should still hurt alot). Since people are fine as long as they are not standing in the orbit, he has a spell which after a short channel makes all the balls switch their orbit at random resulting in making them fly across the entire room for a second.

In phase 3, the energy ball from phase 1 returns (ball could be bigger/faster/have more spawns) So basicly it combines the 2 phases which forces the people to leave the save spaces between the orbits constantly.

Just an example how phase 3 could work;
Orange circles: The points where the phase 1 ball is going to hit
Black points: the damaging balls from phase 2
Circles under the Black points: the orbits the Points are using
![unbenannt](https://cloud.githubusercontent.com/assets/25332142/22267369/c1853a26-e283-11e6-81fd-1b9189cab552.jpg)

**Comment by warpdragon** [comment]
Image: http://www.universetoday.com/wp-content/uploads/2015/02/vega_collision-e1432667172389.jpg
Image: http://lapressegalactique.com/wp-content/uploads/2016/09/sercrea-compressor-compressor.jpg

# LORE

The universe is a frigid, desolate place. The black expanse, my desolation, is but a stagnant sea of emptiness. Stars beaming data patterns over countless aeons, my brethren, driving the gravitational matrix of reality.
Reeling in the transition from void space into this vivid and tumultuous world, I retain but a fragment of my former power. I am summoned here by quite a serendipitous discovery: life. What a novel thing! And so, I have embarked on this inter-dimensional foray with no hope for return. According to my calculations the last of my energy should suffice to either communicate with these beings or consume them.
A triviality.

Custom hero dialog with:
- Enigma
- Ancient Apparition
- Phoenix
- Io
- Darkseer

**Comment by JSampersand** [comment]
Galgaliel isn't in any mythology. But the name is taken from a combination of words in the book of Ezekiel to represent the omni-directional chariot (making it the opposite of an 'immobile boss') which follows four angels. 

warpdragon, no offense, but your lore writeup seems like a jumble of fantasy technical words and abstract thoughts and doesn't explain anything about the boss. It seems like a collection of cool things Enigma might say.

**Comment by l34Um1** [comment]
I like it.

**Comment by Haganeko** [comment]
Sounds like it will completely clog up the arena with stuff and become a dps race. Closed.
