### ISSUE TITLE
Buddy Io boss idea 

### ISSUE THREAD

**Issue by Sixtrings** [AngelArenaAllstars/suggestions#4]
Buddy Io boss idea: Two Ios spawn in the center of the arena, with some kind of timer at the bottom. Phase 1: They stick close together and tethered, both having rot and voodoo restoration. They rotate around the clock, one of them only auto attacks, and can only take damage from physical, the other only uses spells (haven't decided which ones), and can only take magical or pure damage. (of course one of the rot might be needed to be physical).
Phase 2 begins when one of the io is brought below 50% (or some threshold). If it's the one that takes physical damage, then it starts charging around the room while the magic damage stays in the middle. Any magical damage dealt to the middle io will heal the charging io, so focusing the charging io is still ideal. The physical io would be immune to magic and has magic immunity, with anitmage's spell shield to prevent even the spell piercing stuns. It will charge in the direction where the most physical damage is deal or in a random direction if it doesn't get hit. While charging, it deals damage akin to Spirit breaker's charge, and the goal is for it to charge towards the center and be on top of the glowing clock again
If it is the io that takes magical damage, then I suggest having it cast spells like wave form, burrow strike, blink and maybe time lapse. Mainly spells that disjoint projectiles while throwing out spells of its own. However it escapes in the direction opposite of the direction with the most magic damage, again to herd it into the center
Phase 3: The two ios merge together, and regains hp based on the time on the clock.
Kinda like the opposite of Elder titan's astral projection. (This idea came from Zarnotox) And maybe throws out obvious spells while there's a counter on its head. Once the counter hits zero everything in the arena dies and the boss attempt fails. Same thing if the people take too long during phase 1 or phase 2
The exact spells and interactions may be debated and tweaked

**Comment by Sixtrings** [comment]
A potential for lore is the involvement of Keter and Malhut. The two Io's are gateways to two the kingdoms, unintentional rifts that are meant to be closed by the giant clock spell underneath. As Keter is the kingdom of minds, magical attacks serve to strengthen the gate instead of weakening it, as well as physical attacks to the Malhut gate. By attacking a gate with the other property, the energies from the kingdom beyond rushes out to further destabilize the gate. The second phase of the charging part is more due to the excess energy from the unstable connection  than a conscious effort. The clock spell was meant to implode the gates, closing them and killing the challengers as a side-effect, but the merging of the two gates in the final phase was canceling each other out. The merging of the ios meant that neither gate was going to unleash uncontrollable power, but the slight difference of stability meant that unintended energy was leaking out, still able to kill the challengers, and the clock spell acts as a clamp forcing the two gates together. The challengers then force the spell apart, the gates are closed with the power of the other gate, and the small imbalance of power between the gates manifested in the form of items, creating drops.

**Comment by VoidsKeeper** [comment]
Copying my version of the lore here  :   

We've all heard the story of God creating The World in seven days in desire to forge the oblivious infinite to something finite. But not all know how God did it...not all remember The 10 "architects of creation" -  The 10 "Sefirot". They are said to be the attributes of God, but where did they come from and where did they go? 
Rumors state that once , a young child, in sorrow,   ran away from his village. He later found himself lost in the vast land around. Tired , he fell unconscious near a cave entrance. When he woke up , the moon was already up high. What was strange , was the unnatural feeling the boy got from the cave. Upon entering it he saw two spinning lights , radiating with power : one gave off a presence of safety , while the other - terror. But their graceful movements caught the boys attention , charming him ,making him not want to leave.
As time passed, the second orb , as if alive , moved towards the boy at a steady pace. Upon colliding with the boy it knocked him back out to the beginning of the cave. Now back in his senses , feeling fear and agony , the boy fled as fast as he could , wishing to never return. Little did he know that his time was already ticking to its end...
On the next day , a passing caravan found a corpse of a thin , skeleton-like body of an old man. 
The boy's time...had run out...
This was the rumor of Keter and Malkhut - the divine affinities of The Beginning and The End , that now reside deep underground , awaiting for the moment they'll be taken into play once more...
