### ISSUE TITLE
[Boss] Tiamat: Queen of the Chromatic Dragons

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/suggestions#40]
# Tiamat
### Source/Inspiration
- D&D Universe https://pbs.twimg.com/media/CkNo1GIWgAAJQd7.jpg 
- PoE Pale Council Boss Fight https://www.youtube.com/watch?v=qPx5IpPy9kg
- Human Form http://vignette3.wikia.nocookie.net/legendofthecryptids/images/9/9a/Tiamat_of_Malefic_Tyranny.png/revision/latest?cb=20121021041327
- "She was powerful enough to kick the shit out of both the Dungeon Master and the Venger... giving you a general grasp of how goddamned powerful she is." - https://1d4chan.org/wiki/Tiamat

# Lore
Tiamat, the Queen of the Dragons, spreads pure hatred and suffering beneath the canopy of her wings. Her piercing stare, a beam of pure evil, is capable of vaporizing entire armies. Her talons strike quakes of terror across the land. Solid steel plate armor peels like ribbons against the chrome razors running along her spine. What damned sorcery has beguiled this infernal beast to terrorize our land once more!?
# Arena
Our heroes find themselves atop a glistening summit of ash and stone with the hot wind lapping at their cowls. Below them are the fathomless depths of the unknown. Surrounding them, just beyond the edge of the precipitous climb, are the five incredible heads of Tiamat.
# Boss Combat Info
**Attacking:** All heads are attacking at all times.
**Spellcasting:** Only the currently vulnerable head casts spells.
**Short Ranged Bites (Melee):** If there is a hero in melee range, a dragon will bite with a short ranged attack.
**Long Ranged Bites (Ranged Ground-Target):** If there is no such hero, a dragon will attempt a longer ranged lunging bite attack that can miss.
**Elemental Spells (Various):** Each Dragon head has two elemental spells/attacks, described below.
# Common/Shared Abilities
## Invulnerability
**Description:**
Each head is invulnerable at the start of the encounter. One at a time a head is chosen at random from all the heads with highest HP to become invulnerable. The players will attack the vulnerable head until its HP gets below a threshold, say 50%, and it becomes invulnerable again. At this time, another head will become vulnerable. This repeats for the duration of the encounter and all heads are dead.
**Visual Effect:** 
A pale halo encompasses the invulnerable heads. The halo disappearing queues the players to begin their attack.
## Linkens
**Description:**
Many of the Dragon heads' various spells require short channeling times. Having a shared linkens between them with a medium-to-long cooldown increases the difficulty and encourages teamwork. 
**Visual Effect:**
When the Linkens is broken it will play the same animation as when Roshan's Linkens is broken.
# The Five Heads
### Acid rain
Acid falls from the sky, searing the armor from players. Anything hit by this ability takes damage and an armor penalty for several seconds.
**Ability Type:** Physical
**Target Type:** Point/Multiple (displays target on ground)
**Animation:** Acid pours from the sky in random points around the arena.
### Venomous fangs
Its bite applies a slowing poison that does damage over time for a few seconds.
**Ability Type:** Physical
**Target Type:** Unit
**Animation:** A green hue, poison particles, and/or similar.
### Fighting the Poison Head
Weaker characters will have to dodge the falling acid, while stronger characters will have to tank.
### Fireball
After a very short channeling time a tremendous fireball is hurled in a line toward a random hero, piercing all obstacles, doing contact damage, DoT, and slowing attack speed for a few seconds.
**Ability Type:** Magical
**Target Type:** Point/Line (displays directional on ground)
**Projectile Type:** Missile-line
**Animation:** Bright orange fireball leaving a trail of burnt ground in its wake.
### Rapidfire
An array of small damaging fireballs travels across the arena in various wave-patterns that the players will attempt to dodge. Fireballs do not pierce.
**Ability Type:** Magical
**Target Type:** Point
**Projectile Type:** Missile-line/Multiple
**Animation:** Small orange fireballs.
### Fighting the Fire Head
Primary damage dealers should avoid the Fireball at all cost because it lowers their attack speed.
### Lightning Field
A number of bolts of static electricity wander about the arena in random directions doing high damage
**Ability Type:** Summon/Magical
**Animation:** Zeus lightning bolt in the form of a summoned unit.
### All Spark
After targeting a random hero and channeling for a short time, cracks an instant lightning bolt of devastating damage across the arena.
**Ability Type:** Magical
**Target Type:** Point/Line (displays directional on ground)
**Projectile Type:** Instant
**Animation:** Enormous electrical spark going from the dragon to the edge of the arena.
### Fighting the Lightning Head
Do not get hit by the All Spark.
### Depth Charge
After a short channel time, raises its head and slams into the ground, stunning units and causing a wave of water to emanate out from the point of impact, doing more damage the closer units are to the center.
**Ability Type:** Physical
**Target Type:** Point (displays target on ground)
**Projectile Type:** None
**Animation:** Crushed ground at point of impact, water ripples out from center.
### Bubble
Shoots a bubble slowly out toward a random player. The bubble engulfs any unit it contacts, lifting it up into the air, removing it from combat and making it unable to attack or cast spells. Allied players can break the bubble with several melee attacks or fewer ranged attacks.
**Ability Type:** Magical
**Target Type:** Point
**Projectile Type:** Missile
**Animation:** A soap bubble.
### Fighting the Water head.
Save any bubbled allies while avoiding getting stunned by Depth charge.
### Dark Light
After a moderate channeling time shoots a beam of damaging dark light in a sweeping arc 
**Ability Type:** Magical
**Target Type:** Point/Arc
**Projectile Type:** Instant
**Animation:** Like Phoenix Sunray only Black/Purple.
### Storm of Chaos
A fury of Dark Dragon shadow heads thrashes about in a Medium AoE around the Primary Dark head applying fury swipes and doing damage.
**Ability Type:** Physical
**Target  Type:** Melee/AoE
**Animation:** Multiple translucent dragon heads made out of smoke.
### Fighting the Shadow head
Players will have to stay as close as possible to the head to avoid Dark Light, while being sure not to get caught in Storm of Chaos.
# Design considerations
You could make this boss fight last anywhere from a minute-and-a-half to five minutes, depending on some of the data values (attack period and frequency, HP, etc) and also by changing the total number of heads. Based on the length of the encounter and the amount of work to build this hero, I'd say it'd be a high tier boss.

Another option, if you were trying to simplify, would be to simply remake the boss into a single dragon with various types of elemental attacks.

**Comment by LordZenth** [comment]
Love it! Would probably have to be a medium-high tier boss. For drops, an item that cycled through each of the dragon's abilities would be interesting. Or something that emulated her invulnerability Maybe something like:

**Tiamat's Heart:**
Stats:
- 30 Strength
- 10 Intelligence
- 200 Health

Abilities:

**Draconic Endurance** - When your health drops below 25%, become invulnerable and gain a large amount of health regeneration for a short period of time.
Passive
Duration: 3 Seconds
Bonus Health Regen: 8%
Cooldown: 100 Seconds


**Dragontooth Necklace**:
Stats:
- 200% Mana Regen
- 100 Mana
- 3 Armor

Abilities:

Cycles through some of the boss' spells. Every time you cast one, it moves onto the next one. Raw numbers would probably be scaled down to not break the game.
-**Acid Rain**
-**Fireball**
-**All Spark**
-**Depth Charge**
-**Dark Light**
Cooldown: 45 Seconds
Mana Cost: 200

**Comment by warpdragon** [comment]
I would buy those items!

**Comment by l34Um1** [comment]
uninteresting mechanics. closed.
