### ISSUE TITLE
Make Aghanims edible

### ISSUE THREAD

**Issue by Ralayax** [AngelArenaAllstars/suggestions#400]
Also make it give 3 passive Tier 6 cores per minute.
Also make it drop randomly on any creep death with a 20% chance.
Also make it generate a river that prevents radiant to get into their fountain.
Also make it merge-able with every other item in the game.
Also make an effect when eaten that gives you randomly +5000 kills or -5000 kills on the kill count.

Also make the icon
[https://i.ytimg.com/vi/3pf1MkZNyjY/hqdefault.jpg](url)

**Comment by Haganeko** [comment]
Uh... Thank you for the joke? Please refrain from doing it again.

**Comment by Ralayax** [comment]
I'm sorry, I thought it would bring a smile to some of you..
Thinking about it, if everybody does that, the repo will be flooded with shit like that.
Sorry, have a nice day folks !
