### ISSUE TITLE
Boss idea: Tiny/SpiritBreaker/Ursa/EarthSpirit mix Needs Lore

### ISSUE THREAD

**Issue by Sixtrings** [AngelArenaAllstars/suggestions#41]
Boss idea: The Boss is like tiny, someone that hits hard but slow, and has a passive like Spirit Breaker. Phase 1: The boss fights champions like bosses do in Reborn, but gains a stack of impatience per second, all stacks of impatience are removed when the boss autoattacks someone. When the stacks of impatience hits 5, the boss charges the lowest hp champion (point charge) and bashes. The boss also has a sweeping attack that knockbacks a significant amount. For each 5% of hp lost, the boss slams down, dealing aoe damage, and stalagmites drop from the sky. When they drop, they deal no damage but stun heroes, and can be destroyed after they fell. When the hero is knocked backed into a stalagmite, it takes extra damage.  If the boss charges and hits a stalagmite, the stalagmite is destroyed. The charge deals bonus damage, increased range and increased speed per stalagmite destroyed.
Phase 2: At about 50% hp, the boss starts tossing stalagmites for damage, and each toss brings down 3 stalagmites too. Auto attacks and aoe swipes start adding stacks of concussion, which each stack increasing the duration of stuns dealt to the hero.
Phase 3: at about 10% hp, all stalagmites require additional hits to be destroyed, the boss gains an ability to consume stalagmites for damage reduction (physical and magical), which stacks (10% per stalagmite).

**Comment by warpdragon** [comment]
First off, let me start by saying I like his idea. I kind of love the Ability Draft feel it has, too. However, I do have a few questions and concerns:
1. What else, if anything, does **Impatience** do besides triggering the charge?
2. Is **Sweeping Attack** the only knockback he has?
3. You didn't mention if his **Charge** causes a small knockback like Spirit Breaker. If so, you should indicate this in the description. What if it actually **Skewered** them through the rocks as well?
4. **Slam** causing falling rocks is a very interesting mechanic. I like it. It creates a mood.
5. Am I correct in assuming that the **Charging** through rocks mechanic behaves very similarly to Earth Spirit's **Rolling Boulder**?
6. **Rock Toss** is very interesting. Does he pick up rocks from the map or are they created by the toss? Also can he toss players?
7. I don't think **Concussion** is interesting at all. There are better ways to increase the difficulty at phase 2.
8. **Consuming** rocks for damage reduction isn't very interesting either. The "Quick, kill all the rocks!" minigame is a time-consuming chore which might be a complete waste of time if he ends up eating rocks faster than you can kill them. It's a very convoluted way of giving him a very simple benefit: increased sustain. Don't get me wrong. I like the idea of him eating rocks, it's bad ass. But I don't like the mechanic it introduces or the way it changes what was a very fun encounter into a boring minigame.

I think your idea is *incredibly* cool. Possibly just make the description a bit more clear and concise. I like phase 2's **Toss** mechanic but phase 3 could be entirely redone.
Then again, these are all just my opinions. i could be wrong.

**Comment by warpdragon** [comment]
# Marblehardt
![image](https://cloud.githubusercontent.com/assets/13878439/22302251/f31bb3d0-e2fb-11e6-98de-d466a745faef.png)

## Lore
Forged in tectonic collisions billions of years ago, our lineage descends from the mighty Titans themselves. Towering above the highest clouds, tumbling down waterfalls deep into the river's abyss - we are the pillars of the Earth. Man's mighty kings carve at our bones erecting altars in honour of their foolish conquests only to fall to dust. We gaze nobly onward as entire scores of civilizations perish before the mighty green hills, scarcely noticed. 
The astral plain trembles with the unfathomable force of a world's impending destruction. The glaucous haze of uncertainty is lifting and a terrifying reality renders itself clear against the morning sky. Not since the great cataclysm of creation has the world born witness to a war amongst Angels. Yet, the world will not die... for we shall not allow it.

**Comment by l34Um1** [comment]
Phase 1 is great. Not so much a fan of the rest but we can figure that out later.

**Comment by JSampersand** [comment]
warpdragon, I'm pretty sure they mostly want Catholic mythology, or else mythology, and not generic fantasy creations. I notice all of your introduced lore ideas so far don't actually touch on lore as it relates to mythology, and several of your lore suggestions to ideas which other people have introduced ignore the mythos as introduced by the character name.

**Comment by l34Um1** [comment]
We are going with a biblical/religious theme. Frankly for boss ideas I don't want you to post any lore. I don't care about that. Give me mechanics and nothing else.

**Comment by JSampersand** [comment]
I've found that lore is good inspiration for thinking of advanced mechanics. Like, the Larunda stage 1 idea. That kind of mechanic would be way at the back of my mind if I didn't have a 'girl who talks to the point of hurting of people'.

**Comment by Sixtrings** [comment]
For Warpdragon
1. Currently that's all that impatience does, playing on the idea that the heroes have to bring the fight to him.
2. There is also knockback from his autos, which will also deal increased damage if it hits a stalactite.
3&5. That's a good point. I was considering the charge to be a point cast so the players can dodge out of the way. The interactions with the stalactites are exactly like the earth spirit's boulder ability. I'm thinking about adding a certain debuff if the boss charges into the arena wall. During the charge I planned for more SB charge than for skewer, but that would be cooler.
4. Sweeeet.
6. Picks up a nearby stalactite, throws it and creates more stalactites. Ideally yes heroes can be thrown too, and stalactites are formed to "cage" the hero.
7. Concussion is to enable the boss to perma-stun a single target. Demanding the team to rotate the tanking characters.
8. When I planned this, it was more of a Consuming Rocks if they are in reach. So ideally there are going to be people who try to rid the area of stalactites during the previous phases, and letting the Boss charge would be more punishing than in the previous phases. (and of course the protection stacks remove over time)
Awesome lore btw

**Comment by Haganeko** [comment]
Only Phase one was good, and we haven't really gone anywhere with it. Closed.
