### ISSUE TITLE
Item suggestion: Caritas

### ISSUE THREAD

**Issue by thegreatgritzy** [AngelArenaAllstars/suggestions#42]
Caritas, the Latin word for charity, is an upgrade from Hand of Midas that can be used to boost your entire team up. The item consists of building a Hand of Midas, like 2 boss items which aren't yet determined (this is intended to be an item that pushes the rest of your team to late game) and an item that doesn't typically suit the buyer of this kind of item (the hyper farming carry) such as an aether lens, on top of recipe (which could be like 10k). This is to force a decision of whether the carry wants to put their boss items to becoming a monster themself or give team mates a big boost.
It has 2 actives, both on the same 100 second cool down as a normal midas. The gold is increased to 300, and the experience is the same, but the experience is given in the AoE (standard aoe). Instead of being divided however, each ally gets the full XP. The second active is where this gets interesting. Cast on an ally, you lose all of your gold and your ally gets 2/5 (40%) of the gold lost this way. 
My suggestion is probably garbage since there is no definitive buildup and I'm not sure whether this is weak or imba.

**Comment by warpdragon** [comment]
It's not garbage. I like the idea of an AoE Midas. And there's lot of possible other ways to design such an item, such as: What if, instead, the primary active caused an AoE burst in XP gained for a short period?

One criticism: The story of King Midas is a story of greed and the item is the same way. I don't think any Midas based item should have an active abilty which causes a player to *lose* money. Still, it could be interesting.

Very unique idea.

**Comment by thegreatgritzy** [comment]
You say that but the Eagle Relic is a thing in Black Star, and that too is built from a Midas. Both have a huge payoff for the lost gold (although the price to use the relic is too lenient for the power it gives), but gives the item holder themself lots of power.
To solve the lore issue, maybe we can look to Cybele (Magna Mater), the "Great Mother" of the ancient Phrygians and the mythical mother of King Midas himself, and could be related to her wishing prosperity amongst her other "children"
*The goddess Cybele transforms her son's power to one of greed to one of prosperity for all of her children*

**Comment by l34Um1** [comment]
I am currently not keen on midas upgrades. AOE Midas is a noted idea anyway. Closed.
