### ISSUE TITLE
[Item] Sickle of Eyre

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#43]
**Sickle of Eyre**

Builds from: Reaver, Ultimate Orb, Ring of Health (5950 Gold)
Stats:
-  35 Strength
-  10 Agility
-  10 Intelligence
-  9 Health Regen

Ability:
**Ifrit Form** - Transform into an Ifrit, silencing yourself in exchange for casting one of your non-ultimate spells each time you attack and gaining massive cooldown reduction. _(Note: For targeted spells the target is always the person being attacked for target enemy unit spells, and yourself for target ally spells. Removes cast point while active, i.e. you won't waste time casting spells while you could be right-clicking.)_
No Target
Cooldown Reduction: 90%
Duration: 3.5 Seconds
Cooldown: 25 Seconds
Mana Cost: 100

Potential Upgrade (might be too boring/just be a way to save an inventory slot):

**Reaper's Blade**
Builds from: Scythe of Vyse, Sickle of Eyre, Eaglesong, Maybe a Boss item? (14800 Gold)

Stats:

- 50 All Stats
- 300% Mana Regen
- 18 Health Regen

Ability:
**Conduit Hex** - Turns a target unit into a chunk of leyline stone for 3.5 seconds. Whenever an ally attacks this stone, they will also cast a random one of their non-ultimate spells and gain a large amount of cooldown reduction. Detonates illusions, destroying them and dealing 50% of their health as magic damage in an area around them.
Target Unit
Duration: 4 Seconds
Cooldown Reduction: 80%
Cooldown Reduction Duration: 1 second
Cooldown: 30 Seconds
Mana Cost: 300
Explosion AoE: 400

Transformed units are stunned, muted, and have their armor and magic resist reduced by 25%.

**Comment by warpdragon** [comment]
Does this put the random spell on cooldown? If not, then it's severely broken. If it DOES put the random spell on cooldown, then what if I didn't want to cast the spell? I'd be much better off buying a different item. I'm trying to imagine a scenario when accidentally casting a spell would be desirable. Neat fucking idea though.
# 
*I was walkin' to the secret shop when suddenly...*

**Comment by LordZenth** [comment]
It doesn't put the random spell on cooldown, as it would be worse than just casting the spell normally if it did. Ideally, you'd buy this on someone like Bristleback, PA, or QoP (blink would teleport you to the unit you're attacking), who want to both right click and cast spells a lot. To balance, maybe just give 90% CDR while in Ifrit form rather than removing cooldowns entirely?

**Comment by l34Um1** [comment]
Conceptually broken, impossible to balance. Closed.

**Comment by LordZenth** [comment]
In retrospect after watching the "Dota 2 but every time you attack you cast a random spell", I'm going to have to agree. This was basically an attempt to make a reverse-sheepstick (hence the upgrade, punny name, and similar duration), but it just ended up being too powerful. Do you have any tips for making items in the future? A lot of my stuff seems to have gotten removed 😅.
