### ISSUE TITLE
[Item] Galaxy Lens

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#44]
**Galaxy Lens**
Builds from: Aether Lens, Soul Booster, 450 gold Recipe (6000 Gold)
Stats:

- 700 Mana
- 425 Health
- 10 Health Regen
- 10% Spell Damage

Abilities:
**Spell Range Bonus**  - 300 Cast Range Bonus
Passive

**Warp** - The next spell you cast has global range.
No Target
Cooldown: 120 Seconds
Mana Cost: 350

_A fallen piece of sky fashioned into a divining instrument. Its immense mass twists space to its user's will_

**Comment by warpdragon** [comment]
Holy fucking shit! Nice bit of Lore too. And the spell is called *Warp!* ^^

**Comment by warpdragon** [comment]
Holy fucking shit! Nice bit of Lore too. And the spell is called Warp! ^^

**Comment by l34Um1** [comment]
Uninteractive. Closed.
