### ISSUE TITLE
Anti Chase Item

### ISSUE THREAD

**Issue by r3kr4p** [AngelArenaAllstars/suggestions#45]
an item that is single target that you cast on an enemy. If then run away, they take damage, if they run towards, they get healed. Would make it risky to use unless you were sure you were stronger than them

**Comment by LordZenth** [comment]
Made a mock-up for you:

**Stave of Thorns**
Builds from: Blademail, Oblivion Staff, Wraith Band (4335 Gold)

Stats:
- 5 Strength
- 5 Agility
- 20 Intelligence
- 30 Attack Damage
- 6 Armor

Abilities:

**Lesser Damage Return** - Reflects 5% of damage taken back to the unit that dealt the damage
Passive


**Bramblepath** - Damages the target as it moves away from you, and heals them as they move toward you.
Target Unit
Damage/Heal: 25% of distance moved _(Note: 5% less than level 1 bloodseeker ult)_
Cooldown: 45 Seconds
Mana Cost: 150

**Comment by r3kr4p** [comment]
I think the stats may make that a little op. May need to tone down the passive a little as well. Thanks for the mock up! That's awesome

**Comment by LordZenth** [comment]
Toned down the stats a bit

**Comment by warpdragon** [comment]
Seems pretty crazy. I like Bramblepath. In practice, though, I think it will be very nearly identical to a certain hero spell except that it can function in reverse, which is crazy weird and cool

**Comment by l34Um1** [comment]
Interesting. Worth discussing. Closed but I noted it down for further discussion.
