### ISSUE TITLE
[Item] Platinum Talon

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#46]
**Platinum Talon** 
Builds from: Iron Talon, Hand of Midas, Sacred Relic (6350)

Stats:
- 40 attack speed
- 5 armor
- 60 damage 

Abilities:

**Platinum Quell** - Increases attack damage against non-hero units, based on whether the equipped hero is ranged or melee.
Passive
Attack Damage Bonus (Melee): 50% GPM
Attack Damage Bonus (Ranged): 25% GPM

**Greed** - gain gold whenever you damage a unit.
Passive
Gold Gained per Damage Dealt: 5%

**Greater Transmutation** - kills a non-hero unit for gold equal to 50% that units health and 3x experience. Cannot be used on Ancient Creeps.
Target Unit
Cast Range: 1000
Cooldown: 90 Seconds

**Comment by l34Um1** [comment]
Promotes hoarding gold, which I don't like. Closed.

**Comment by JSampersand** [comment]
Since it's based on GPM not current savings, you'd think it would promote more intense farming (not sure this is possible in an Angel Arena), not hoarding per se. That said, seems like a snowball for snowball's sake item. The more damage you do to creeps, the more damage you do to creeps, etc, etc.
