### ISSUE TITLE
[Boss] Big Mama Ju Ju

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/suggestions#47]
# Big Mama Ju Ju
### Source/Inspiration
Freaky demon - http://www.cityofheroes.ca/global/includes/images/mt4/game_info/nerva_01.jpg
Voodoo woman - http://img14.deviantart.net/a7f4/i/2011/016/8/a/voodoo_by_roseandthorn-d37dbmz.jpg
The Mighty Rokhan - http://www.zbrushcentral.com/attachment.php?attachmentid=113847

# Lore
The crystal flame holds the truth. Don't you see? I know you've come in search of answers, but you will not find them here. Turmoil blackens the lens of the future at this precise point in time. But I have an artifact here that you may be more interested in. Eh? Oh, it is an ancient demon sigil, of course. It is said to have been created by mad alchemists out of dragon's teeth and angel's eyes - designed to unleash a most powerful demon of wrath. A prize such as this is surely a rare find!
For you? Of course my friends, I will give you a fair price! Simply buy me boat passage to the sho---
*"It is far too late, Rokhan! You will all suffer..."*

# Arena
Rotting skulls and shrunken heads adorns the decrepit walls. Purple haze covers the dank, dead ground. In the center of the room is a candle casting wild shadows in every direction. Suddenly a massive visage of death ascends from the smoke and the candle burns an eerie green flame. Above hovers the ghastly nasty Big Mama Ju Ju!

# Phase 1 - Spirit Form
## Appearance
A very large spectre veiled in translucent purple smoke. Has horrible glowing green eyes, vaguely resembles a human upper body with two arms.

## Attack
Magical projectile attack with unlimited range.
**Attack type:** Magical/Ranged
**Attack speed:** Moderate
**Projectile speed:** Slow

### Insatiable Rage (Passive)
 Due to her intense lust for pain and anguish, she does not immediately re-agro after a target quits attacking her like a normal boss would. Instead, she continues to attack the target for a brief period doing bonus damage.
**Agro re-initialization Delay:** 3s
**Agro re-initialization Priority:** Normal
**Bonus dmg:** 50%
**Visual Effect:** Burns brighter with wrathful delight until, at last, switching agro.

### Megaton Tincture (Active)
Hurls a magic potion onto a random spot on the playing field. The first hero to pick it up is healed for a moderate amount over a short period. A side effect of the potion is that it causes a fairly devastating explosion shortly after ingestion, damaging all nearby allied units (except the hero who ingested it) for a moderate amount. If the potion is not picked up after a long period of time it explodes.
**Explosion Radius:** Small-Medium
**Visual Effect:** A round flask with a mysterious silver liquid trailing purple fumes.

### Pit of Snakes (Passive)
Snakes can be seen around the arena slithering about beneath the haze slithering. If you see a snake you should avoid the area because it will target any nearby heroes and, after a short delay, entangle the nearest hero, rooting them in place, doing light damage.
**Scan radius:** Small
**Visual Effect:** Occasionally backs of snakes protrude atop the haze, slithering, signalling players to stay away. When constricting a player the neck and head of the snake is visibly strangling the hero.

## How it works
Players soon realize that this spirit isn't fucking around. You can't just drop agro instantly. The boss throws **Megaton Tinctures** onto the field of play, tempting heroes to pick them up but at serious risk. Also if a tank hero drops agro to pick up the item they will take bonus damage from her attacks due to **Insatiable Rage**. **Pit of Snakes** adds quite a bit of additional risk to drinking the **Megaton Tincture** as anyone who is rooted near the hero ingesting the item will take damage from the items explosive after effects.

Once the players have reduced the boss to 50% health, Big Mama Ju Ju's living form falls from the sky, extinguishing her spirit form.

# Phase 2 - Living Form
## Appearance
A very attractive, curvy, tall middle-aged voodoo priestess covered in skulls and paint.

## Attack
A long, hollow, wooden staff painted with mystical runes. Handles light as a feather but hits like a freight train.
**Attack type:** Physical/Melee
**Attack speed:** Moderate

### Big Mama Smash (Active)
A targetting circle appears on the ground and, after a short delay, unleashes a powerful overhead smash of her weapon doing high damage to heroes in front of her, slowing them.
**AoE:** Medium/Line
**Visual Effect:** A powerful and focused overhead attack, smashing the ground.

### Twister (Active)
She spins around shooting several corrosive whirlwinds on winding paths in random directions. Targets hit receive light damage, pulling them slightly toward her, and cursing them, completely reversing any healing or regen for a medium period of time.
**Visual Effect:** Small green whirlwinds. Regen reversing debuff looks like grey fog spewing around them.

### Counterattack (Active)
When activated blocks 100% of the effects and damage of the next attack or ability to affect her during a very short window of time. She then immediately dashes to random point adjacent to the target, striking them for high damage and knocking them back. 
Has no real cooldown, instead casts instantly in response to a random player's actions during periodic, undisclosed time windows. Gives the illusion that she is predicting their actions.
**Visual Effect:** When attempting to counter, she very quickly flourishes her staff around her for a split second. If successful, she bolts in a lightning quick flash toward the target. Her next attack triggers a crit animation.

## How it works
Heroes relying on regen should avoid **Twisters**. Heroes will inevitably get hit by **Counterattack**, which they will  attempt to recover from using regen. The relocation from **Counterattack** make this boss very slippery, increasing the reliance on supports for stuns. The slow from **Big Mama Smash** makes **Twisters** harder to dodge.

Once the players have reduced the boss to 1% health, Big Mama Ju Ju falls to the ground with a terrible cry of pain.

# Phase 3 - Out of Body Experience
## Is this the end?
Big Mama Ju Ju disappears while chanting an unknown curse. Suddenly a possessed version of a random enemy or allied hero materializes in the area where she was slain - has the same abilities as the actual hero including ultimates and all abilities have reduced cooldowns. Crowd control effects are only 50% effective against it.  This is her final form. When killed, a cyclone of evil spirits is unleashed and the fight ends.

**Comment by JSampersand** [comment]
I'm sure there's a name of a queen of a fetishist culture or something which could be used instead. This name could be construed as racist.

**Comment by warpdragon** [comment]
You're right. I'll fix it. It should be "Mama".

https://blackamericaweb.com/2014/10/17/big-momma-in-black-families/
http://newsreel.org/video/big-mama
https://en.wikipedia.org/wiki/Big_Mama_Thornton
https://www.youtube.com/watch?v=OijFtJ5iHzg
http://rayman.wikia.com/wiki/Big_Mama
https://www.amazon.com/Voodoo-Mama/dp/B00433E3EY
http://sydhius.deviantart.com/art/Voodoo-Child-Crew-One-Piece-OC-Mama-Sam-390391574

**Comment by l34Um1** [comment]
I don't find this idea very appealing. You obviously put a lot of effort into it but everything is based around a theme that doesn't fit with our general theme. Reduce the theme away from the abilities and it's not interesting. I am gonna leave this open since you put so much effort in and we'll discuss it at the townhall meeting.

**Comment by JSampersand** [comment]
That's interesting. I didn't know there was such a great 'big mama' history. I felt like the name combination with 'ju ju' seemed a bit jibberish-y or 'jive talk-y'. Juju being a force within a spirituality and not a proper name.

**Comment by Haganeko** [comment]
Closed, If you wish, you may repost a version with less fluff.
