### ISSUE TITLE
[Items] Consumable Upgrades

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#49]
**Grovegrass**

Builds From: Tango, Tango, Tango, Tango, Iron Branch (550 gold)

Stats:
- 1 All Attributes
- 1 Health Regen

Ability:
**Instant Forest** - Creates a wall of trees
Target Point
Cast Range: 200
Duration: 20

_(Note: The wall is a 5x2 rectangle of trees)_

**Sprite Bomb**

Builds from: Mango, Faerie Fire, Smoke of Deceit (235 Gold) 

Stats: 
- 2 Attack Damage
- 2 Health Regen

Ability:
**Concealing Fog** - Upon using, creates a smokescreen in an AoE around the user. While in this smokescreen, allies gain invisibility, health and mana regeneration, and movement speed. Attacking, or moving within 200 range of an enemy hero or tower, will break the invisibility.
No Target
Radius: 750
Fade Time: 2 Seconds
Health Regen: +5
Mana Regen: +2.5
Movespeed Bonus: +15% 
Duration: 15 Seconds

**Martyr's Elixir**
_(Note: Doesn't Stack in inventory)_
Builds from: Healing Salve, Healing Salve, Blademail, 80 Gold Recipe  (2500 Gold)

Ability

**Greater Good** - Gain bonus health regeneration and heal all nearby allies for a percentage of all of the damage you take.
No Target
Health Regen: 5%
Damage as Health: 50%
Heal Radius: 650
Duration: 25 Seconds

**Portable Tower**
Builds from: Iron Branch, Iron Branch, Sacred Relic, 1100 Gold Recipe (6000 Gold)

Ability:
**Construct Tower** - After a short channeling time, create a tower at target location. The tower will automatically attack any heroes in its range.
Target Point
Cast Range: 200
Channeling Time: 2.5 Seconds

Tower Stats:
- Health: 2000
- Armor: 30
- Damage: 200-275
- Attack Range: 700
- Base Attack Time: 0.9
- Attack Animation: 0.5 + 0.4 
- Projectile Speed: 750
- Collision Size: 144
- Vision Range: 1900  •  800 (G)
- Bounty: 150‒250 (+ 280)
- Experience: 200

**Comment by JSampersand** [comment]
10 tightly packed towers is 2000 damage a shot. Any reason why people wouldn't want to just make massive walls of these? Might devolve into a tower war.

I like the idea of making consumables from expensive base items, though. This might really add some depth to the late game. Where it's just all beefed up items in other AAs. I'd suggest if consumables are done like this, make them usable from the backpack.

**Comment by l34Um1** [comment]
I don't like consumables. Martyr potion is interesting. Closed.
