### ISSUE TITLE
Boss Mechanics/Abilities Dump

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#50]
1. A fragmented boss fight: Bosses cannot go below 80% health until they're all at 80% health. In stage 2, 40%, and stage 3 10%. At these stages, the boss does something until the other boss character(s) are reduced below this threshold.

2. Minotaur Maze: Players must find an artifact that makes the Minotaur vulnerable, perhaps then transporting them to a burn phase where the boss is DPS'd.

3. A lasso that entangles the whole party, spreading damage between them. Perhaps standing position would nullify the effect.

4. Blockable Charge: Taken from World of Warcraft: One player is charged, all other players must stand in the boss' path to nullify damage. For each player hit on the way, damage taken from the charge's aftershock is reduced by ~20%. Alternatively, they had this stunning the boss and player when a single person stood in the way, and redirected aggro.

5. Infinite Dimensions: Boss is DPS'd in one room, move to another. Players must navigate through different colored rooms to find the boss, in a trippy fashion that's not easy to get lost but could take a few seconds to find the boss while players who've already found it will have to fight it alone.

6. Springs: Boss bounds around his area as if on springs, attempting to land on players. 

7. Stampede: As in Warcraft 3, but more dodgeable. A horde of models runs towards the players, who must weave through them to avoid taking damage. Perhaps this could be preceded by a pushback to the opposite wall, or they come from multiple directions. 

8. Electrified grid: Pattern on the floor, sections become electrified. Players must move out of telegraphed area.

9. Creep Wave Wall: a mass of creeps spawn toward players at the other end of the room, who must cut them down to get past and fight the boss. I think it could be possible that the creeps do no damage, or damage players on contact (although this might not be intuitive without an immolate aura, suicide explosion, or so forth).

10. Death Clock: all but 1 health is removed from players and put into crystals. Players must break the crystals to return their health before the boss does a timed AOE. This could happen to all players at once or one player at a time.

11. Pacman: Players collect tons of pellets on the map to weaken a boss' damage shield while avoiding NPCs that chase them. Or just, generally, a collection game of some sort which helps kill the boss.

12. Jump Rope: A rope is swung around the arena, and players must collect jump powerups to dodge the damage.

13. Imprisoned with Impending Doom: The boss cages a player, who must be broken free before they're hit with a spell or an environmental mechanic. 

14. Caged with Beasts: Players are transported to cages where they must fight 1v1 an enemy suited to their strengths (support/magic dps/ranged dps/ meele dps).

15. Star Field: Players are transported to space, where stars/meteors streak from left to right

16. Reverse polarity room: Players are sucked from one end of the room to the other, and this effect shifts to different ends of the room. Add a few environmental details like dodgeables, walls to drab onto, 'trash mobs', and/or AOEs and this effect becomes fun and scary. Guild Wars Factions did this for one of their endgame bosses, and it was one of the most fun experiences I've had in a video game.

I'll add more in followup posts when I think of them.

**Comment by l34Um1** [comment]
1 Yes, 2 Yes, 3 No, 4 Yes, 5 No, 6 Kinda but different, 7 Yes but different, 8 Yes, 9 Yes but different, 10 Yes, 11 No, 12 No, 13 Yes, 14 No, 15 No, 16 please elaborate

**Comment by JSampersand** [comment]
16: Basically, you're alerted to a polarity shift, at which point all players are sucked to one side of the room. They've got to try and hit obstacles which are inert (like a wall that stops you from falling too far) or else avoid obstacles which are dangerous.

This could be paired or center around a tether, like puck's ult, or various other mechanics. Trying not to slide into something like spikes around the arena might seem a bit unfair, though. I'm thinking it's incorporated into the fight rather than being the thing that kills you in a fight. 

If there were some kind of mechanic involved where you could use the shift to help you (like grab something needed for the fight), that might be optimal.

**Comment by Haganeko** [comment]
Could you make a new issue with the cleaned up/explained ideas among those approved? Thank you!

**Comment by Haganeko** [comment]
1 is sort of in, with the twins
2 doesn't really work with the current arena format
4 is too similar to Charger
6 is sort of in with Slime
8 is sort of in with Havres
7 and 9 are similar. Posted them in #331.
10 doesn't really work with open boss arenas
13 is the same.
Closed.
