### ISSUE TITLE
Boss Idea (Shameless steal from the special event)

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#51]
I was watching the special event video, and I thought we could "snatch" the warlock level.
The boss would continuously summon minions that would be stronger the closer they were to the boss itself.
At first, there is only one type of minion, a balanced melee type which would hit the heroes. These spawn at the arena corners and just aggro players like they're creeps and the boss is an enemy hero hero. Aggro range is small compared to the size of the arena, but if not aggro'd, the minions would walk to the boss.
Then, after the boss has dropped to 70% health, a different minion is added. This one will occasionally spawn in small clumps near the boss's location. It is a ranged, immobile minion. It would take some time while it spawns, before attacking, so the players can lure the boss away and avoid taking buffed damage.
At 40% health, the boss gets some slower, tanky minions which harass heroes who don't move for too long. These would walk towards the nearest hero, attacking for high damage. They'd spawn at random locations and just start going at the heroes.

I thought of including a healing minion, or a buffing critter, but this seems complex enough.

**Comment by l34Um1** [comment]
Yes. Similar ideas have been noted already. Definitely worth exploring.

**Comment by Haganeko** [comment]
Not very creative. Closed.
