### ISSUE TITLE
Item Idea: Force Staff upgrade

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#52]
This would work like regular force staff, except when used on enemies it'll always pull them toward the user.
Cast range/pull distance might be nerfed in relation to regular force staff, or this use might merit a longer cooldown than the use on allies; balance stuff.
This upgrade adds versatility to the force staff, making it a better gank/chase item.

**Comment by l34Um1** [comment]
Already had that idea. Noted. Closed.
