### ISSUE TITLE
[Boss] Eden (High-Level)

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#53]
A bit of a weird boss: Instead of fighting a singular enemy, you're fighting more or less everything in an area.

As you enter the arena, all that's visible is the Tree of Knowledge in the center of the area

**Phase 1:** _Weeding the Garden_
A wave of highly upgraded jungle creeps appears on the edges of the arena and makes its way towards the center, fighting any hero it encounters. These creeps are invincible until being force-fed the fruit of knowledge (periodically provided from a helpful snake resting on the tree of knowledge). After being fed the fruit, the creeps lose their invincibility and may be slain. After the first wave of creeps is defeated, a second spawns, and after that a third. Once the third wave is defeated, the fight moves onto the next stage.

**Phase 2:** _Against the Serpent_
The serpent reveals its gigantic true form and coils around the Tree. It has three different modes of attacking: the first is a simple slam of its head/tail, the second is a beam that charges up after a certain amount of mana is spent in the arena, and the third is the most interesting: the snake will passively give intelligence to everyone in the arena, the amount increasing the closer to the serpent you are and the more spells you cast at it. If your intelligence goes above a certain threshold, the serpent temporarily possesses your hero, forcing it to attack your allies. When the possession ends, the intelligence bonus resets, and the decrease in your total mana pool is dealt to you as damage. When the serpent is killed, all possesion effects ends, all heroes are knocked back to the edges of the arena, and the next phase begins.

**Phase 3:** _Escape_
Your meddling in the garden has attracted the attention of a higher power. You should probably run. To escape, you need to reach the Tree of Knowledge and eat some of its fruit yourself. Standing in your way is a host of seraphim, who will periodically descend and try to prevent you from leaving. Seraphim have medium-low health, high attack damage/speed, and will begin dragging you back to the edges of the arena if more than one is currently attacking you (the more that are attacking you, the faster they pull). After 15-20 seconds, everyone still in the arena is instantly blasted into oblivion (a giant sunstrike that deals 999999 damage or something would be cool). Only one hero needs to escape for the encounter to be cleared, although the others will still have to make their way out if they don't want to die.

**Drops:**
TBD depending on if Baumi likes this or not. 

**Visual Inspirations** _(Not created by me)_:

Seraphim:
![image](https://cloud.githubusercontent.com/assets/25274980/22393616/18d5b08e-e4d8-11e6-886c-7e4969ca026f.png)

**Comment by l34Um1** [comment]
Too complicated. Closed.
