### ISSUE TITLE
[Boss] Some kind of shark? Perhaps tier 3-4

### ISSUE THREAD

**Issue by VoidsKeeper** [AngelArenaAllstars/suggestions#54]
Arena: A semi-big circle with a smaller circle made out of sand-ish textures in the middle. The rest of the floor has the river textures until phase 2. (Maybe place around some trees to make it look more detailed?)

Boss model: Most of the time stays under the map , moving only in the areas that are cover with the river textures (aka , the "Shark from "Jaws"  that swims around with only it's "fin" staying out of the water). Don't really know how the boss should look overall (depends on who's lore will be attached to this boss).

Battle and battle mechanics:

1) Your team starts off in the middle of the sand island ,surrounded by water (The other players walk through the gates over the water). The boss lurks around underwater , it's "fin" showing it's location. It sometimes stops and surfaces (whilst staying in the water) and starts shooting 3-4 small waves (similar to Tidehunter's gush ability) towards the players (preferably, to the closest to the centre/furthest away from it) , at the same time dealing damage in melee range around itself (to damage melee players hitting it). After finishing it's attack it , once again , dives back into the ground.
The water affects the players , if they decide to enter it , making them slower (in order for them to not stupidly run around , chasing the "fin", but wait out on the island).
The wave attacks deal less damage , the furthur it has traveled and have a high movement speed. Also , each wave decreases armor by 2 on hit. The affect lasts for some time (not too much). The affects stack and refresh (kinda like Ursa's additional damage stacks)
On this phase the players must , preferably, wait out until the boss surfaces and then rush it.

2) At around 70%-65% HP (maybe earlier, to make the fight more intense) , the boss enters phase 2.
The arena gets fully covered in water(dunno if the slow should remain).
Apart from the gush attacks from phase 1 it now sometimes produces another attack:
The boss starts swimming much faster and circles towards the centre in a spiral shape (Closes from the sides of the arena to the centre) , occasionaly spawning Kunkka's torrent ability on itself. When reaching the centre , the boss jumps out and then dives down with enough strength to send large circle waves towards the walls of the arena (But the waves don't touch the walls --> the players must run to the walls to not receive damage). This wave deals a lot of damage and applies a debuff of -8 armor (It stacks with the wave attacks)
 If a player gets hit by the torrent , whilst the boss is swimming to the centre , the player gets stunned for long enough to get hit by the "Tsunami wave"(aka big wave from the dive).

3) At the last 20%-10% HP the boss rages and surfaces for the last time , in the centre of the arena. It starts fighting back more furiously(just a slow right click attack that ,maybe pushes the tanking-player back?) , whilst staying in one place. The boss creates a "Tsunami wave" the veeeerryyy slowly makes the safe part of the arena smaller (Starting from the walls and closing in on the centre. You can think of it as of boiling hot water , that the players should not step on. It deals a lot of DoT and lowers armor very fast(or something else) really fast). The players must give their all in order to kill the boss in time , before the wave closes in on them and starts killing them at a fast pace.

Well , I guess that's my idea overall. Would like to hear peoples opinions.

-Voids Keeper

**Comment by warpdragon** [comment]
I like the idea of the water in the arena changing shape and chasing the heroes around, letting the water be the primary source of danger.

Also what if it wasn't just waves and tsunamis? What about water spouts coming up and throwing heroes around. Whirlpools like mini-black holes that swirl people around. maybe a ship(or ghost ship?) comes passing through that attacks the heroes (or helps the heroes).

**Comment by Haganeko** [comment]
You mind reformatting this according to standards? See #37

**Comment by VoidsKeeper** [comment]
@Haganeko, sure.

**Comment by Haganeko** [comment]
This doesn't really work with non-isolated boss fights. Closed.
