### ISSUE TITLE
[Item] Gravity Booster

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#55]
**Gravity Booster**
Builds from: Heart of Tarrasque, Soul Booster, 1300 Gold Recipe (10,000 Gold)

Stats:
- 700 Health
- 450 Mana
- 60 Strength

Abilities:

_Health Regeneration:_ Restores a percentage of max health per second.
Passive
Regen Percent: 3.5%

_Gravity Well:_ Slows enemies moving away from you.
Passive
Slow Percentage: 5%
Slow Radius: 800

_Event Horizon:_ Pulls nearby enemies closer to you.
No Target
Pull Distance per Second: 200
Pull Radius: 1200
Duration: 10 Seconds
Mana Cost: 200 
Cooldown: 60 Seconds

**Comment by warpdragon** [comment]
Gravity Well - A Passive like that might generate a bit of lag. I still think it's fucking terrific!
Event Horizon is just blackhole, right?

**Comment by LordZenth** [comment]
Kinda, it doesn't stun or deal damage though. If you run away from the guy holding the item, you'll eventually leave the Radius

**Comment by VoidsKeeper** [comment]
I too like the "Gravity well", and I don't think it'll turn out as Warp described it (it'll lag only if you hoard to many creeps, but ,if you're hoarding creeps , then that should mean you're strong enough to take them on --> the lag won't take long.)
The problem I'm concerned about is arena battles (might become a nuisance, if everyone has such an item)

**Comment by Haganeko** [comment]
I like Gravity Well. Event Horizon is too similar to Black Hole.
