### ISSUE TITLE
[Boss] Medusa/Phoniex mix Sun boss

### ISSUE THREAD

**Issue by Sixtrings** [AngelArenaAllstars/suggestions#56]
Boss idea: Medusa/Phoniex ult mix sun thing. So the arena has lava around the edges, massive dot if a hero stands on it.
Phase 1: The boss only uses obvious ground targeting spells, but kinda moves around the arena in a circle while he does it.
Phase 2: 75% hp the boss starts be able to use another ability. Basically medusa ult: it's uninterruptible, but knockback and stun and bonus magical damage instead of physical if the heroes are facing this boss. Heavy damage is dealt if people face the boss, no damage is deal if they turn their backs on the boss but the knockback effect still happens.
Phase 3: 50% hp The boss starts throwing "sun grenades", which does the aoe knockback spell but without the knockback part. Boss is still able to use his massive aoe spell.
Jack Grayling - Today at 12:01 PM
Phase 4: 25% hp The boss sometimes goes into rage mode, throwing sun bombs in the four corners in a random order. The players have to remember the order and turn accordingly.

**Comment by warpdragon** [comment]
I see the idea here. It's actually really good. The fact that you can't look at the boss/suns is very interesting. His main spell makes him glow so brightly it hurts the players. The boss could be an angel/demon of light or something.

You refer to "spells" in phase 1. Maybe you could elaborate on what those spells are. Also

**Comment by Sixtrings** [comment]
Spells: Lina stun but without the stun. Sun grenades later on

**Comment by LordZenth** [comment]
Seems pretty cool, although not being able to look at the boss might be extremely frustrating

**Comment by Haganeko** [comment]
Any review on this? Try to format it according to #37
