### ISSUE TITLE
[boss] Mithras/spartan soldier

### ISSUE THREAD

**Issue by yommi1999** [AngelArenaAllstars/suggestions#58]
Edit1: Fixed some typos and added when I think phases trigger.
Basic concept: A boss centered around two ways of fighting. 
       1: Without defense but high damage output. You can hardly dodge him but  he is vulnerable as well.
       2: He lashes out with attacks that are heavily telegraphed but he also blocks most of your attacks.

Now the long explanation. Below are all abilities summarized.

**Phase one** (100%-50%):
 In the arena stands a hoplite with with a shield and spear. Armor or no armor doesn't matter to me. He will keep his shield high which gives him a passive of damage reduction or damage block (whatever makes most sense for game balance). He will lunge his spear towards a target. There is an pretty long cast point before he actually stings towards an area so with mobility the spear should be dodge able.  If he hits a hero with a spear the hero will be stunned but not damaged. Now that the hero is stunned every 3 seconds a "bleed" build up (dark souls) will fill a bar. The longer someone is attached to the spear the fuller the bar gets. If the bar reaches 100% then Mithras will withdraw the spear and deal 100% damage. If the stunned hero gets moved by force staff or other force movement or OD casts astral imprisonment then he will take the damage as much as the bar was filled. A single target strong heal (weird way of saying it I know) will block the bleed build up for once and a gradual heal will either slow down or decrease the bleed build up. Which healing spells do what is elaborated below.
If during phase one one of the heroes attacks Mithras with an range attack that strikes from above (like light strike array) then he will block the spell or attack completely and continue fighting with his shield rised. Now he doesn't block your attacks anymore but he has a new attack. He will now sweep an area in front of him with his spear. This attack deals less damage if more people stand in it (like powershot). These sweeping attacks deals high damage if you stand in it alone but if you work together then the damage is bearable.

**Phase two (50% 5%)**
You have dealt enough damage to mithras for him to enter a phase. He will call for his warriors to [shield him in](https://lh6.googleusercontent.com/-32KfJ5Lgo4Y/UBFlQyG1WCI/AAAAAAAAACA/k44sSGuOuyM/s560/Hoplite%2520turtle%2520formation.png). Now he gains high armor making physical damage really bad in this fase. Magical damage and pure damage can still reasonable damage him. During this fase his old stabbing spear ability returns only now you don't know when he does it. Also he gains a new passive which allows him to find out who deals the most damage. After some time (I was thinking 30 seconds) mithras will yell: "And now I know my thorn" and mark the hero who dealt the most damage to him allowing him to not only stab once with his spear but twice. Once normally and the second one for the marked hero. If a hero gets punctured with the spear then mithras can still, contrary to phase one stab with other spears, stab again. So in this phase it's vital to keep everyone out of spears as he can permastun an entire team if they are too slow or not fast enough.

**phase three (5%-0%)**
You break the shields which drives Mithras into a rage. He drops his spear and shield and pulls out his sword. He loses the marked hero passive, the stabby spear ability and damage block from his shield.
He now gets high movement speed and also gains a new ability which is basically a imba version of omnislash. He can now with a coo ldown of like 1-5 seconds run at someone to strike them, dealing high damage. When in the first two rounds you had to work as a team you now only want your strongest hero to fight him alone as Mithras can easily cut through your team as he will never "ommnislash" the hero he is attacking. Putting the heroes in the back line at risk. He also gains a passive called "drink their blood"(feel free to change) which upgrades his "omnislash" ability every time he kills someone. So in this phase if he gets a kill on your support then he grows stronger which then allows him to kill another one and another one until he grows out of control and kills you all.

**ALL ABILITIES PER PHASE**

**phase one**
"stabby spear": Mithras will stab at someone. If he hits a hero that hero is stunned. [Every 3 seconds a meter is filled with bleed build up](http://vignette2.wikia.nocookie.net/darksouls/images/f/f3/Blood_loss02.jpg/revision/latest?cb=20130225080119). If the meter is full then Mithras will pull out his spear dealing 100 percent damage. If you are force moved or cast away from this world then you are dealt damage in how much percent of the meter is filled up. A strong heal (purification) will block the next built up and a weak heal(witch doctor) will slowly decrease the bleed built up(but never reverse it).

"Shield of Mithras": Mithras will block or reduce massive amounts of damage(game design note: Never more then 80% otherwise it would be boring). If Mithras gets attacked by a ranged attack coming from above then he will block that and change "stabby spear" to "sweeping spear".

"sweeping spear": Mithras will now in an arc of 180 degrees sweep everything in front of him. Dealing massive damage. Damage is reduced if it hits multiple targets.

**phase two**
"testudo": Mithras calls forth other warriors and they make a testudo. The testudo gives high armor making physical damage ineffective.

"stabby spear" Mithras will stab at someone. If he hits a hero that hero is stunned. [Every 3 seconds a meter is filled with bleed build up](http://vignette2.wikia.nocookie.net/darksouls/images/f/f3/Blood_loss02.jpg/revision/latest?cb=20130225080119). If the meter is full then Mithras will pull out his spear dealing 100 percent damage. If you are force moved or cast away from this world then you are dealt damage in how much percent of the meter is filled up. A strong heal (purification) will block the next built up and a weak heal(witch doctor) will slowly decrease the bleed built up(but never reverse it).

"stand in my place": After a "stabby spear" has hit someone Mithras can now continue stabbing with his spear whilst the first spear doesn't get pulled by but is kept in place by one of Mithras warriors.

"Now I know my thorn": Mithras will find out after some time who dealt the most damage to him (30 seconds). Now will he throw out a spear for "stabby spear" and also another one independently for the marked hero. "stand in my place" fully applies to both spears. Spears who are stabbed with at marked targets have their own cool down.

**phase three**
"godlike fury": Every few seconds (1-5) Mithras will run/teleport to someone and strike him dealing massive damage. "Godlike fury" is never cast on someone who Mithras is already attacking.

"Drink their blood": After Mithras killed someone his "Godlike fury" becomes more effective. Decreasing cooldown and/or increasing damage.

Would love to hear feedback.

Lore will be added later on. No time now.

**Comment by warpdragon** [comment]
Phase 1, high defense, stabby stabby. This is really cool. Would be interesting to forcestaff people out of the spear. This is my favorite phase.
Phase 2, turtle formation. Really cool. Not sure whether you meant to say "perma-stun the whole team" because perma-stunning a whole team is simply a broken mechanic.
Phase 3, love it except "drink their blood" being designed specifically to "teamwipe" seems a bit odd.

**Comment by yommi1999** [comment]
Phase two: permastunning should only happen if you are really slow and you
take long to kill him.

Phase three: this fase should be very short.  So while he can kill you fast
he loses his armour and only deals serious damage via an attack that can be
nullified by boring king bar, forced movement and disjointing. So his last
fase is high Risk high reward while his second phase you should play safe.
In the first phase you can choose between the two.



Op 30 jan. 2017 19:57 schreef "warpdragon" <notifications@github.com>:

**Comment by yommi1999** [comment]
I chose Mithras because when I was reading paradise lost I found out that lots of demons were middle eastern god's converted into the Christian pantheon. So I thought that mithras would fit in that theme and by extent also in the biblical theme.

**Comment by yommi1999** [comment]
I am thinking about completely changing his third phase. Replace the sword like combat with the sweeping spear. Deleting the godlike fury ability as it makes teamwiping probably too easy.

**Comment by Haganeko** [comment]
Pretty interesting, if a bit overly convoluted. Try to look at some of the approved ideas in the main repo, so as to make the description cleaner and more mechanical.

**Comment by yommi1999** [comment]
Oh yeah I will delete this one and post a clean one with only describing
the spear and shield mechanics.

**Comment by Haganeko** [comment]
Looking forward to the clean post.

**Comment by yommi1999** [comment]
Oh shit I should actually do that. Thanks for reminding

Op 9 mei 2017 17:33 schreef "Haganeko" <notifications@github.com>:
