### ISSUE TITLE
Dis: Ice Boss Idea

### ISSUE THREAD

**Issue by DrWallaceBreen** [AngelArenaAllstars/suggestions#6]
Dis, as it appears on The Divine Comedy, is the Lord of Hell himself, a partially frozen, tri-headed monstruosity. The flap of his wings brings forth a blizzard, and his three faces are busy chewing for all eternity on the most important betrayers of history. 

As a concept, I can see him as sort of an static boss, since it's partially frozen, that could maybe blink or move very fast but on few occasions.
Positioning would be key against him, and most of his ice abilities would revolve around either slowing down players or even rooting them.

Some ideas for his skills could be:
-**Ice Spikes**: Stalagmites (Or stalactites? I always mess up both) suddendly sprout forth from the ground, dealing heavy damage and pushing players upwards (Like Nyx's stun). They would come out transversally to the way the boss is looking. This would be the boss main source of damage.

-**Freezing Gale**: Very similar to, say, Venomous Gale of Venomancer, but it also pushes players aside. The slow of this ability plus the knockback could make dodging the ice spikes quite tricky.

-**Frozen Eyes**: To tie the flavour of the boss with DotA mechanics, maybe he could be able to summon floating Eyes of Skadi. This eyes would attack nearby targets really fast, although for little damage. However, being under a constant stream of slow and damage can wear down heroes, so focusing them down will become a priority, giving Dis more room to breathe.

**Ice Beam**: If an Eye of Skadi is left alive long enough, it will place itself up in the air, becoming invulnerable, and shoot down a freezing ray. If a player touches the beam, they will become rooted and take heavy damage. Ideally, the Eyes would try to freeze playes where they could be hit by the Ice Spikes.

**Snowblind**: After the Ice Beam, the Eyes could launch themselves against the players, exploding on contact with the ground, dealing medium damage, slowing players and reducing their chance to hit for a few seconds.

**Betrayal**: The boss would receive some strong visual indicator, like say, a red cloud around him. During this period, a big % of the damage dealt to the boss (Say, 65% or something) would be redirected to nearby players, so your team could very easily destroy you. Esentially, imagine Mercurial's passive, but far stronger. After this ends, Dis blinks to another spot, and the fight resumes normally, only that his spikes will now come from a different direction.

**Tie-in concept: Eye of Dis**: While  thinking of this boss, and its whole Eye of Skadi theme, maybe we could have some flavourful upgrade for our good ol' friend, the aforementioned Eye of Skadi. Maybe, to reach this Eye of Dis you would need some boss items only he can drop (Or that he has the highest chance). This Eye could maybe give you one of his abilities as an active (Like Betrayal, if we also include Blade Mail in the formula) or the Ice Spikes, or whatever. Just as additional flavour.

This is of course a very flawed concept in many aspects. There's so much that can be done with ice and frost and the like, as well as the concept of the betrayer, who is forever bound to punish those who follow in his steps. Take this mock-up of a boss as a suggestion.

**Comment by Haganeko** [comment]
Great design! I love this take on an Ice Demon, and also the use of Skadi. May I contribute?
I think his Betrayal aspect could use something like:
Incite Betrayal: Dis's influence incites mistrust and disloyalty among the heroes. All heroes who are within a 300 radius of each other immediately start attacking each other, as if under Winter Wyvern's original ultimate. Mutes all attack slows as long as heroes are attacking their allies.
This would make positioning even more important, and is also something that can be played around, unlike the current ability, which basically amounts to blademail.

**Comment by DrWallaceBreen** [comment]
Well, in my iteration the damage reflection happens close to him, at least that's the idea I tried to convey, so if all meelee heroes run (Remember, he's static or very slow in any case) the ranged one's could still deal damage in the mean time. 
Your idea is not bad either, and I really dig it (I just really like Winter Wyvern...) but I feel that there was a general dislike for big loss of control of the PC among the crew during our discussions, and I felt that just this damage bounce required more reaction rather than prevention. 
Hell, maybe even both concepts could be added as different abilities for the boss.
Anyways, any further comment on the boss is greatly appreciated, not only by me, but the entire team. We are here to brainstorm after all!! :D
