### ISSUE TITLE
[Item] Necronomicon Rework

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#62]
Necronomicon is an item that is supposed to be good for an objective-based playstyle. However, the non hero killing objectives in Angel Arena are completely different from those in the regular game, making Necronomicon more or less useless. Thus, I've reworked it into an item that plays well into the alternate objectives in AA: Boss Killing and Farming

Note: All of the stats granted by the item are the same, and so are the stats of the summoned units. The only thing different are their abilities

**Fighter Abilities:**

_Demonic Aura_- Grants cleave and lifesteal to nearby allies
Cleave Damage Percentage: 25%/40%/55%
Starting Radius: 150
Distance: 550
End Radius: 300
Lifesteal Percentage: 5%/12%/19%

_Forbidden Knowledge_ - Upon its death, the fighter grants bonus experience to nearby allies
Bonus Experience: 180/360/540
Radius: 1000

_Slake Thirst (level three only)_- Being near a unit when it dies will fully heal the fighter and reset its duration.
Radius: 500

**Archer Abilities** 
 
_Debasement_ - The archer reduces its enemy's armor and magic resist with each attack
Debuff Duration: 45 Seconds
Armor Removed: 1/3/5
Magic Resist Removed: 3%/6%/9%

_Imperceptibility_ - While near allied heroes, the archer gains health regen, armor, magic resistance, and becomes immune to detection _(similar to slark's ultimate)_
Health Regen: 40
Bonus Armor: 5
Bonus Magic Resist: 40%
Hero Requirement Radius: 1000

**Comment by Wujekklawy** [comment]
The archer one with invis is broken as hell ;)

**Comment by LordZenth** [comment]
Yeah, it's to prevent it from getting instagibbed by bosses, maybe it should only work on neutrals?

**Comment by Haganeko** [comment]
All the abilities on these things are bonkers. 55% aura cleave, and 2700 bonus XP upon death are very very powerful. So is Slark-style invis.
I think we're not altering basic dota items, but these ideas could work for upgrades. Keep up the good work!
