### ISSUE TITLE
[Item] Soul Core 

### ISSUE THREAD

**Issue by CalmStorm63** [AngelArenaAllstars/suggestions#67]
Soul Core
Builds from: Urn of Shadows, Diffusal Blade 1, Soul Booster, recipe (~1000g?)/boss item.
Cost: 7225g or more
Stats:
•	500 health
•	500 mana
•	10 strength
•	10 intelligence
•	25 agility
•	50% mana regen
Abilities:
•	Rejuvenation Mote(Active: target ground): drop an orb on the ground that basic dispels and heals over time a hero that picks it up. The healing effect is lost if the effected hero takes damage from an enemy hero.
Gains charges every time an enemy hero dies within 1400 units. Only the closest Soul Core to the dying hero gains a charge. Starts with 8 charges
Cast range: 300
Charge gain radius: 1400
Total heal: 600
Heal duration: 8
Cooldown: 7
•	Mana Oppression(Passive): each spell cast burns the mana from enemies around you overtime, and dealing 1 times magical damage per burned mana, stacks independently.
Radius: 600
Total mana burned: 40
Duration: 5
Burned mana as damage: 100% (magical)

**Comment by l34Um1** [comment]
Modified and added. Closed.
