### ISSUE TITLE
General Question on Closed VS Open suggestions 

### ISSUE THREAD

**Issue by LordZenth** [AngelArenaAllstars/suggestions#68]
What is the general criteria for a suggestion being closed? If a suggestion is left open for an extended period of time, has it been rejected? Or are only ideas that aren't up to snuff on their own closed?

**Comment by warpdragon** [comment]
According to a quick Search in #general for the word "github": on 1/23/2017 Baumi went thru and "closed all the boss encounters on github that [he found] to not be worth pursuing." It's as simple as that. I'm gonna assume this will continue as the Github suggestions continue to pile up over time.

**Comment by JSampersand** [comment]
He said he wanted more mechanics, cool mechanics, sky's the limit sort of stuff and let the programmers try to work out in time whether the ideas are possible. He said he wasn't interested in lore right now, just ideas for good fights.

He has a very specific idea of what he wants out of boss fights. You can check out the stuff he said hes liked here on GitHub, but he said he was going to drop his own boss ideas sometime. If he hasn't already.
