### ISSUE TITLE
[Item/Spell Idea] I would like a Spirit Bomb

### ISSUE THREAD

**Issue by JSampersand** [AngelArenaAllstars/suggestions#69]
As in Dragon Ball Z. A very obviously telegraphed spell that calls down a decimating sphere in an area. Maybe it even harms the caster. There was an old DBZ Arena (Angel Arena Spinoff) that had this, and it was so satisfying to get the cast off (when it actually did damage). This'd be a last ditch move, and a nice throwback to that series. Come on, Baumi. You know you want to Spirit Bomb some fools.

**Comment by Haganeko** [comment]
Thanks for the submission. Could you refine your description?
