### ISSUE TITLE
[Boss] Iron Maiden

### ISSUE THREAD

**Issue by Zallas69** [AngelArenaAllstars/suggestions#70]
Arena:
The boss area consists of a grid of spike traps. Your hero takes damage every tick he's on an active spike trap.
Every few seconds the spikes deactivate on one trap and activate on another one.
The spikes move in a certain pattern at each boss Phase.

Special Conditions:
At the start of the fight the boss creates a clone of your hero. Whenever the clone takes damage, your Hero takes the same amount of damage. You have full control over the clone. It should be tested if the clones should be able to deal damage, how much they would deal, or if your hero and your clone each deal 50% damage.

Boss Abilities:
Give the Boss Dark Seers Vacuum, Invokers Force Blast (both with a short channel).
The boss should also be able to cast a debuff which automatically casts Force Staff whenever you move next to a friendly unit (so no cuddling, more dodging).

Boss Phases:
100%-66%: The Spikes activate/deactivate every ~6seconds, and move from the outside and get closer to the inside.
The boss only uses his debuff.

66%-33%: The Spikes activate/deactivate every ~4seconds, also the Spikes additionaly move from the inside to the outside
The boss uses his debuff + vacuum.

33%-0%: The Spikes activate/deactivate every ~2seconds, there is no more pattern but the Spikes activate randomly in the whole Arena.
The Boss uses all 3 of his abilities.

**Comment by VoidsKeeper** [comment]
I like this idea: you're utilizing the boss arena's space and the fight doesn't seem to complicated - just hit the boss and watch the spikes (people will get the hand of it fast). Although , for this to work,  we'll have to make the spike rows have a smaller width (in order to allow heroes to escape).

**Comment by Zallas69** [comment]
There are many ways to create patterns.
It could also be completely random all the time (just code it the way that at least ~3 spaces next to a spike are always deactivated).
Or maybe include 2 small walkways without spikes.
There are a lot of possibilities.
Glad someone likes the idea.

**Comment by Haganeko** [comment]
Seems interesting, if a bit similar to Havres.

**Comment by Haganeko** [comment]
This doesn't really work with non-isolated boss arenas. Closed.
