### ISSUE TITLE
The Traveler

### ISSUE THREAD

**Issue by CapsE** [AngelArenaAllstars/suggestions#71]
A boss idea that I posted as a youtube comment a while back. I think it would fit the criteria quite nicely.

In the first phase the boss will apply a strong heal over time effect on itself that the players should dispel to make the fight easier. 
In the second phase the boss will turn into a raven (something that is able to fly) and leave the "boss pit" while also having the heal over time applied. The players need to catch the boss as soon as possible (by dealing a bit of damage) so it doesn't heal back to full hp.
In the third phase the boss returns to it's pit and turns into a bear hibernating and again regenerating hp. Your team needs to wake him up as fast as possible. Once he is awake he enrages and deals a lot more damage than before. If you managed to deal enough damage and deny enough healing in the first two phases you will still be able to defeat him though.

**Why is this boss great?** 
The first phase gives the supports something to do. Purging the heal effect could be done with just regular purge effects but there might not be enough so maybe every single target spell can remove the effect (a bit like the linkens effect of Roshan). This job is something you don't need a carry for.

The second phase is very dangerous. Not because of the boss itself but because of the enemy team. It will require you to split up or at least run around the map where the enemies could easily pick you off. Also there is a lot of strategies you can go for. One guy stays behind to wake the bear as soon as possible... but that guy has to be tanky. Or maybe two guys stay behind. But can you catch the raven with just three heroes? And what if the enemy team shows up on the map... or in the pit?

The third phase is pretty straight forward. You should feel right away like you are fighting a fight that you will loose if it lasts to long but you just need to deal this bit of extra damage and it will be really rewarding to get it done.

The mechanics of this boss might not be clear right away but once the phases happen it will be clear and the players will be like "Ohhh that's how it's done". I think this learning experience could be very nice in AAA. It is also possible to pick a team that looks just like a regular team but is actually amazing at killing this specific boss. For example: Shadow Shaman / Disruptor to keep the raven in place, Ursa to tank the bear for a bit once it awoke and maybe a PA to spam her dagger. (There is better teams for sure)

**Comment by Haganeko** [comment]
Thanks for the submission, and sorry for the wait. 
The boss leaving the arena would be hard to use - it would give away players trying to do it quietly. Try to style this like the template in #37 .
