### ISSUE TITLE
[Boss]

### ISSUE THREAD

**Issue by Risheridan** [AngelArenaAllstars/suggestions#72]
As the fight starts everything starts burning, apart from area around the boss. This area gets smaller with each stage of the boss. At the very last stage boss will force you to leave the safe area with sweep attacks, so you will have to take a bit of damage from the fire. This will become a problem if you cannot finish the boss fast enough.

**Comment by Haganeko** [comment]
So, the boss has a shrinking arena around it, outside of which the players take DoT. Phase 2/3 would introduce sweep attacks which push the players back. Seems interesting.

**Comment by Haganeko** [comment]
Any updates on this idea?
