### ISSUE TITLE
Boss idea

### ISSUE THREAD

**Issue by Gilus** [AngelArenaAllstars/suggestions#73]
how about a boss that Starts with an empty mana pool, shown below his health bar. As you deal damage to him, his manabar will fill up. When the bar is full, which could be at like 33% Hp, the boss enters a second stage, and he becomes way more powerful, he gains a strong attack slow and regen or something. The boss is countered by diffusal, which makes it so that the second stage triggers later, so you need to fight less

**Comment by JTuppatsch** [comment]
I would think, of a skill activation if you inflict enough dmg, so a full manabar may trigger a specific skill (dmg, cast range or type of skill maybe depend on the overall amount of dmg the Boss has taken)

**Comment by Gilus** [comment]
Yeah, something in that genre

**Comment by Haganeko** [comment]
This seems like a basic phase design, except it can be countered by mana burn/break. Could you elaborate on what you see this boss doing, besides that? Some way it could be interesting while its mana is charging up, for example.

**Comment by Gilus** [comment]
Maybe as his mana reached different levels, like 33%, he Starts putting down nether wards, at 66% maybe tombstones or something, and at 100% he van maybe Spawns axes that call you, but don't rly deal much dmg, just district you

**Comment by Gilus** [comment]
*distract
