### ISSUE TITLE
[Boss] Vlad of the Deep Woods

### ISSUE THREAD

**Issue by JTuppatsch** [AngelArenaAllstars/suggestions#74]
Boss is located in a forest type Arena.

The Arena is darker then the surrounding terrain
spread in the Arena are 6 - 7 Trees (building type) 

[Boss] - lower dmg and atk-speed than average boss
[Trees] - 1% current boss hp (updated by 1. skill)
destroyed trees spawn [Aoe of light]
Boss inside Aoe -> Boss slowed/takes more dmg

# Skills
## 1. Regrow:
**[Channel/Boss] - trees respawn and get healed**
casted when trees are missing
_light spots close; not destroyed trees, heal the boss or provide healing stacks (similar to living armor),_

## 2. Natures Command:
**[Channel/Boss] - Aoe on the trees (dmg/root)**
_will only be casted when players near trees (attacking or passing by)_

## 3. Citizen of the Forrest/Call of the Vampire:
**[Summon/Tree] - trees spawn orb (%hp drain)**
upon hit, orb sticks to player, drains hp -> healing boss if not killed in time
_orb gets slowed in light_
_targeted in a direction of a player (its not homing, upon spawning wont change direction)_

## 4. I have no idea how to call it:
**[Passive/Tree] - builds up over time (no benefit)**
reduced by inflicting dmg,
at 25 (stacks) provides 1 stack to boss -> refreshes to 0
**[Passive/Boss] - 1 stack lasts 30 sec (increase atk-speed/move-speed/dmg)**
_reduced by inflicting dmg_

**Comment by Haganeko** [comment]
Try to make the description more mechanical, with less lore. Increases the chance of your idea being looked at. It looks really cool, though.

**Comment by JTuppatsch** [comment]
reworked it a bit, hoping it seems more mechanical now

**Comment by VoidsKeeper** [comment]
This might be a bit complicated for people who blindly challenge the boss(what to do with the 3rd ability ,etc). Otherwise , I like this boss , especially the 4 ability

**Comment by Haganeko** [comment]
Any updates on this idea? It has potential.
