### ISSUE TITLE
Hero idea: Forgotten Samurai

### ISSUE THREAD

**Issue by Joeks421** [AngelArenaAllstars/suggestions#75]
*Ember Spirit base model
*Melee, Agility.
*1st Ability: (Dash for Honor) Dashes forward and damages all units in its way. (invincible for duration)
*2nd Ability: (Extreme Training) Get X permanent Agility for every boss/hero kill.
*3rd Ability: (Keen Eye) Lets you ignore a percentage of evasion + If enemy doesn't have evasion you get a crit chance.
*4th Ability (Ult): (Last Stand) Sacrifices percentage of max HP to become invincible for a duration. If you have less HP than the Ult takes you die after Ult ends. (can get health back through life steal only)

**Comment by Haganeko** [comment]
I don't think we're doing heroes yet. Keep those for later.
