### ISSUE TITLE
[Boss] DieNoctis

### ISSUE THREAD

**Issue by sellionrb** [AngelArenaAllstars/suggestions#76]
First thing, sorry about the english. Im from brazil ^^
I had an ideia about a boss that is unfluencied by the time (day, night), thats why the name (daynight in latin). The look to him i have in mind will be linked (the model is from a game called ragnarok 2), his concept on that game is completly diferent from what im sugesting. 
        For his abilities would be cool 2 diferents sets of abilities ( like 3 abilites on day time and 3 on night time). First abilitie i thought is about an passive that on daytime he will be more tanky, and his abilites more Aoe based. For his special abilitie for the day, would be cool  pillars of light start falling from the sky and marks appears on the ground where it will fall. At night time he will be more single target burst based and with a passive similar to husark's passive but instead of attack speed he would gain damage. For his special abilitie he would devour a player making him unable to do anything and to take damage while he gains all benefits of the devoured player itens and passives. Would be cool too, when the boss drops to a certain amount of hp% he would mix the 2 forms using all the abilities at the same time. 
        If you guys liked the ideia, you can modify him as much as you want, im just giving a base concept. Thx for the attention ;)

LInk:

https://www.google.com.br/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjCpPXbhP_RAhVBF5AKHdWWDUkQjRwIBw&url=http%3A%2F%2Fwww.neogaf.com%2Fforum%2Fshowthread.php%3Ft%3D505350%26page%3D19&bvm=bv.146094739,d.Y2I&psig=AFQjCNGxdES78J4QbJ-dHw0IcMIN5X15PA&ust=1486593023442127

**Comment by Haganeko** [comment]
Hi there, fellow BR person. Hue.
Your English seems ok, but the formatting could use some clarification. Anyways, day/night phases are really cool, but I don't see how this boss could use them - day and night are 4 mins long each, so the boss fight would either be too long or happen in only one of them.
