### ISSUE TITLE
Boss Idea: Shadow Master (Level 1 - 2 Boss)

### ISSUE THREAD

**Issue by adamball1092** [AngelArenaAllstars/suggestions#78]
Boss with similar model / attack animation to Shadow fiend. 

Main Damage source - Skill Inferno Raze

Inferno Raze uses same cast animation as SFs ultimate with 2-3 second cast time however razes form an AOE ring all around the boss - like a doughnut! (Areas can be identified in red during channeling if needed).

The boss has 3 raze skills that form rings at different distances (same distances at SFs skills: close/middle/far) - high magic damage!

Stage 1 - Razes pattern: close/ middle / far
Stage 2 - Razes pattern: close/ middle / far / middle/ close 
Stage 3 - Razes pattern: close + middle / close + far / middle + far

Gameplay: Players move backwards and forwards to avoid the razes and deal damage to the boss - as players reduce bosses health and become familiar with the pattern the cast time slowly decreases.

Would be great if you could credit my name somewhere if you use this idea thanks!

**Comment by Haganeko** [comment]
Thank you for the idea! I'd like to throw some thoughts at it, if you don't mind.
We're using mostly bosses with phases - can you think of a way to convert the boss so it has those?
Also, mechanical descriptions are appreciated. Don't focus on the bosses model or what the spells look like. What do they do? In this case, damage in small aoes in a ring around the boss.

**Comment by Haganeko** [comment]
Any update on this? #37 has a useful template for clarity. If you do rework this, please make a new issue for it.
