### ISSUE TITLE
Boss Idea Mimic

### ISSUE THREAD

**Issue by ReinoSwanepoel** [AngelArenaAllstars/suggestions#80]
# **Mimic**
Boss is dressed like a jester or a actor nothing fancy with a full [White](https://drive.google.com/file/d/0B-llP0Dy-gKFZWlrUG1NaTRyZUU/view?usp=sharing) mask or [Black](https://drive.google.com/file/d/0B-llP0Dy-gKFR1V0QnJVRUltTjA/view?usp=sharing) mask
## Arena
A Theater/Stage dark gloomy and at the end of the Stage a Boss

## Phase 1 (100%-66% HP)

Boss has a AOE attack that covers the the entire Arena there are 2 designated Safe Zones if hit will do % HP damage and will apply a stun over time effect (Enigma's Stun). Drawing I made of the [Arena](https://drive.google.com/file/d/0B-llP0Dy-gKFYjVaUFp4TFQtUmc/view?usp=sharing) 

## Phase 2 (66%-33% HP)

Boss will cast a spell and select a random hero and the boss and this selected player will disappear for 0.2 seconds like Doppelganger  and reappears but now the boss has turned himself into that hero Visually and will mimic the player he turned into movement ability's (if possible) and the other hero's have to silence the mimic to let him turn back to his normal form(when the hero and the boss reappear both of them have to be seen as enemies or at least both of them should be able to take damage from the other hero's)

 ## Phase 3 (33%-0% HP)

Boss will charge up and cast a Deafening Blast hero's must run back to the Safe Zone  but every time the boss charges up the Deafening Blast and casts it he falls to his feet but every time he casts Deafening Blast it gets +-75% stronger (in short kill him FAST or DIE )

Bey

**Comment by Wujekklawy** [comment]
Why "mimic"? First, he's a jester not a chest and second he is not mimicking anything. Therefore why that name?

**Comment by Wujekklawy** [comment]
Ok, i just not looked on this part :), btw, p3 is the unnoing part ;)

**Comment by Haganeko** [comment]
Thanks for the submission! I have a couple of points to comment on.
I didn't quite understand the third phase - that's a lot of "but"s. Could you clarify it?
Anyways, focus more on mechanics than lore, if at all possible. Lore distracts from the design, and the writing team will probably just tear it all down anyways.
I don't see the point of the second phase. In the first and third, the importance of safe zones is highlighted, but in the second they don't seem to matter. Why the shift in mechanics? Also, what's to stop players from just hitting the boss from the safe zones for the whole battle (aside from the second phase)

**Comment by ReinoSwanepoel** [comment]
Hey

well what i was thinking was phase one will be a run to safety mechanic and what i was thinking is the following 

boss will fight he will then go back to the original point of contact if you have a look at the arena drawing i made he will run back to that location and begin his channeling for the AOE attack and after the aoe is done they can run to the boss again the point is just no matter where the boss is at any givin point if he wants to do the AOE attach he will teleport back to that marked zone and channel his AOE.

well phase 2 was one of the things i struggled with what i wanted is to create a mimic skill that the boss can use to mimic a player character so that there is confusion so your party members will attack you and not the mimic boss, but if there is some changes you can suggest something or i can scrap it and recreate the phase 2.

Phase 3 is best described as the boss is over loading with power and he will remain at his marked location and charge his blast and players need to run up try and kill him see his charge is almost done and run back and i don't want it to be a one hit kill but after the boss has charged and sent out his blast he will kneel down and then get back up after some time 10s +- and the begin to charge his blast again and every time he charges his blast the blast skill will get 75% stronger.

phase 2 is maybe not 100% a good idea but i wanted to do something in the line of misleading or making team mates attack one another

**Comment by Haganeko** [comment]
Ok, I think I get it.
This looks to me like two different bosses - one with a confusion theme (party members attacking each other) and another with a safety area + cyclic mechanic - rolled into one. Have you considered splitting them?

**Comment by ReinoSwanepoel** [comment]
well i can yes let me have a look later today and ill change the mimic (confusion theme) and another boss with the safe zone mechanic

**Comment by Haganeko** [comment]
Any update on this idea? I was looking forward to the reviewed version!

**Comment by Haganeko** [comment]
The confusion boss wasn't the best part of the boss. The best part was the safe zone nuke, which is very similar to one of the abilities we ended up using for Evil Io. Since we're using the Second Day stuff, this is not relevant anymore.
