### ISSUE TITLE
Boss & mechanic idea

### ISSUE THREAD

**Issue by Galax94** [AngelArenaAllstars/suggestions#81]
So, I was thinking for a bit about something I personally enjoyed taking down in one of games I played recently, it was kidna cool boss that if you work a bit more with it could fit in well and could make for interesting fight that relies lot on decision making, actually there are two, but other one is not as specific and is more open to changes and basicly whatever would you wish it to do in the end, its more like base that you can build out of if you find it interesting
I also included a mechanic that I thought might be interesting but it could also be rather annoying, still I think it could be neat and it could be balanced out by counter like I mentioned or basicly anything you can come up with for that specific boss it would be used for

1.) Boss that is made out of 3 units
- The main body, which have highest HP pool, resist and armor, and does most of the damage, it basically "is the boss", you take it down, you take down boss
- The defensive part, which has more armor but is easily hurt by magic
- The resistant part, which has higher resistance against magic, but is easily damaged by physical damage
- Two smaller parts of the boss would be "supportive" parts of the boss, one of them would do some damage and apply debuffs on people, while other part would be giving auras to main boss body that would empower it
- You can of course choose to ignore small parts and rush main body, but small parts make that harder, but, if you take out the smaller parts, boss is enraged and does increased damage, while also having reduced resistances (As in true enrage, throwing everything in attack)
- Smaller parts can either be simply killable, or can be "respawnable" after certain ammount of time, lets say that taking down boss would take ten minutes (Of course overexagerating), so those smaller parts would respawn like 4 minutes after they are taken down, boss looses enrage at that point)

2.) Boss that switches between forms
- With that you can basically play out a lot, it can be simple as switching between defensive and aggressive forms, or you can give it nearly endless ammount of forms, like one where he heals himself with channeling spell that can be broken with hard CC, he can go ethereal and do aoe dmg, he can do single target high burst
- Of course each phase also has its weakness, as in you go for high damage phase, he has nearly no defense, he goes for channeled healing, he doesn't attack, he goes for spellcasting, he can't autoattack, and such, it is really open to many possibilities there

Also, I though there could be something used as sort of mechanic, I am not sure how will you like it, as it is rather annoying mechanic, but it could spice things up
One of the bosses, someone who would be sort of "Temptress" could have unique mechanic that "charms" enemy (Hero or summon), it would be probably hard CC, and it would make player temporarily loose control of his hero and it would start attacking allies for short while (How long is up to debate), also if it would be just autoattacking, or using abilities too, I really dunno, but I think this sort of "charm/confusion" could make an interesting boss, like, boss itself could be rather weak, but it takes an enemy and makes it fight for him, while he controls enemy, he has high resistances, and when you break out of his charm/confusion, he could for example get stunned and loose resistances
How you can break that charm/confusion, with pretty much every item that is capable of breaking hard CC, or your allies can deal certain amount of damage to you, like lets say, they do 10% of your current HP as damage, you snap out of it

**Comment by Haganeko** [comment]
Thank you for the submission, and sorry for the wait. Could you format this like in #37, and maybe focus more on the mechanics? In your case, this last part is pretty much done, but doing this work can help your idea shine through!
