### ISSUE TITLE
[BOSS] Reaper

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#82]
Probably someone submitted similar idea but you never know. Long story short, big dark mist in robes using scythe as a primary weapon. (still name, weapon, looks or some skills can be changed)

**Combat** 
---------------

**Phase 1** (100%~66% hp)

- Boss swings with scythe to direct attack heroes (AoE in front of he, after short incantation).

- Boss have short dash with around 420speed (while dashing is invonureable [what is even proper spelling for that word?]) with he is using to doge spell projectals like sven stun, lion spikes or mirana spear (still wander why it is called "arrow")

**Phase 2** (~66%~18% hp)

- Boss still attacking like in phase 1

- On the start of phase 2 Boss spawning on top of evry hero spining scythe with deal AoE dmg (after short incantation, to give time to get out of range, scythes don't despaire).

- Boss from now can throw his weapon like a boomerang (AoE damage, similar to Phoenix q).
While his weapon is flying he cannot attack (obviously).

- Evry x second of phase 2 he starting invocation (unless he throwed his weapon, in this case he starts when his weapon is back to he). After it evry spawned scythe dash to random hero on arena.(scythes cannot target same enemy as other one or be in range of other ones. Similar to new techies mines, if no target dash to random place ir radius)

- Boss dash is echanted, dash now deal damage to units in his way and always dash to hero with is further than attack radius (if no target is not usable unless like in phase 1), after reaching point when hero was standing on star of dash instantly doing AoE attack ("basic" attack with no incantation).

**Phase 3** (~18%-0% to be able to kill boss in 2 attempts but not longer)

- On start of phase boss dashes to one side of arena. (furtest from heroes)

- Scythes moves to boss creating wall, then slowly moving in straight lane to other side of arena. After x second next scyth wall apire and also start moving.  (this part can be doned in 2 ways, safe area in every wall to pass it through it with taking no damage or arena have something tall like pillars or something to stop scytes. Also scythes should be spawning around 700 units away from boss to create safe zone near him)

- Boss is incanting blast of energy dealing hudge damage on whole arena, can be cancelled by attacking him what force him to back to boosted (more aggressive, shorter time to doge his attack etc.) phase 2, after x seconds he throws an scythe towards opposite side of arena and dashes there. After catching weapon he do phase 3 again.(not counting dashing to one of sides, he doned it already)

**Short description of general idea of phases:**
-----------
**First phase**
 is for warm up, should give information about animation speed of boss and show easy way that he cannot be attacked by ground targeting spells or spells with work with dely like Laguna blade, storm hammer (shortly evry spell that is able to doge). His "dash" (visually i think about something like storm spirit ultimate but made by black myst) should have no cooldown and no cast time but be rather slowly.

**Second phase:**
 for introducing new abilities and proper fight, with boosted dash fighting with him you get punished for attacking him with spells that can't harm him. The Dash + Attack would be over power with no cooldown so it can be doned as separate ability to avoid bot spamming it.

**Third phase:**
 is for changing completely rules of fight. This phase have two parts of it, first one is variation of bullet hell in dota and second part is ultimate test of what players learned fighting him. The bullet hell part should be like softcore hell ;), not impossible to do but not easy to beat with no dmg taken without short practice to avoid irritation. Invocation is to force players to be fast and not getting fight slow down and punish them for doing fight longer than it should be. After successful incantation can be doned in few ways, forcing boss to go on part 2 of phase 3 or repeat again first part by choosing side of arena with is furthest to nearest hero of that side (it seems complicated on paper but it's simple to visualize and looks intuitive), first option can make fight shorter because forcing boss to go further in fight phase no matter what but second one can also make it faster by making pulse deal like 60% health dmg (so no matter what still it should take 2 max 3 attempts before team dies, meaby even 1 if it was not doing well) both have pluses and minuses.

**Visual and arena aspects** 
-----------------

Visuals (and name) depend on dev team but myself i see boss as a black myst (is it called like that?) in robes with hood puted on, as a weapon i see a scythe but in reality evry would work, even counting arcane magic. As a color of particles for casting and attacks animations green should look good.

Depending on a phase 3 arena could have 4 rectangular spots where boss would dash to, borders (just borders to simplify and being more intuitive but terrain different terrain can make arena not look boring) center mirrored.

This is just my ideas and feel free to change it in some points to your vision.

**Comment by VoidsKeeper** [comment]
(Answering you questions : 
1) Invulnerable - it's like vulnerable,  but vise versa
2) It's called an "arrow" , because the heroine wields a longbow as her weapon-of-choice)

To the boss: 
First of all , thank you for the commitment.  This boss reminds me of a certain enemy from a PSP game called "Lord of Arcana" (The monster was called the same,  as I recall).
Now , about the boss battle. Phase 1 sounds a bit too blunt. You could leave it as an ability the boss has , but I don't think it needs to stay for a whole ~34% of the boss's health. 
Phase 2 would act nicely as a way to ambush the new players , but , it also needs a way for people to be able to escape it (otherwise it'd become a massacre).
Phase 3 sounds way too overcomplicated to me (I'd not be able to keep up with all the stuff the boss brings upon me in such a short amount of time , especially ,if it is , as you say , "massive damage").

I get your general idea , but I believe you should make it a bit more "user-friendly". Imagine yourself challenging this boss blindly for the first time ( You'd get pwned and pretty fast)

P.S. please use less flavour in your ideas. We want mechanics (and I do see what mechanics you're introducing) , but it hides the true idea of the boss battle. Try using (if possible) more game related words , as DoT (damage over time) , AoE attack (Area of effect attack) and so on.

**Comment by Wujekklawy** [comment]
Phase 3 is just buffed phase 2 plus moveing wall of projectiles, and this massive damage thing is punishment for not going through maze of projectiles not fas enough, or just simply hiding somewhere. Incanation should be interrupted while take damage, similar to toombstones reincarnation from events

**Comment by Haganeko** [comment]
Any update on this? #37 presents a nice template to use.

**Comment by Wujekklawy** [comment]
i would need to rewrite evrything so i enchanced it a little

**Comment by Wujekklawy** [comment]
also, depending that bosses fight on small area 3 phase could phase boss to midle of arena and push evryone to sides.

**Comment by Haganeko** [comment]
This is very complicated and, in the end, I don't know whether the fight would be very interesting. It's hard to tell under all the fluff. Closed.
