### ISSUE TITLE
Boss Idea: Icarus the Flamelord (Level 3+)

### ISSUE THREAD

**Issue by adamball1092** [AngelArenaAllstars/suggestions#83]
Boss with similar base model and attack rate of Ember Spirit.

Main Damage Sources - 

Fire Remnants - Standard ES remnants boss will cast on positions of players around the arena based on Stage (Max: 3, 6, 9 remnants respectively). After placing these he will jump to a random Remant after a short animation delay.

Searing Chains/ Flame Guard - Before Jumping to remnants (use ember teleport animation for cast delay) the flamelord will cast a small AOE searring chains to hold heros in place for 4 seconds dealing burn damage over time.

For Each hero effected by Searing chains the flame ford gains 1 stack of Flame guard (50dps/-500 magicdmg) making him more dangerous after jumping.

Stage 1 - 3 remnants Max and searing chains in a 200 AOE (red indicator).

Stage 2 - 6 remnants max and searing chains in a 350 AOE (red indicator).

Stage 3 - 6 remnants max and will repeatedly cast searing chains in a 150 AOE for the full duration of travel between remnants (red indicator). After Jumping Icarus will become a Phoenix Egg with associated slow and Damage (Phoenix ult).

If the egg is killed Icarus (flew to high) and falls to the ground stunned for 5 seconds.

If the egg hatches... 
Easy / Boring (Icarus regains 30% HP)
Or
Hard / Fun (Icarus splits his soul in two producing an identical copy of himself with the same abilities and powers.

Gameplay: Players have to work together moving out of the searing chains AOE or using magic immunity - particularly at stage 3 with the Phoenix egg. Manta Style would also be a hard counter for the dispel and extra illusion hits.

Thanks, please credit my name somewhere if you like my ideas and I'll keep adding more!

**Comment by Haganeko** [comment]
Thanks for the idea!
Please focus on mechanics instead of flavor and lore. Including those reduces the clarity of your idea and makes it harder for it to be appreciated.
Also, please refrain from making heroes into bosses - the heroes will be in the game, so they can't also be bosses.
