### ISSUE TITLE
Right click boss(can't be killed by right click only)

### ISSUE THREAD

**Issue by lollipop01** [AngelArenaAllstars/suggestions#84]
Right click boss has armor and no magic resistance. Right click boss cannot be taken down through just right click. Boss treat like normal heroes will be stun or hex for the full duration by hero's abilities or items. 

Boss abilities: 
1. Enrage(active ability): purge out of stun and be immune to stun or hex from all source. Also gain 30% damage reduction from all sources for a certain duration)

2. Talkative: all silence duration is cut down by half (passive)
 
3. Lifesteal(passive)

Phase 1: 
No extra abilities 

Phase 2 :
1. Active ability blurr: gain evasion for a certain duration. 
2. Fury swipe( last 6 sec instead of 15 sec ) 

Phase 3: boss has no armor. 
1. Berserk(passive): as hp decrease ,attack speed and magic resistance increase. 
2.  Earthshock(auto active ability): **when boss under the break effect or recieve more than 3 debuff( not include aura type), this ability will be used.**  Boss slam on the ground( during this animation boss cannot be interrupted and take 80% less damage from all source) , dealing massive damage in an huge aoe around the boss. Stun heroes that got hit by the attack. Removing all debuff on the boss.

**Comment by LordZenth** [comment]
Isn't this kinda the thing Baumi was trying to avoid?

**Comment by Haganeko** [comment]
I am confused - does the boss auto purge all relevant disables, or is it vulnerable like a regular hero? You seem to contradict yourself. Or do you mean this boss is supposed to be under Break for the whole fight - until it triggers phase 3, upon which time the players are punished for having figured it out? Also, isn't giving the boss 30% damage reduction basically giving it about +40% HP?

**Comment by lollipop01** [comment]
Edited. Baumi is trying to avoid boring right click boss with no strategy involve to kill it, mine is different. My boss idea is that you cant purely rely on right click to kill him. You may need to chain stun, slience,disarmor,hex to lock him down in order to kill him.

Boss has a ability enrage that allows him to purge off disables, something like ursa's enrage with aghs. Break disable passive, so EarthShock is an ability that purge of those annoying debuff.

**Comment by Haganeko** [comment]
Any updates on this idea? If you have some, please make a new issue. This concept has potential, please expand on it!
