### ISSUE TITLE
[Boss] Mind swapping

### ISSUE THREAD

**Issue by SztoDwa** [AngelArenaAllstars/suggestions#85]
Inspired by "The last castle" comic by Valve (the one with Axe in it). 

## Arena
One mage plus 4 soldiers guarding him. 

## Short rundown

Phase 1: Goal is to kill all the soldiers, because the mage is invincible at the time. However, soldiers are simple, identical tanky characters, while mage just sits around and does nothing. 

Phase 2: Once all soldiers die, the mage chooses the strongest hero in the group and swaps control with him. The goal is to kill the chosen hero. Once he gets lowered to 1 HP,  he survives (as in Dazzle's "shallow grave"), player regains control, and the original mage character dies. 

## Rationale

The purpose of phase 1 is to set some power level to the whole fight. That way you can expect that the victim of mind control will pose some challenge to the rest of the team.  

Also, phase 1 can serve as a way to mince up the heroes and make it harder to prepare for phase 2.

## Details of mind swap

The hero that becomes controlled is not out of the fight - he can now control the mage. However, like in the comic, he turns out to be pretty weak - just some simple abilities and basic items. That character should be ignored by the boss until it's the last one in the arena. Also, this character should not be able to truly die under player's control, but go to sleep instead - until the fight is over. 

The fight should be able to end in 2 ways - by defeating the boss or by all party members dying to the boss. In the latter case, the boss insta-kills the controlled hero (or just tp's him back to his base) and resets the arena back to phase 1. As an idea o make this more clear which heroes count as party members,  the arena can get sealed shut the moment phase 2 is about to begin. Everybody closed inside counts. 

While the boss is controlling the hero of his choice, he should get some kind of advantage to be a challenge to a team of 3-4 heroes. That might be either some aura buffs or a bonus ability. 

## Last thoughts

I think that this boss hard-counters a strategy relying on one player leveling up ahead of the rest of the team and being the main boss-killing engine. If at least two heroes are at similar power level, this battle should be very possible to beat. 

Also, the act of mind swap is very straightforward and apparent - one of the heroes struck by the spell suddenly attacks allies; times goes on and he doesn't stop! We should do something about that! 

Also I want to see someone unaware of this boss' mechanic to be as surprised as Axe was in The Last Castle :)

**Comment by Wujekklawy** [comment]
It will be disaster to make AI, you will be need one for every hero. Cool idea but o don't think they will make boss from it, meaby there will be hero with that concept but i bet it would be too much work to make it boss, also when new hero is added boss AI also would be must be updated

**Comment by Haganeko** [comment]
Interesting idea. I just worry about having a caster do the most damage, then drop some items before being insta-killed by teammates. I also wonder about a disputed boss fight - what if there are members of both teams inside?

**Comment by SztoDwa** [comment]
@Haganeko when I used an awkward term "party members" I had it on my mind that it can involve both teams.  Also, if the boss would be to be buffed up to give him an edge, it could scale up with number of people sealed inside at the start of phase 2.

And if it comes to selecting "most powerful hero" - it could be based not only by stats and levels, but also on total worth of items held. However, I see a new problem - the caster guy drops the items, avoids mind swap,  then picks up the items and kills the boss. Well, this needs more thought (if items are dropped before phase 2 move them to a safe cache outside the arena? Or when the boss starts his phase 2, he stuns all the other heroes to walk around and pick up all the items that hero dropped, then starts the fight?). 

@Wujekklawy I can't say that you're wrong. However, if at some point there will add an option to play AAA against bots (which I don't say is even considered by the team) then all needed AIs would have to be implemented either way and this boss would be more plausible.

**Comment by Haganeko** [comment]
Any updates on this idea?
