### ISSUE TITLE
[Hero] Scorch, the Pyromane

### ISSUE THREAD

**Issue by Maxilos33** [AngelArenaAllstars/suggestions#86]
This idea has been already quite a while in my head, so bear with me.
Basically from an optical standpoint, Scorch would use the Timbersaw base model with altered animations to make him a ranged hero.
His main concept bases around overheating of his weapons, while autoattacking you build up heat, the heat can be used then in an offensive manner to further increase your damage potential. He would boast a very low base attack time, however will be a strenght hero and have a really bad strenght gain, so he has a limited autoattack damage output and has to rely on his abilities to dish out the damage. His abilities are as follows:

**[Q] Passive: Heat Vent** 
Pierces Spell immunity: **NO**
Damage type: Magical

-a heat stack is generated upon every autoattack
-passively vents accumulated heat
-vent rate would be around 1 stack every 0.5 sec
-each level grants an increase to max. heat stacks **(30/60/90/120)** (increase is linear, so can be expanded upon)
-for each 10 stacks Scorch's armor is reduced by 1
-for each stack there is an aura around scorch, that damages enemies in a radiance esque fashion
-each stack affects damage (1 stack translates into one damage) and range (1 stack equals around 2,5 units)
-base range would be **(250/300/350/400)**
-if stacks exeed 150% of current stack limit **(45/90/135/180)** scorch is disarmed for 10 seconds, in which he vents all heat and damages himself for twice the amount of heat he had (damage is done as damage overtime, proportional to vented amount per second)

**[W] Active: Heat Propulsion Jet**
Pierces Spell immunity: **NO**
Damage type: Magical

-a dash with minor mana cost that primarly utilizes heat as a resource the player has to manage
-damage is directly affected by heatstacks **(125/150/175/200)** base damage, current heatstacks added directly as damage
-range also increases with heat amount, however it can be shorter just like Magnus' Skewer
-range increases by 2 with each heatstack
-base range is **500**
-damage is only dealt when passing trough an enemy, can pass trough multiple enemies
-cooldown base is 6 seconds, gets reduced by half of the current percentage of heatstacks (example: lv 4 Heat Vent with 120 stacks is 100% of (safe) Heatstacks, so Heat Propulsion Jet cooldown is reduced by 100%/2 so 50%. overheat values also reduce even further, assuming the user accumulated 180 stacks so the cooldown is being reduced by 75%)
-could use the flaming tree hook effect current timber has
-consumes **(5/10/15/20)** Heat and **(20/30/40/50)** Mana

**[E] Passive: Thermophile**

-grants passive health and mana regeneration based on heatstacks 
-**(20%/30%/40%/50%)** of heatstacks into health regeneration (example: 100 Heat equals to 50 Hp regen)
-**(10%/15%/20%/25%)** of heatstacks into Mana regeneration

**[F] Passive: Molten Lead**

Pierces Spell immunity: **YES** (miss chance and damage increase on yourself pierces Spell Immunity, the Magic resistance reduction not)

-increases autoattack damage in exchange for misschance (barrel heats up, gets inaccurate)
-adds **50%** of current heat value as damage to autoattacks
-applies **25%** of current heatstack value as misschance on Scorch
-reduces magic resistance of enemies by **(2%/3%/4%/5%)** for each hit for 10 seconds, reduces maximum of **(10%/20%/30%/40%)**

**[R] Active: Heatslam**
Pierces Spell immunity: **YES**
Damage type: Magical

-after **~0.8s** cast animation releases all heat in a large aoe
-damages for 3 times the current heat value
-uses up all heat and disarms scorch for 5 seconds
-costs **(100/200/300)** Mana
-roots him in place for 2 seconds

**Talents**

25-->Thermophile to 100% HP regen; 50% MP regen / Molten Lead adds 100% of Heat as damage
20-->Invulnerable during dash / Dash sets enemies on fire*
15-->Heat Vent applies 10% blind on enemies / Heat vent stacks go down 30% slower**
10-->+10 Armor / +30 Attack speed

_*deals additional 10% of enemies max. HP in 5 seconds (burns 2% each second)_
_** instead of 0.5s per stack it needs 0.65s per stack_

**General Inspirations and how I envision him being played:**

The main inspiration was drawn from the Incinerator class mech from the game Hawken. Its main role was to outlast its enemies by sheer volume of fire it could put down range due to its mechanic of generating and using up heat, thus being able to completely ignore the limiting factor of overheating that your enemies faced. However it was very slow as a heavy class mech and had one of the smallest C-class mech healthpools, thus required good positioning to be able to utilize its firepower. It also could release all its heat in a ground slam, overheating mechs around it and damaging them.

This particular playstyle, of a glass cannon wreaking havoc on the enemy team with required positioning, awareness and somewhat mechanical skill to utilize a movement ability, to get in and out of danger pretty quick is Scorch's main purpose. The stronger your offense gets the weaker your armor becomes, putting you into a high risk, high reward situation, where one wrong move means that you have crossed the point of no return and have to comitt to the fight, or else you are a free kill for the enemy team. You either will be able to maximize heat gain and damage output by building attackspeed items like Mjollnir for added magical damage synergy or can build around a teamfighter with Shivas' to keep your enemies in place to deal more damage and accumulate heat, also efffectively increasing the effectivenes of Thermophile. Uniquely, the hero doesent scale indefinetively, but will have to either get rid of accumulated heat midst battle, be it with a retreat or with the use of his Ultimate, that is designed around being a finishing move, with incredible damage but dire consequences if you dare to use it whilst your enemies will survive. The regeneration of hp and mana will surely assist you, however your armor is very weak so high HP regen wont make you unkillable, since your healthpool and armor are rather weak.
calculating and taking risks before going balls deep will be the focus of this hero, either you commit fully or will die trying, since you need to be in the heat of battle (Hehe get it?) to be able to dish out damage, favoring aggressive but calculated gameplay, much like huskar but in a much more action packed and agressive manner.

I know that the values may be not perfectly lined up with the more skills system of AA2, however this is just a suggestion, a bare scaffold for (maybe and hopefully) a new hero. most of the scaling is linear anyway so adding more levels wont be a problem.

Constructive critisizm always welcome, feel free to point out grammatical or orthographical mistakes.

Thank you for reading!

**Comment by Haganeko** [comment]
Thank you for the idea! It looks pretty interesting. Alternative resources generally are.
However, we are not currently working on heroes, and won't for a long time. Please keep a copy locally, so you can put it on the table once we do start.
On the other hand, if you believe you could salvage some of the mechanics for an item, or a boss. please post those,
