### ISSUE TITLE
[BOSS] Trickster 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#87]
**Mad Jester** and his tricks. 

Combat
-------

**Phase 1** (100%~40% hp)

- Throws projecktail in straight way, deal damage on hit.

- If attacked from mele range for x damage starts dealing AoE damage. 

- can go invisible (preferable not detected by sentries or dust but invis similar to this from Heroes of the storm, so you can see somehow where he is if you look good, could be made by making his textures/model transparent ), for short time he is getting away from heroes and cannot attack (few seconds) also getting movement speed bonus. After that he go towards random hero and mele attack it, attack from invis have 100% critical chance(should hurt a lot) and brake it. When he is invisible can't be targeted, invis break when damaged by something (#ground targeting spells op, nerf lina). 

- after 4-6 used of first abbility starts moving in straight lane to last hero that got hit by first abbility, if noone got hit target random her, damage evryone in his way, goes straight (like 240movment speed) for around 1200 units, always go full length if not interrupted by wall or stun.

- Create x projecktails that land in random places around arena. After short dely from landing cause fear around them. Feared units move in straight lane away from center of AoE (like reversed Axe taunt).

**Phase** 2 (~40%-0% hp)

On start of phase 2 create 7 (to choose by dev, preferable more than 5) illusions of himself, illusions work like arc warden ones, can use all his abilities, illusions deal around 70% of his damage and take around 20% more damage. Illusions don't disapire (unless main jester was killed).

 General idea of combat.
--------
First phase is basically for players learn moves of Trickster and how to avoid them. Boss is pretty easy to figure out and can be easily beaten on phase 1. The second phase is a chaos, this part is main fight, % of health is so low from 2 reasons,  to beat phase 2 players must know almost everything about boss and second one to be able to kill boss/clones faster.

Visuals and other.
---------

**Abbilities**

 1.  Throws daggers.
 2.  Spins around. 
 3.  Invis similar to one in Heroes of the storm. 
 4.  Walk spinning his arms.

**Hero**
In my vision of boss he is a Jester and his fight style is awkward.  His looks and fighting style are similar to one from dark souls.(i think from DS)His weak spot is ground target spells and AoE, but melee heroes can struggle against him because of his move set. Of course feel free to change things to your vision if you think about adding him to game

**Comment by Haganeko** [comment]
Thanks for the idea!
These are some interesting mechanics. Please focus on them, instead of flavor/lore. For example, instead of saying the boss throws daggers, say it throws projectiles.
Question: when you say the illusions would be like arc warden's, do you mean they would also be clearly identified as such?

**Comment by Wujekklawy** [comment]
I meant to more ilustrate how illusion would work and arc one is closest to that.

A: actually i not thinked about that option at all, it depends on how you want to make fight, if give high durable to boss it would be good idea to make them clearly identified but actually one of reasons i sugestet so low hp % left on phase 2 is to decrease time to kill them also keeping so low bonus dmg to them to be harder to identify real one. So long story short, i maked it to illusions be not easily identified, and to kill real one would take to kill 1-2 illusions before identify real one. But if wanted it could be easily identify, that just would need some modification in strength of main one.

**Comment by Haganeko** [comment]
Any updates on this, given the comments above?
If at all possible, try to format this better - #37 has a very useful template for this.

**Comment by Wujekklawy** [comment]
@Haganeko any updates depends on dev team :) not on me ;)

**Comment by Haganeko** [comment]
You hadn't addressed the concerns with this idea. As it currently is, it would be hard to use it or even gauge how good it would be for implementation. Since you said you didn't wish to update it, and no one else took it up, I considered the topic abandoned.

**Comment by Wujekklawy** [comment]
@Haganeko It nit useing anything that dota don't have already, slightly modified Abbilities that are already in game first abbility can be modified sacred arrow second one is just modified jugger spin therd one is modified shadow blade forth one is AI triggered magnus dash mixed with meteor and last one is modified lone druid roar. Phase 2 is bassicly creating Arc warden like ilusions.  If you want i can rewrite it so it will be more of mechanical side but for now I'm not able to do it in comfortable way (laptop was for while out of order and will be that way for non specified time)

**Comment by Haganeko** [comment]
This boss has four abilities, each one unrelated to the others. The phase progression is not intuitive, and the invisibility is likely to get annoying. Plus, there is a lot of fluff in the post. Closed.
