### ISSUE TITLE
Bosses of the Elementals, lots of tryhard Boss fight designs and "Soul Stones" mechanics

### ISSUE THREAD

**Issue by preddator32** [AngelArenaAllstars/suggestions#88]
So, inspired by the last Vlog about Boss examples and some unique ways to defeat them, I came up with an idea of not only making the fighting style of Boss unique, but also helping players to possess something one and only in each game What if we take the mechanics of some boss and create some item(or more like an orb effect) that actually contains some significant part of their powers. 
# Exemplary boss concept(not mine) with few topic related changes
For example, lets "steal" the idea from one of other suggestions about sunlike Phoenix Boss [](https://github.com/AngelArenaAllstars/suggestions/issues/56) (it might be any other, but I really liked its concept and also this one should illustrate the idea in most obvious way) and modify it a little. Lets make this boss some kind of spellproof guy, with not that much of physical resistance, stick to idea of him blinding enemies (causing disarm effect in 600 AOE for about 3 sec) when they stare at him while he casts any of his spells (the casting itself does not cause the blinding effect, but when spell is done it creates the "Blinding flash"). Also I would like to suggest some changes for the Boss arena, because in the given state I see no funny interaction helping to defeat the Boss and not only to annoy players, slipping into lava of his skills all the time. So lets make his habitat all bloomy and green, having some high rocks near the edge of the map. And there in the middle on some sort of pedestal is going to be an egg, which turns into the Phoenix at the start of the boss fight. He is going to glide around casting spells and hitting enemies in his reach (in my head, it seems like he should be more passive kind of a boss that doesn't really want to fight and has to be provoked by spell of regular attack). Both his attacks and skills cause "Sunburn" debuff, dealing damage for 4 sec and reducing rightclick damage for 5% for a minute (it stacks and refreshes, but also gets purged) .There are also 4 crystal pillars around the pedestal. They are capable of protecting from Phoenix's skills in a small area behind them and restoring health and mana for all heroes around for every spell blocked, to help players in late stages of the fight. What is going to be unique about this Boss? Well, my suggestion is to give him a shit lot of HP, much more, than most other bosses have. But in exchange, just as regular Dota 2 Phoenix, his skills will require not only mana but also his HP, providing him heals for each hero it hits (restoring about 25% of spent HP for a hero hit). This mechanics additionally motivates players to actually try their best in dodging shit and on purpose provoke the Boss to use his skills (let it kinda burn itself). But if somebody finds this way too slow, there gonna be 2 waterfalls on 2 different edges of the arena, causing aghanim "Gush" effect on activation (has 1 min cooldown) in a small range around it. The effect gives temporary 15 sec purge effect on heroes (dispelling all debuffs) and if Phoenix is in that range he loses all his spell resistance and gets stunned for about 5-7 sec, giving your team a lot of time to deal a shit load of damage (including magical). This gives at least 2 possible ways of fighting the boss (exhausting or active one; the choise depends on your fighing capabitilies and what damage type prevails in your team).
Now in short about the stages:

1st - I like the original idea about Lina's stun ability adding him capability of making some usual hits between times.
2nd (75 % HP)- As we decided to make the blinding effect some kind of passive, I think that those "sun grenades" are actually really neat idea for the second stage. They should have the same mechanic as regular Phoenix's fire spirits, with their effects slightly changed. 
3rd (35% HP) - Our Phoenix is almoust out of HP and goes to berserk mode. At this stage the number of his "sun grenades" is x3 and the cooldown is twice lower. He furiously bombards the arena in circles, targeting ground ( not players). Here is also another use for waterfalls, which now can't be used to stun the boss (because he is not in range), but are capable to make your rightclickers fight in full power, without worrying about debuffs caused by the boss.
4th (0% HP) - Finally, Phoenix is basically dead and he Icarus Dives into the pedestal, he was on at the very beginning of the fight, turning himself into an egg, trying to reborn. He causes magic explosions every five second (these explosions have his passive effects, so u still have to avoid looking straight on the egg, while it explodes. In the worst case scenario, on the 6th flash (in 30 seconds) he will rise again (OMFG). U and your team have to hit the egg with 30 instances of phys damage before that happens and u won. Congrats!
# The "Soul Stone"
And here comes the new hero mechanics! (finally!!!) On death he drops all kinds of items around the pedestal (just casual boss loot, like in usual AA). But on the pedestal itself is going to be some another thing. Not just a regular Item, but more like a blessing(or a curse) - "The soul of fire" (or some other nameless disaster xD). It gets consumed by one of the heroes and turns into a passive effect (much like a consumed Moon shard). For this specific one the effect will be something like this:
+ Spell Damage resistance (+15% - +60%) (to the base of 25%). Increases for 1% for every instance of enemy hero spell damage "tanked"
+ Spell Damage amplification (+15% - + 60%). Increases for 1% every time your spell hits enemy hero.
Passive effects:
Adds "Sunburn" effect to your attacks.
Every time you cast a spell, enemies within the range (200-800), looking in your direction, get a "Sunburn" effect and "Blinding flash" effect on them (the continuety is twice lower than Phoenix's ones). The range increases for 15 for every enemy hero hit with this passive.
+ 10% lifesteal from spells
Every spell cast takes 5 % of your current HP and converts it into additional damage
Negative effects
- Physical damage resistanse (-5% - - 35%). Decreases for 3% for each death.
## Conclusion
So, as you can see, this effect has two sides, both positive and negative, but provides an absolutely different gameplay style for a player, who has obtained it. 
So, that's my suggestion, Though all these numbers barely matter, they show the basic idea. Create an impression that player, who actually consumed one of these souls, kind of obtained the essense of the boss himself. And yes, with only one of such things in game there won't be any balance at all. However, if you add, lets say, at least 3 more of these unique artefacts into the game, getting them and fighting to make them even more powerful (that is also + one more activity motivating factor in game) is going to be another one exciting part of the game mode. 
# Afterwords
I already have some ideas about other boss arenas and their "Soul stone" effects. I actually see now that it is a shit load of text (omg). And with my english skills below average, reading all of it must be a real torture, so I don't think that even half of the readers have reached the main point. However, I still would be happy to see your responds for my ideas and hope that at least some of these thoughts will make it through into the final game mode, in one way or another.

**Comment by preddator32** [comment]
The original boss idea belongs to JackGrayling. https://github.com/AngelArenaAllstars/suggestions/issues/56
I'm sorry for merciless distortion of your concept and thanks for giving me some base to start with!

**Comment by Haganeko** [comment]
Thanks for the post! Boss items which contain parts of the boss mechanics have been suggested, and are in the game. So I can say with confidence that most of the team thinks it's a great idea.
About the boss: if you have ideas to alter a boss, please post them on the original issue. Also, please format it more clearly, as it is currently it is hard to read.
The item idea looks interesting, although I dislike how its stats change with deaths and tanking spells. Also, I don't believe it should be a consumable. Effects like this should take item slots, and it also robs us of an item upgrade path.

**Comment by preddator32** [comment]
Thanks for your respond! Yey, that's already something!
Okay, next time I will. Though I thought that these changes were kind of too much to keep sticking to the original post.
Well, that was just an example. I just thought about all kinds of possible spell interactions and that's what came to my mind.
And although upgrading boss items (as usual ones) is a fine idea in general, that would kind of kill the mechanics of upgrading an effect buy the actual game activity (because the idea was to bring into the game some other upgrade mechanics, except buying (or collecting) stuff. In somelike a "bloodstone" way of upgrading - the more you kill, the more powerful you are). Well, if only you keep the collected effect on the item after upgrading it. 
Will keep working on those and try to give some interesting suggestions next time!

**Comment by Haganeko** [comment]
Any update on this? #37 has a useful template for formatting which would help with clarity.

**Comment by Haganeko** [comment]
This ticket is very confused, but I took some of the ideas and posted in #331. Closed.
