### ISSUE TITLE
Boss Idea: The Trickster (Any Tier)

### ISSUE THREAD

**Issue by Haganeko** [AngelArenaAllstars/suggestions#9]
When the heroes come upon the boss, it mimics another boss of the given tier... except it only deals 70% of the damage the real boss is supposed to deal, and takes only 50% of the damage it's supposed to. The heroes must discover that, and attack the real boss, who is hiding, invisible, in one of the corners of the arena.
Gem doesn't work, but dust does. Damaging the boss (through area spells or skill shots, but not radiance or auras) also reveals it.
Still needs work, but it could be fun, with visual and auditory cues...

**Comment by l34Um1** [comment]
a cool one time thing but afterwards people will always just dust him and then the gimmick is voided.

**Comment by Haganeko** [comment]
Well, that assumes people figure out he's the Trickster - They need to know the boss he's mimicking very well to notice that something is off...
