### ISSUE TITLE
Boss idea

### ISSUE THREAD

**Issue by ScorpiionMKD** [AngelArenaAllstars/suggestions#91]
Hey, how about an idea, a boss that is invulnerable to all physical damage except magical (for a weaker boss tier 1 for example) so heroes need to use only magical damage to defeat the boss, but the boss only attacks one closest target to him (example Ursa only uses the Earthshock to cause damage and tank the boss and heroes like supports, Dazzle with the healing wave, Lina with all the spells etc. can do damage so they don`t feel useless in the fights and of course the boss takes certain % more spell dmg).
Here is another idea for the heroes/bosses - in the current Angel Arena there are heroes that are hardly picked, so i thought to make some heroes "useful" not for PVP, instead for the bosses (for example: if the Lone Druid is not picked because its not useful for PVP, just assume, then make him really useful for killing/tanking bosses, if all other heroes can tank bosses on for ex. lvl 10, the spirit bear can tank earlier, if anyone can modify this idea to make it possible for implementation that would be great, the purpose of this idea is to play ALL the heroes, not just a few that are extremely good naturally)

**Comment by Haganeko** [comment]
Thanks for posting!
There was a boss idea going around which revolves around a boss with high physical resistance, low magic resistance, and during which players  have increased mana regen. I took it and did something with it - maybe try your own spin on the concept?
On the second point: that's something of a balance exercise. We'll closely monitor data from the alpha, once it launches, and buff or nerf heroes as necessary.
