### ISSUE TITLE
Boss Idea, Tree boss

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/suggestions#93]
Large circular arena with tree in the middle. Stage 1 tree drops projectile (apples) that roll in a straight line outwards (invoker meatball), as well as summons treants at regular intervals. The projectiles can be knocked back with an autoattack to damage treants and/or the tree. Stage 2 treants spawning cease but apples continue to spawn and roll faster, tree gains new attack where, (I know you said no flowery language but idk how to describe it otherwise,) from the center of the tree a slow burrowing animation begins one for every player, the trees roots slowly travel underground and somewhat/loosely home in on players. After 3 or so seconds the roots stop seeking their target if they have not hit yet, but if they hit they root the player making them prone to the apples and dealing damage (and maybe restoring the trees life?). Final stage the tree dies/breaks and falls over. From the stump a giant treant appears picks up the fallen tree to use as a club and this is stage three. The tree normally fights exactly like the boss from poke the angry ogre with constant ground slams and pursuing the last hero that hit him. However the boss has an animation that summons projectiles/apples from the sky in multiple small AOEs randomly (like sunstrikes) (this animation is channeled he doesnt attack while he performs it). In addition to other items killing this boss drops a few golden apples which act the same as a cheese.

**Comment by Haganeko** [comment]
Thanks for the post! This looks quite interesting. I like the idea of a sessile boss which turns mobile after losing HP.
Please do focus on mechanics instead of flavor. Instead of saying the boss is a tree which drops apples and summons treants, say it is immobile and uses aoe spells which summon minions. This will make it easier for your design to shine through!

**Comment by prodigiousking** [comment]
K thank you

**Comment by Haganeko** [comment]
Any updates on this? If you could format this according to the template in #37, it would help a lot.

**Comment by prodigiousking** [comment]
Yeah but give me till sunday plz I am a bit busy at the moment
