### ISSUE TITLE
[mechanic] Boss/Hero currency 

### ISSUE THREAD

**Issue by Wujekklawy** [AngelArenaAllstars/suggestions#95]
What is most unnoyng thing in bosses in evry angel arena? That you need kill him like 10 times to he drop item you need... and then teammate pick it up and bind to himself. If add some currency different from gold being splited between heroes in xp range could be possible to avoid grinding for items over and over and just buy it from shop (meaby something like special "secret" shop on middle of map). Also if keep boss drops it could be rly few of it and increase through boss tiers so when you won't be able to buy same tier items without killing more than 3 bosses but enough when you will be want buy new item and need low tier boss items for lower upgrades.

Also currency gaining from killing enemy heroes and that would be currency for buying tomes of some sort (like tomes in AA reborn) and flat hero upgrades like more night/day vision or more range (randged only ofc) or for mele deflect chance (to balance ranged buff) with will give like 1-2% per upgrade etc. It could be obtainable by duels, kiling sprees, 1 per x kills or multikills. Options are endless (not rly [but still]).

**Comment by prodigiousking** [comment]
I think you touched on it but i was confused so i will try to clarify. This currency idea would fix the problem of getting unlucky and the wrong items dropping, (like needing an angels blood but only getting blessed essences,) as well as fix any confusion as to what boss you need to beat to defeat to get what item. As far as the issue of preventing powerful items from being accessed too early you could make the cost of high tier items( as well as the bounty of high tier bosses) scale largely in magnitude so no matter how many low tier bosses you kill you cant afford high tier items, or organize boss items by tier and firther subdivide the special currency by tier. The second option would be more complicated but it would eliminate the possibility of issues arising from defeating a powerful boss and being able to buy a massive amount of low tier god items. Idk if this is what you are looking for as far as how bosses correspind to item but i certainly think it is a domewhat viable route.

**Comment by Haganeko** [comment]
The idea of an alternate currency has been proposed before, but we decided against using it, because we preferred our current item drop system.
The boss drops will never be on the floor for people to pick up; we're implementing a ngp system to deal with that. Additionally, some items will always drop from specific bosses, while others will be obtainable from every boss in a given tier. This will make getting the item you need much easier.
There is also Azazel, if your team is getting really unlucky with their drops.

**Comment by Wujekklawy** [comment]
Haganeko, you only explained why first part will most likely be denied but what about second one? It also force players to be more agreement what means more ganks/fights and possibly faster phase of game.

**Comment by Haganeko** [comment]
I didn't because I have no problem with it. We're not doing stat tomes, out of concern for attack speed inflation, but a currency from hero killing with alternate uses could be pretty interesting.

**Comment by Wujekklawy** [comment]
Submit closed,  moved to https://github.com/AngelArenaAllstars/suggestions/issues/146
