### ISSUE TITLE
Boss Idea

### ISSUE THREAD

**Issue by ZTK211** [AngelArenaAllstars/suggestions#99]
twin bosses with a shared total hp (two bosses with 1 hp bar, think of it as if they have fatal bonds but it transferred 100% dmg dealt)
one takes and deals only magic dmg and the other only takes and deals physical dmg (both can be dmged with pure dmg)

tbh I'm taking a little bit from Epic Boss Fight but I always thought it would be cooler if they shared their hp pool

**Comment by Haganeko** [comment]
A double boss has been suggested before. Such a concept is being considered. Thank you for your submission, and sorry for the wait.
